var M15 = [
{Name:"Ajani Steadfast", Cost:"3W", Color:["W"], Rarity:"M", Type:["P"], Rating:"10", Sort:"", Set:"M15", Number:"1", Image:"/Images/M15/AjaniSteadfast.jpg"},
{Name:"Ajani's Pridemate", Cost:"1W", Color:["W"], Rarity:"U", Type:["C"], Rating:"7", Sort:"", Set:"M15", Number:"2", Image:"/Images/M15/AjanisPridemate.jpg"},
{Name:"Avacyn, Guardian Angel", Cost:"2WWW", Color:["W"], Rarity:"R", Type:["C"], Rating:"9", Sort:"", Set:"M15", Number:"3", Image:"/Images/M15/Avacyn--GuardianAngel.jpg"},
{Name:"Battle Mastery", Cost:"2W", Color:["W"], Rarity:"U", Type:["E"], Rating:"6", Sort:"", Set:"M15", Number:"4", Image:"/Images/M15/BattleMastery.jpg"},
{Name:"Boonweaver Giant", Cost:"6W", Color:["W"], Rarity:"U", Type:["C"], Rating:"7", Sort:"", Set:"M15", Number:"5", Image:"/Images/M15/BoonweaverGiant.jpg"},
{Name:"Congregate", Cost:"3W", Color:["W"], Rarity:"U", Type:["I"], Rating:"5", Sort:"", Set:"M15", Number:"6", Image:"/Images/M15/Congregate.jpg"},
{Name:"Constricting Sliver", Cost:"5W", Color:["W"], Rarity:"U", Type:["C"], Rating:"6", Sort:"", Set:"M15", Number:"7", Image:"/Images/M15/ConstrictingSliver.jpg"},
{Name:"Dauntless River Marshal", Cost:"1W", Color:["W"], Rarity:"U", Type:["C"], Rating:"5", Sort:"", Set:"M15", Number:"8", Image:"/Images/M15/DauntlessRiverMarshal.jpg"},
{Name:"Devouring Light", Cost:"1WW", Color:["W"], Rarity:"U", Type:["I"], Rating:"7", Sort:"", Set:"M15", Number:"9", Image:"/Images/M15/DevouringLight.jpg"},
{Name:"Divine Favor", Cost:"1W", Color:["W"], Rarity:"C", Type:["E"], Rating:"5", Sort:"", Set:"M15", Number:"10", Image:"/Images/M15/DivineFavor.jpg"},
{Name:"Ephemeral Shields", Cost:"1W", Color:["W"], Rarity:"C", Type:["I"], Rating:"5", Sort:"", Set:"M15", Number:"11", Image:"/Images/M15/EphemeralShields.jpg"},
{Name:"First Response", Cost:"3W", Color:["W"], Rarity:"U", Type:["E"], Rating:"4", Sort:"", Set:"M15", Number:"12", Image:"/Images/M15/FirstResponse.jpg"},
{Name:"Geist of the Moors", Cost:"1WW", Color:["W"], Rarity:"U", Type:["C"], Rating:"7", Sort:"", Set:"M15", Number:"13", Image:"/Images/M15/GeistoftheMoors.jpg"},
{Name:"Heliods Pilgrim", Cost:"2W", Color:["W"], Rarity:"C", Type:["C"], Rating:"7", Sort:"", Set:"M15", Number:"14", Image:"/Images/M15/HeliodsPilgrim.jpg"},
{Name:"Hushwing Gryff", Cost:"2W", Color:["W"], Rarity:"R", Type:["C"], Rating:"5", Sort:"", Set:"M15", Number:"15", Image:"/Images/M15/HushwingGryff.jpg"},
{Name:"Kinsbaile Skirmisher", Cost:"1W", Color:["W"], Rarity:"C", Type:["C"], Rating:"5", Sort:"", Set:"M15", Number:"16", Image:"/Images/M15/KinsbaileSkirmisher.jpg"},
{Name:"Marked by Honor", Cost:"3W", Color:["W"], Rarity:"C", Type:["E"], Rating:"3", Sort:"", Set:"M15", Number:"17", Image:"/Images/M15/MarkedbyHonor.jpg"},
{Name:"Mass Calcify", Cost:"5WW", Color:["W"], Rarity:"R", Type:["S"], Rating:"5", Sort:"", Set:"M15", Number:"18", Image:"/Images/M15/MassCalcify.jpg"},
{Name:"Meditation Puzzle", Cost:"3WW", Color:["W"], Rarity:"C", Type:["I"], Rating:"1", Sort:"", Set:"M15", Number:"19", Image:"/Images/M15/MeditationPuzzle.jpg"},
{Name:"Midnight Guard", Cost:"2W", Color:["W"], Rarity:"C", Type:["C"], Rating:"3", Sort:"", Set:"M15", Number:"20", Image:"/Images/M15/MidnightGuard.jpg"},
{Name:"Oppressive Rays", Cost:"0W", Color:["W"], Rarity:"C", Type:["E"], Rating:"6", Sort:"", Set:"M15", Number:"21", Image:"/Images/M15/OppressiveRays.jpg"},
{Name:"Oreskos Swiftclaw", Cost:"1W", Color:["W"], Rarity:"C", Type:["C"], Rating:"6", Sort:"", Set:"M15", Number:"22", Image:"/Images/M15/OreskosSwiftclaw.jpg"},
{Name:"Paragon of New Dawns", Cost:"3W", Color:["W"], Rarity:"U", Type:["C"], Rating:"6", Sort:"", Set:"M15", Number:"23", Image:"/Images/M15/ParagonofNewDawns.jpg"},
{Name:"Pillar of Light", Cost:"2W", Color:["W"], Rarity:"C", Type:["I"], Rating:"5", Sort:"", Set:"M15", Number:"24", Image:"/Images/M15/PillarofLight.jpg"},
{Name:"Preeminent Captain", Cost:"2W", Color:["W"], Rarity:"R", Type:["C"], Rating:"7", Sort:"", Set:"M15", Number:"25", Image:"/Images/M15/PreeminentCaptain.jpg"},
{Name:"Raise the Alarm", Cost:"1W", Color:["W"], Rarity:"C", Type:["I"], Rating:"6", Sort:"", Set:"M15", Number:"26", Image:"/Images/M15/RaisetheAlarm.jpg"},
{Name:"Razorfoot Griffin", Cost:"3W", Color:["W"], Rarity:"C", Type:["C"], Rating:"6", Sort:"", Set:"M15", Number:"27", Image:"/Images/M15/RazorfootGriffin.jpg"},
{Name:"Resolute Archangel", Cost:"5WW", Color:["W"], Rarity:"R", Type:["C"], Rating:"6", Sort:"", Set:"M15", Number:"28", Image:"/Images/M15/ResoluteArchangel.jpg"},
{Name:"Return to the Ranks", Cost:"0WW", Color:["W"], Rarity:"R", Type:["S"], Rating:"7", Sort:"", Set:"M15", Number:"29", Image:"/Images/M15/ReturntotheRanks.jpg"},
{Name:"Sanctified Charge", Cost:"4W", Color:["W"], Rarity:"C", Type:["I"], Rating:"4", Sort:"", Set:"M15", Number:"30", Image:"/Images/M15/SanctifiedCharge.jpg"},
{Name:"Selfless Cathar", Cost:"0W", Color:["W"], Rarity:"C", Type:["C"], Rating:"6", Sort:"", Set:"M15", Number:"31", Image:"/Images/M15/SelflessCathar.jpg"},
{Name:"Seraph of the Masses", Cost:"5WW", Color:["W"], Rarity:"U", Type:["C"], Rating:"6", Sort:"", Set:"M15", Number:"32", Image:"/Images/M15/SeraphoftheMasses.jpg"},
{Name:"Solemn Offering", Cost:"2W", Color:["W"], Rarity:"C", Type:["S"], Rating:"5", Sort:"", Set:"M15", Number:"33", Image:"/Images/M15/SolemnOffering.jpg"},
{Name:"Soul of Theros", Cost:"4WW", Color:["W"], Rarity:"M", Type:["C"], Rating:"8", Sort:"", Set:"M15", Number:"34", Image:"/Images/M15/SoulofTheros.jpg"},
{Name:"Soulmender", Cost:"0W", Color:["W"], Rarity:"C", Type:["C"], Rating:"4", Sort:"", Set:"M15", Number:"35", Image:"/Images/M15/Soulmender.jpg"},
{Name:"Spectral Ward", Cost:"3WW", Color:["W"], Rarity:"R", Type:["E"], Rating:"9", Sort:"", Set:"M15", Number:"36", Image:"/Images/M15/SpectralWard.jpg"},
{Name:"Spirit Bonds", Cost:"1W", Color:["W"], Rarity:"R", Type:["E"], Rating:"9", Sort:"", Set:"M15", Number:"37", Image:"/Images/M15/SpiritBonds.jpg"},
{Name:"Sungrace Pegasus", Cost:"1W", Color:["W"], Rarity:"C", Type:["C"], Rating:"7", Sort:"", Set:"M15", Number:"38", Image:"/Images/M15/SungracePegasus.jpg"},
{Name:"Tireless Missionaries", Cost:"4W", Color:["W"], Rarity:"C", Type:["C"], Rating:"3", Sort:"", Set:"M15", Number:"39", Image:"/Images/M15/TirelessMissionaries.jpg"},
{Name:"Triplicate Spirits", Cost:"4WW", Color:["W"], Rarity:"C", Type:["S"], Rating:"5", Sort:"", Set:"M15", Number:"40", Image:"/Images/M15/TriplicateSpirits.jpg"},
{Name:"Wall of Essence", Cost:"1W", Color:["W"], Rarity:"U", Type:["C"], Rating:"6", Sort:"", Set:"M15", Number:"41", Image:"/Images/M15/WallofEssence.jpg"},
{Name:"Warden of the Beyond", Cost:"2W", Color:["W"], Rarity:"U", Type:["C"], Rating:"6", Sort:"", Set:"M15", Number:"42", Image:"/Images/M15/WardenoftheBeyond.jpg"},
{Name:"Aeronaut Tinkerer", Cost:"2U", Color:["U"], Rarity:"C", Type:["C"], Rating:"5", Sort:"", Set:"M15", Number:"43", Image:"/Images/M15/AeronautTinkerer.jpg"},
{Name:"AEtherspouts", Cost:"3UU", Color:["U"], Rarity:"R", Type:["I"], Rating:"8", Sort:"", Set:"M15", Number:"44", Image:"/Images/M15/AEtherspouts.jpg"},
{Name:"Amphin Pathmage", Cost:"3U", Color:["U"], Rarity:"C", Type:["C"], Rating:"5", Sort:"", Set:"M15", Number:"45", Image:"/Images/M15/AmphinPathmage.jpg"},
{Name:"Chasm Skulker", Cost:"2U", Color:["U"], Rarity:"R", Type:["C"], Rating:"7", Sort:"", Set:"M15", Number:"46", Image:"/Images/M15/ChasmSkulker.jpg"},
{Name:"Chief Engineer", Cost:"1U", Color:["U"], Rarity:"R", Type:["C"], Rating:"5", Sort:"", Set:"M15", Number:"47", Image:"/Images/M15/ChiefEngineer.jpg"},
{Name:"Chronostutter", Cost:"5U", Color:["U"], Rarity:"C", Type:["I"], Rating:"5", Sort:"", Set:"M15", Number:"48", Image:"/Images/M15/Chronostutter.jpg"},
{Name:"Coral Barrier", Cost:"2U", Color:["U"], Rarity:"C", Type:["C"], Rating:"6", Sort:"", Set:"M15", Number:"49", Image:"/Images/M15/CoralBarrier.jpg"},
{Name:"Diffusion Sliver", Cost:"1U", Color:["U"], Rarity:"U", Type:["C"], Rating:"3", Sort:"", Set:"M15", Number:"50", Image:"/Images/M15/DiffusionSliver.jpg"},
{Name:"Dissipate", Cost:"1UU", Color:["U"], Rarity:"U", Type:["I"], Rating:"6", Sort:"", Set:"M15", Number:"51", Image:"/Images/M15/Dissipate.jpg"},
{Name:"Divination", Cost:"2U", Color:["U"], Rarity:"C", Type:["S"], Rating:"6", Sort:"", Set:"M15", Number:"52", Image:"/Images/M15/Divination.jpg"},
{Name:"Encrust", Cost:"1UU", Color:["U"], Rarity:"C", Type:["E"], Rating:"7", Sort:"", Set:"M15", Number:"53", Image:"/Images/M15/Encrust.jpg"},
{Name:"Ensoul Artifact", Cost:"1U", Color:["U"], Rarity:"U", Type:["E"], Rating:"5", Sort:"", Set:"M15", Number:"54", Image:"/Images/M15/EnsoulArtifact.jpg"},
{Name:"Frost Lynx", Cost:"2U", Color:["U"], Rarity:"C", Type:["C"], Rating:"5", Sort:"", Set:"M15", Number:"55", Image:"/Images/M15/FrostLynx.jpg"},
{Name:"Fugitive Wizard", Cost:"0U", Color:["U"], Rarity:"C", Type:["C"], Rating:"1", Sort:"", Set:"M15", Number:"56", Image:"/Images/M15/FugitiveWizard.jpg"},
{Name:"Glacial Crasher", Cost:"4UU", Color:["U"], Rarity:"C", Type:["C"], Rating:"4", Sort:"", Set:"M15", Number:"57", Image:"/Images/M15/GlacialCrasher.jpg"},
{Name:"Hydrosurge", Cost:"0U", Color:["U"], Rarity:"C", Type:["I"], Rating:"3", Sort:"", Set:"M15", Number:"58", Image:"/Images/M15/Hydrosurge.jpg"},
{Name:"Illusory Angel", Cost:"2U", Color:["U"], Rarity:"U", Type:["C"], Rating:"8", Sort:"", Set:"M15", Number:"59", Image:"/Images/M15/IllusoryAngel.jpg"},
{Name:"Into the Void", Cost:"3U", Color:["U"], Rarity:"U", Type:["S"], Rating:"6", Sort:"", Set:"M15", Number:"60", Image:"/Images/M15/IntotheVoid.jpg"},
{Name:"Invisibility", Cost:"0UU", Color:["U"], Rarity:"C", Type:["E"], Rating:"5", Sort:"", Set:"M15", Number:"61", Image:"/Images/M15/Invisibility.jpg"},
{Name:"Jace, the Living Guildpact", Cost:"2UU", Color:["U"], Rarity:"M", Type:["P"], Rating:"10", Sort:"", Set:"M15", Number:"62", Image:"/Images/M15/Jace--theLivingGuildpact.jpg"},
{Name:"Jace's Ingenuity", Cost:"3UU", Color:["U"], Rarity:"U", Type:["I"], Rating:"7", Sort:"", Set:"M15", Number:"63", Image:"/Images/M15/JacesIngenuity.jpg"},
{Name:"Jalira, Master Polymorphist", Cost:"3U", Color:["U"], Rarity:"R", Type:["C"], Rating:"8", Sort:"", Set:"M15", Number:"64", Image:"/Images/M15/Jalira--MasterPolymorphist.jpg"},
{Name:"Jorubai Murk Lurker", Cost:"2U", Color:["U"], Rarity:"U", Type:["C"], Rating:"5", Sort:"", Set:"M15", Number:"65", Image:"/Images/M15/JorubaiMurkLurker.jpg"},
{Name:"Kapsho Kitefins", Cost:"4UU", Color:["U"], Rarity:"U", Type:["C"], Rating:"6", Sort:"", Set:"M15", Number:"66", Image:"/Images/M15/KapshoKitefins.jpg"},
{Name:"Master of Predicaments", Cost:"3UU", Color:["U"], Rarity:"R", Type:["C"], Rating:"8", Sort:"", Set:"M15", Number:"67", Image:"/Images/M15/MasterofPredicaments.jpg"},
{Name:"Mercurial Pretender", Cost:"4U", Color:["U"], Rarity:"R", Type:["C"], Rating:"7", Sort:"", Set:"M15", Number:"68", Image:"/Images/M15/MercurialPretender.jpg"},
{Name:"Military Intelligence", Cost:"1U", Color:["U"], Rarity:"U", Type:["E"], Rating:"7", Sort:"", Set:"M15", Number:"69", Image:"/Images/M15/MilitaryIntelligence.jpg"},
{Name:"Mind Sculpt", Cost:"1U", Color:["U"], Rarity:"C", Type:["S"], Rating:"2", Sort:"", Set:"M15", Number:"70", Image:"/Images/M15/MindSculpt.jpg"},
{Name:"Negate", Cost:"1U", Color:["U"], Rarity:"C", Type:["I"], Rating:"5", Sort:"", Set:"M15", Number:"71", Image:"/Images/M15/Negate.jpg"},
{Name:"Nimbus of the Isles", Cost:"4U", Color:["U"], Rarity:"C", Type:["C"], Rating:"4", Sort:"", Set:"M15", Number:"72", Image:"/Images/M15/NimbusoftheIsles.jpg"},
{Name:"Paragon of Gathering Mists", Cost:"3U", Color:["U"], Rarity:"U", Type:["C"], Rating:"5", Sort:"", Set:"M15", Number:"73", Image:"/Images/M15/ParagonofGatheringMists.jpg"},
{Name:"Peel from Reality", Cost:"1U", Color:["U"], Rarity:"C", Type:["I"], Rating:"4", Sort:"", Set:"M15", Number:"74", Image:"/Images/M15/PeelfromReality.jpg"},
{Name:"Polymorphist's Jest", Cost:"1UU", Color:["U"], Rarity:"R", Type:["I"], Rating:"8", Sort:"", Set:"M15", Number:"75", Image:"/Images/M15/PolymorphistsJest.jpg"},
{Name:"Quickling", Cost:"1U", Color:["U"], Rarity:"U", Type:["C"], Rating:"5", Sort:"", Set:"M15", Number:"76", Image:"/Images/M15/Quickling.jpg"},
{Name:"Research Assistant", Cost:"1U", Color:["U"], Rarity:"C", Type:["C"], Rating:"4", Sort:"", Set:"M15", Number:"77", Image:"/Images/M15/ResearchAssistant.jpg"},
{Name:"Soul of Ravnica", Cost:"4UU", Color:["U"], Rarity:"M", Type:["C"], Rating:"8", Sort:"", Set:"M15", Number:"78", Image:"/Images/M15/SoulofRavnica.jpg"},
{Name:"Statute of Denial", Cost:"2UU", Color:["U"], Rarity:"C", Type:["C"], Rating:"5", Sort:"", Set:"M15", Number:"79", Image:"/Images/M15/StatuteofDenial.jpg"},
{Name:"Stormtide Leviathan", Cost:"5UUU", Color:["U"], Rarity:"R", Type:["C"], Rating:"8", Sort:"", Set:"M15", Number:"80", Image:"/Images/M15/StormtideLeviathan.jpg"},
{Name:"Turn to Frog", Cost:"1U", Color:["U"], Rarity:"U", Type:["I"], Rating:"8", Sort:"", Set:"M15", Number:"81", Image:"/Images/M15/TurntoFrog.jpg"},
{Name:"Void Snare", Cost:"0U", Color:["U"], Rarity:"C", Type:["S"], Rating:"6", Sort:"", Set:"M15", Number:"82", Image:"/Images/M15/VoidSnare.jpg"},
{Name:"Wall of Frost", Cost:"1UU", Color:["U"], Rarity:"U", Type:["C"], Rating:"6", Sort:"", Set:"M15", Number:"83", Image:"/Images/M15/WallofFrost.jpg"},
{Name:"Welkin Tern", Cost:"1U", Color:["U"], Rarity:"C", Type:["C"], Rating:"7", Sort:"", Set:"M15", Number:"84", Image:"/Images/M15/WelkinTern.jpg"},
{Name:"Accursed Spirit", Cost:"3B", Color:["B"], Rarity:"C", Type:["C"], Rating:"7", Sort:"", Set:"M15", Number:"85", Image:"/Images/M15/AccursedSpirit.jpg"},
{Name:"Black Cat", Cost:"1B", Color:["B"], Rarity:"C", Type:["C"], Rating:"7", Sort:"", Set:"M15", Number:"86", Image:"/Images/M15/BlackCat.jpg"},
{Name:"Blood Host", Cost:"3BB", Color:["B"], Rarity:"U", Type:["C"], Rating:"6", Sort:"", Set:"M15", Number:"87", Image:"/Images/M15/BloodHost.jpg"},
{Name:"Carrion Crow", Cost:"2B", Color:["B"], Rarity:"C", Type:["C"], Rating:"6", Sort:"", Set:"M15", Number:"88", Image:"/Images/M15/CarrionCrow.jpg"},
{Name:"Caustic Tar", Cost:"4BB", Color:["B"], Rarity:"U", Type:["E"], Rating:"3", Sort:"", Set:"M15", Number:"89", Image:"/Images/M15/CausticTar.jpg"},
{Name:"Child of Night", Cost:"1B", Color:["B"], Rarity:"C", Type:["C"], Rating:"6", Sort:"", Set:"M15", Number:"90", Image:"/Images/M15/ChildofNight.jpg"},
{Name:"Covenant of Blood", Cost:"6B", Color:["B"], Rarity:"C", Type:["S"], Rating:"4", Sort:"", Set:"M15", Number:"91", Image:"/Images/M15/CovenantofBlood.jpg"},
{Name:"Crippling Blight", Cost:"0B", Color:["B"], Rarity:"C", Type:["E"], Rating:"6", Sort:"", Set:"M15", Number:"92", Image:"/Images/M15/CripplingBlight.jpg"},
{Name:"Cruel Sadist", Cost:"0B", Color:["B"], Rarity:"R", Type:["C"], Rating:"8", Sort:"", Set:"M15", Number:"93", Image:"/Images/M15/CruelSadist.jpg"},
{Name:"Endless Obedience", Cost:"4BB", Color:["B"], Rarity:"U", Type:["S"], Rating:"6", Sort:"", Set:"M15", Number:"94", Image:"/Images/M15/EndlessObedience.jpg"},
{Name:"Eternal Thirst", Cost:"1B", Color:["B"], Rarity:"C", Type:["E"], Rating:"5", Sort:"", Set:"M15", Number:"95", Image:"/Images/M15/EternalThirst.jpg"},
{Name:"Feast on the Fallen", Cost:"2B", Color:["B"], Rarity:"U", Type:["E"], Rating:"6", Sort:"", Set:"M15", Number:"96", Image:"/Images/M15/FeastontheFallen.jpg"},
{Name:"Festergloom", Cost:"2B", Color:["B"], Rarity:"C", Type:["S"], Rating:"4", Sort:"", Set:"M15", Number:"97", Image:"/Images/M15/Festergloom.jpg"},
{Name:"Flesh to Dust", Cost:"3BB", Color:["B"], Rarity:"C", Type:["I"], Rating:"7", Sort:"", Set:"M15", Number:"98", Image:"/Images/M15/FleshtoDust.jpg"},
{Name:"Gravedigger", Cost:"3B", Color:["B"], Rarity:"U", Type:["C"], Rating:"7", Sort:"", Set:"M15", Number:"99", Image:"/Images/M15/Gravedigger.jpg"},
{Name:"In Garruk's Wake", Cost:"7BB", Color:["B"], Rarity:"R", Type:["S"], Rating:"4", Sort:"", Set:"M15", Number:"100", Image:"/Images/M15/InGarruksWake.jpg"},
{Name:"Indulgent Tormentor", Cost:"3BB", Color:["B"], Rarity:"R", Type:["C"], Rating:"9", Sort:"", Set:"M15", Number:"101", Image:"/Images/M15/IndulgentTormentor.jpg"},
{Name:"Leeching Sliver", Cost:"1B", Color:["B"], Rarity:"U", Type:["C"], Rating:"5", Sort:"", Set:"M15", Number:"102", Image:"/Images/M15/LeechingSliver.jpg"},
{Name:"Liliana Vess", Cost:"3BB", Color:["B"], Rarity:"M", Type:["P"], Rating:"10", Sort:"", Set:"M15", Number:"103", Image:"/Images/M15/LilianaVess.jpg"},
{Name:"Mind Rot", Cost:"2B", Color:["B"], Rarity:"C", Type:["S"], Rating:"4", Sort:"", Set:"M15", Number:"104", Image:"/Images/M15/MindRot.jpg"},
{Name:"Necrobite", Cost:"2B", Color:["B"], Rarity:"C", Type:["I"], Rating:"7", Sort:"", Set:"M15", Number:"105", Image:"/Images/M15/Necrobite.jpg"},
{Name:"Necrogen Scudder", Cost:"2B", Color:["B"], Rarity:"U", Type:["C"], Rating:"8", Sort:"", Set:"M15", Number:"106", Image:"/Images/M15/NecrogenScudder.jpg"},
{Name:"Necromancer's Assistant", Cost:"2B", Color:["B"], Rarity:"C", Type:["C"], Rating:"5", Sort:"", Set:"M15", Number:"107", Image:"/Images/M15/NecromancersAssistant.jpg"},
{Name:"Necromancer's Stockpile", Cost:"1B", Color:["B"], Rarity:"R", Type:["E"], Rating:"3", Sort:"", Set:"M15", Number:"108", Image:"/Images/M15/NecromancersStockpile.jpg"},
{Name:"Nightfire Giant", Cost:"4B", Color:["B"], Rarity:"U", Type:["C"], Rating:"5", Sort:"", Set:"M15", Number:"109", Image:"/Images/M15/NightfireGiant.jpg"},
{Name:"Ob Nixilis, Unshackled", Cost:"4BB", Color:["B"], Rarity:"R", Type:["C"], Rating:"9", Sort:"", Set:"M15", Number:"110", Image:"/Images/M15/ObNixilis--Unshackled.jpg"},
{Name:"Paragon of Open Graves", Cost:"3B", Color:["B"], Rarity:"U", Type:["C"], Rating:"7", Sort:"", Set:"M15", Number:"111", Image:"/Images/M15/ParagonofOpenGraves.jpg"},
{Name:"Rotfeaster Maggot", Cost:"4B", Color:["B"], Rarity:"C", Type:["C"], Rating:"4", Sort:"", Set:"M15", Number:"112", Image:"/Images/M15/RotfeasterMaggot.jpg"},
{Name:"Shadowcloak Vampire", Cost:"4B", Color:["B"], Rarity:"C", Type:["C"], Rating:"6", Sort:"", Set:"M15", Number:"113", Image:"/Images/M15/ShadowcloakVampire.jpg"},
{Name:"Sign in Blood", Cost:"0BB", Color:["B"], Rarity:"C", Type:["S"], Rating:"7", Sort:"", Set:"M15", Number:"114", Image:"/Images/M15/SigninBlood.jpg"},
{Name:"Soul of Innistrad", Cost:"4BB", Color:["B"], Rarity:"M", Type:["C"], Rating:"8", Sort:"", Set:"M15", Number:"115", Image:"/Images/M15/SoulofInnistrad.jpg"},
{Name:"Stab Wound", Cost:"2B", Color:["B"], Rarity:"U", Type:["E"], Rating:"4", Sort:"", Set:"M15", Number:"116", Image:"/Images/M15/StabWound.jpg"},
{Name:"Stain the Mind", Cost:"4B", Color:["B"], Rarity:"R", Type:["S"], Rating:"4", Sort:"", Set:"M15", Number:"117", Image:"/Images/M15/StaintheMind.jpg"},
{Name:"Typhoid Rats", Cost:"0B", Color:["B"], Rarity:"C", Type:["C"], Rating:"6", Sort:"", Set:"M15", Number:"118", Image:"/Images/M15/TyphoidRats.jpg"},
{Name:"Ulcerate", Cost:"0B", Color:["B"], Rarity:"U", Type:["I"], Rating:"8", Sort:"", Set:"M15", Number:"119", Image:"/Images/M15/Ulcerate.jpg"},
{Name:"Unmake the Graves", Cost:"4B", Color:["B"], Rarity:"C", Type:["I"], Rating:"4", Sort:"", Set:"M15", Number:"120", Image:"/Images/M15/UnmaketheGraves.jpg"},
{Name:"Wall of Limbs", Cost:"2B", Color:["B"], Rarity:"U", Type:["C"], Rating:"7", Sort:"", Set:"M15", Number:"121", Image:"/Images/M15/WallofLimbs.jpg"},
{Name:"Waste Not", Cost:"1B", Color:["B"], Rarity:"R", Type:["E"], Rating:"6", Sort:"", Set:"M15", Number:"122", Image:"/Images/M15/WasteNot.jpg"},
{Name:"Witch's Familiar", Cost:"2B", Color:["B"], Rarity:"C", Type:["C"], Rating:"3", Sort:"", Set:"M15", Number:"123", Image:"/Images/M15/WitchsFamiliar.jpg"},
{Name:"Xathrid Slyblade", Cost:"2B", Color:["B"], Rarity:"U", Type:["C"], Rating:"8", Sort:"", Set:"M15", Number:"124", Image:"/Images/M15/XathridSlyblade.jpg"},
{Name:"Zof Shade", Cost:"3B", Color:["B"], Rarity:"C", Type:["C"], Rating:"6", Sort:"", Set:"M15", Number:"125", Image:"/Images/M15/ZofShade.jpg"},
{Name:"Act on Impulse", Cost:"2R", Color:["R"], Rarity:"U", Type:["S"], Rating:"7", Sort:"", Set:"M15", Number:"126", Image:"/Images/M15/ActonImpulse.jpg"},
{Name:"Aggressive Mining", Cost:"3R", Color:["R"], Rarity:"R", Type:["E"], Rating:"5", Sort:"", Set:"M15", Number:"127", Image:"/Images/M15/AggressiveMining.jpg"},
{Name:"Altac Bloodseeker", Cost:"1R", Color:["R"], Rarity:"U", Type:["C"], Rating:"6", Sort:"", Set:"M15", Number:"128", Image:"/Images/M15/AltacBloodseeker.jpg"},
{Name:"Belligerent Sliver", Cost:"2R", Color:["R"], Rarity:"U", Type:["C"], Rating:"6", Sort:"", Set:"M15", Number:"129", Image:"/Images/M15/BelligerentSliver.jpg"},
{Name:"Blastfire Bolt", Cost:"5R", Color:["R"], Rarity:"C", Type:["I"], Rating:"4", Sort:"", Set:"M15", Number:"130", Image:"/Images/M15/BlastfireBolt.jpg"},
{Name:"Borderland Marauder", Cost:"1R", Color:["R"], Rarity:"C", Type:["C"], Rating:"6", Sort:"", Set:"M15", Number:"131", Image:"/Images/M15/BorderlandMarauder.jpg"},
{Name:"Brood Keeper", Cost:"3R", Color:["R"], Rarity:"U", Type:["C"], Rating:"6", Sort:"", Set:"M15", Number:"132", Image:"/Images/M15/BroodKeeper.jpg"},
{Name:"Burning Anger", Cost:"4R", Color:["R"], Rarity:"R", Type:["E"], Rating:"5", Sort:"", Set:"M15", Number:"133", Image:"/Images/M15/BurningAnger.jpg"},
{Name:"Chandra, Pyromaster", Cost:"2RR", Color:["R"], Rarity:"M", Type:["P"], Rating:"10", Sort:"", Set:"M15", Number:"134", Image:"/Images/M15/Chandra--Pyromaster.jpg"},
{Name:"Circle of Flame", Cost:"1R", Color:["R"], Rarity:"U", Type:["E"], Rating:"6", Sort:"", Set:"M15", Number:"135", Image:"/Images/M15/CircleofFlame.jpg"},
{Name:"Clear a Path", Cost:"0R", Color:["R"], Rarity:"C", Type:["S"], Rating:"3", Sort:"", Set:"M15", Number:"136", Image:"/Images/M15/ClearaPath.jpg"},
{Name:"Cone of Flame", Cost:"3RR", Color:["R"], Rarity:"U", Type:["S"], Rating:"6", Sort:"", Set:"M15", Number:"137", Image:"/Images/M15/ConeofFlame.jpg"},
{Name:"Crowd's Favor", Cost:"0R", Color:["R"], Rarity:"C", Type:["I"], Rating:"5", Sort:"", Set:"M15", Number:"138", Image:"/Images/M15/CrowdsFavor.jpg"},
{Name:"Crucible of Fire", Cost:"3R", Color:["R"], Rarity:"R", Type:["E"], Rating:"4", Sort:"", Set:"M15", Number:"139", Image:"/Images/M15/CrucibleofFire.jpg"},
{Name:"Forge Devil", Cost:"0R", Color:["R"], Rarity:"C", Type:["C"], Rating:"6", Sort:"", Set:"M15", Number:"140", Image:"/Images/M15/ForgeDevil.jpg"},
{Name:"Foundry Street Denizen", Cost:"0R", Color:["R"], Rarity:"C", Type:["C"], Rating:"4", Sort:"", Set:"M15", Number:"141", Image:"/Images/M15/FoundryStreetDenizen.jpg"},
{Name:"Frenzied Goblin", Cost:"0R", Color:["R"], Rarity:"U", Type:["C"], Rating:"7", Sort:"", Set:"M15", Number:"142", Image:"/Images/M15/FrenziedGoblin.jpg"},
{Name:"Generator Servant", Cost:"1R", Color:["R"], Rarity:"C", Type:["C"], Rating:"6", Sort:"", Set:"M15", Number:"143", Image:"/Images/M15/GeneratorServant.jpg"},
{Name:"Goblin Kaboomist", Cost:"1R", Color:["R"], Rarity:"R", Type:["C"], Rating:"8", Sort:"", Set:"M15", Number:"144", Image:"/Images/M15/GoblinKaboomist.jpg"},
{Name:"Goblin Rabblemaster", Cost:"2R", Color:["R"], Rarity:"R", Type:["C"], Rating:"9", Sort:"", Set:"M15", Number:"145", Image:"/Images/M15/GoblinRabblemaster.jpg"},
{Name:"Goblin Roughrider", Cost:"2R", Color:["R"], Rarity:"C", Type:["C"], Rating:"6", Sort:"", Set:"M15", Number:"146", Image:"/Images/M15/GoblinRoughrider.jpg"},
{Name:"Hammerhand", Cost:"0R", Color:["R"], Rarity:"C", Type:["E"], Rating:"5", Sort:"", Set:"M15", Number:"147", Image:"/Images/M15/Hammerhand.jpg"},
{Name:"Heat Ray", Cost:"0R", Color:["R"], Rarity:"U", Type:["I"], Rating:"7", Sort:"", Set:"M15", Number:"148", Image:"/Images/M15/HeatRay.jpg"},
{Name:"Hoarding Dragon", Cost:"3RR", Color:["R"], Rarity:"R", Type:["C"], Rating:"8", Sort:"", Set:"M15", Number:"149", Image:"/Images/M15/HoardingDragon.jpg"},
{Name:"Inferno Fist", Cost:"1R", Color:["R"], Rarity:"C", Type:["E"], Rating:"7", Sort:"", Set:"M15", Number:"150", Image:"/Images/M15/InfernoFist.jpg"},
{Name:"Kird Chieftain", Cost:"3R", Color:["R"], Rarity:"U", Type:["C"], Rating:"5", Sort:"", Set:"M15", Number:"151", Image:"/Images/M15/KirdChieftain.jpg"},
{Name:"Krenko's Enforcer", Cost:"1RR", Color:["R"], Rarity:"C", Type:["C"], Rating:"6", Sort:"", Set:"M15", Number:"152", Image:"/Images/M15/KrenkosEnforcer.jpg"},
{Name:"Kurkesh, Onakke Ancient", Cost:"2RR", Color:["R"], Rarity:"R", Type:["C"], Rating:"6", Sort:"", Set:"M15", Number:"153", Image:"/Images/M15/Kurkesh--OnakkeAncient.jpg"},
{Name:"Lava Axe", Cost:"4R", Color:["R"], Rarity:"C", Type:["S"], Rating:"3", Sort:"", Set:"M15", Number:"154", Image:"/Images/M15/LavaAxe.jpg"},
{Name:"Lightning Strike", Cost:"1R", Color:["R"], Rarity:"C", Type:["I"], Rating:"8", Sort:"", Set:"M15", Number:"155", Image:"/Images/M15/LightningStrike.jpg"},
{Name:"Might Makes Right", Cost:"5R", Color:["R"], Rarity:"U", Type:["E"], Rating:"5", Sort:"", Set:"M15", Number:"156", Image:"/Images/M15/MightMakesRight.jpg"},
{Name:"Miner's Bane", Cost:"4RR", Color:["R"], Rarity:"C", Type:["C"], Rating:"6", Sort:"", Set:"M15", Number:"157", Image:"/Images/M15/MinersBane.jpg"},
{Name:"Paragon of Fierce Defiance", Cost:"3R", Color:["R"], Rarity:"U", Type:["C"], Rating:"5", Sort:"", Set:"M15", Number:"158", Image:"/Images/M15/ParagonofFierceDefiance.jpg"},
{Name:"Rummaging Goblin", Cost:"2R", Color:["R"], Rarity:"C", Type:["C"], Rating:"3", Sort:"", Set:"M15", Number:"159", Image:"/Images/M15/RummagingGoblin.jpg"},
{Name:"Scrapyard Mongrel", Cost:"3R", Color:["R"], Rarity:"C", Type:["C"], Rating:"4", Sort:"", Set:"M15", Number:"160", Image:"/Images/M15/ScrapyardMongrel.jpg"},
{Name:"Shrapnel Blast", Cost:"1R", Color:["R"], Rarity:"U", Type:["I"], Rating:"4", Sort:"", Set:"M15", Number:"161", Image:"/Images/M15/ShrapnelBlast.jpg"},
{Name:"Siege Dragon", Cost:"5RR", Color:["R"], Rarity:"R", Type:["C"], Rating:"8", Sort:"", Set:"M15", Number:"162", Image:"/Images/M15/SiegeDragon.jpg"},
{Name:"Soul of Shandalar", Cost:"4RR", Color:["R"], Rarity:"M", Type:["C"], Rating:"9", Sort:"", Set:"M15", Number:"163", Image:"/Images/M15/SoulofShandalar.jpg"},
{Name:"Stoke the Flames", Cost:"2RR", Color:["R"], Rarity:"U", Type:["I"], Rating:"8", Sort:"", Set:"M15", Number:"164", Image:"/Images/M15/StoketheFlames.jpg"},
{Name:"Thundering Giant", Cost:"3RR", Color:["R"], Rarity:"C", Type:["C"], Rating:"7", Sort:"", Set:"M15", Number:"165", Image:"/Images/M15/ThunderingGiant.jpg"},
{Name:"Torch Fiend", Cost:"1R", Color:["R"], Rarity:"C", Type:["C"], Rating:"5", Sort:"", Set:"M15", Number:"166", Image:"/Images/M15/TorchFiend.jpg"},
{Name:"Wall of Fire", Cost:"1RR", Color:["R"], Rarity:"C", Type:["C"], Rating:"5", Sort:"", Set:"M15", Number:"167", Image:"/Images/M15/WallofFire.jpg"},
{Name:"Ancient Silverback", Cost:"4GG", Color:["G"], Rarity:"U", Type:["C"], Rating:"7", Sort:"", Set:"M15", Number:"168", Image:"/Images/M15/AncientSilverback.jpg"},
{Name:"Back to Nature", Cost:"1G", Color:["G"], Rarity:"U", Type:["I"], Rating:"6", Sort:"", Set:"M15", Number:"169", Image:"/Images/M15/BacktoNature.jpg"},
{Name:"Carnivorous Moss-Beast", Cost:"4GG", Color:["G"], Rarity:"C", Type:["C"], Rating:"5", Sort:"", Set:"M15", Number:"170", Image:"/Images/M15/CarnivorousMoss-Beast.jpg"},
{Name:"Charging Rhino", Cost:"3GG", Color:["G"], Rarity:"C", Type:["C"], Rating:"6", Sort:"", Set:"M15", Number:"171", Image:"/Images/M15/ChargingRhino.jpg"},
{Name:"Chord of Calling", Cost:"0GGG", Color:["G"], Rarity:"R", Type:["I"], Rating:"8", Sort:"", Set:"M15", Number:"172", Image:"/Images/M15/ChordofCalling.jpg"},
{Name:"Elvish Mystic", Cost:"0G", Color:["G"], Rarity:"C", Type:["C"], Rating:"7", Sort:"", Set:"M15", Number:"173", Image:"/Images/M15/ElvishMystic.jpg"},
{Name:"Feral Incarnation", Cost:"8G", Color:["G"], Rarity:"U", Type:["S"], Rating:"6", Sort:"", Set:"M15", Number:"174", Image:"/Images/M15/FeralIncarnation.jpg"},
{Name:"Gather Courage", Cost:"0G", Color:["G"], Rarity:"U", Type:["I"], Rating:"5", Sort:"", Set:"M15", Number:"175", Image:"/Images/M15/GatherCourage.jpg"},
{Name:"Genesis Hydra", Cost:"0GG", Color:["G"], Rarity:"R", Type:["C"], Rating:"9", Sort:"", Set:"M15", Number:"176", Image:"/Images/M15/GenesisHydra.jpg"},
{Name:"Hornet Nest", Cost:"2G", Color:["G"], Rarity:"R", Type:["C"], Rating:"9", Sort:"", Set:"M15", Number:"177", Image:"/Images/M15/HornetNest.jpg"},
{Name:"Hornet Queen", Cost:"4GGG", Color:["G"], Rarity:"R", Type:["C"], Rating:"9", Sort:"", Set:"M15", Number:"178", Image:"/Images/M15/HornetQueen.jpg"},
{Name:"Hunt the Weak", Cost:"3G", Color:["G"], Rarity:"C", Type:["S"], Rating:"5", Sort:"", Set:"M15", Number:"179", Image:"/Images/M15/HunttheWeak.jpg"},
{Name:"Hunter's Ambush", Cost:"2G", Color:["G"], Rarity:"C", Type:["I"], Rating:"6", Sort:"", Set:"M15", Number:"180", Image:"/Images/M15/HuntersAmbush.jpg"},
{Name:"Invasive Species", Cost:"2G", Color:["G"], Rarity:"C", Type:["C"], Rating:"4", Sort:"", Set:"M15", Number:"181", Image:"/Images/M15/InvasiveSpecies.jpg"},
{Name:"Kalonian Twingrove", Cost:"5G", Color:["G"], Rarity:"R", Type:["C"], Rating:"9", Sort:"", Set:"M15", Number:"182", Image:"/Images/M15/KalonianTwingrove.jpg"},
{Name:"Life's Legacy", Cost:"1G", Color:["G"], Rarity:"R", Type:["S"], Rating:"7", Sort:"", Set:"M15", Number:"183", Image:"/Images/M15/LifesLegacy.jpg"},
{Name:"Living Totem", Cost:"3G", Color:["G"], Rarity:"C", Type:["C"], Rating:"6", Sort:"", Set:"M15", Number:"184", Image:"/Images/M15/LivingTotem.jpg"},
{Name:"Naturalize", Cost:"1G", Color:["G"], Rarity:"C", Type:["I"], Rating:"4", Sort:"", Set:"M15", Number:"185", Image:"/Images/M15/Naturalize.jpg"},
{Name:"Netcaster Spider", Cost:"2G", Color:["G"], Rarity:"C", Type:["C"], Rating:"5", Sort:"", Set:"M15", Number:"186", Image:"/Images/M15/NetcasterSpider.jpg"},
{Name:"Nissa, Worldwaker", Cost:"3GG", Color:["G"], Rarity:"M", Type:["P"], Rating:"10", Sort:"", Set:"M15", Number:"187", Image:"/Images/M15/Nissa--Worldwaker.jpg"},
{Name:"Nissa's Expedition", Cost:"4G", Color:["G"], Rarity:"U", Type:["S"], Rating:"7", Sort:"", Set:"M15", Number:"188", Image:"/Images/M15/NissasExpedition.jpg"},
{Name:"Overwhelm", Cost:"5GG", Color:["G"], Rarity:"U", Type:["S"], Rating:"6", Sort:"", Set:"M15", Number:"189", Image:"/Images/M15/Overwhelm.jpg"},
{Name:"Paragon of Eternal Wilds", Cost:"3G", Color:["G"], Rarity:"U", Type:["C"], Rating:"7", Sort:"", Set:"M15", Number:"190", Image:"/Images/M15/ParagonofEternalWilds.jpg"},
{Name:"Phytotitan", Cost:"4GG", Color:["G"], Rarity:"R", Type:["C"], Rating:"10", Sort:"", Set:"M15", Number:"191", Image:"/Images/M15/Phytotitan.jpg"},
{Name:"Plummet", Cost:"1G", Color:["G"], Rarity:"C", Type:["I"], Rating:"4", Sort:"", Set:"M15", Number:"192", Image:"/Images/M15/Plummet.jpg"},
{Name:"Ranger's Guile", Cost:"0G", Color:["G"], Rarity:"C", Type:["I"], Rating:"6", Sort:"", Set:"M15", Number:"193", Image:"/Images/M15/RangersGuile.jpg"},
{Name:"Reclamation Sage", Cost:"2G", Color:["G"], Rarity:"U", Type:["C"], Rating:"6", Sort:"", Set:"M15", Number:"194", Image:"/Images/M15/ReclamationSage.jpg"},
{Name:"Restock", Cost:"3GG", Color:["G"], Rarity:"U", Type:["S"], Rating:"5", Sort:"", Set:"M15", Number:"195", Image:"/Images/M15/Restock.jpg"},
{Name:"Roaring Primadox", Cost:"3G", Color:["G"], Rarity:"U", Type:["C"], Rating:"4", Sort:"", Set:"M15", Number:"196", Image:"/Images/M15/RoaringPrimadox.jpg"},
{Name:"Runeclaw Bear", Cost:"1G", Color:["G"], Rarity:"C", Type:["C"], Rating:"4", Sort:"", Set:"M15", Number:"197", Image:"/Images/M15/RuneclawBear.jpg"},
{Name:"Satyr Wayfinder", Cost:"1G", Color:["G"], Rarity:"C", Type:["C"], Rating:"4", Sort:"", Set:"M15", Number:"198", Image:"/Images/M15/SatyrWayfinder.jpg"},
{Name:"Shaman of Spring", Cost:"3G", Color:["G"], Rarity:"C", Type:["C"], Rating:"5", Sort:"", Set:"M15", Number:"199", Image:"/Images/M15/ShamanofSpring.jpg"},
{Name:"Siege Wurm", Cost:"5GG", Color:["G"], Rarity:"C", Type:["C"], Rating:"6", Sort:"", Set:"M15", Number:"200", Image:"/Images/M15/SiegeWurm.jpg"},
{Name:"Soul of Zendikar", Cost:"4GG", Color:["G"], Rarity:"M", Type:["C"], Rating:"10", Sort:"", Set:"M15", Number:"201", Image:"/Images/M15/SoulofZendikar.jpg"},
{Name:"Sunblade Elf", Cost:"0G", Color:["G"], Rarity:"U", Type:["C"], Rating:"6", Sort:"", Set:"M15", Number:"202", Image:"/Images/M15/SunbladeElf.jpg"},
{Name:"Titanic Growth", Cost:"1G", Color:["G"], Rarity:"C", Type:["I"], Rating:"6", Sort:"", Set:"M15", Number:"203", Image:"/Images/M15/TitanicGrowth.jpg"},
{Name:"Undergrowth Scavenger", Cost:"3G", Color:["G"], Rarity:"C", Type:["C"], Rating:"4", Sort:"", Set:"M15", Number:"204", Image:"/Images/M15/UndergrowthScavenger.jpg"},
{Name:"Venom Sliver", Cost:"1G", Color:["G"], Rarity:"U", Type:["C"], Rating:"6", Sort:"", Set:"M15", Number:"205", Image:"/Images/M15/VenomSliver.jpg"},
{Name:"Verdant Haven", Cost:"2G", Color:["G"], Rarity:"C", Type:["E"], Rating:"5", Sort:"", Set:"M15", Number:"206", Image:"/Images/M15/VerdantHaven.jpg"},
{Name:"Vineweft", Cost:"0G", Color:["G"], Rarity:"C", Type:["E"], Rating:"6", Sort:"", Set:"M15", Number:"207", Image:"/Images/M15/Vineweft.jpg"},
{Name:"Wall of Mulch", Cost:"1G", Color:["G"], Rarity:"U", Type:["C"], Rating:"7", Sort:"", Set:"M15", Number:"208", Image:"/Images/M15/WallofMulch.jpg"},
{Name:"Yisan, the Wanderer Bard", Cost:"2G", Color:["G"], Rarity:"R", Type:["C"], Rating:"7", Sort:"", Set:"M15", Number:"209", Image:"/Images/M15/Yisan--theWandererBard.jpg"},
{Name:"Garruk, Apex Predator", Cost:"5BG", Color:["B","G"], Rarity:"M", Type:["P"], Rating:"9", Sort:"", Set:"M15", Number:"210", Image:"/Images/M15/Garruk--ApexPredator.jpg"},
{Name:"Sliver Hivelord", Cost:"0WUBRG", Color:["W","U","B","R","G"], Rarity:"M", Type:["C"], Rating:"4", Sort:"", Set:"M15", Number:"211", Image:"/Images/M15/SliverHivelord.jpg"},
{Name:"Avarice Amulet", Cost:"4", Color:["C"], Rarity:"R", Type:["A"], Rating:"6", Sort:"", Set:"M15", Number:"212", Image:"/Images/M15/AvariceAmulet.jpg"},
{Name:"Brawler's Plate", Cost:"3", Color:["C"], Rarity:"U", Type:["A"], Rating:"5", Sort:"", Set:"M15", Number:"213", Image:"/Images/M15/BrawlersPlate.jpg"},
{Name:"Bronze Sable", Cost:"2", Color:["C"], Rarity:"C", Type:["C","A"], Rating:"4", Sort:"", Set:"M15", Number:"214", Image:"/Images/M15/BronzeSable.jpg"},
{Name:"The Chain Veil", Cost:"4", Color:["C"], Rarity:"M", Type:["A"], Rating:"3", Sort:"", Set:"M15", Number:"215", Image:"/Images/M15/TheChainVeil.jpg"},
{Name:"Gargoyle Sentinel", Cost:"3", Color:["C"], Rarity:"U", Type:["C","A"], Rating:"5", Sort:"", Set:"M15", Number:"216", Image:"/Images/M15/GargoyleSentinel.jpg"},
{Name:"Grindclock", Cost:"2", Color:["C"], Rarity:"R", Type:["A"], Rating:"6", Sort:"", Set:"M15", Number:"217", Image:"/Images/M15/Grindclock.jpg"},
{Name:"Haunted Plate Mail", Cost:"4", Color:["C"], Rarity:"R", Type:["A"], Rating:"7", Sort:"", Set:"M15", Number:"218", Image:"/Images/M15/HauntedPlateMail.jpg"},
{Name:"Hot Soup", Cost:"1", Color:["C"], Rarity:"U", Type:["A"], Rating:"5", Sort:"", Set:"M15", Number:"219", Image:"/Images/M15/HotSoup.jpg"},
{Name:"Juggernaut", Cost:"4", Color:["C"], Rarity:"U", Type:["C","A"], Rating:"7", Sort:"", Set:"M15", Number:"220", Image:"/Images/M15/Juggernaut.jpg"},
{Name:"Meteorite", Cost:"5", Color:["C"], Rarity:"U", Type:["A"], Rating:"4", Sort:"", Set:"M15", Number:"221", Image:"/Images/M15/Meteorite.jpg"},
{Name:"Obelisk of Urd", Cost:"6", Color:["C"], Rarity:"R", Type:["A"], Rating:"4", Sort:"", Set:"M15", Number:"222", Image:"/Images/M15/ObeliskofUrd.jpg"},
{Name:"Ornithopter", Cost:"0", Color:["C"], Rarity:"C", Type:["C","A"], Rating:"6", Sort:"", Set:"M15", Number:"223", Image:"/Images/M15/Ornithopter.jpg"},
{Name:"Perilous Vault", Cost:"4", Color:["C"], Rarity:"M", Type:["A"], Rating:"7", Sort:"", Set:"M15", Number:"224", Image:"/Images/M15/PerilousVault.jpg"},
{Name:"Phyrexian Revoker", Cost:"2", Color:["C"], Rarity:"R", Type:["C","A"], Rating:"6", Sort:"", Set:"M15", Number:"225", Image:"/Images/M15/PhyrexianRevoker.jpg"},
{Name:"Profane Memento", Cost:"1", Color:["C"], Rarity:"U", Type:["A"], Rating:"4", Sort:"", Set:"M15", Number:"226", Image:"/Images/M15/ProfaneMemento.jpg"},
{Name:"Rogue's Gloves", Cost:"2", Color:["C"], Rarity:"U", Type:["A"], Rating:"6", Sort:"", Set:"M15", Number:"227", Image:"/Images/M15/RoguesGloves.jpg"},
{Name:"Sacred Armory", Cost:"2", Color:["C"], Rarity:"U", Type:["A"], Rating:"5", Sort:"", Set:"M15", Number:"228", Image:"/Images/M15/SacredArmory.jpg"},
{Name:"Scuttling Doom Engine", Cost:"6", Color:["C"], Rarity:"R", Type:["C","A"], Rating:"9", Sort:"", Set:"M15", Number:"229", Image:"/Images/M15/ScuttlingDoomEngine.jpg"},
{Name:"Shield of the Avatar", Cost:"1", Color:["C"], Rarity:"R", Type:["A"], Rating:"7", Sort:"", Set:"M15", Number:"230", Image:"/Images/M15/ShieldoftheAvatar.jpg"},
{Name:"Soul of New Phyrexia", Cost:"6", Color:["C"], Rarity:"M", Type:["C","A"], Rating:"10", Sort:"", Set:"M15", Number:"231", Image:"/Images/M15/SoulofNewPhyrexia.jpg"},
{Name:"Staff of the Death Magus", Cost:"3", Color:["B"], Rarity:"U", Type:["A"], Rating:"2", Sort:"", Set:"M15", Number:"232", Image:"/Images/M15/StaffoftheDeathMagus.jpg"},
{Name:"Staff of the Flame Magus", Cost:"3", Color:["R"], Rarity:"U", Type:["A"], Rating:"2", Sort:"", Set:"M15", Number:"233", Image:"/Images/M15/StaffoftheFlameMagus.jpg"},
{Name:"Staff of the Mind Magus", Cost:"3", Color:["U"], Rarity:"U", Type:["A"], Rating:"2", Sort:"", Set:"M15", Number:"234", Image:"/Images/M15/StaffoftheMindMagus.jpg"},
{Name:"Staff of the Sun Magus", Cost:"3", Color:["W"], Rarity:"U", Type:["A"], Rating:"2", Sort:"", Set:"M15", Number:"235", Image:"/Images/M15/StaffoftheSunMagus.jpg"},
{Name:"Staff of the Wild Magus", Cost:"3", Color:["G"], Rarity:"U", Type:["A"], Rating:"2", Sort:"", Set:"M15", Number:"236", Image:"/Images/M15/StaffoftheWildMagus.jpg"},
{Name:"Tormod's Crypt", Cost:"0", Color:["C"], Rarity:"U", Type:["A"], Rating:"1", Sort:"", Set:"M15", Number:"237", Image:"/Images/M15/TormodsCrypt.jpg"},
{Name:"Tyrant's Machine", Cost:"2", Color:["C"], Rarity:"C", Type:["A"], Rating:"4", Sort:"", Set:"M15", Number:"238", Image:"/Images/M15/TyrantsMachine.jpg"},
{Name:"Will-Forged Golem", Cost:"6", Color:["C"], Rarity:"C", Type:["C","A"], Rating:"3", Sort:"", Set:"M15", Number:"239", Image:"/Images/M15/Will-ForgedGolem.jpg"},
{Name:"Battlefield Forge", Cost:"0", Color:["W","R"], Rarity:"R", Type:["L"], Rating:"6", Sort:"", Set:"M15", Number:"240", Image:"/Images/M15/BattlefieldForge.jpg"},
{Name:"Caves of Koilos", Cost:"0", Color:["W","B"], Rarity:"R", Type:["L"], Rating:"6", Sort:"", Set:"M15", Number:"241", Image:"/Images/M15/CavesofKoilos.jpg"},
{Name:"Darksteel Citadel", Cost:"0", Color:["C"], Rarity:"U", Type:["L"], Rating:"3", Sort:"", Set:"M15", Number:"242", Image:"/Images/M15/DarksteelCitadel.jpg"},
{Name:"Evolving Wilds", Cost:"0", Color:["C"], Rarity:"C", Type:["L"], Rating:"6", Sort:"", Set:"M15", Number:"243", Image:"/Images/M15/EvolvingWilds.jpg"},
{Name:"Llanowar Wastes", Cost:"0", Color:["B","G"], Rarity:"R", Type:["L"], Rating:"6", Sort:"", Set:"M15", Number:"244", Image:"/Images/M15/LlanowarWastes.jpg"},
{Name:"Radiant Fountain", Cost:"0", Color:["C"], Rarity:"C", Type:["L"], Rating:"3", Sort:"", Set:"M15", Number:"245", Image:"/Images/M15/RadiantFountain.jpg"},
{Name:"Shivan Reef", Cost:"0", Color:["U","R"], Rarity:"R", Type:["L"], Rating:"6", Sort:"", Set:"M15", Number:"246", Image:"/Images/M15/ShivanReef.jpg"},
{Name:"Sliver Hive", Cost:"0", Color:["C"], Rarity:"R", Type:["L"], Rating:"3", Sort:"", Set:"M15", Number:"247", Image:"/Images/M15/SliverHive.jpg"},
{Name:"Urborg, Tomb of Yawgmoth", Cost:"0", Color:["B"], Rarity:"R", Type:["L"], Rating:"6", Sort:"", Set:"M15", Number:"248", Image:"/Images/M15/Urborg--TombofYawgmoth.jpg"},
{Name:"Yavimaya Coast", Cost:"0", Color:["G","U"], Rarity:"R", Type:["L"], Rating:"6", Sort:"", Set:"M15", Number:"249", Image:"/Images/M15/YavimayaCoast.jpg"},
];