var OGW = [
{Name:"Deceiver of Form", Cost:"7", Color:["C"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"OGW", Number:"1", Image:"/Images/OGW/DeceiverofForm.jpg", ReverseImage:"/Images/OGW/EldraziMimic.jpg"},
{Name:"Eldrazi Mimic", Cost:"2", Color:["C"], Rarity:"R", Type:["C"], Rating:"6", Sort:"1", Set:"OGW", Number:"2", Image:"/Images/OGW/EldraziMimic.jpg"},
{Name:"Endbringer", Cost:"6", Color:["C"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"OGW", Number:"3", Image:"/Images/OGW/Endbringer.jpg"},
{Name:"Kozilek, the Great Distortion", Cost:"10", Color:["C"], Rarity:"M", Type:["C"], Rating:"8", Sort:"1", Set:"OGW", Number:"4", Image:"/Images/OGW/Kozilek--theGreatDistortion.jpg"},
{Name:"Kozilek's Pathfinder", Cost:"6", Color:["C"], Rarity:"C", Type:["C"], Rating:"2", Sort:"1", Set:"OGW", Number:"5", Image:"/Images/OGW/KozileksPathfinder.jpg"},
{Name:"Matter Reshaper", Cost:"3", Color:["C"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"OGW", Number:"6", Image:"/Images/OGW/MatterReshaper.jpg"},
{Name:"Reality Smasher", Cost:"5", Color:["C"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"OGW", Number:"7", Image:"/Images/OGW/RealitySmasher.jpg"},
{Name:"Spatial Contortion", Cost:"2", Color:["C"], Rarity:"U", Type:["I"], Rating:"7", Sort:"1", Set:"OGW", Number:"8", Image:"/Images/OGW/SpatialContortion.jpg"},
{Name:"Thought-Knot Seer", Cost:"4", Color:["C"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"OGW", Number:"9", Image:"/Images/OGW/Thought-KnotSeer.jpg"},
{Name:"Walker of the Wastes", Cost:"5", Color:["C"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"OGW", Number:"10", Image:"/Images/OGW/WalkeroftheWastes.jpg"},
{Name:"Warden of Geometries", Cost:"4", Color:["C"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"OGW", Number:"11", Image:"/Images/OGW/WardenofGeometries.jpg"},
{Name:"Warping Wail", Cost:"2", Color:["C"], Rarity:"U", Type:["I"], Rating:"7", Sort:"1", Set:"OGW", Number:"12", Image:"/Images/OGW/WarpingWail.jpg"},
{Name:"Eldrazi Displacer", Cost:"2W", Color:["W"], Rarity:"R", Type:["C"], Rating:"6", Sort:"1", Set:"OGW", Number:"13", Image:"/Images/OGW/EldraziDisplacer.jpg"},
{Name:"Affa Protector", Cost:"2W", Color:["W"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"OGW", Number:"14", Image:"/Images/OGW/AffaProtector.jpg"},
{Name:"Allied Reinforcements", Cost:"3W", Color:["W"], Rarity:"U", Type:["S"], Rating:"5", Sort:"1", Set:"OGW", Number:"15", Image:"/Images/OGW/AlliedReinforcements.jpg"},
{Name:"Call the Gatewatch", Cost:"2W", Color:["W"], Rarity:"R", Type:["S"], Rating:"5", Sort:"1", Set:"OGW", Number:"16", Image:"/Images/OGW/CalltheGatewatch.jpg"},
{Name:"Dazzling Reflection", Cost:"1W", Color:["W"], Rarity:"C", Type:["I"], Rating:"1", Sort:"1", Set:"OGW", Number:"17", Image:"/Images/OGW/DazzlingReflection.jpg"},
{Name:"Expedition Raptor", Cost:"3WW", Color:["W"], Rarity:"C", Type:["C"], Rating:"2", Sort:"1", Set:"OGW", Number:"18", Image:"/Images/OGW/ExpeditionRaptor.jpg"},
{Name:"General Tazri", Cost:"4W", Color:["W"], Rarity:"M", Type:["C"], Rating:"7", Sort:"1", Set:"OGW", Number:"19", Image:"/Images/OGW/GeneralTazri.jpg"},
{Name:"Immolating Glare", Cost:"1W", Color:["W"], Rarity:"U", Type:["I"], Rating:"7", Sort:"1", Set:"OGW", Number:"20", Image:"/Images/OGW/ImmolatingGlare.jpg"},
{Name:"Iona's Blessing", Cost:"3W", Color:["W"], Rarity:"U", Type:["E"], Rating:"3", Sort:"1", Set:"OGW", Number:"21", Image:"/Images/OGW/IonasBlessing.jpg"},
{Name:"Isolation Zone", Cost:"2WW", Color:["W"], Rarity:"C", Type:["E"], Rating:"6", Sort:"1", Set:"OGW", Number:"22", Image:"/Images/OGW/IsolationZone.jpg"},
{Name:"Kor Scythemaster", Cost:"2W", Color:["W"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"OGW", Number:"23", Image:"/Images/OGW/KorScythemaster.jpg"},
{Name:"Kor Sky Climber", Cost:"2W", Color:["W"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"OGW", Number:"24", Image:"/Images/OGW/KorSkyClimber.jpg"},
{Name:"Linvala, the Preserver", Cost:"4WW", Color:["W"], Rarity:"M", Type:["C"], Rating:"8", Sort:"1", Set:"OGW", Number:"25", Image:"/Images/OGW/Linvala--thePreserver.jpg"},
{Name:"Make a Stand", Cost:"2W", Color:["W"], Rarity:"U", Type:["I"], Rating:"5", Sort:"1", Set:"OGW", Number:"26", Image:"/Images/OGW/MakeaStand.jpg"},
{Name:"Makindi Aeronaut", Cost:"1W", Color:["W"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"OGW", Number:"27", Image:"/Images/OGW/MakindiAeronaut.jpg"},
{Name:"Mighty Leap", Cost:"1W", Color:["W"], Rarity:"C", Type:["I"], Rating:"3", Sort:"1", Set:"OGW", Number:"28", Image:"/Images/OGW/MightyLeap.jpg"},
{Name:"Munda's Vanguard", Cost:"4W", Color:["W"], Rarity:"R", Type:["C"], Rating:"6", Sort:"1", Set:"OGW", Number:"29", Image:"/Images/OGW/MundasVanguard.jpg"},
{Name:"Oath of Gideon", Cost:"2W", Color:["W"], Rarity:"R", Type:["E"], Rating:"6", Sort:"1", Set:"OGW", Number:"30", Image:"/Images/OGW/OathofGideon.jpg"},
{Name:"Ondu War Cleric", Cost:"1W", Color:["W"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"OGW", Number:"31", Image:"/Images/OGW/OnduWarCleric.jpg"},
{Name:"Relief Captain", Cost:"2WW", Color:["W"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"OGW", Number:"32", Image:"/Images/OGW/ReliefCaptain.jpg"},
{Name:"Searing Light", Cost:"0W", Color:["W"], Rarity:"C", Type:["I"], Rating:"2", Sort:"1", Set:"OGW", Number:"33", Image:"/Images/OGW/SearingLight.jpg"},
{Name:"Shoulder to Shoulder", Cost:"2W", Color:["W"], Rarity:"C", Type:["S"], Rating:"2", Sort:"1", Set:"OGW", Number:"34", Image:"/Images/OGW/ShouldertoShoulder.jpg"},
{Name:"Spawnbinder Mage", Cost:"3W", Color:["W"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"OGW", Number:"35", Image:"/Images/OGW/SpawnbinderMage.jpg"},
{Name:"Steppe Glider", Cost:"4W", Color:["W"], Rarity:"U", Type:["C"], Rating:"3", Sort:"1", Set:"OGW", Number:"36", Image:"/Images/OGW/SteppeGlider.jpg"},
{Name:"Stone Haven Outfitter", Cost:"1W", Color:["W"], Rarity:"R", Type:["C"], Rating:"6", Sort:"1", Set:"OGW", Number:"37", Image:"/Images/OGW/StoneHavenOutfitter.jpg"},
{Name:"Stoneforge Acolyte", Cost:"0W", Color:["W"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"OGW", Number:"38", Image:"/Images/OGW/StoneforgeAcolyte.jpg"},
{Name:"Wall of Resurgence", Cost:"2W", Color:["W"], Rarity:"U", Type:["C"], Rating:"7", Sort:"1", Set:"OGW", Number:"39", Image:"/Images/OGW/WallofResurgence.jpg"},
{Name:"Abstruse Interference", Cost:"2U", Color:["U"], Rarity:"C", Type:["I"], Rating:"4", Sort:"1", Set:"OGW", Number:"40", Image:"/Images/OGW/AbstruseInterference.jpg"},
{Name:"Blinding Drone", Cost:"1U", Color:["U"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"OGW", Number:"41", Image:"/Images/OGW/BlindingDrone.jpg"},
{Name:"Cultivator Drone", Cost:"2U", Color:["U"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"OGW", Number:"42", Image:"/Images/OGW/CultivatorDrone.jpg"},
{Name:"Deepfathom Skulker", Cost:"5U", Color:["U"], Rarity:"R", Type:["C"], Rating:"6", Sort:"1", Set:"OGW", Number:"43", Image:"/Images/OGW/DeepfathomSkulker.jpg"},
{Name:"Dimensional Infiltrator", Cost:"1U", Color:["U"], Rarity:"R", Type:["C"], Rating:"6", Sort:"1", Set:"OGW", Number:"44", Image:"/Images/OGW/DimensionalInfiltrator.jpg"},
{Name:"Gravity Negator", Cost:"3U", Color:["U"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"OGW", Number:"45", Image:"/Images/OGW/GravityNegator.jpg"},
{Name:"Prophet of Distortion", Cost:"0U", Color:["U"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"OGW", Number:"46", Image:"/Images/OGW/ProphetofDistortion.jpg"},
{Name:"Slip Through Space", Cost:"0U", Color:["U"], Rarity:"C", Type:["S"], Rating:"3", Sort:"1", Set:"OGW", Number:"47", Image:"/Images/OGW/SlipThroughSpace.jpg"},
{Name:"Thought Harvester", Cost:"3U", Color:["U"], Rarity:"U", Type:["C"], Rating:"3", Sort:"1", Set:"OGW", Number:"48", Image:"/Images/OGW/ThoughtHarvester.jpg"},
{Name:"Void Shatter", Cost:"1UU", Color:["U"], Rarity:"U", Type:["I"], Rating:"4", Sort:"1", Set:"OGW", Number:"49", Image:"/Images/OGW/VoidShatter.jpg"},
{Name:"Ancient Crab", Cost:"1UU", Color:["U"], Rarity:"C", Type:["C"], Rating:"2", Sort:"1", Set:"OGW", Number:"50", Image:"/Images/OGW/AncientCrab.jpg"},
{Name:"Comparative Analysis", Cost:"3U", Color:["U"], Rarity:"C", Type:["I"], Rating:"4", Sort:"1", Set:"OGW", Number:"51", Image:"/Images/OGW/ComparativeAnalysis.jpg"},
{Name:"Containment Membrane", Cost:"2U", Color:["U"], Rarity:"C", Type:["E"], Rating:"4", Sort:"1", Set:"OGW", Number:"52", Image:"/Images/OGW/ContainmentMembrane.jpg"},
{Name:"Crush of Tentacles", Cost:"4UU", Color:["U"], Rarity:"M", Type:["S"], Rating:"7", Sort:"1", Set:"OGW", Number:"53", Image:"/Images/OGW/CrushofTentacles.jpg"},
{Name:"Cyclone Sire", Cost:"4U", Color:["U"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"OGW", Number:"54", Image:"/Images/OGW/CycloneSire.jpg"},
{Name:"Gift of Tusks", Cost:"0U", Color:["U"], Rarity:"U", Type:["I"], Rating:"7", Sort:"1", Set:"OGW", Number:"55", Image:"/Images/OGW/GiftofTusks.jpg"},
{Name:"Grip of the Roil", Cost:"2U", Color:["U"], Rarity:"U", Type:["I"], Rating:"5", Sort:"1", Set:"OGW", Number:"56", Image:"/Images/OGW/GripoftheRoil.jpg"},
{Name:"Hedron Alignment", Cost:"2U", Color:["U"], Rarity:"R", Type:["E"], Rating:"5", Sort:"1", Set:"OGW", Number:"57", Image:"/Images/OGW/HedronAlignment.jpg"},
{Name:"Jwar Isle Avenger", Cost:"4U", Color:["U"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"OGW", Number:"58", Image:"/Images/OGW/JwarIsleAvenger.jpg"},
{Name:"Negate", Cost:"1U", Color:["U"], Rarity:"C", Type:["I"], Rating:"3", Sort:"1", Set:"OGW", Number:"59", Image:"/Images/OGW/Negate.jpg"},
{Name:"Oath of Jace", Cost:"2U", Color:["U"], Rarity:"R", Type:["E"], Rating:"6", Sort:"1", Set:"OGW", Number:"60", Image:"/Images/OGW/OathofJace.jpg"},
{Name:"Overwhelming Denial", Cost:"2UU", Color:["U"], Rarity:"R", Type:["I"], Rating:"5", Sort:"1", Set:"OGW", Number:"61", Image:"/Images/OGW/OverwhelmingDenial.jpg"},
{Name:"Roiling Waters", Cost:"5UU", Color:["U"], Rarity:"U", Type:["S"], Rating:"4", Sort:"1", Set:"OGW", Number:"62", Image:"/Images/OGW/RoilingWaters.jpg"},
{Name:"Sphinx of the Final Word", Cost:"5UU", Color:["U"], Rarity:"M", Type:["C"], Rating:"9", Sort:"1", Set:"OGW", Number:"63", Image:"/Images/OGW/SphinxoftheFinalWord.jpg"},
{Name:"Sweep Away", Cost:"2U", Color:["U"], Rarity:"C", Type:["I"], Rating:"4", Sort:"1", Set:"OGW", Number:"64", Image:"/Images/OGW/SweepAway.jpg"},
{Name:"Umara Entangler", Cost:"1U", Color:["U"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"OGW", Number:"65", Image:"/Images/OGW/UmaraEntangler.jpg"},
{Name:"Unity of Purpose", Cost:"3U", Color:["U"], Rarity:"U", Type:["I"], Rating:"3", Sort:"1", Set:"OGW", Number:"66", Image:"/Images/OGW/UnityofPurpose.jpg"},
{Name:"Bearer of Silence", Cost:"1B", Color:["B"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"OGW", Number:"67", Image:"/Images/OGW/BearerofSilence.jpg"},
{Name:"Dread Defiler", Cost:"6B", Color:["B"], Rarity:"R", Type:["C"], Rating:"6", Sort:"1", Set:"OGW", Number:"68", Image:"/Images/OGW/DreadDefiler.jpg"},
{Name:"Essence Depleter", Cost:"2B", Color:["B"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"OGW", Number:"69", Image:"/Images/OGW/EssenceDepleter.jpg"},
{Name:"Flaying Tendrils", Cost:"1BB", Color:["B"], Rarity:"U", Type:["S"], Rating:"6", Sort:"1", Set:"OGW", Number:"70", Image:"/Images/OGW/FlayingTendrils.jpg"},
{Name:"Havoc Sower", Cost:"3B", Color:["B"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"OGW", Number:"71", Image:"/Images/OGW/HavocSower.jpg"},
{Name:"Inverter of Truth", Cost:"2BB", Color:["B"], Rarity:"M", Type:["C"], Rating:"8", Sort:"1", Set:"OGW", Number:"72", Image:"/Images/OGW/InverterofTruth.jpg"},
{Name:"Kozilek's Shrieker", Cost:"2B", Color:["B"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"OGW", Number:"73", Image:"/Images/OGW/KozileksShrieker.jpg"},
{Name:"Kozilek's Translator", Cost:"4B", Color:["B"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"OGW", Number:"74", Image:"/Images/OGW/KozileksTranslator.jpg"},
{Name:"Oblivion Strike", Cost:"3B", Color:["B"], Rarity:"C", Type:["S"], Rating:"7", Sort:"1", Set:"OGW", Number:"75", Image:"/Images/OGW/OblivionStrike.jpg"},
{Name:"Reaver Drone", Cost:"0B", Color:["B"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"OGW", Number:"76", Image:"/Images/OGW/ReaverDrone.jpg"},
{Name:"Sifter of Skulls", Cost:"3B", Color:["B"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"OGW", Number:"77", Image:"/Images/OGW/SifterofSkulls.jpg"},
{Name:"Sky Scourer", Cost:"1B", Color:["B"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"OGW", Number:"78", Image:"/Images/OGW/SkyScourer.jpg"},
{Name:"Slaughter Drone", Cost:"1B", Color:["B"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"OGW", Number:"79", Image:"/Images/OGW/SlaughterDrone.jpg"},
{Name:"Unnatural Endurance", Cost:"0B", Color:["B"], Rarity:"C", Type:["I"], Rating:"3", Sort:"1", Set:"OGW", Number:"80", Image:"/Images/OGW/UnnaturalEndurance.jpg"},
{Name:"Visions of Brutality", Cost:"1B", Color:["B"], Rarity:"U", Type:["E"], Rating:"4", Sort:"1", Set:"OGW", Number:"81", Image:"/Images/OGW/VisionsofBrutality.jpg"},
{Name:"Witness the End", Cost:"3B", Color:["B"], Rarity:"C", Type:["S"], Rating:"3", Sort:"1", Set:"OGW", Number:"82", Image:"/Images/OGW/WitnesstheEnd.jpg"},
{Name:"Corpse Churn", Cost:"1B", Color:["B"], Rarity:"C", Type:["I"], Rating:"3", Sort:"1", Set:"OGW", Number:"83", Image:"/Images/OGW/CorpseChurn.jpg"},
{Name:"Drana's Chosen", Cost:"3B", Color:["B"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"OGW", Number:"84", Image:"/Images/OGW/DranasChosen.jpg"},
{Name:"Grasp of Darkness", Cost:"0BB", Color:["B"], Rarity:"U", Type:["I"], Rating:"7", Sort:"1", Set:"OGW", Number:"85", Image:"/Images/OGW/GraspofDarkness.jpg"},
{Name:"Kalitas, Traitor of Ghet", Cost:"2BB", Color:["B"], Rarity:"M", Type:["C"], Rating:"9", Sort:"1", Set:"OGW", Number:"86", Image:"/Images/OGW/Kalitas--TraitorofGhet.jpg"},
{Name:"Malakir Soothsayer", Cost:"4B", Color:["B"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"OGW", Number:"87", Image:"/Images/OGW/MalakirSoothsayer.jpg"},
{Name:"Null Caller", Cost:"3B", Color:["B"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"OGW", Number:"88", Image:"/Images/OGW/NullCaller.jpg"},
{Name:"Remorseless Punishment", Cost:"3BB", Color:["B"], Rarity:"R", Type:["S"], Rating:"8", Sort:"1", Set:"OGW", Number:"89", Image:"/Images/OGW/RemorselessPunishment.jpg"},
{Name:"Tar Snare", Cost:"2B", Color:["B"], Rarity:"C", Type:["I"], Rating:"4", Sort:"1", Set:"OGW", Number:"90", Image:"/Images/OGW/TarSnare.jpg"},
{Name:"Untamed Hunger", Cost:"2B", Color:["B"], Rarity:"C", Type:["E"], Rating:"2", Sort:"1", Set:"OGW", Number:"91", Image:"/Images/OGW/UntamedHunger.jpg"},
{Name:"Vampire Envoy", Cost:"2B", Color:["B"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"OGW", Number:"92", Image:"/Images/OGW/VampireEnvoy.jpg"},
{Name:"Zulaport Chainmage", Cost:"3B", Color:["B"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"OGW", Number:"93", Image:"/Images/OGW/ZulaportChainmage.jpg"},
{Name:"Consuming Sinkhole", Cost:"3R", Color:["R"], Rarity:"C", Type:["I"], Rating:"2", Sort:"1", Set:"OGW", Number:"94", Image:"/Images/OGW/ConsumingSinkhole.jpg"},
{Name:"Eldrazi Aggressor", Cost:"2R", Color:["R"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"OGW", Number:"95", Image:"/Images/OGW/EldraziAggressor.jpg"},
{Name:"Eldrazi Obligator", Cost:"2R", Color:["R"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"OGW", Number:"96", Image:"/Images/OGW/EldraziObligator.jpg"},
{Name:"Immobilizer Eldrazi", Cost:"1R", Color:["R"], Rarity:"U", Type:["C"], Rating:"3", Sort:"1", Set:"OGW", Number:"97", Image:"/Images/OGW/ImmobilizerEldrazi.jpg"},
{Name:"Kozilek's Return", Cost:"2R", Color:["R"], Rarity:"M", Type:["I"], Rating:"8", Sort:"1", Set:"OGW", Number:"98", Image:"/Images/OGW/KozileksReturn.jpg"},
{Name:"Maw of Kozilek", Cost:"3R", Color:["R"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"OGW", Number:"99", Image:"/Images/OGW/MawofKozilek.jpg"},
{Name:"Reality Hemorrhage", Cost:"1R", Color:["R"], Rarity:"C", Type:["I"], Rating:"3", Sort:"1", Set:"OGW", Number:"100", Image:"/Images/OGW/RealityHemorrhage.jpg"},
{Name:"Akoum Flameseeker", Cost:"2R", Color:["R"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"OGW", Number:"101", Image:"/Images/OGW/AkoumFlameseeker.jpg"},
{Name:"Boulder Salvo", Cost:"4R", Color:["R"], Rarity:"C", Type:["S"], Rating:"4", Sort:"1", Set:"OGW", Number:"102", Image:"/Images/OGW/BoulderSalvo.jpg"},
{Name:"Brute Strength", Cost:"1R", Color:["R"], Rarity:"C", Type:["I"], Rating:"2", Sort:"1", Set:"OGW", Number:"103", Image:"/Images/OGW/BruteStrength.jpg"},
{Name:"Chandra, Flamecaller", Cost:"4RR", Color:["R"], Rarity:"M", Type:["P"], Rating:"8", Sort:"1", Set:"OGW", Number:"104", Image:"/Images/OGW/Chandra--Flamecaller.jpg"},
{Name:"Cinder Hellion", Cost:"4R", Color:["R"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"OGW", Number:"105", Image:"/Images/OGW/CinderHellion.jpg"},
{Name:"Devour in Flames", Cost:"2R", Color:["R"], Rarity:"U", Type:["S"], Rating:"5", Sort:"1", Set:"OGW", Number:"106", Image:"/Images/OGW/DevourinFlames.jpg"},
{Name:"Embodiment of Fury", Cost:"3R", Color:["R"], Rarity:"U", Type:["C"], Rating:"7", Sort:"1", Set:"OGW", Number:"107", Image:"/Images/OGW/EmbodimentofFury.jpg"},
{Name:"Expedite", Cost:"0R", Color:["R"], Rarity:"C", Type:["I"], Rating:"3", Sort:"1", Set:"OGW", Number:"108", Image:"/Images/OGW/Expedite.jpg"},
{Name:"Fall of the Titans", Cost:"0R", Color:["R"], Rarity:"R", Type:["I"], Rating:"7", Sort:"1", Set:"OGW", Number:"109", Image:"/Images/OGW/FalloftheTitans.jpg"},
{Name:"Goblin Dark-Dwellers", Cost:"3RR", Color:["R"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"OGW", Number:"110", Image:"/Images/OGW/GoblinDark-Dwellers.jpg"},
{Name:"Goblin Freerunner", Cost:"3R", Color:["R"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"OGW", Number:"111", Image:"/Images/OGW/GoblinFreerunner.jpg"},
{Name:"Kazuul's Toll Collector", Cost:"2R", Color:["R"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"OGW", Number:"112", Image:"/Images/OGW/KazuulsTollCollector.jpg"},
{Name:"Oath of Chandra", Cost:"1R", Color:["R"], Rarity:"R", Type:["E"], Rating:"7", Sort:"1", Set:"OGW", Number:"113", Image:"/Images/OGW/OathofChandra.jpg"},
{Name:"Press into Service", Cost:"4R", Color:["R"], Rarity:"U", Type:["S"], Rating:"4", Sort:"1", Set:"OGW", Number:"114", Image:"/Images/OGW/PressintoService.jpg"},
{Name:"Pyromancer's Assault", Cost:"3R", Color:["R"], Rarity:"U", Type:["E"], Rating:"3", Sort:"1", Set:"OGW", Number:"115", Image:"/Images/OGW/PyromancersAssault.jpg"},
{Name:"Reckless Bushwhacker", Cost:"2R", Color:["R"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"OGW", Number:"116", Image:"/Images/OGW/RecklessBushwhacker.jpg"},
{Name:"Sparkmage's Gambit", Cost:"1R", Color:["R"], Rarity:"C", Type:["S"], Rating:"2", Sort:"1", Set:"OGW", Number:"117", Image:"/Images/OGW/SparkmagesGambit.jpg"},
{Name:"Tears of Valakut", Cost:"1R", Color:["R"], Rarity:"U", Type:["I"], Rating:"3", Sort:"1", Set:"OGW", Number:"118", Image:"/Images/OGW/TearsofValakut.jpg"},
{Name:"Tyrant of Valakut", Cost:"5RR", Color:["R"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"OGW", Number:"119", Image:"/Images/OGW/TyrantofValakut.jpg"},
{Name:"Zada's Commando", Cost:"1R", Color:["R"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"OGW", Number:"120", Image:"/Images/OGW/ZadasCommando.jpg"},
{Name:"Birthing Hulk", Cost:"6G", Color:["G"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"OGW", Number:"121", Image:"/Images/OGW/BirthingHulk.jpg"},
{Name:"Ruin in Their Wake", Cost:"1G", Color:["G"], Rarity:"U", Type:["S"], Rating:"5", Sort:"1", Set:"OGW", Number:"122", Image:"/Images/OGW/RuininTheirWake.jpg"},
{Name:"Scion Summoner", Cost:"2G", Color:["G"], Rarity:"C", Type:["C"], Rating:"5", Sort:"1", Set:"OGW", Number:"123", Image:"/Images/OGW/ScionSummoner.jpg"},
{Name:"Stalking Drone", Cost:"1G", Color:["G"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"OGW", Number:"124", Image:"/Images/OGW/StalkingDrone.jpg"},
{Name:"Vile Redeemer", Cost:"2G", Color:["G"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"OGW", Number:"125", Image:"/Images/OGW/VileRedeemer.jpg"},
{Name:"World Breaker", Cost:"6G", Color:["G"], Rarity:"M", Type:["C"], Rating:"9", Sort:"1", Set:"OGW", Number:"126", Image:"/Images/OGW/WorldBreaker.jpg"},
{Name:"Baloth Pup", Cost:"1G", Color:["G"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"OGW", Number:"127", Image:"/Images/OGW/BalothPup.jpg"},
{Name:"Bonds of Mortality", Cost:"1G", Color:["G"], Rarity:"U", Type:["E"], Rating:"4", Sort:"1", Set:"OGW", Number:"128", Image:"/Images/OGW/BondsofMortality.jpg"},
{Name:"Canopy Gorger", Cost:"4GG", Color:["G"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"OGW", Number:"129", Image:"/Images/OGW/CanopyGorger.jpg"},
{Name:"Elemental Uprising", Cost:"1G", Color:["G"], Rarity:"C", Type:["I"], Rating:"2", Sort:"1", Set:"OGW", Number:"130", Image:"/Images/OGW/ElementalUprising.jpg"},
{Name:"Embodiment of Insight", Cost:"4G", Color:["G"], Rarity:"U", Type:["C"], Rating:"7", Sort:"1", Set:"OGW", Number:"131", Image:"/Images/OGW/EmbodimentofInsight.jpg"},
{Name:"Gladehart Cavalry", Cost:"5GG", Color:["G"], Rarity:"R", Type:["C"], Rating:"5", Sort:"1", Set:"OGW", Number:"132", Image:"/Images/OGW/GladehartCavalry.jpg"},
{Name:"Harvester Troll", Cost:"3G", Color:["G"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"OGW", Number:"133", Image:"/Images/OGW/HarvesterTroll.jpg"},
{Name:"Lead by Example", Cost:"1G", Color:["G"], Rarity:"C", Type:["I"], Rating:"2", Sort:"1", Set:"OGW", Number:"134", Image:"/Images/OGW/LeadbyExample.jpg"},
{Name:"Loam Larva", Cost:"1G", Color:["G"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"OGW", Number:"135", Image:"/Images/OGW/LoamLarva.jpg"},
{Name:"Natural State", Cost:"0G", Color:["G"], Rarity:"C", Type:["I"], Rating:"1", Sort:"1", Set:"OGW", Number:"136", Image:"/Images/OGW/NaturalState.jpg"},
{Name:"Netcaster Spider", Cost:"2G", Color:["G"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"OGW", Number:"137", Image:"/Images/OGW/NetcasterSpider.jpg"},
{Name:"Nissa, Voice of Zendikar", Cost:"1GG", Color:["G"], Rarity:"M", Type:["P"], Rating:"9", Sort:"1", Set:"OGW", Number:"138", Image:"/Images/OGW/Nissa--VoiceofZendikar.jpg"},
{Name:"Nissa's Judgment", Cost:"4G", Color:["G"], Rarity:"U", Type:["S"], Rating:"5", Sort:"1", Set:"OGW", Number:"139", Image:"/Images/OGW/NissasJudgment.jpg"},
{Name:"Oath of Nissa", Cost:"0G", Color:["G"], Rarity:"R", Type:["E"], Rating:"6", Sort:"1", Set:"OGW", Number:"140", Image:"/Images/OGW/OathofNissa.jpg"},
{Name:"Pulse of Murasa", Cost:"2G", Color:["G"], Rarity:"C", Type:["I"], Rating:"2", Sort:"1", Set:"OGW", Number:"141", Image:"/Images/OGW/PulseofMurasa.jpg"},
{Name:"Saddleback Lagac", Cost:"3G", Color:["G"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"OGW", Number:"142", Image:"/Images/OGW/SaddlebackLagac.jpg"},
{Name:"Seed Guardian", Cost:"2GG", Color:["G"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"OGW", Number:"143", Image:"/Images/OGW/SeedGuardian.jpg"},
{Name:"Sylvan Advocate", Cost:"1G", Color:["G"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"OGW", Number:"144", Image:"/Images/OGW/SylvanAdvocate.jpg"},
{Name:"Tajuru Pathwarden", Cost:"4G", Color:["G"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"OGW", Number:"145", Image:"/Images/OGW/TajuruPathwarden.jpg"},
{Name:"Vines of the Recluse", Cost:"0G", Color:["G"], Rarity:"C", Type:["I"], Rating:"2", Sort:"1", Set:"OGW", Number:"146", Image:"/Images/OGW/VinesoftheRecluse.jpg"},
{Name:"Zendikar Resurgent", Cost:"5GG", Color:["G"], Rarity:"R", Type:["E"], Rating:"5", Sort:"1", Set:"OGW", Number:"147", Image:"/Images/OGW/ZendikarResurgent.jpg"},
{Name:"Flayer Drone", Cost:"1BR", Color:["B","R"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"OGW", Number:"148", Image:"/Images/OGW/FlayerDrone.jpg"},
{Name:"Mindmelter", Cost:"1UB", Color:["U","B"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"OGW", Number:"149", Image:"/Images/OGW/Mindmelter.jpg"},
{Name:"Void Grafter", Cost:"1UG", Color:["U","G"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"OGW", Number:"150", Image:"/Images/OGW/VoidGrafter.jpg"},
{Name:"Ayli, Eternal Pilgrim", Cost:"0WB", Color:["W","B"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"OGW", Number:"151", Image:"/Images/OGW/Ayli--EternalPilgrim.jpg"},
{Name:"Baloth Null", Cost:"4BG", Color:["B","G"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"OGW", Number:"152", Image:"/Images/OGW/BalothNull.jpg"},
{Name:"Cliffhaven Vampire", Cost:"2WB", Color:["W","B"], Rarity:"U", Type:["C"], Rating:"3", Sort:"1", Set:"OGW", Number:"153", Image:"/Images/OGW/CliffhavenVampire.jpg"},
{Name:"Joraga Auxiliary", Cost:"1WG", Color:["W","G"], Rarity:"U", Type:["C"], Rating:"3", Sort:"1", Set:"OGW", Number:"154", Image:"/Images/OGW/JoragaAuxiliary.jpg"},
{Name:"Jori En, Ruin Diver", Cost:"1UR", Color:["U","R"], Rarity:"R", Type:["C"], Rating:"6", Sort:"1", Set:"OGW", Number:"155", Image:"/Images/OGW/JoriEn--RuinDiver.jpg"},
{Name:"Mina and Denn, Wildborn", Cost:"2RG", Color:["R","G"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"OGW", Number:"156", Image:"/Images/OGW/MinaandDenn--Wildborn.jpg"},
{Name:"Reflector Mage", Cost:"1WU", Color:["W","U"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"OGW", Number:"157", Image:"/Images/OGW/ReflectorMage.jpg"},
{Name:"Relentless Hunter", Cost:"1RG", Color:["R","G"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"OGW", Number:"158", Image:"/Images/OGW/RelentlessHunter.jpg"},
{Name:"Stormchaser Mage", Cost:"0UR", Color:["U","R"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"OGW", Number:"159", Image:"/Images/OGW/StormchaserMage.jpg"},
{Name:"Weapons Trainer", Cost:"0WR", Color:["W","R"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"OGW", Number:"160", Image:"/Images/OGW/WeaponsTrainer.jpg"},
{Name:"Bone Saw", Cost:"0", Color:["C"], Rarity:"C", Type:["A"], Rating:"3", Sort:"1", Set:"OGW", Number:"161", Image:"/Images/OGW/BoneSaw.jpg"},
{Name:"Captain's Claws", Cost:"2", Color:["C"], Rarity:"R", Type:["A"], Rating:"7", Sort:"1", Set:"OGW", Number:"162", Image:"/Images/OGW/CaptainsClaws.jpg"},
{Name:"Chitinous Cloak", Cost:"3", Color:["C"], Rarity:"U", Type:["A"], Rating:"4", Sort:"1", Set:"OGW", Number:"163", Image:"/Images/OGW/ChitinousCloak.jpg"},
{Name:"Hedron Crawler", Cost:"2", Color:["C"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"OGW", Number:"164", Image:"/Images/OGW/HedronCrawler.jpg"},
{Name:"Seer's Lantern", Cost:"3", Color:["C"], Rarity:"C", Type:["A"], Rating:"4", Sort:"1", Set:"OGW", Number:"165", Image:"/Images/OGW/SeersLantern.jpg"},
{Name:"Stoneforge Masterwork", Cost:"1", Color:["C"], Rarity:"R", Type:["A"], Rating:"5", Sort:"1", Set:"OGW", Number:"166", Image:"/Images/OGW/StoneforgeMasterwork.jpg"},
{Name:"Strider Harness", Cost:"3", Color:["C"], Rarity:"U", Type:["A"], Rating:"3", Sort:"1", Set:"OGW", Number:"167", Image:"/Images/OGW/StriderHarness.jpg"},
{Name:"Cinder Barrens", Cost:"0", Color:["B","R"], Rarity:"U", Type:["L"], Rating:"6", Sort:"1", Set:"OGW", Number:"168", Image:"/Images/OGW/CinderBarrens.jpg"},
{Name:"Corrupted Crossroads", Cost:"0", Color:["C"], Rarity:"R", Type:["L"], Rating:"6", Sort:"1", Set:"OGW", Number:"169", Image:"/Images/OGW/CorruptedCrossroads.jpg"},
{Name:"Crumbling Vestige", Cost:"0", Color:["C"], Rarity:"C", Type:["L"], Rating:"5", Sort:"1", Set:"OGW", Number:"170", Image:"/Images/OGW/CrumblingVestige.jpg"},
{Name:"Hissing Quagmire", Cost:"0", Color:["B","G"], Rarity:"R", Type:["L"], Rating:"7", Sort:"1", Set:"OGW", Number:"171", Image:"/Images/OGW/HissingQuagmire.jpg"},
{Name:"Holdout Settlement", Cost:"0", Color:["C"], Rarity:"C", Type:["L"], Rating:"4", Sort:"1", Set:"OGW", Number:"172", Image:"/Images/OGW/HoldoutSettlement.jpg"},
{Name:"Meandering River", Cost:"0", Color:["W","U"], Rarity:"U", Type:["L"], Rating:"6", Sort:"1", Set:"OGW", Number:"173", Image:"/Images/OGW/MeanderingRiver.jpg"},
{Name:"Mirrorpool", Cost:"0", Color:["C"], Rarity:"M", Type:["L"], Rating:"8", Sort:"1", Set:"OGW", Number:"174", Image:"/Images/OGW/Mirrorpool.jpg"},
{Name:"Needle Spires", Cost:"0", Color:["W","R"], Rarity:"R", Type:["L"], Rating:"7", Sort:"1", Set:"OGW", Number:"175", Image:"/Images/OGW/NeedleSpires.jpg"},
{Name:"Ruins of Oran-Rief", Cost:"0", Color:["C"], Rarity:"R", Type:["L"], Rating:"7", Sort:"1", Set:"OGW", Number:"176", Image:"/Images/OGW/RuinsofOran-Rief.jpg"},
{Name:"Sea Gate Wreckage", Cost:"0", Color:["C"], Rarity:"R", Type:["L"], Rating:"6", Sort:"1", Set:"OGW", Number:"177", Image:"/Images/OGW/SeaGateWreckage.jpg"},
{Name:"Submerged Boneyard", Cost:"0", Color:["U","B"], Rarity:"U", Type:["L"], Rating:"6", Sort:"1", Set:"OGW", Number:"178", Image:"/Images/OGW/SubmergedBoneyard.jpg"},
{Name:"Timber Gorge", Cost:"0", Color:["R","G"], Rarity:"U", Type:["L"], Rating:"6", Sort:"1", Set:"OGW", Number:"179", Image:"/Images/OGW/TimberGorge.jpg"},
{Name:"Tranquil Expanse", Cost:"0", Color:["W","G"], Rarity:"U", Type:["L"], Rating:"6", Sort:"1", Set:"OGW", Number:"180", Image:"/Images/OGW/TranquilExpanse.jpg"},
{Name:"Unknown Shores", Cost:"0", Color:["C"], Rarity:"C", Type:["L"], Rating:"5", Sort:"1", Set:"OGW", Number:"181", Image:"/Images/OGW/UnknownShores.jpg"},
{Name:"Wandering Fumarole", Cost:"0", Color:["U","B"], Rarity:"R", Type:["L"], Rating:"8", Sort:"1", Set:"OGW", Number:"182", Image:"/Images/OGW/WanderingFumarole.jpg"},
{Name:"Wastes", Cost:"0", Color:["C"], Rarity:"C", Type:["L"], Rating:"3", Sort:"1", Set:"OGW", Number:"183", Image:"/Images/OGW/Wastes.jpg"},
{Name:"Wastes", Cost:"0", Color:["C"], Rarity:"C", Type:["L"], Rating:"3", Sort:"1", Set:"OGW", Number:"183", Image:"/Images/OGW/Wastes.jpg"}
];
