var JOU = [
{Name:"Aegis of the Gods", Cost:"2", Color:["W"], Rarity:"R", Type:["C","E"], Rating:"6", Sort:"1", Set:"JOU", Number:"1", Image:"/Images/JOU/1.jpg"},
{Name:"Ajani's Presence", Cost:"1", Color:["W"], Rarity:"C", Type:["I"], Rating:"5", Sort:"1", Set:"JOU", Number:"2", Image:"/Images/JOU/2.jpg"},
{Name:"Akroan Mastiff", Cost:"4", Color:["W"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"JOU", Number:"3", Image:"/Images/JOU/3.jpg"},
{Name:"Arnament of Nyx", Cost:"3", Color:["W"], Rarity:"C", Type:["E"], Rating:"5", Sort:"1", Set:"JOU", Number:"4", Image:"/Images/JOU/4.jpg"},
{Name:"Banishing Light", Cost:"3", Color:["W"], Rarity:"U", Type:["E"], Rating:"8", Sort:"1", Set:"JOU", Number:"5", Image:"/Images/JOU/5.jpg"},
{Name:"Dawnbringer Charioteers", Cost:"4", Color:["W"], Rarity:"R", Type:["C"], Rating:"6", Sort:"1", Set:"JOU", Number:"6", Image:"/Images/JOU/6.jpg"},
{Name:"Deicide", Cost:"2", Color:["W"], Rarity:"R", Type:["I"], Rating:"7", Sort:"1", Set:"JOU", Number:"7", Image:"/Images/JOU/7.jpg"},
{Name:"Dictate of Heliod", Cost:"5", Color:["W"], Rarity:"R", Type:["E"], Rating:"7", Sort:"1", Set:"JOU", Number:"8", Image:"/Images/JOU/8.jpg"},
{Name:"Eagle of the Watch", Cost:"3", Color:["W"], Rarity:"C", Type:["C"], Rating:"5", Sort:"1", Set:"JOU", Number:"9", Image:"/Images/JOU/9.jpg"},
{Name:"Eidolon of Rhetoric", Cost:"3", Color:["W"], Rarity:"U", Type:["C","E"], Rating:"5", Sort:"1", Set:"JOU", Number:"10", Image:"/Images/JOU/10.jpg"},
{Name:"Font of Vigor", Cost:"2", Color:["W"], Rarity:"C", Type:["E"], Rating:"3", Sort:"1", Set:"JOU", Number:"11", Image:"/Images/JOU/11.jpg"},
{Name:"Godsend", Cost:"3", Color:["W"], Rarity:"M", Type:["A"], Rating:"9", Sort:"1", Set:"JOU", Number:"12", Image:"/Images/JOU/12.jpg"},
{Name:"Harvest Alseids", Cost:"3", Color:["W"], Rarity:"C", Type:["C","E"], Rating:"6", Sort:"1", Set:"JOU", Number:"13", Image:"/Images/JOU/13.jpg"},
{Name:"Lagonna-Band Trailblazer", Cost:"1", Color:["W"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"JOU", Number:"14", Image:"/Images/JOU/14.jpg"},
{Name:"Launch the Fleet", Cost:"1", Color:["W"], Rarity:"R", Type:["S"], Rating:"9", Sort:"1", Set:"JOU", Number:"15", Image:"/Images/JOU/15.jpg"},
{Name:"Leonin Ironoclast", Cost:"4", Color:["W"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"JOU", Number:"16", Image:"/Images/JOU/16.jpg"},
{Name:"Mortal Obstinancy", Cost:"1", Color:["W"], Rarity:"C", Type:["E"], Rating:"6", Sort:"1", Set:"JOU", Number:"17", Image:"/Images/JOU/17.jpg"},
{Name:"Nyx-Fleece Ram", Cost:"2", Color:["W"], Rarity:"U", Type:["C","E"], Rating:"8", Sort:"1", Set:"JOU", Number:"18", Image:"/Images/JOU/18.jpg"},
{Name:"Oppressive Rays", Cost:"1", Color:["W"], Rarity:"C", Type:["E"], Rating:"6", Sort:"1", Set:"JOU", Number:"19", Image:"/Images/JOU/19.jpg"},
{Name:"Oreskos Swiftclaw", Cost:"2", Color:["W"], Rarity:"C", Type:["C"], Rating:"6", Sort:"1", Set:"JOU", Number:"20", Image:"/Images/JOU/20.jpg"},
{Name:"Phalanx Formation", Cost:"3", Color:["W"], Rarity:"U", Type:["I"], Rating:"6", Sort:"1", Set:"JOU", Number:"21", Image:"/Images/JOU/21.jpg"},
{Name:"Quarry Colossus", Cost:"7", Color:["W"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"JOU", Number:"22", Image:"/Images/JOU/22.jpg"},
{Name:"Reprisal", Cost:"2", Color:["W"], Rarity:"U", Type:["I"], Rating:"6", Sort:"1", Set:"JOU", Number:"23", Image:"/Images/JOU/23.jpg"},
{Name:"Sightless Brawler", Cost:"2", Color:["W"], Rarity:"U", Type:["C","E"], Rating:"7", Sort:"1", Set:"JOU", Number:"24", Image:"/Images/JOU/24.jpg"},
{Name:"Skybind", Cost:"5", Color:["W"], Rarity:"R", Type:["E"], Rating:"6", Sort:"1", Set:"JOU", Number:"25", Image:"/Images/JOU/25.jpg"},
{Name:"Skyspear Cavalry", Cost:"5", Color:["W"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"JOU", Number:"26", Image:"/Images/JOU/26.jpg"},
{Name:"Stonewise Fortifier", Cost:"2", Color:["W"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"JOU", Number:"27", Image:"/Images/JOU/27.jpg"},
{Name:"Supply-Line Cranes", Cost:"5", Color:["W"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"JOU", Number:"28", Image:"/Images/JOU/28.jpg"},
{Name:"Tethmos High Priest", Cost:"3", Color:["W"], Rarity:"U", Type:["C"], Rating:"7", Sort:"1", Set:"JOU", Number:"29", Image:"/Images/JOU/29.jpg"},
{Name:"Aerial Formation", Cost:"1", Color:["U"], Rarity:"C", Type:["I"], Rating:"7", Sort:"1", Set:"JOU", Number:"30", Image:"/Images/JOU/30.jpg"},
{Name:"Battlefield Thaumaturge", Cost:"2", Color:["U"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"JOU", Number:"31", Image:"/Images/JOU/31.jpg"},
{Name:"Cloaked Siren", Cost:"4", Color:["U"], Rarity:"C", Type:["C"], Rating:"5", Sort:"1", Set:"JOU", Number:"32", Image:"/Images/JOU/32.jpg"},
{Name:"Countermand", Cost:"4", Color:["U"], Rarity:"C", Type:["I"], Rating:"5", Sort:"1", Set:"JOU", Number:"33", Image:"/Images/JOU/33.jpg"},
{Name:"Crystalline Nautilus", Cost:"3", Color:["U"], Rarity:"U", Type:["C","E"], Rating:"7", Sort:"1", Set:"JOU", Number:"34", Image:"/Images/JOU/34.jpg"},
{Name:"Dakra Mystic", Cost:"1", Color:["U"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"JOU", Number:"35", Image:"/Images/JOU/35.jpg"},
{Name:"Daring Thief", Cost:"3", Color:["U"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"JOU", Number:"36", Image:"/Images/JOU/36.jpg"},
{Name:"Dictate of Kruphix", Cost:"3", Color:["U"], Rarity:"R", Type:["E"], Rating:"6", Sort:"1", Set:"JOU", Number:"37", Image:"/Images/JOU/37.jpg"},
{Name:"Font of Fortunes", Cost:"2", Color:["U"], Rarity:"C", Type:["E"], Rating:"6", Sort:"1", Set:"JOU", Number:"38", Image:"/Images/JOU/38.jpg"},
{Name:"Godhunter Octopus", Cost:"4", Color:["U"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"JOU", Number:"39", Image:"/Images/JOU/39.jpg"},
{Name:"Hour of Need", Cost:"3", Color:["U"], Rarity:"U", Type:["I"], Rating:"7", Sort:"1", Set:"JOU", Number:"40", Image:"/Images/JOU/40.jpg"},
{Name:"Hubris", Cost:"2", Color:["U"], Rarity:"C", Type:["I"], Rating:"5", Sort:"1", Set:"JOU", Number:"41", Image:"/Images/JOU/41.jpg"},
{Name:"Hypnotic Siren", Cost:"1", Color:["U"], Rarity:"R", Type:["C","E"], Rating:"8", Sort:"1", Set:"JOU", Number:"42", Image:"/Images/JOU/42.jpg"},
{Name:"Interpret the Signs", Cost:"6", Color:["U"], Rarity:"U", Type:["S"], Rating:"6", Sort:"1", Set:"JOU", Number:"43", Image:"/Images/JOU/43.jpg"},
{Name:"Kiora's Dismissal", Cost:"1", Color:["U"], Rarity:"U", Type:["I"], Rating:"8", Sort:"1", Set:"JOU", Number:"44", Image:"/Images/JOU/44.jpg"},
{Name:"Pin to the Earth", Cost:"2", Color:["U"], Rarity:"C", Type:["E"], Rating:"3", Sort:"1", Set:"JOU", Number:"45", Image:"/Images/JOU/45.jpg"},
{Name:"Polymorphous Rush", Cost:"3", Color:["U"], Rarity:"R", Type:["I"], Rating:"8", Sort:"1", Set:"JOU", Number:"46", Image:"/Images/JOU/46.jpg"},
{Name:"Pull from the Deep", Cost:"4", Color:["U"], Rarity:"U", Type:["S"], Rating:"5", Sort:"1", Set:"JOU", Number:"47", Image:"/Images/JOU/47.jpg"},
{Name:"Riptide Chimera", Cost:"3", Color:["U"], Rarity:"U", Type:["C","E"], Rating:"6", Sort:"1", Set:"JOU", Number:"48", Image:"/Images/JOU/48.jpg"},
{Name:"Rise of Eagles", Cost:"6", Color:["U"], Rarity:"C", Type:["S"], Rating:"5", Sort:"1", Set:"JOU", Number:"49", Image:"/Images/JOU/49.jpg"},
{Name:"Sage of Hours", Cost:"2", Color:["U"], Rarity:"M", Type:["C"], Rating:"8", Sort:"1", Set:"JOU", Number:"50", Image:"/Images/JOU/50.jpg"},
{Name:"Scourge of Fleets", Cost:"7", Color:["U"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"JOU", Number:"51", Image:"/Images/JOU/51.jpg"},
{Name:"Sigiled Starfish", Cost:"2", Color:["U"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"JOU", Number:"52", Image:"/Images/JOU/52.jpg"},
{Name:"Thassa's Devourer", Cost:"5", Color:["U"], Rarity:"C", Type:["C","E"], Rating:"3", Sort:"1", Set:"JOU", Number:"53", Image:"/Images/JOU/53.jpg"},
{Name:"Thassa's Ire", Cost:"1", Color:["U"], Rarity:"U", Type:["E"], Rating:"5", Sort:"1", Set:"JOU", Number:"54", Image:"/Images/JOU/54.jpg"},
{Name:"Triton Cavalry", Cost:"4", Color:["U"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"JOU", Number:"55", Image:"/Images/JOU/55.jpg"},
{Name:"Triton Shorestalker", Cost:"1", Color:["U"], Rarity:"C", Type:["C"], Rating:"6", Sort:"1", Set:"JOU", Number:"56", Image:"/Images/JOU/56.jpg"},
{Name:"War-Wing Siren", Cost:"3", Color:["U"], Rarity:"C", Type:["C"], Rating:"5", Sort:"1", Set:"JOU", Number:"57", Image:"/Images/JOU/57.jpg"},
{Name:"Whitewater Naiads", Cost:"5", Color:["U"], Rarity:"U", Type:["C","E"], Rating:"4", Sort:"1", Set:"JOU", Number:"58", Image:"/Images/JOU/58.jpg"},
{Name:"Agent of Erebos", Cost:"4", Color:["B"], Rarity:"U", Type:["C","E"], Rating:"3", Sort:"1", Set:"JOU", Number:"59", Image:"/Images/JOU/59.jpg"},
{Name:"Aspect of Gorgon", Cost:"3", Color:["B"], Rarity:"C", Type:["E"], Rating:"3", Sort:"1", Set:"JOU", Number:"60", Image:"/Images/JOU/60.jpg"},
{Name:"Bloodcrazed Hoplite", Cost:"2", Color:["B"], Rarity:"C", Type:["C"], Rating:"5", Sort:"1", Set:"JOU", Number:"61", Image:"/Images/JOU/61.jpg"},
{Name:"Brain Maggot", Cost:"2", Color:["B"], Rarity:"U", Type:["C"], Rating:"7", Sort:"1", Set:"JOU", Number:"62", Image:"/Images/JOU/62.jpg"},
{Name:"Cast into Darkness", Cost:"2", Color:["B"], Rarity:"C", Type:["E"], Rating:"4", Sort:"1", Set:"JOU", Number:"63", Image:"/Images/JOU/63.jpg"},
{Name:"Cruel Feeding", Cost:"1", Color:["B"], Rarity:"C", Type:["I"], Rating:"3", Sort:"1", Set:"JOU", Number:"64", Image:"/Images/JOU/64.jpg"},
{Name:"Dictate of Erebos", Cost:"5", Color:["B"], Rarity:"R", Type:["E"], Rating:"8", Sort:"1", Set:"JOU", Number:"65", Image:"/Images/JOU/65.jpg"},
{Name:"Doomwake Giant", Cost:"5", Color:["B"], Rarity:"R", Type:["C","E"], Rating:"7", Sort:"1", Set:"JOU", Number:"66", Image:"/Images/JOU/66.jpg"},
{Name:"Deadbringer Lampads", Cost:"5", Color:["B"], Rarity:"C", Type:["C","E"], Rating:"5", Sort:"1", Set:"JOU", Number:"67", Image:"/Images/JOU/67.jpg"},
{Name:"Extinguish All Hope", Cost:"6", Color:["B"], Rarity:"R", Type:["S"], Rating:"7", Sort:"1", Set:"JOU", Number:"68", Image:"/Images/JOU/68.jpg"},
{Name:"Feast of Dreams", Cost:"2", Color:["B"], Rarity:"C", Type:["I"], Rating:"7", Sort:"1", Set:"JOU", Number:"69", Image:"/Images/JOU/69.jpg"},
{Name:"Felhide Petrifier", Cost:"3", Color:["B"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"JOU", Number:"70", Image:"/Images/JOU/70.jpg"},
{Name:"Font of Return", Cost:"2", Color:["B"], Rarity:"C", Type:["E"], Rating:"3", Sort:"1", Set:"JOU", Number:"71", Image:"/Images/JOU/71.jpg"},
{Name:"Gnarled Scarhide", Cost:"1", Color:["B"], Rarity:"U", Type:["C"], Rating:"7", Sort:"1", Set:"JOU", Number:"72", Image:"/Images/JOU/72.jpg"},
{Name:"Grim Guardian", Cost:"3", Color:["B"], Rarity:"C", Type:["C","E"], Rating:"5", Sort:"1", Set:"JOU", Number:"73", Image:"/Images/JOU/73.jpg"},
{Name:"King Macar, the Gold-Cursed", Cost:"4", Color:["B"], Rarity:"R", Type:["C"], Rating:"9", Sort:"1", Set:"JOU", Number:"74", Image:"/Images/JOU/74.jpg"},
{Name:"Master of the Feast", Cost:"3", Color:["B"], Rarity:"R", Type:["C","E"], Rating:"7", Sort:"1", Set:"JOU", Number:"75", Image:"/Images/JOU/75.jpg"},
{Name:"Nightmarish End", Cost:"3", Color:["B"], Rarity:"U", Type:["I"], Rating:"4", Sort:"1", Set:"JOU", Number:"76", Image:"/Images/JOU/76.jpg"},
{Name:"Nyx Infusion", Cost:"3", Color:["B"], Rarity:"C", Type:["E"], Rating:"5", Sort:"1", Set:"JOU", Number:"77", Image:"/Images/JOU/77.jpg"},
{Name:"Pharika's Chosen", Cost:"1", Color:["B"], Rarity:"C", Type:["C"], Rating:"5", Sort:"1", Set:"JOU", Number:"78", Image:"/Images/JOU/78.jpg"},
{Name:"Returned Reveler", Cost:"2", Color:["B"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"JOU", Number:"79", Image:"/Images/JOU/79.jpg"},
{Name:"Ritual of the Returned", Cost:"4", Color:["B"], Rarity:"U", Type:["I"], Rating:"6", Sort:"1", Set:"JOU", Number:"80", Image:"/Images/JOU/80.jpg"},
{Name:"Rotted Hulk", Cost:"4", Color:["B"], Rarity:"C", Type:["C"], Rating:"5", Sort:"1", Set:"JOU", Number:"81", Image:"/Images/JOU/81.jpg"},
{Name:"Silence the Believers", Cost:"4", Color:["B"], Rarity:"R", Type:["I"], Rating:"9", Sort:"1", Set:"JOU", Number:"82", Image:"/Images/JOU/82.jpg"},
{Name:"Spiteful Blow", Cost:"6", Color:["B"], Rarity:"U", Type:["S"], Rating:"6", Sort:"1", Set:"JOU", Number:"83", Image:"/Images/JOU/83.jpg"},
{Name:"Squelching Leeches", Cost:"4", Color:["B"], Rarity:"U", Type:["C"], Rating:"7", Sort:"1", Set:"JOU", Number:"84", Image:"/Images/JOU/84.jpg"},
{Name:"Thoughtrender Lamia", Cost:"6", Color:["B"], Rarity:"U", Type:["C","E"], Rating:"7", Sort:"1", Set:"JOU", Number:"85", Image:"/Images/JOU/85.jpg"},
{Name:"Tormented Thoughts", Cost:"3", Color:["B"], Rarity:"U", Type:["S"], Rating:"6", Sort:"1", Set:"JOU", Number:"86", Image:"/Images/JOU/86.jpg"},
{Name:"Worst Fears", Cost:"8", Color:["B"], Rarity:"M", Type:["S"], Rating:"9", Sort:"1", Set:"JOU", Number:"87", Image:"/Images/JOU/87.jpg"},
{Name:"Akroan Line Breaker", Cost:"3", Color:["R"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"JOU", Number:"88", Image:"/Images/JOU/88.jpg"},
{Name:"Bearer of the Heavens", Cost:"8", Color:["R"], Rarity:"R", Type:["C"], Rating:"6", Sort:"1", Set:"JOU", Number:"89", Image:"/Images/JOU/89.jpg"},
{Name:"Bladetusk Boar", Cost:"4", Color:["R"], Rarity:"C", Type:["C"], Rating:"6", Sort:"1", Set:"JOU", Number:"90", Image:"/Images/JOU/90.jpg"},
{Name:"Blinding Flare", Cost:"1", Color:["R"], Rarity:"U", Type:["S"], Rating:"7", Sort:"1", Set:"JOU", Number:"91", Image:"/Images/JOU/91.jpg"},
{Name:"Cyclops of Eternal Fury", Cost:"6", Color:["R"], Rarity:"U", Type:["C","E"], Rating:"6", Sort:"1", Set:"JOU", Number:"92", Image:"/Images/JOU/92.jpg"},
{Name:"Dictate of the Twin Gods", Cost:"5", Color:["R"], Rarity:"R", Type:["E"], Rating:"6", Sort:"1", Set:"JOU", Number:"93", Image:"/Images/JOU/93.jpg"},
{Name:"Eidolon of the Great Revel", Cost:"2", Color:["R"], Rarity:"R", Type:["C","E"], Rating:"7", Sort:"1", Set:"JOU", Number:"94", Image:"/Images/JOU/94.jpg"},
{Name:"Flamespeaker's Will", Cost:"1", Color:["R"], Rarity:"C", Type:["E"], Rating:"6", Sort:"1", Set:"JOU", Number:"95", Image:"/Images/JOU/95.jpg"},
{Name:"Flurry of Horns", Cost:"5", Color:["R"], Rarity:"C", Type:["S"], Rating:"4", Sort:"1", Set:"JOU", Number:"96", Image:"/Images/JOU/96.jpg"},
{Name:"Font of Ire", Cost:"2", Color:["R"], Rarity:"C", Type:["E"], Rating:"4", Sort:"1", Set:"JOU", Number:"97", Image:"/Images/JOU/97.jpg"},
{Name:"Forgeborn Oreads", Cost:"4", Color:["R"], Rarity:"U", Type:["C","E"], Rating:"6", Sort:"1", Set:"JOU", Number:"98", Image:"/Images/JOU/98.jpg"},
{Name:"Gluttonous Cyclops", Cost:"6", Color:["R"], Rarity:"C", Type:["C"], Rating:"5", Sort:"1", Set:"JOU", Number:"99", Image:"/Images/JOU/99.jpg"},
{Name:"Harness by Force", Cost:"3", Color:["R"], Rarity:"R", Type:["S"], Rating:"7", Sort:"1", Set:"JOU", Number:"100", Image:"/Images/JOU/100.jpg"},
{Name:"Knowledge and Power", Cost:"5", Color:["R"], Rarity:"U", Type:["E"], Rating:"2", Sort:"1", Set:"JOU", Number:"101", Image:"/Images/JOU/101.jpg"},
{Name:"Lightning Diadem", Cost:"6", Color:["R"], Rarity:"C", Type:["E"], Rating:"3", Sort:"1", Set:"JOU", Number:"102", Image:"/Images/JOU/102.jpg"},
{Name:"Magma Spray", Cost:"1", Color:["R"], Rarity:"C", Type:["I"], Rating:"7", Sort:"1", Set:"JOU", Number:"103", Image:"/Images/JOU/103.jpg"},
{Name:"Mogis's Warhound", Cost:"2", Color:["R"], Rarity:"U", Type:["C","E"], Rating:"6", Sort:"1", Set:"JOU", Number:"104", Image:"/Images/JOU/104.jpg"},
{Name:"Pensive Minotaur", Cost:"3", Color:["R"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"JOU", Number:"105", Image:"/Images/JOU/105.jpg"},
{Name:"Prophetic Flamespeaker", Cost:"3", Color:["R"], Rarity:"M", Type:["C","E"], Rating:"10", Sort:"1", Set:"JOU", Number:"106", Image:"/Images/JOU/106.jpg"},
{Name:"Riddle of Lightning", Cost:"5", Color:["R"], Rarity:"U", Type:["I"], Rating:"6", Sort:"1", Set:"JOU", Number:"107", Image:"/Images/JOU/107.jpg"},
{Name:"Rollick of Abandon", Cost:"5", Color:["R"], Rarity:"U", Type:["S"], Rating:"4", Sort:"1", Set:"JOU", Number:"108", Image:"/Images/JOU/108.jpg"},
{Name:"Rouse the Mob", Cost:"1", Color:["R"], Rarity:"C", Type:["I"], Rating:"5", Sort:"1", Set:"JOU", Number:"109", Image:"/Images/JOU/109.jpg"},
{Name:"Satyr Hoplite", Cost:"1", Color:["R"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"JOU", Number:"110", Image:"/Images/JOU/110.jpg"},
{Name:"Sigiled Skink", Cost:"2", Color:["R"], Rarity:"C", Type:["C"], Rating:"6", Sort:"1", Set:"JOU", Number:"111", Image:"/Images/JOU/111.jpg"},
{Name:"Spawn of Thraxes", Cost:"7", Color:["R"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"JOU", Number:"112", Image:"/Images/JOU/112.jpg"},
{Name:"Spite of Mogis", Cost:"1", Color:["R"], Rarity:"U", Type:["S"], Rating:"3", Sort:"1", Set:"JOU", Number:"113", Image:"/Images/JOU/113.jpg"},
{Name:"Starfall", Cost:"5", Color:["R"], Rarity:"C", Type:["I"], Rating:"6", Sort:"1", Set:"JOU", Number:"114", Image:"/Images/JOU/114.jpg"},
{Name:"Twinflame", Cost:"2", Color:["R"], Rarity:"R", Type:["S"], Rating:"9", Sort:"1", Set:"JOU", Number:"115", Image:"/Images/JOU/115.jpg"},
{Name:"Wildfire Cerberus", Cost:"5", Color:["R"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"JOU", Number:"116", Image:"/Images/JOU/116.jpg"},
{Name:"Bassara Tower Archer", Cost:"2", Color:["G"], Rarity:"U", Type:["C"], Rating:"8", Sort:"1", Set:"JOU", Number:"117", Image:"/Images/JOU/117.jpg"},
{Name:"Colossal Heroics", Cost:"3", Color:["G"], Rarity:"U", Type:["I"], Rating:"5", Sort:"1", Set:"JOU", Number:"118", Image:"/Images/JOU/118.jpg"},
{Name:"Consign to Dust", Cost:"3", Color:["G"], Rarity:"U", Type:["I"], Rating:"5", Sort:"1", Set:"JOU", Number:"119", Image:"/Images/JOU/119.jpg"},
{Name:"Desecration Plague", Cost:"4", Color:["G"], Rarity:"C", Type:["S"], Rating:"6", Sort:"1", Set:"JOU", Number:"120", Image:"/Images/JOU/120.jpg"},
{Name:"Dictate of Karametra", Cost:"5", Color:["G"], Rarity:"R", Type:["E"], Rating:"7", Sort:"1", Set:"JOU", Number:"121", Image:"/Images/JOU/121.jpg"},
{Name:"Eidolon of Blossoms", Cost:"4", Color:["G"], Rarity:"R", Type:["C","E"], Rating:"8", Sort:"1", Set:"JOU", Number:"122", Image:"/Images/JOU/122.jpg"},
{Name:"Font of Fertility", Cost:"1", Color:["G"], Rarity:"C", Type:["E"], Rating:"6", Sort:"1", Set:"JOU", Number:"123", Image:"/Images/JOU/123.jpg"},
{Name:"Golden Hind", Cost:"2", Color:["G"], Rarity:"C", Type:["C"], Rating:"5", Sort:"1", Set:"JOU", Number:"124", Image:"/Images/JOU/124.jpg"},
{Name:"Goldenhide Ox", Cost:"6", Color:["G"], Rarity:"U", Type:["C","E"], Rating:"4", Sort:"1", Set:"JOU", Number:"125", Image:"/Images/JOU/125.jpg"},
{Name:"Heroes' Bane", Cost:"5", Color:["G"], Rarity:"R", Type:["C"], Rating:"9", Sort:"1", Set:"JOU", Number:"126", Image:"/Images/JOU/126.jpg"},
{Name:"Humbler of Mortals", Cost:"6", Color:["G"], Rarity:"C", Type:["C","E"], Rating:"6", Sort:"1", Set:"JOU", Number:"127", Image:"/Images/JOU/127.jpg"},
{Name:"Hydra Broodmaster", Cost:"6", Color:["G"], Rarity:"R", Type:["C"], Rating:"9", Sort:"1", Set:"JOU", Number:"128", Image:"/Images/JOU/128.jpg"},
{Name:"Kruphix's Insight", Cost:"3", Color:["G"], Rarity:"C", Type:["S"], Rating:"6", Sort:"1", Set:"JOU", Number:"129", Image:"/Images/JOU/129.jpg"},
{Name:"Market Festival", Cost:"4", Color:["G"], Rarity:"C", Type:["E"], Rating:"6", Sort:"1", Set:"JOU", Number:"130", Image:"/Images/JOU/130.jpg"},
{Name:"Nature's Panoply", Cost:"1", Color:["G"], Rarity:"C", Type:["I"], Rating:"6", Sort:"1", Set:"JOU", Number:"131", Image:"/Images/JOU/131.jpg"},
{Name:"Nessian Game Warden", Cost:"5", Color:["G"], Rarity:"U", Type:["C"], Rating:"7", Sort:"1", Set:"JOU", Number:"132", Image:"/Images/JOU/132.jpg"},
{Name:"Oakheart Dryads", Cost:"3", Color:["G"], Rarity:"C", Type:["C","E"], Rating:"7", Sort:"1", Set:"JOU", Number:"133", Image:"/Images/JOU/133.jpg"},
{Name:"Pheres-Band Thunderhoof", Cost:"5", Color:["G"], Rarity:"C", Type:["C"], Rating:"5", Sort:"1", Set:"JOU", Number:"134", Image:"/Images/JOU/134.jpg"},
{Name:"Pheres-Band Warchief", Cost:"4", Color:["G"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"JOU", Number:"135", Image:"/Images/JOU/135.jpg"},
{Name:"Ravenous Leucrocota", Cost:"4", Color:["G"], Rarity:"C", Type:["C"], Rating:"5", Sort:"1", Set:"JOU", Number:"136", Image:"/Images/JOU/136.jpg"},
{Name:"Renowned Weaver", Cost:"1", Color:["G"], Rarity:"C", Type:["C"], Rating:"5", Sort:"1", Set:"JOU", Number:"137", Image:"/Images/JOU/137.jpg"},
{Name:"Reviving Melody", Cost:"3", Color:["G"], Rarity:"U", Type:["S"], Rating:"4", Sort:"1", Set:"JOU", Number:"138", Image:"/Images/JOU/138.jpg"},
{Name:"Satyr Grovedancer", Cost:"2", Color:["G"], Rarity:"C", Type:["C"], Rating:"5", Sort:"1", Set:"JOU", Number:"139", Image:"/Images/JOU/139.jpg"},
{Name:"Setessan Tactics", Cost:"2", Color:["G"], Rarity:"R", Type:["I"], Rating:"9", Sort:"1", Set:"JOU", Number:"140", Image:"/Images/JOU/140.jpg"},
{Name:"Solidarity of Heroes", Cost:"2", Color:["G"], Rarity:"U", Type:["I"], Rating:"5", Sort:"1", Set:"JOU", Number:"141", Image:"/Images/JOU/141.jpg"},
{Name:"Spirespine", Cost:"3", Color:["G"], Rarity:"U", Type:["C","E"], Rating:"5", Sort:"1", Set:"JOU", Number:"142", Image:"/Images/JOU/142.jpg"},
{Name:"Strength of the Fallen", Cost:"2", Color:["G"], Rarity:"U", Type:["E"], Rating:"5", Sort:"1", Set:"JOU", Number:"143", Image:"/Images/JOU/143.jpg"},
{Name:"Swarmborn Giant", Cost:"4", Color:["G"], Rarity:"U", Type:["C"], Rating:"7", Sort:"1", Set:"JOU", Number:"144", Image:"/Images/JOU/144.jpg"},
{Name:"Ajani, Mentor of Heroes", Cost:"5", Color:["W","G"], Rarity:"M", Type:["P"], Rating:"9", Sort:"1", Set:"JOU", Number:"145", Image:"/Images/JOU/145.jpg"},
{Name:"Athreos, God of Passage", Cost:"3", Color:["W","B"], Rarity:"M", Type:["C","E"], Rating:"10", Sort:"1", Set:"JOU", Number:"146", Image:"/Images/JOU/146.jpg"},
{Name:"Desperate Stand", Cost:"2", Color:["W","R"], Rarity:"U", Type:["S"], Rating:"5", Sort:"1", Set:"JOU", Number:"147", Image:"/Images/JOU/147.jpg"},
{Name:"Disciple of Deceit", Cost:"2", Color:["B","U"], Rarity:"U", Type:["C"], Rating:"8", Sort:"1", Set:"JOU", Number:"148", Image:"/Images/JOU/148.jpg"},
{Name:"Fleetfeather Cockatrice", Cost:"5", Color:["G","U"], Rarity:"U", Type:["C"], Rating:"7", Sort:"1", Set:"JOU", Number:"149", Image:"/Images/JOU/149.jpg"},
{Name:"Iroas, God of Victory", Cost:"4", Color:["W","R"], Rarity:"M", Type:["C","E"], Rating:"10", Sort:"1", Set:"JOU", Number:"150", Image:"/Images/JOU/150.jpg"},
{Name:"Keranos, God of Storms", Cost:"5", Color:["R","U"], Rarity:"M", Type:["C","E"], Rating:"10", Sort:"1", Set:"JOU", Number:"151", Image:"/Images/JOU/151.jpg"},
{Name:"Kruphix, God of Horizons", Cost:"5", Color:["G","U"], Rarity:"M", Type:["C","E"], Rating:"9", Sort:"1", Set:"JOU", Number:"152", Image:"/Images/JOU/152.jpg"},
{Name:"Nyxborn Weaver", Cost:"3", Color:["G","B"], Rarity:"U", Type:["C","E"], Rating:"6", Sort:"1", Set:"JOU", Number:"153", Image:"/Images/JOU/153.jpg"},
{Name:"Pharika, God of Affliction", Cost:"3", Color:["G","B"], Rarity:"M", Type:["C","E"], Rating:"9", Sort:"1", Set:"JOU", Number:"154", Image:"/Images/JOU/154.jpg"},
{Name:"Revel of the Fallen God", Cost:"7", Color:["G","R"], Rarity:"R", Type:["S"], Rating:"6", Sort:"1", Set:"JOU", Number:"155", Image:"/Images/JOU/155.jpg"},
{Name:"Stormchaser Chimera", Cost:"4", Color:["R","U"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"JOU", Number:"156", Image:"/Images/JOU/156.jpg"},
{Name:"Underworld Coinsmith", Cost:"2", Color:["W","B"], Rarity:"U", Type:["C","E"], Rating:"6", Sort:"1", Set:"JOU", Number:"157", Image:"/Images/JOU/157.jpg"},
{Name:"Armory of Iroas", Cost:"2", Color:["C"], Rarity:"U", Type:["A"], Rating:"7", Sort:"1", Set:"JOU", Number:"158", Image:"/Images/JOU/158.jpg"},
{Name:"Chariot of Victory", Cost:"3", Color:["C"], Rarity:"U", Type:["A"], Rating:"6", Sort:"1", Set:"JOU", Number:"159", Image:"/Images/JOU/159.jpg"},
{Name:"Deserter's Quarters", Cost:"2", Color:["C"], Rarity:"U", Type:["A"], Rating:"4", Sort:"1", Set:"JOU", Number:"160", Image:"/Images/JOU/160.jpg"},
{Name:"Gold-Forged Sentinel", Cost:"6", Color:["C"], Rarity:"U", Type:["A","C"], Rating:"4", Sort:"1", Set:"JOU", Number:"161", Image:"/Images/JOU/161.jpg"},
{Name:"Hall of Triumph", Cost:"3", Color:["C"], Rarity:"R", Type:["A"], Rating:"7", Sort:"1", Set:"JOU", Number:"162", Image:"/Images/JOU/162.jpg"},
{Name:"Mana Confluence", Cost:"0", Color:["C"], Rarity:"R", Type:["L"], Rating:"8", Sort:"1", Set:"JOU", Number:"163", Image:"/Images/JOU/163.jpg"},
{Name:"Temple of Epiphany", Cost:"0", Color:["U","R"], Rarity:"R", Type:["L"], Rating:"6", Sort:"1", Set:"JOU", Number:"164", Image:"/Images/JOU/164.jpg"},
{Name:"Temple of Malady", Cost:"0", Color:["G","B"], Rarity:"R", Type:["L"], Rating:"6", Sort:"1", Set:"JOU", Number:"165", Image:"/Images/JOU/165.jpg"},
];