var DTK = [
{Name:"Scion of Ugin", Cost:"6", Color:["C"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"DTK", Number:"1", Image:"/Images/DTK/ScionofUgin.jpg"},
{Name:"Anafenza, Kin-Tree Spirit", Cost:"0WW", Color:["W"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"DTK", Number:"2", Image:"/Images/DTK/Anafenza--Kin-TreeSpirit.jpg"},
{Name:"Arashin Foremost", Cost:"1WW", Color:["W"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"DTK", Number:"3", Image:"/Images/DTK/ArashinForemost.jpg"},
{Name:"Artful Maneuver", Cost:"1W", Color:["W"], Rarity:"C", Type:["I"], Rating:"3", Sort:"1", Set:"DTK", Number:"4", Image:"/Images/DTK/ArtfulManeuver.jpg"},
{Name:"Aven Sunstriker", Cost:"1WW", Color:["W"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"DTK", Number:"5", Image:"/Images/DTK/AvenSunstriker.jpg"},
{Name:"Aven Tactician", Cost:"4W", Color:["W"], Rarity:"C", Type:["C"], Rating:"2", Sort:"1", Set:"DTK", Number:"6", Image:"/Images/DTK/AvenTactician.jpg"},
{Name:"Battle Mastery", Cost:"2W", Color:["W"], Rarity:"U", Type:["E"], Rating:"3", Sort:"1", Set:"DTK", Number:"7", Image:"/Images/DTK/BattleMastery.jpg"},
{Name:"Center Soul", Cost:"1W", Color:["W"], Rarity:"C", Type:["I"], Rating:"4", Sort:"1", Set:"DTK", Number:"8", Image:"/Images/DTK/CenterSoul.jpg"},
{Name:"Champion of Arashin", Cost:"3W", Color:["W"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"DTK", Number:"9", Image:"/Images/DTK/ChampionofArashin.jpg"},
{Name:"Dragon Hunter", Cost:"0W", Color:["W"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"DTK", Number:"10", Image:"/Images/DTK/DragonHunter.jpg"},
{Name:"Dragon's Eye Sentry", Cost:"0W", Color:["W"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"DTK", Number:"11", Image:"/Images/DTK/DragonsEyeSentry.jpg"},
{Name:"Dromoka Captain", Cost:"2W", Color:["W"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"DTK", Number:"12", Image:"/Images/DTK/DromokaCaptain.jpg"},
{Name:"Dromoka Dunecaster", Cost:"0W", Color:["W"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"DTK", Number:"13", Image:"/Images/DTK/DromokaDunecaster.jpg"},
{Name:"Dromoka Warrior", Cost:"1W", Color:["W"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"DTK", Number:"14", Image:"/Images/DTK/DromokaWarrior.jpg"},
{Name:"Echoes of the Kin Tree", Cost:"1W", Color:["W"], Rarity:"U", Type:["E"], Rating:"6", Sort:"1", Set:"DTK", Number:"15", Image:"/Images/DTK/EchoesoftheKinTree.jpg"},
{Name:"Enduring Victory", Cost:"4W", Color:["W"], Rarity:"C", Type:["I"], Rating:"6", Sort:"1", Set:"DTK", Number:"16", Image:"/Images/DTK/EnduringVictory.jpg"},
{Name:"Fate Forgotten", Cost:"2W", Color:["W"], Rarity:"C", Type:["I"], Rating:"1", Sort:"1", Set:"DTK", Number:"17", Image:"/Images/DTK/FateForgotten.jpg"},
{Name:"Glaring Aegis", Cost:"0W", Color:["W"], Rarity:"C", Type:["E"], Rating:"2", Sort:"1", Set:"DTK", Number:"18", Image:"/Images/DTK/GlaringAegis.jpg"},
{Name:"Gleam of Authority", Cost:"1W", Color:["W"], Rarity:"R", Type:["E"], Rating:"7", Sort:"1", Set:"DTK", Number:"19", Image:"/Images/DTK/GleamofAuthority.jpg"},
{Name:"Graceblade Artisan", Cost:"2W", Color:["W"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"DTK", Number:"20", Image:"/Images/DTK/GracebladeArtisan.jpg"},
{Name:"Great Teacher's Decree", Cost:"3W", Color:["W"], Rarity:"U", Type:["S"], Rating:"4", Sort:"1", Set:"DTK", Number:"21", Image:"/Images/DTK/GreatTeachersDecree.jpg"},
{Name:"Herald of Dromoka", Cost:"1W", Color:["W"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"DTK", Number:"22", Image:"/Images/DTK/HeraldofDromoka.jpg"},
{Name:"Hidden Dragonslayer", Cost:"1W", Color:["W"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"DTK", Number:"23", Image:"/Images/DTK/HiddenDragonslayer.jpg"},
{Name:"Lightwalker", Cost:"1W", Color:["W"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"DTK", Number:"24", Image:"/Images/DTK/Lightwalker.jpg"},
{Name:"Misthoof Kirin", Cost:"2W", Color:["W"], Rarity:"C", Type:["C"], Rating:"5", Sort:"1", Set:"DTK", Number:"25", Image:"/Images/DTK/MisthoofKirin.jpg"},
{Name:"Myth Realized", Cost:"0W", Color:["W"], Rarity:"R", Type:["E"], Rating:"8", Sort:"1", Set:"DTK", Number:"26", Image:"/Images/DTK/MythRealized.jpg"},
{Name:"Orator of Ojutai", Cost:"1W", Color:["W"], Rarity:"U", Type:["C"], Rating:"7", Sort:"1", Set:"DTK", Number:"27", Image:"/Images/DTK/OratorofOjutai.jpg"},
{Name:"Ojutai Exemplars", Cost:"2WW", Color:["W"], Rarity:"M", Type:["C"], Rating:"9", Sort:"1", Set:"DTK", Number:"28", Image:"/Images/DTK/OjutaiExemplars.jpg"},
{Name:"Pacifism", Cost:"1W", Color:["W"], Rarity:"C", Type:["E"], Rating:"6", Sort:"1", Set:"DTK", Number:"29", Image:"/Images/DTK/Pacifism.jpg"},
{Name:"Profound Journey", Cost:"5WW", Color:["W"], Rarity:"R", Type:["S"], Rating:"6", Sort:"1", Set:"DTK", Number:"30", Image:"/Images/DTK/ProfoundJourney.jpg"},
{Name:"Radiant Purge", Cost:"1W", Color:["W"], Rarity:"R", Type:["I"], Rating:"6", Sort:"1", Set:"DTK", Number:"31", Image:"/Images/DTK/RadiantPurge.jpg"},
{Name:"Resupply", Cost:"5W", Color:["W"], Rarity:"C", Type:["I"], Rating:"1", Sort:"1", Set:"DTK", Number:"32", Image:"/Images/DTK/Resupply.jpg"},
{Name:"Sandcrafter Mage", Cost:"2W", Color:["W"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"DTK", Number:"33", Image:"/Images/DTK/SandcrafterMage.jpg"},
{Name:"Sandstorm Charger", Cost:"4W", Color:["W"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"DTK", Number:"34", Image:"/Images/DTK/SandstormCharger.jpg"},
{Name:"Scale Blessing", Cost:"3W", Color:["W"], Rarity:"U", Type:["I"], Rating:"3", Sort:"1", Set:"DTK", Number:"35", Image:"/Images/DTK/ScaleBlessing.jpg"},
{Name:"Secure the Wastes", Cost:"0W", Color:["W"], Rarity:"R", Type:["I"], Rating:"8", Sort:"1", Set:"DTK", Number:"36", Image:"/Images/DTK/SecuretheWastes.jpg"},
{Name:"Shieldhide Dragon", Cost:"5W", Color:["W"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"DTK", Number:"37", Image:"/Images/DTK/ShieldhideDragon.jpg"},
{Name:"Silkwrap", Cost:"1W", Color:["W"], Rarity:"U", Type:["E"], Rating:"7", Sort:"1", Set:"DTK", Number:"38", Image:"/Images/DTK/Silkwrap.jpg"},
{Name:"Strongarm Monk", Cost:"4W", Color:["W"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"DTK", Number:"39", Image:"/Images/DTK/StrongarmMonk.jpg"},
{Name:"Student of Ojutai", Cost:"3W", Color:["W"], Rarity:"C", Type:["C"], Rating:"2", Sort:"1", Set:"DTK", Number:"40", Image:"/Images/DTK/StudentofOjutai.jpg"},
{Name:"Sunscorch Regent", Cost:"3WW", Color:["W"], Rarity:"R", Type:["C"], Rating:"9", Sort:"1", Set:"DTK", Number:"41", Image:"/Images/DTK/SunscorchRegent.jpg"},
{Name:"Surge of Righteousness", Cost:"1W", Color:["W"], Rarity:"U", Type:["I"], Rating:"4", Sort:"1", Set:"DTK", Number:"42", Image:"/Images/DTK/SurgeofRighteousness.jpg"},
{Name:"Territorial Roc", Cost:"1W", Color:["W"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"DTK", Number:"43", Image:"/Images/DTK/TerritorialRoc.jpg"},
{Name:"Ancient Carp", Cost:"4U", Color:["U"], Rarity:"C", Type:["C"], Rating:"2", Sort:"1", Set:"DTK", Number:"44", Image:"/Images/DTK/AncientCarp.jpg"},
{Name:"Anticipate", Cost:"1U", Color:["U"], Rarity:"C", Type:["I"], Rating:"6", Sort:"1", Set:"DTK", Number:"45", Image:"/Images/DTK/Anticipate.jpg"},
{Name:"Belltoll Dragon", Cost:"5U", Color:["U"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"DTK", Number:"46", Image:"/Images/DTK/BelltollDragon.jpg"},
{Name:"Blessed Reincarnation", Cost:"3U", Color:["U"], Rarity:"R", Type:["I"], Rating:"7", Sort:"1", Set:"DTK", Number:"47", Image:"/Images/DTK/BlessedReincarnation.jpg"},
{Name:"Clone Legion", Cost:"7UU", Color:["U"], Rarity:"M", Type:["S"], Rating:"7", Sort:"1", Set:"DTK", Number:"48", Image:"/Images/DTK/CloneLegion.jpg"},
{Name:"Contradict", Cost:"3UU", Color:["U"], Rarity:"C", Type:["I"], Rating:"3", Sort:"1", Set:"DTK", Number:"49", Image:"/Images/DTK/Contradict.jpg"},
{Name:"Dance of the Skywise", Cost:"1U", Color:["U"], Rarity:"U", Type:["I"], Rating:"3", Sort:"1", Set:"DTK", Number:"50", Image:"/Images/DTK/DanceoftheSkywise.jpg"},
{Name:"Dirgur Nemesis", Cost:"5U", Color:["U"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"DTK", Number:"51", Image:"/Images/DTK/DirgurNemesis.jpg"},
{Name:"Dragonlord's Prerogative", Cost:"4UU", Color:["U"], Rarity:"R", Type:["I"], Rating:"6", Sort:"1", Set:"DTK", Number:"52", Image:"/Images/DTK/DragonlordsPrerogative.jpg"},
{Name:"Elusive Spellfist", Cost:"1U", Color:["U"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"DTK", Number:"53", Image:"/Images/DTK/ElusiveSpellfist.jpg"},
{Name:"Encase in Ice", Cost:"1U", Color:["U"], Rarity:"U", Type:["E"], Rating:"4", Sort:"1", Set:"DTK", Number:"54", Image:"/Images/DTK/EncaseinIce.jpg"},
{Name:"Glint", Cost:"1U", Color:["U"], Rarity:"C", Type:["I"], Rating:"4", Sort:"1", Set:"DTK", Number:"55", Image:"/Images/DTK/Glint.jpg"},
{Name:"Gudul Lurker", Cost:"0U", Color:["U"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"DTK", Number:"56", Image:"/Images/DTK/GudulLurker.jpg"},
{Name:"Gurmag Drowner", Cost:"3U", Color:["U"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"DTK", Number:"57", Image:"/Images/DTK/GurmagDrowner.jpg"},
{Name:"Icefall Regent", Cost:"3UU", Color:["U"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"DTK", Number:"58", Image:"/Images/DTK/IcefallRegent.jpg"},
{Name:"Illusory Gains", Cost:"3UU", Color:["U"], Rarity:"R", Type:["E"], Rating:"6", Sort:"1", Set:"DTK", Number:"59", Image:"/Images/DTK/IllusoryGains.jpg"},
{Name:"Learn from the Past", Cost:"3U", Color:["U"], Rarity:"U", Type:["I"], Rating:"3", Sort:"1", Set:"DTK", Number:"60", Image:"/Images/DTK/LearnfromthePast.jpg"},
{Name:"Living Lore", Cost:"3U", Color:["U"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"DTK", Number:"61", Image:"/Images/DTK/LivingLore.jpg"},
{Name:"Mirror Mockery", Cost:"1U", Color:["U"], Rarity:"R", Type:["E"], Rating:"7", Sort:"1", Set:"DTK", Number:"62", Image:"/Images/DTK/MirrorMockery.jpg"},
{Name:"Monastery Loremaster", Cost:"3U", Color:["U"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"DTK", Number:"63", Image:"/Images/DTK/MonasteryLoremaster.jpg"},
{Name:"Mystic Meditation", Cost:"3U", Color:["U"], Rarity:"C", Type:["S"], Rating:"3", Sort:"1", Set:"DTK", Number:"64", Image:"/Images/DTK/MysticMeditation.jpg"},
{Name:"Negate", Cost:"1U", Color:["U"], Rarity:"C", Type:["I"], Rating:"3", Sort:"1", Set:"DTK", Number:"65", Image:"/Images/DTK/Negate.jpg"},
{Name:"Ojutai Interceptor", Cost:"3U", Color:["U"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"DTK", Number:"66", Image:"/Images/DTK/OjutaiInterceptor.jpg"},
{Name:"Ojutai's Breath", Cost:"2U", Color:["U"], Rarity:"C", Type:["I"], Rating:"4", Sort:"1", Set:"DTK", Number:"67", Image:"/Images/DTK/OjutaisBreath.jpg"},
{Name:"Ojutai's Summons", Cost:"3UU", Color:["U"], Rarity:"C", Type:["S"], Rating:"3", Sort:"1", Set:"DTK", Number:"68", Image:"/Images/DTK/OjutaisSummons.jpg"},
{Name:"Palace Familiar", Cost:"1U", Color:["U"], Rarity:"C", Type:["C"], Rating:"6", Sort:"1", Set:"DTK", Number:"69", Image:"/Images/DTK/PalaceFamiliar.jpg"},
{Name:"Profaner of the Dead", Cost:"3U", Color:["U"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"DTK", Number:"70", Image:"/Images/DTK/ProfaneroftheDead.jpg"},
{Name:"Qarsi Deceiver", Cost:"1U", Color:["U"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"DTK", Number:"71", Image:"/Images/DTK/QarsiDeceiver.jpg"},
{Name:"Reduce in Stature", Cost:"2U", Color:["U"], Rarity:"C", Type:["E"], Rating:"6", Sort:"1", Set:"DTK", Number:"72", Image:"/Images/DTK/ReduceinStature.jpg"},
{Name:"Shorecrasher Elemental", Cost:"0UUU", Color:["U"], Rarity:"M", Type:["C"], Rating:"7", Sort:"1", Set:"DTK", Number:"73", Image:"/Images/DTK/ShorecrasherElemental.jpg"},
{Name:"Sidisi's Faithful", Cost:"0U", Color:["U"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"DTK", Number:"74", Image:"/Images/DTK/SidisisFaithful.jpg"},
{Name:"Sight Beyond Sight", Cost:"3U", Color:["U"], Rarity:"U", Type:["S"], Rating:"7", Sort:"1", Set:"DTK", Number:"75", Image:"/Images/DTK/SightBeyondSight.jpg"},
{Name:"Silumgar Sorcerer", Cost:"1UU", Color:["U"], Rarity:"U", Type:["C"], Rating:"8", Sort:"1", Set:"DTK", Number:"76", Image:"/Images/DTK/SilumgarSorcerer.jpg"},
{Name:"Silumgar Spell-Eater", Cost:"2U", Color:["U"], Rarity:"U", Type:["C"], Rating:"8", Sort:"1", Set:"DTK", Number:"77", Image:"/Images/DTK/SilumgarSpell-Eater.jpg"},
{Name:"Silumgar's Scorn", Cost:"0UU", Color:["U"], Rarity:"U", Type:["I"], Rating:"5", Sort:"1", Set:"DTK", Number:"78", Image:"/Images/DTK/SilumgarsScorn.jpg"},
{Name:"Skywise Teachings", Cost:"0UU", Color:["U"], Rarity:"U", Type:["I"], Rating:"5", Sort:"1", Set:"DTK", Number:"79", Image:"/Images/DTK/SkywiseTeachings.jpg"},
{Name:"Stratus Dancer", Cost:"1U", Color:["U"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"DTK", Number:"80", Image:"/Images/DTK/StratusDancer.jpg"},
{Name:"Taigam's Strike", Cost:"3U", Color:["U"], Rarity:"C", Type:["S"], Rating:"3", Sort:"1", Set:"DTK", Number:"81", Image:"/Images/DTK/TaigamsStrike.jpg"},
{Name:"Updraft Elemental", Cost:"2U", Color:["U"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"DTK", Number:"82", Image:"/Images/DTK/UpdraftElemental.jpg"},
{Name:"Void Squall", Cost:"4U", Color:["U"], Rarity:"U", Type:["S"], Rating:"4", Sort:"1", Set:"DTK", Number:"83", Image:"/Images/DTK/VoidSquall.jpg"},
{Name:"Youthful Scholar", Cost:"3U", Color:["U"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"DTK", Number:"84", Image:"/Images/DTK/YouthfulScholar.jpg"},
{Name:"Zephyr Scribe", Cost:"2U", Color:["U"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"DTK", Number:"85", Image:"/Images/DTK/ZephyrScribe.jpg"},
{Name:"Acid-Spewer Dragon", Cost:"5B", Color:["B"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"DTK", Number:"86", Image:"/Images/DTK/Acid-SpewerDragon.jpg"},
{Name:"Ambuscade Shaman", Cost:"2B", Color:["B"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"DTK", Number:"87", Image:"/Images/DTK/AmbuscadeShaman.jpg"},
{Name:"Blood-Chin Fanatic", Cost:"1BB", Color:["B"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"DTK", Number:"88", Image:"/Images/DTK/Blood-ChinFanatic.jpg"},
{Name:"Blood-Chin Rager", Cost:"1B", Color:["B"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"DTK", Number:"89", Image:"/Images/DTK/Blood-ChinRager.jpg"},
{Name:"Butcher's Glee", Cost:"2B", Color:["B"], Rarity:"C", Type:["I"], Rating:"5", Sort:"1", Set:"DTK", Number:"90", Image:"/Images/DTK/ButchersGlee.jpg"},
{Name:"Coat with Venom", Cost:"0B", Color:["B"], Rarity:"C", Type:["I"], Rating:"3", Sort:"1", Set:"DTK", Number:"91", Image:"/Images/DTK/CoatwithVenom.jpg"},
{Name:"Corpseweft", Cost:"2B", Color:["B"], Rarity:"R", Type:["E"], Rating:"8", Sort:"1", Set:"DTK", Number:"92", Image:"/Images/DTK/Corpseweft.jpg"},
{Name:"Damnable Pact", Cost:"0BB", Color:["B"], Rarity:"R", Type:["S"], Rating:"8", Sort:"1", Set:"DTK", Number:"93", Image:"/Images/DTK/DamnablePact.jpg"},
{Name:"Deadly Wanderings", Cost:"3BB", Color:["B"], Rarity:"U", Type:["E"], Rating:"6", Sort:"1", Set:"DTK", Number:"94", Image:"/Images/DTK/DeadlyWanderings.jpg"},
{Name:"Death Wind", Cost:"0B", Color:["B"], Rarity:"U", Type:["I"], Rating:"7", Sort:"1", Set:"DTK", Number:"95", Image:"/Images/DTK/DeathWind.jpg"},
{Name:"Deathbringer Regent", Cost:"5BB", Color:["B"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"DTK", Number:"96", Image:"/Images/DTK/DeathbringerRegent.jpg"},
{Name:"Defeat", Cost:"1B", Color:["B"], Rarity:"C", Type:["S"], Rating:"4", Sort:"1", Set:"DTK", Number:"97", Image:"/Images/DTK/Defeat.jpg"},
{Name:"Duress", Cost:"0B", Color:["B"], Rarity:"C", Type:["S"], Rating:"4", Sort:"1", Set:"DTK", Number:"98", Image:"/Images/DTK/Duress.jpg"},
{Name:"Dutiful Attendant", Cost:"2B", Color:["B"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"DTK", Number:"99", Image:"/Images/DTK/DutifulAttendant.jpg"},
{Name:"Flatten", Cost:"3B", Color:["B"], Rarity:"C", Type:["I"], Rating:"5", Sort:"1", Set:"DTK", Number:"100", Image:"/Images/DTK/Flatten.jpg"},
{Name:"Foul Renewal", Cost:"3B", Color:["B"], Rarity:"R", Type:["I"], Rating:"8", Sort:"1", Set:"DTK", Number:"101", Image:"/Images/DTK/FoulRenewal.jpg"},
{Name:"Foul-Tongue Invocation", Cost:"2B", Color:["B"], Rarity:"U", Type:["I"], Rating:"8", Sort:"1", Set:"DTK", Number:"102", Image:"/Images/DTK/Foul-TongueInvocation.jpg"},
{Name:"Foul-Tongue Shriek", Cost:"0B", Color:["B"], Rarity:"C", Type:["I"], Rating:"2", Sort:"1", Set:"DTK", Number:"103", Image:"/Images/DTK/Foul-TongueShriek.jpg"},
{Name:"Gravepurge", Cost:"2B", Color:["B"], Rarity:"C", Type:["I"], Rating:"4", Sort:"1", Set:"DTK", Number:"104", Image:"/Images/DTK/Gravepurge.jpg"},
{Name:"Hand of Silumgar", Cost:"1B", Color:["B"], Rarity:"C", Type:["C"], Rating:"5", Sort:"1", Set:"DTK", Number:"105", Image:"/Images/DTK/HandofSilumgar.jpg"},
{Name:"Hedonist's Trove", Cost:"5BB", Color:["B"], Rarity:"R", Type:["E"], Rating:"8", Sort:"1", Set:"DTK", Number:"106", Image:"/Images/DTK/HedonistsTrove.jpg"},
{Name:"Kolaghan Skirmisher", Cost:"1B", Color:["B"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"DTK", Number:"107", Image:"/Images/DTK/KolaghanSkirmisher.jpg"},
{Name:"Marang River Skeleton", Cost:"1B", Color:["B"], Rarity:"U", Type:["C"], Rating:"3", Sort:"1", Set:"DTK", Number:"108", Image:"/Images/DTK/MarangRiverSkeleton.jpg"},
{Name:"Marsh Hulk", Cost:"4BB", Color:["B"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"DTK", Number:"109", Image:"/Images/DTK/MarshHulk.jpg"},
{Name:"Mind Rot", Cost:"2B", Color:["B"], Rarity:"C", Type:["S"], Rating:"3", Sort:"1", Set:"DTK", Number:"110", Image:"/Images/DTK/MindRot.jpg"},
{Name:"Minister of Pain", Cost:"2B", Color:["B"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"DTK", Number:"111", Image:"/Images/DTK/MinisterofPain.jpg"},
{Name:"Pitiless Horde", Cost:"2B", Color:["B"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"DTK", Number:"112", Image:"/Images/DTK/PitilessHorde.jpg"},
{Name:"Qarsi Sadist", Cost:"1B", Color:["B"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"DTK", Number:"113", Image:"/Images/DTK/QarsiSadist.jpg"},
{Name:"Rakshasa Gravecaller", Cost:"4B", Color:["B"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"DTK", Number:"114", Image:"/Images/DTK/RakshasaGravecaller.jpg"},
{Name:"Reckless Imp", Cost:"2B", Color:["B"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"DTK", Number:"115", Image:"/Images/DTK/RecklessImp.jpg"},
{Name:"Risen Executioner", Cost:"2BB", Color:["B"], Rarity:"M", Type:["C"], Rating:"9", Sort:"1", Set:"DTK", Number:"116", Image:"/Images/DTK/RisenExecutioner.jpg"},
{Name:"Self-Inflicted Wound", Cost:"1B", Color:["B"], Rarity:"U", Type:["S"], Rating:"4", Sort:"1", Set:"DTK", Number:"117", Image:"/Images/DTK/Self-InflictedWound.jpg"},
{Name:"Shambling Goblin", Cost:"0B", Color:["B"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"DTK", Number:"118", Image:"/Images/DTK/ShamblingGoblin.jpg"},
{Name:"Sibsig Icebreakers", Cost:"2B", Color:["B"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"DTK", Number:"119", Image:"/Images/DTK/SibsigIcebreakers.jpg"},
{Name:"Sidisi, Undead Vizier", Cost:"3BB", Color:["B"], Rarity:"R", Type:["C"], Rating:"9", Sort:"1", Set:"DTK", Number:"120", Image:"/Images/DTK/Sidisi--UndeadVizier.jpg"},
{Name:"Silumgar's Assassin", Cost:"1B", Color:["B"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"DTK", Number:"121", Image:"/Images/DTK/SilumgarsAssassin.jpg"},
{Name:"Silumgar Butcher", Cost:"4B", Color:["B"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"DTK", Number:"122", Image:"/Images/DTK/SilumgarButcher.jpg"},
{Name:"Ukud Cobra", Cost:"3B", Color:["B"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"DTK", Number:"123", Image:"/Images/DTK/UkudCobra.jpg"},
{Name:"Ultimate Price", Cost:"1B", Color:["B"], Rarity:"U", Type:["I"], Rating:"8", Sort:"1", Set:"DTK", Number:"124", Image:"/Images/DTK/UltimatePrice.jpg"},
{Name:"Virulent Plague", Cost:"2B", Color:["B"], Rarity:"U", Type:["E"], Rating:"2", Sort:"1", Set:"DTK", Number:"125", Image:"/Images/DTK/VirulentPlague.jpg"},
{Name:"Vulturous Aven", Cost:"3B", Color:["B"], Rarity:"C", Type:["C"], Rating:"5", Sort:"1", Set:"DTK", Number:"126", Image:"/Images/DTK/VulturousAven.jpg"},
{Name:"Wandering Tombshell", Cost:"3B", Color:["B"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"DTK", Number:"127", Image:"/Images/DTK/WanderingTombshell.jpg"},
{Name:"Atarka Efreet", Cost:"3R", Color:["R"], Rarity:"C", Type:["C"], Rating:"5", Sort:"1", Set:"DTK", Number:"128", Image:"/Images/DTK/AtarkaEfreet.jpg"},
{Name:"Atarka Pummeler", Cost:"4R", Color:["R"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"DTK", Number:"129", Image:"/Images/DTK/AtarkaPummeler.jpg"},
{Name:"Berserkers' Onslaught", Cost:"3RR", Color:["R"], Rarity:"R", Type:["E"], Rating:"7", Sort:"1", Set:"DTK", Number:"130", Image:"/Images/DTK/BerserkersOnslaught.jpg"},
{Name:"Commune with Lava", Cost:"0RR", Color:["R"], Rarity:"R", Type:["I"], Rating:"8", Sort:"1", Set:"DTK", Number:"131", Image:"/Images/DTK/CommunewithLava.jpg"},
{Name:"Crater Elemental", Cost:"1R", Color:["R"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"DTK", Number:"132", Image:"/Images/DTK/CraterElemental.jpg"},
{Name:"Descent of the Dragons", Cost:"4RR", Color:["R"], Rarity:"M", Type:["S"], Rating:"9", Sort:"1", Set:"DTK", Number:"133", Image:"/Images/DTK/DescentoftheDragons.jpg"},
{Name:"Draconic Roar", Cost:"1R", Color:["R"], Rarity:"U", Type:["I"], Rating:"7", Sort:"1", Set:"DTK", Number:"134", Image:"/Images/DTK/DraconicRoar.jpg"},
{Name:"Dragon Fodder", Cost:"1R", Color:["R"], Rarity:"C", Type:["S"], Rating:"5", Sort:"1", Set:"DTK", Number:"135", Image:"/Images/DTK/DragonFodder.jpg"},
{Name:"Dragon Tempest", Cost:"1R", Color:["R"], Rarity:"R", Type:["E"], Rating:"6", Sort:"1", Set:"DTK", Number:"136", Image:"/Images/DTK/DragonTempest.jpg"},
{Name:"Dragon Whisperer", Cost:"0RR", Color:["R"], Rarity:"M", Type:["C"], Rating:"9", Sort:"1", Set:"DTK", Number:"137", Image:"/Images/DTK/DragonWhisperer.jpg"},
{Name:"Dragonlord's Servant", Cost:"1R", Color:["R"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"DTK", Number:"138", Image:"/Images/DTK/DragonlordsServant.jpg"},
{Name:"Hardened Berserker", Cost:"2R", Color:["R"], Rarity:"C", Type:["C"], Rating:"5", Sort:"1", Set:"DTK", Number:"139", Image:"/Images/DTK/HardenedBerserker.jpg"},
{Name:"Impact Tremors", Cost:"1R", Color:["R"], Rarity:"C", Type:["E"], Rating:"3", Sort:"1", Set:"DTK", Number:"140", Image:"/Images/DTK/ImpactTremors.jpg"},
{Name:"Ire Shaman", Cost:"1R", Color:["R"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"DTK", Number:"141", Image:"/Images/DTK/IreShaman.jpg"},
{Name:"Kindled Fury", Cost:"0R", Color:["R"], Rarity:"C", Type:["I"], Rating:"3", Sort:"1", Set:"DTK", Number:"142", Image:"/Images/DTK/KindledFury.jpg"},
{Name:"Kolaghan Aspirant", Cost:"1R", Color:["R"], Rarity:"C", Type:["C"], Rating:"5", Sort:"1", Set:"DTK", Number:"143", Image:"/Images/DTK/KolaghanAspirant.jpg"},
{Name:"Kolaghan Forerunners", Cost:"2R", Color:["R"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"DTK", Number:"144", Image:"/Images/DTK/KolaghanForerunners.jpg"},
{Name:"Kolaghan Stormsinger", Cost:"0R", Color:["R"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"DTK", Number:"145", Image:"/Images/DTK/KolaghanStormsinger.jpg"},
{Name:"Lightning Berserker", Cost:"0R", Color:["R"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"DTK", Number:"146", Image:"/Images/DTK/LightningBerserker.jpg"},
{Name:"Lose Calm", Cost:"3R", Color:["R"], Rarity:"C", Type:["S"], Rating:"3", Sort:"1", Set:"DTK", Number:"147", Image:"/Images/DTK/LoseCalm.jpg"},
{Name:"Magmatic Chasm", Cost:"1R", Color:["R"], Rarity:"C", Type:["S"], Rating:"2", Sort:"1", Set:"DTK", Number:"148", Image:"/Images/DTK/MagmaticChasm.jpg"},
{Name:"Qal Sisma Behemoth", Cost:"2R", Color:["R"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"DTK", Number:"149", Image:"/Images/DTK/QalSismaBehemoth.jpg"},
{Name:"Rending Volley", Cost:"0R", Color:["R"], Rarity:"U", Type:["I"], Rating:"5", Sort:"1", Set:"DTK", Number:"150", Image:"/Images/DTK/RendingVolley.jpg"},
{Name:"Roast", Cost:"1R", Color:["R"], Rarity:"U", Type:["S"], Rating:"6", Sort:"1", Set:"DTK", Number:"151", Image:"/Images/DTK/Roast.jpg"},
{Name:"Sabertooth Outrider", Cost:"3R", Color:["R"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"DTK", Number:"152", Image:"/Images/DTK/SabertoothOutrider.jpg"},
{Name:"Sarkhan's Rage", Cost:"4R", Color:["R"], Rarity:"C", Type:["I"], Rating:"7", Sort:"1", Set:"DTK", Number:"153", Image:"/Images/DTK/SarkhansRage.jpg"},
{Name:"Sarkhan's Triumph", Cost:"2R", Color:["R"], Rarity:"U", Type:["I"], Rating:"6", Sort:"1", Set:"DTK", Number:"154", Image:"/Images/DTK/SarkhansTriumph.jpg"},
{Name:"Screamreach Brawler", Cost:"2R", Color:["R"], Rarity:"C", Type:["I"], Rating:"4", Sort:"1", Set:"DTK", Number:"155", Image:"/Images/DTK/ScreamreachBrawler.jpg"},
{Name:"Seismic Rupture", Cost:"2R", Color:["R"], Rarity:"U", Type:["C"], Rating:"7", Sort:"1", Set:"DTK", Number:"156", Image:"/Images/DTK/SeismicRupture.jpg"},
{Name:"Sprinting Warbrute", Cost:"4R", Color:["R"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"DTK", Number:"157", Image:"/Images/DTK/SprintingWarbrute.jpg"},
{Name:"Stormcrag Elemental", Cost:"5R", Color:["R"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"DTK", Number:"158", Image:"/Images/DTK/StormcragElemental.jpg"},
{Name:"Stormwing Dragon", Cost:"5R", Color:["R"], Rarity:"U", Type:["C"], Rating:"3", Sort:"1", Set:"DTK", Number:"159", Image:"/Images/DTK/StormwingDragon.jpg"},
{Name:"Summit Prowler", Cost:"2RR", Color:["R"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"DTK", Number:"160", Image:"/Images/DTK/SummitProwler.jpg"},
{Name:"Tail Slash", Cost:"2R", Color:["R"], Rarity:"C", Type:["I"], Rating:"5", Sort:"1", Set:"DTK", Number:"161", Image:"/Images/DTK/TailSlash.jpg"},
{Name:"Thunderbreak Regent", Cost:"2RR", Color:["R"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"DTK", Number:"162", Image:"/Images/DTK/ThunderbreakRegent.jpg"},
{Name:"Tormenting Voice", Cost:"1R", Color:["R"], Rarity:"C", Type:["S"], Rating:"5", Sort:"1", Set:"DTK", Number:"163", Image:"/Images/DTK/TormentingVoice.jpg"},
{Name:"Twin Bolt", Cost:"1R", Color:["R"], Rarity:"C", Type:["I"], Rating:"6", Sort:"1", Set:"DTK", Number:"164", Image:"/Images/DTK/TwinBolt.jpg"},
{Name:"Vandalize", Cost:"4R", Color:["R"], Rarity:"C", Type:["S"], Rating:"3", Sort:"1", Set:"DTK", Number:"165", Image:"/Images/DTK/Vandalize.jpg"},
{Name:"Volcanic Rush", Cost:"4R", Color:["R"], Rarity:"C", Type:["I"], Rating:"2", Sort:"1", Set:"DTK", Number:"166", Image:"/Images/DTK/VolcanicRush.jpg"},
{Name:"Volcanic Vision", Cost:"5RR", Color:["R"], Rarity:"R", Type:["S"], Rating:"6", Sort:"1", Set:"DTK", Number:"167", Image:"/Images/DTK/VolcanicVision.jpg"},
{Name:"Warbringer", Cost:"3R", Color:["R"], Rarity:"U", Type:["C"], Rating:"7", Sort:"1", Set:"DTK", Number:"168", Image:"/Images/DTK/Warbringer.jpg"},
{Name:"Zurgo Bellstriker", Cost:"0R", Color:["R"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"DTK", Number:"169", Image:"/Images/DTK/ZurgoBellstriker.jpg"},
{Name:"Aerie Bowmasters", Cost:"2GG", Color:["G"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"DTK", Number:"170", Image:"/Images/DTK/AerieBowmasters.jpg"},
{Name:"Ainok Artillerist", Cost:"2G", Color:["G"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"DTK", Number:"171", Image:"/Images/DTK/AinokArtillerist.jpg"},
{Name:"Ainok Survivalist", Cost:"1G", Color:["G"], Rarity:"U", Type:["C"], Rating:"7", Sort:"1", Set:"DTK", Number:"172", Image:"/Images/DTK/AinokSurvivalist.jpg"},
{Name:"Assault Formation", Cost:"1G", Color:["G"], Rarity:"R", Type:["E"], Rating:"7", Sort:"1", Set:"DTK", Number:"173", Image:"/Images/DTK/AssaultFormation.jpg"},
{Name:"Atarka Beastbreaker", Cost:"1G", Color:["G"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"DTK", Number:"174", Image:"/Images/DTK/AtarkaBeastbreaker.jpg"},
{Name:"Avatar of the Resolute", Cost:"0GG", Color:["G"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"DTK", Number:"175", Image:"/Images/DTK/AvataroftheResolute.jpg"},
{Name:"Circle of Elders", Cost:"2GG", Color:["G"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"DTK", Number:"176", Image:"/Images/DTK/CircleofElders.jpg"},
{Name:"Collected Company", Cost:"3G", Color:["G"], Rarity:"R", Type:["I"], Rating:"7", Sort:"1", Set:"DTK", Number:"177", Image:"/Images/DTK/CollectedCompany.jpg"},
{Name:"Colossodon Yearling", Cost:"2G", Color:["G"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"DTK", Number:"178", Image:"/Images/DTK/ColossodonYearling.jpg"},
{Name:"Conifer Strider", Cost:"3G", Color:["G"], Rarity:"C", Type:["C"], Rating:"5", Sort:"1", Set:"DTK", Number:"179", Image:"/Images/DTK/ConiferStrider.jpg"},
{Name:"Deathmist Raptor", Cost:"1GG", Color:["G"], Rarity:"M", Type:["C"], Rating:"9", Sort:"1", Set:"DTK", Number:"180", Image:"/Images/DTK/DeathmistRaptor.jpg"},
{Name:"Den Protector", Cost:"1G", Color:["G"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"DTK", Number:"181", Image:"/Images/DTK/DenProtector.jpg"},
{Name:"Display of Dominance", Cost:"1G", Color:["G"], Rarity:"U", Type:["I"], Rating:"3", Sort:"1", Set:"DTK", Number:"182", Image:"/Images/DTK/DisplayofDominance.jpg"},
{Name:"Dragon-Scarred Bear", Cost:"2G", Color:["G"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"DTK", Number:"183", Image:"/Images/DTK/Dragon-ScarredBear.jpg"},
{Name:"Dromoka's Gift", Cost:"4G", Color:["G"], Rarity:"U", Type:["I"], Rating:"4", Sort:"1", Set:"DTK", Number:"184", Image:"/Images/DTK/DromokasGift.jpg"},
{Name:"Epic Confrontation", Cost:"1G", Color:["G"], Rarity:"C", Type:["S"], Rating:"5", Sort:"1", Set:"DTK", Number:"185", Image:"/Images/DTK/EpicConfrontation.jpg"},
{Name:"Explosive Vegetation", Cost:"3G", Color:["G"], Rarity:"U", Type:["S"], Rating:"7", Sort:"1", Set:"DTK", Number:"186", Image:"/Images/DTK/ExplosiveVegetation.jpg"},
{Name:"Foe-Razer Regent", Cost:"5GG", Color:["G"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"DTK", Number:"187", Image:"/Images/DTK/Foe-RazerRegent.jpg"},
{Name:"Glade Watcher", Cost:"1G", Color:["G"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"DTK", Number:"188", Image:"/Images/DTK/GladeWatcher.jpg"},
{Name:"Guardian Shield-Bearer", Cost:"1G", Color:["G"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"DTK", Number:"189", Image:"/Images/DTK/GuardianShield-Bearer.jpg"},
{Name:"Herdchaser Dragon", Cost:"5G", Color:["G"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"DTK", Number:"190", Image:"/Images/DTK/HerdchaserDragon.jpg"},
{Name:"Inspiring Call", Cost:"2G", Color:["G"], Rarity:"U", Type:["I"], Rating:"6", Sort:"1", Set:"DTK", Number:"191", Image:"/Images/DTK/InspiringCall.jpg"},
{Name:"Lurking Arynx", Cost:"4G", Color:["G"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"DTK", Number:"192", Image:"/Images/DTK/LurkingArynx.jpg"},
{Name:"Naturalize", Cost:"1G", Color:["G"], Rarity:"C", Type:["I"], Rating:"2", Sort:"1", Set:"DTK", Number:"193", Image:"/Images/DTK/Naturalize.jpg"},
{Name:"Obscuring AEther", Cost:"0G", Color:["G"], Rarity:"R", Type:["E"], Rating:"8", Sort:"1", Set:"DTK", Number:"194", Image:"/Images/DTK/ObscuringAEther.jpg"},
{Name:"Pinion Feast", Cost:"4G", Color:["G"], Rarity:"C", Type:["I"], Rating:"4", Sort:"1", Set:"DTK", Number:"195", Image:"/Images/DTK/PinionFeast.jpg"},
{Name:"Press the Advantage", Cost:"2GG", Color:["G"], Rarity:"U", Type:["I"], Rating:"5", Sort:"1", Set:"DTK", Number:"196", Image:"/Images/DTK/PresstheAdvantage.jpg"},
{Name:"Revealing Wind", Cost:"2G", Color:["G"], Rarity:"C", Type:["I"], Rating:"2", Sort:"1", Set:"DTK", Number:"197", Image:"/Images/DTK/RevealingWind.jpg"},
{Name:"Salt Road Ambushers", Cost:"3G", Color:["G"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"DTK", Number:"198", Image:"/Images/DTK/SaltRoadAmbushers.jpg"},
{Name:"Salt Road Quartermasters", Cost:"2G", Color:["G"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"DTK", Number:"199", Image:"/Images/DTK/SaltRoadQuartermasters.jpg"},
{Name:"Sandsteppe Scavenger", Cost:"4G", Color:["G"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"DTK", Number:"200", Image:"/Images/DTK/SandsteppeScavenger.jpg"},
{Name:"Scaleguard Sentinels", Cost:"0GG", Color:["G"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"DTK", Number:"201", Image:"/Images/DTK/ScaleguardSentinels.jpg"},
{Name:"Segmented Krotiq", Cost:"5G", Color:["G"], Rarity:"C", Type:["C"], Rating:"5", Sort:"1", Set:"DTK", Number:"202", Image:"/Images/DTK/SegmentedKrotiq.jpg"},
{Name:"Servant of the Scale", Cost:"0G", Color:["G"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"DTK", Number:"203", Image:"/Images/DTK/ServantoftheScale.jpg"},
{Name:"Shaman of Forgotten Ways", Cost:"2G", Color:["G"], Rarity:"M", Type:["C"], Rating:"9", Sort:"1", Set:"DTK", Number:"204", Image:"/Images/DTK/ShamanofForgottenWays.jpg"},
{Name:"Shape the Sands", Cost:"0G", Color:["G"], Rarity:"C", Type:["I"], Rating:"3", Sort:"1", Set:"DTK", Number:"205", Image:"/Images/DTK/ShapetheSands.jpg"},
{Name:"Sheltered Aerie", Cost:"2G", Color:["G"], Rarity:"C", Type:["E"], Rating:"4", Sort:"1", Set:"DTK", Number:"206", Image:"/Images/DTK/ShelteredAerie.jpg"},
{Name:"Sight of the Scalelords", Cost:"4G", Color:["G"], Rarity:"U", Type:["E"], Rating:"6", Sort:"1", Set:"DTK", Number:"207", Image:"/Images/DTK/SightoftheScalelords.jpg"},
{Name:"Stampeding Elk Herd", Cost:"3GG", Color:["G"], Rarity:"C", Type:["C"], Rating:"5", Sort:"1", Set:"DTK", Number:"208", Image:"/Images/DTK/StampedingElkHerd.jpg"},
{Name:"Sunbringer's Touch", Cost:"2GG", Color:["G"], Rarity:"R", Type:["S"], Rating:"6", Sort:"1", Set:"DTK", Number:"209", Image:"/Images/DTK/SunbringersTouch.jpg"},
{Name:"Surrak, the Hunt Caller", Cost:"2GG", Color:["G"], Rarity:"R", Type:["C"], Rating:"6", Sort:"1", Set:"DTK", Number:"210", Image:"/Images/DTK/Surrak--theHuntCaller.jpg"},
{Name:"Tread Upon", Cost:"1G", Color:["G"], Rarity:"C", Type:["I"], Rating:"3", Sort:"1", Set:"DTK", Number:"211", Image:"/Images/DTK/TreadUpon.jpg"},
{Name:"Arashin Sovereign", Cost:"5WG", Color:["W","G"], Rarity:"R", Type:["C"], Rating:"9", Sort:"1", Set:"DTK", Number:"212", Image:"/Images/DTK/ArashinSovereign.jpg"},
{Name:"Atarka's Command", Cost:"0RG", Color:["R","G"], Rarity:"R", Type:["I"], Rating:"7", Sort:"1", Set:"DTK", Number:"213", Image:"/Images/DTK/AtarkasCommand.jpg"},
{Name:"Boltwing Marauder", Cost:"3BR", Color:["B","R"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"DTK", Number:"214", Image:"/Images/DTK/BoltwingMarauder.jpg"},
{Name:"Cunning Breezedancer", Cost:"4WU", Color:["W","U"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"DTK", Number:"215", Image:"/Images/DTK/CunningBreezedancer.jpg"},
{Name:"Dragonlord Atarka", Cost:"5RG", Color:["R","G"], Rarity:"M", Type:["C"], Rating:"9", Sort:"1", Set:"DTK", Number:"216", Image:"/Images/DTK/DragonlordAtarka.jpg"},
{Name:"Dragonlord Dromoka", Cost:"4WG", Color:["W","G"], Rarity:"M", Type:["C"], Rating:"9", Sort:"1", Set:"DTK", Number:"217", Image:"/Images/DTK/DragonlordDromoka.jpg"},
{Name:"Dragonlord Kolaghan", Cost:"4BR", Color:["B","R"], Rarity:"M", Type:["C"], Rating:"9", Sort:"1", Set:"DTK", Number:"218", Image:"/Images/DTK/DragonlordKolaghan.jpg"},
{Name:"Dragonlord Ojutai", Cost:"3WU", Color:["W","U"], Rarity:"M", Type:["C"], Rating:"9", Sort:"1", Set:"DTK", Number:"219", Image:"/Images/DTK/DragonlordOjutai.jpg"},
{Name:"Dragonlord Silumgar", Cost:"4UB", Color:["U","B"], Rarity:"M", Type:["C"], Rating:"9", Sort:"1", Set:"DTK", Number:"220", Image:"/Images/DTK/DragonlordSilumgar.jpg"},
{Name:"Dromoka's Command", Cost:"0WG", Color:["W","G"], Rarity:"R", Type:["I"], Rating:"7", Sort:"1", Set:"DTK", Number:"221", Image:"/Images/DTK/DromokasCommand.jpg"},
{Name:"Enduring Scalelord", Cost:"4WG", Color:["W","G"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"DTK", Number:"222", Image:"/Images/DTK/EnduringScalelord.jpg"},
{Name:"Harbinger of the Hunt", Cost:"3RG", Color:["R","G"], Rarity:"R", Type:["C"], Rating:"9", Sort:"1", Set:"DTK", Number:"223", Image:"/Images/DTK/HarbingeroftheHunt.jpg"},
{Name:"Kolaghan's Command", Cost:"1BR", Color:["B","R"], Rarity:"R", Type:["I"], Rating:"8", Sort:"1", Set:"DTK", Number:"224", Image:"/Images/DTK/KolaghansCommand.jpg"},
{Name:"Narset Transcendent", Cost:"2WU", Color:["W","U"], Rarity:"M", Type:["P"], Rating:"10", Sort:"1", Set:"DTK", Number:"225", Image:"/Images/DTK/NarsetTranscendent.jpg"},
{Name:"Necromaster Dragon", Cost:"3UB", Color:["U","B"], Rarity:"R", Type:["C"], Rating:"9", Sort:"1", Set:"DTK", Number:"226", Image:"/Images/DTK/NecromasterDragon.jpg"},
{Name:"Ojutai's Command", Cost:"2WU", Color:["W","U"], Rarity:"R", Type:["I"], Rating:"9", Sort:"1", Set:"DTK", Number:"227", Image:"/Images/DTK/OjutaisCommand.jpg"},
{Name:"Pristine Skywise", Cost:"4WU", Color:["W","U"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"DTK", Number:"228", Image:"/Images/DTK/PristineSkywise.jpg"},
{Name:"Ruthless Deathfang", Cost:"4UB", Color:["U","B"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"DTK", Number:"229", Image:"/Images/DTK/RuthlessDeathfang.jpg"},
{Name:"Sarkhan Unbroken", Cost:"2URG", Color:["U","R","G"], Rarity:"M", Type:["P"], Rating:"9", Sort:"1", Set:"DTK", Number:"230", Image:"/Images/DTK/SarkhanUnbroken.jpg"},
{Name:"Savage Ventmaw", Cost:"4RG", Color:["R","G"], Rarity:"U", Type:["C"], Rating:"7", Sort:"1", Set:"DTK", Number:"231", Image:"/Images/DTK/SavageVentmaw.jpg"},
{Name:"Silumgar's Command", Cost:"3UB", Color:["U","B"], Rarity:"R", Type:["I"], Rating:"8", Sort:"1", Set:"DTK", Number:"232", Image:"/Images/DTK/SilumgarsCommand.jpg"},
{Name:"Swift Warkite", Cost:"4BR", Color:["B","R"], Rarity:"U", Type:["C"], Rating:"7", Sort:"1", Set:"DTK", Number:"233", Image:"/Images/DTK/SwiftWarkite.jpg"},
{Name:"Ancestral Statue", Cost:"4", Color:["C"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"DTK", Number:"234", Image:"/Images/DTK/AncestralStatue.jpg"},
{Name:"Atarka Monument", Cost:"3", Color:["C"], Rarity:"U", Type:["A"], Rating:"5", Sort:"1", Set:"DTK", Number:"235", Image:"/Images/DTK/AtarkaMonument.jpg"},
{Name:"Custodian of the Trove", Cost:"3", Color:["C"], Rarity:"C", Type:["A"], Rating:"3", Sort:"1", Set:"DTK", Number:"236", Image:"/Images/DTK/CustodianoftheTrove.jpg"},
{Name:"Dragonloft Idol", Cost:"4", Color:["C"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"DTK", Number:"237", Image:"/Images/DTK/DragonloftIdol.jpg"},
{Name:"Dromoka Monument", Cost:"3", Color:["C"], Rarity:"U", Type:["A"], Rating:"5", Sort:"1", Set:"DTK", Number:"238", Image:"/Images/DTK/DromokaMonument.jpg"},
{Name:"Gate Smasher", Cost:"3", Color:["C"], Rarity:"U", Type:["A"], Rating:"4", Sort:"1", Set:"DTK", Number:"239", Image:"/Images/DTK/GateSmasher.jpg"},
{Name:"Keeper of the Lens", Cost:"1", Color:["C"], Rarity:"C", Type:["C"], Rating:"2", Sort:"1", Set:"DTK", Number:"240", Image:"/Images/DTK/KeeperoftheLens.jpg"},
{Name:"Kolaghan Monument", Cost:"3", Color:["C"], Rarity:"U", Type:["A"], Rating:"5", Sort:"1", Set:"DTK", Number:"241", Image:"/Images/DTK/KolaghanMonument.jpg"},
{Name:"Ojutai Monument", Cost:"3", Color:["C"], Rarity:"U", Type:["A"], Rating:"5", Sort:"1", Set:"DTK", Number:"242", Image:"/Images/DTK/OjutaiMonument.jpg"},
{Name:"Silumgar Monument", Cost:"3", Color:["C"], Rarity:"U", Type:["A"], Rating:"5", Sort:"1", Set:"DTK", Number:"243", Image:"/Images/DTK/SilumgarMonument.jpg"},
{Name:"Spidersilk Net", Cost:"0", Color:["C"], Rarity:"C", Type:["A"], Rating:"3", Sort:"1", Set:"DTK", Number:"244", Image:"/Images/DTK/SpidersilkNet.jpg"},
{Name:"Stormrider Rig", Cost:"2", Color:["C"], Rarity:"U", Type:["A"], Rating:"4", Sort:"1", Set:"DTK", Number:"245", Image:"/Images/DTK/StormriderRig.jpg"},
{Name:"Tapestry of the Ages", Cost:"4", Color:["C"], Rarity:"U", Type:["A"], Rating:"3", Sort:"1", Set:"DTK", Number:"246", Image:"/Images/DTK/TapestryoftheAges.jpg"},
{Name:"Vial of Dragonfire", Cost:"2", Color:["C"], Rarity:"C", Type:["A"], Rating:"4", Sort:"1", Set:"DTK", Number:"247", Image:"/Images/DTK/VialofDragonfire.jpg"},
{Name:"Evolving Wilds", Cost:"0", Color:["C"], Rarity:"C", Type:["L"], Rating:"5", Sort:"1", Set:"DTK", Number:"248", Image:"/Images/DTK/EvolvingWilds.jpg"},
{Name:"Haven of the Spirit Dragon", Cost:"0", Color:["C"], Rarity:"R", Type:["L"], Rating:"7", Sort:"1", Set:"DTK", Number:"249", Image:"/Images/DTK/HavenoftheSpiritDragon.jpg"},
];