var BFZ = [
{Name:"Bane of Bala Ged", Cost:"7", Color:["C"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"BFZ", Number:"1", Image:"/Images/BFZ/BaneofBalaGed.jpg"},
{Name:"Blight Herder", Cost:"5", Color:["C"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"BFZ", Number:"2", Image:"/Images/BFZ/BlightHerder.jpg"},
{Name:"Breaker of Armies", Cost:"8", Color:["C"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"BFZ", Number:"3", Image:"/Images/BFZ/BreakerofArmies.jpg"},
{Name:"Conduit of Ruin", Cost:"6", Color:["C"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"BFZ", Number:"4", Image:"/Images/BFZ/ConduitofRuin.jpg"},
{Name:"Deathless Behemoth", Cost:"6", Color:["C"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"BFZ", Number:"5", Image:"/Images/BFZ/DeathlessBehemoth.jpg"},
{Name:"Desolation Twin", Cost:"9", Color:["C"], Rarity:"R", Type:["C"], Rating:"6", Sort:"1", Set:"BFZ", Number:"6", Image:"/Images/BFZ/DesolationTwin.jpg"},
{Name:"Eldrazi Devastator", Cost:"8", Color:["C"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"BFZ", Number:"7", Image:"/Images/BFZ/EldraziDevastator.jpg"},
{Name:"Endless One", Cost:"0", Color:["C"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"BFZ", Number:"8", Image:"/Images/BFZ/EndlessOne.jpg"},
{Name:"Gruesome Slaughter", Cost:"6", Color:["C"], Rarity:"R", Type:["S"], Rating:"6", Sort:"1", Set:"BFZ", Number:"9", Image:"/Images/BFZ/GruesomeSlaughter.jpg"},
{Name:"Kozilek's Channeler", Cost:"5", Color:["C"], Rarity:"C", Type:["C"], Rating:"2", Sort:"1", Set:"BFZ", Number:"10", Image:"/Images/BFZ/KozileksChanneler.jpg"},
{Name:"Oblivion Sower", Cost:"6", Color:["C"], Rarity:"M", Type:["C"], Rating:"9", Sort:"1", Set:"BFZ", Number:"11", Image:"/Images/BFZ/OblivionSower.jpg"},
{Name:"Ruin Processor", Cost:"7", Color:["C"], Rarity:"C", Type:["C"], Rating:"2", Sort:"1", Set:"BFZ", Number:"12", Image:"/Images/BFZ/RuinProcessor.jpg"},
{Name:"Scour from Existence", Cost:"7", Color:["C"], Rarity:"C", Type:["I"], Rating:"3", Sort:"1", Set:"BFZ", Number:"13", Image:"/Images/BFZ/ScourfromExistence.jpg"},
{Name:"Titan's Presence", Cost:"3", Color:["C"], Rarity:"U", Type:["I"], Rating:"6", Sort:"1", Set:"BFZ", Number:"14", Image:"/Images/BFZ/TitansPresence.jpg"},
{Name:"Ulamog, the Ceaseless Hunger", Cost:"9", Color:["C"], Rarity:"M", Type:["C"], Rating:"7", Sort:"1", Set:"BFZ", Number:"15", Image:"/Images/BFZ/Ulamog--theCeaselessHunger.jpg"},
{Name:"Ulamog's Despoiler", Cost:"6", Color:["C"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"BFZ", Number:"16", Image:"/Images/BFZ/UlamogsDespoiler.jpg"},
{Name:"Void Winnower", Cost:"9", Color:["C"], Rarity:"M", Type:["C"], Rating:"7", Sort:"1", Set:"BFZ", Number:"17", Image:"/Images/BFZ/VoidWinnower.jpg"},
{Name:"Angel of Renewal", Cost:"5W", Color:["W"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"BFZ", Number:"18", Image:"/Images/BFZ/AngelofRenewal.jpg"},
{Name:"Angelic Gift", Cost:"1W", Color:["W"], Rarity:"C", Type:["E"], Rating:"2", Sort:"1", Set:"BFZ", Number:"19", Image:"/Images/BFZ/AngelicGift.jpg"},
{Name:"Cliffside Lookout", Cost:"0W", Color:["W"], Rarity:"C", Type:["C"], Rating:"2", Sort:"1", Set:"BFZ", Number:"20", Image:"/Images/BFZ/CliffsideLookout.jpg"},
{Name:"Courier Griffin", Cost:"3W", Color:["W"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"BFZ", Number:"21", Image:"/Images/BFZ/CourierGriffin.jpg"},
{Name:"Emeria Shepherd", Cost:"5WW", Color:["W"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"BFZ", Number:"22", Image:"/Images/BFZ/EmeriaShepherd.jpg"},
{Name:"Encircling Fissure", Cost:"2W", Color:["W"], Rarity:"U", Type:["I"], Rating:"5", Sort:"1", Set:"BFZ", Number:"23", Image:"/Images/BFZ/EncirclingFissure.jpg"},
{Name:"Expedition Envoy", Cost:"0W", Color:["W"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"BFZ", Number:"24", Image:"/Images/BFZ/ExpeditionEnvoy.jpg"},
{Name:"Felidar Cub", Cost:"1W", Color:["W"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"BFZ", Number:"25", Image:"/Images/BFZ/FelidarCub.jpg"},
{Name:"Felidar Sovereign", Cost:"4WW", Color:["W"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"BFZ", Number:"26", Image:"/Images/BFZ/FelidarSovereign.jpg"},
{Name:"Fortified Rampart", Cost:"1W", Color:["W"], Rarity:"C", Type:["C"], Rating:"2", Sort:"1", Set:"BFZ", Number:"27", Image:"/Images/BFZ/FortifiedRampart.jpg"},
{Name:"Ghostly Sentinel", Cost:"4W", Color:["W"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"BFZ", Number:"28", Image:"/Images/BFZ/GhostlySentinel.jpg"},
{Name:"Gideon, Ally of Zendikar", Cost:"2WW", Color:["W"], Rarity:"M", Type:["P"], Rating:"10", Sort:"1", Set:"BFZ", Number:"29", Image:"/Images/BFZ/Gideon--AllyofZendikar.jpg"},
{Name:"Gideon's Reproach", Cost:"1W", Color:["W"], Rarity:"C", Type:["I"], Rating:"4", Sort:"1", Set:"BFZ", Number:"30", Image:"/Images/BFZ/GideonsReproach.jpg"},
{Name:"Hero of Goma Fada", Cost:"4W", Color:["W"], Rarity:"R", Type:["C"], Rating:"6", Sort:"1", Set:"BFZ", Number:"31", Image:"/Images/BFZ/HeroofGomaFada.jpg"},
{Name:"Inspired Charge", Cost:"2WW", Color:["W"], Rarity:"C", Type:["I"], Rating:"2", Sort:"1", Set:"BFZ", Number:"32", Image:"/Images/BFZ/InspiredCharge.jpg"},
{Name:"Kitesail Scout", Cost:"0W", Color:["W"], Rarity:"C", Type:["C"], Rating:"2", Sort:"1", Set:"BFZ", Number:"33", Image:"/Images/BFZ/KitesailScout.jpg"},
{Name:"Kor Bladewhirl", Cost:"1W", Color:["W"], Rarity:"U", Type:["U"], Rating:"7", Sort:"1", Set:"BFZ", Number:"34", Image:"/Images/BFZ/KorBladewhirl.jpg"},
{Name:"Kor Castigator", Cost:"1W", Color:["W"], Rarity:"C", Type:["C"], Rating:"5", Sort:"1", Set:"BFZ", Number:"35", Image:"/Images/BFZ/KorCastigator.jpg"},
{Name:"Kor Entanglers", Cost:"4W", Color:["W"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"BFZ", Number:"36", Image:"/Images/BFZ/KorEntanglers.jpg"},
{Name:"Lantern Scout", Cost:"2W", Color:["W"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"BFZ", Number:"37", Image:"/Images/BFZ/LanternScout.jpg"},
{Name:"Lithomancer's Focus", Cost:"0W", Color:["W"], Rarity:"C", Type:["I"], Rating:"2", Sort:"1", Set:"BFZ", Number:"38", Image:"/Images/BFZ/LithomancersFocus.jpg"},
{Name:"Makindi Patrol", Cost:"2W", Color:["W"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"BFZ", Number:"39", Image:"/Images/BFZ/MakindiPatrol.jpg"},
{Name:"Ondu Greathorn", Cost:"3W", Color:["W"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"BFZ", Number:"40", Image:"/Images/BFZ/OnduGreathorn.jpg"},
{Name:"Ondu Rising", Cost:"1W", Color:["W"], Rarity:"U", Type:["S"], Rating:"5", Sort:"1", Set:"BFZ", Number:"41", Image:"/Images/BFZ/OnduRising.jpg"},
{Name:"Planar Outburst", Cost:"3WW", Color:["W"], Rarity:"R", Type:["S"], Rating:"9", Sort:"1", Set:"BFZ", Number:"42", Image:"/Images/BFZ/PlanarOutburst.jpg"},
{Name:"Quarantine Field", Cost:"0WW", Color:["W"], Rarity:"M", Type:["E"], Rating:"7", Sort:"1", Set:"BFZ", Number:"43", Image:"/Images/BFZ/QuarantineField.jpg"},
{Name:"Retreat to Emeria", Cost:"3W", Color:["W"], Rarity:"U", Type:["E"], Rating:"6", Sort:"1", Set:"BFZ", Number:"44", Image:"/Images/BFZ/RetreattoEmeria.jpg"},
{Name:"Roil's Retribution", Cost:"3WW", Color:["W"], Rarity:"U", Type:["I"], Rating:"6", Sort:"1", Set:"BFZ", Number:"45", Image:"/Images/BFZ/RoilsRetribution.jpg"},
{Name:"Serene Steward", Cost:"1W", Color:["W"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"BFZ", Number:"46", Image:"/Images/BFZ/SereneSteward.jpg"},
{Name:"Shadow Glider", Cost:"2W", Color:["W"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"BFZ", Number:"47", Image:"/Images/BFZ/ShadowGlider.jpg"},
{Name:"Sheer Drop", Cost:"2W", Color:["W"], Rarity:"C", Type:["S"], Rating:"5", Sort:"1", Set:"BFZ", Number:"48", Image:"/Images/BFZ/SheerDrop.jpg"},
{Name:"Smite the Monstrous", Cost:"3W", Color:["W"], Rarity:"C", Type:["I"], Rating:"4", Sort:"1", Set:"BFZ", Number:"49", Image:"/Images/BFZ/SmitetheMonstrous.jpg"},
{Name:"Stasis Snare", Cost:"1WW", Color:["W"], Rarity:"U", Type:["E"], Rating:"8", Sort:"1", Set:"BFZ", Number:"50", Image:"/Images/BFZ/StasisSnare.jpg"},
{Name:"Stone Haven Medic", Cost:"1W", Color:["W"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"BFZ", Number:"51", Image:"/Images/BFZ/StoneHavenMedic.jpg"},
{Name:"Tandem Tactics", Cost:"1W", Color:["W"], Rarity:"C", Type:["I"], Rating:"2", Sort:"1", Set:"BFZ", Number:"52", Image:"/Images/BFZ/TandemTactics.jpg"},
{Name:"Unified Front", Cost:"3W", Color:["W"], Rarity:"U", Type:["S"], Rating:"2", Sort:"1", Set:"BFZ", Number:"53", Image:"/Images/BFZ/UnifiedFront.jpg"},
{Name:"Adverse Conditions", Cost:"3U", Color:["U"], Rarity:"U", Type:["I"], Rating:"6", Sort:"1", Set:"BFZ", Number:"54", Image:"/Images/BFZ/AdverseConditions.jpg"},
{Name:"Benthic Infiltrator", Cost:"2U", Color:["U"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"BFZ", Number:"55", Image:"/Images/BFZ/BenthicInfiltrator.jpg"},
{Name:"Cryptic Cruiser", Cost:"3U", Color:["U"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"BFZ", Number:"56", Image:"/Images/BFZ/CrypticCruiser.jpg"},
{Name:"Drowner of Hope", Cost:"5U", Color:["U"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"BFZ", Number:"57", Image:"/Images/BFZ/DrownerofHope.jpg"},
{Name:"Eldrazi Skyspawner", Cost:"2U", Color:["U"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"BFZ", Number:"58", Image:"/Images/BFZ/EldraziSkyspawner.jpg"},
{Name:"Horribly Awry", Cost:"1U", Color:["U"], Rarity:"U", Type:["I"], Rating:"7", Sort:"1", Set:"BFZ", Number:"59", Image:"/Images/BFZ/HorriblyAwry.jpg"},
{Name:"Incubator Drone", Cost:"3U", Color:["U"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"BFZ", Number:"60", Image:"/Images/BFZ/IncubatorDrone.jpg"},
{Name:"Mist Intruder", Cost:"1U", Color:["U"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"BFZ", Number:"61", Image:"/Images/BFZ/MistIntruder.jpg"},
{Name:"Murk Strider", Cost:"3U", Color:["U"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"BFZ", Number:"62", Image:"/Images/BFZ/MurkStrider.jpg"},
{Name:"Oracle of Dust", Cost:"4U", Color:["U"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"BFZ", Number:"63", Image:"/Images/BFZ/OracleofDust.jpg"},
{Name:"Ruination Guide", Cost:"2U", Color:["U"], Rarity:"U", Type:["C"], Rating:"7", Sort:"1", Set:"BFZ", Number:"64", Image:"/Images/BFZ/RuinationGuide.jpg"},
{Name:"Salvage Drone", Cost:"0U", Color:["U"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"BFZ", Number:"65", Image:"/Images/BFZ/SalvageDrone.jpg"},
{Name:"Spell Shrivel", Cost:"2U", Color:["U"], Rarity:"C", Type:["I"], Rating:"4", Sort:"1", Set:"BFZ", Number:"66", Image:"/Images/BFZ/SpellShrivel.jpg"},
{Name:"Tide Drifter", Cost:"1U", Color:["U"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"BFZ", Number:"67", Image:"/Images/BFZ/TideDrifter.jpg"},
{Name:"Ulamog's Reclaimer", Cost:"4U", Color:["U"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"BFZ", Number:"68", Image:"/Images/BFZ/UlamogsReclaimer.jpg"},
{Name:"Anticipate", Cost:"1U", Color:["U"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"BFZ", Number:"69", Image:"/Images/BFZ/Anticipate.jpg"},
{Name:"Brilliant Spectrum", Cost:"3U", Color:["U"], Rarity:"C", Type:["S"], Rating:"1", Sort:"1", Set:"BFZ", Number:"70", Image:"/Images/BFZ/BrilliantSpectrum.jpg"},
{Name:"Cloud Manta", Cost:"3U", Color:["U"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"BFZ", Number:"71", Image:"/Images/BFZ/CloudManta.jpg"},
{Name:"Clutch of Currents", Cost:"0U", Color:["U"], Rarity:"C", Type:["S"], Rating:"3", Sort:"1", Set:"BFZ", Number:"72", Image:"/Images/BFZ/ClutchofCurrents.jpg"},
{Name:"Coastal Discovery", Cost:"3U", Color:["U"], Rarity:"U", Type:["S"], Rating:"5", Sort:"1", Set:"BFZ", Number:"73", Image:"/Images/BFZ/CoastalDiscovery.jpg"},
{Name:"Coralhelm Guide", Cost:"1U", Color:["U"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"BFZ", Number:"74", Image:"/Images/BFZ/CoralhelmGuide.jpg"},
{Name:"Dampening Pulse", Cost:"3U", Color:["U"], Rarity:"U", Type:["E"], Rating:"4", Sort:"1", Set:"BFZ", Number:"75", Image:"/Images/BFZ/DampeningPulse.jpg"},
{Name:"Dispel", Cost:"0U", Color:["U"], Rarity:"C", Type:["I"], Rating:"2", Sort:"1", Set:"BFZ", Number:"76", Image:"/Images/BFZ/Dispel.jpg"},
{Name:"Exert Influence", Cost:"4U", Color:["U"], Rarity:"R", Type:["S"], Rating:"4", Sort:"1", Set:"BFZ", Number:"77", Image:"/Images/BFZ/ExertInfluence.jpg"},
{Name:"Guardian of Tazeem", Cost:"3UU", Color:["U"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"BFZ", Number:"78", Image:"/Images/BFZ/GuardianofTazeem.jpg"},
{Name:"Halimar Tidecaller", Cost:"2U", Color:["U"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"BFZ", Number:"79", Image:"/Images/BFZ/HalimarTidecaller.jpg"},
{Name:"Part the Waterveil", Cost:"4UU", Color:["U"], Rarity:"M", Type:["S"], Rating:"8", Sort:"1", Set:"BFZ", Number:"80", Image:"/Images/BFZ/ParttheWaterveil.jpg"},
{Name:"Prism Array", Cost:"4U", Color:["U"], Rarity:"R", Type:["E"], Rating:"4", Sort:"1", Set:"BFZ", Number:"81", Image:"/Images/BFZ/PrismArray.jpg"},
{Name:"Retreat to Coralhelm", Cost:"2U", Color:["U"], Rarity:"U", Type:["E"], Rating:"5", Sort:"1", Set:"BFZ", Number:"82", Image:"/Images/BFZ/RetreattoCoralhelm.jpg"},
{Name:"Roilmage's Trick", Cost:"3U", Color:["U"], Rarity:"C", Type:["I"], Rating:"2", Sort:"1", Set:"BFZ", Number:"83", Image:"/Images/BFZ/RoilmagesTrick.jpg"},
{Name:"Rush of Ice", Cost:"0U", Color:["U"], Rarity:"C", Type:["S"], Rating:"3", Sort:"1", Set:"BFZ", Number:"84", Image:"/Images/BFZ/RushofIce.jpg"},
{Name:"Scatter to the Winds", Cost:"1UU", Color:["U"], Rarity:"R", Type:["I"], Rating:"7", Sort:"1", Set:"BFZ", Number:"85", Image:"/Images/BFZ/ScattertotheWinds.jpg"},
{Name:"Tightening Coils", Cost:"1U", Color:["U"], Rarity:"C", Type:["E"], Rating:"4", Sort:"1", Set:"BFZ", Number:"86", Image:"/Images/BFZ/TighteningCoils.jpg"},
{Name:"Ugin's Insight", Cost:"3UU", Color:["U"], Rarity:"R", Type:["S"], Rating:"6", Sort:"1", Set:"BFZ", Number:"87", Image:"/Images/BFZ/UginsInsight.jpg"},
{Name:"Wave-Wing Elemental", Cost:"5U", Color:["U"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"BFZ", Number:"88", Image:"/Images/BFZ/Wave-WingElemental.jpg"},
{Name:"Windrider Patrol", Cost:"3UU", Color:["U"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"BFZ", Number:"89", Image:"/Images/BFZ/WindriderPatrol.jpg"},
{Name:"Complete Disregard", Cost:"2B", Color:["B"], Rarity:"C", Type:["I"], Rating:"3", Sort:"1", Set:"BFZ", Number:"90", Image:"/Images/BFZ/CompleteDisregard.jpg"},
{Name:"Culling Drone", Cost:"1B", Color:["B"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"BFZ", Number:"91", Image:"/Images/BFZ/CullingDrone.jpg"},
{Name:"Dominator Drone", Cost:"2B", Color:["B"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"BFZ", Number:"92", Image:"/Images/BFZ/DominatorDrone.jpg"},
{Name:"Grave Birthing", Cost:"2B", Color:["B"], Rarity:"C", Type:["I"], Rating:"3", Sort:"1", Set:"BFZ", Number:"93", Image:"/Images/BFZ/GraveBirthing.jpg"},
{Name:"Grip of Desolation", Cost:"4BB", Color:["B"], Rarity:"U", Type:["I"], Rating:"5", Sort:"1", Set:"BFZ", Number:"94", Image:"/Images/BFZ/GripofDesolation.jpg"},
{Name:"Mind Raker", Cost:"3B", Color:["B"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"BFZ", Number:"95", Image:"/Images/BFZ/MindRaker.jpg"},
{Name:"Silent Skimmer", Cost:"3B", Color:["B"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"BFZ", Number:"96", Image:"/Images/BFZ/SilentSkimmer.jpg"},
{Name:"Skitterskin", Cost:"3B", Color:["B"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"BFZ", Number:"97", Image:"/Images/BFZ/Skitterskin.jpg"},
{Name:"Sludge Crawler", Cost:"0B", Color:["B"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"BFZ", Number:"98", Image:"/Images/BFZ/SludgeCrawler.jpg"},
{Name:"Smothering Abomination", Cost:"2BB", Color:["B"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"BFZ", Number:"99", Image:"/Images/BFZ/SmotheringAbomination.jpg"},
{Name:"Swarm Surge", Cost:"2B", Color:["B"], Rarity:"C", Type:["S"], Rating:"3", Sort:"1", Set:"BFZ", Number:"100", Image:"/Images/BFZ/SwarmSurge.jpg"},
{Name:"Transgress the Mind", Cost:"1B", Color:["B"], Rarity:"U", Type:["S"], Rating:"6", Sort:"1", Set:"BFZ", Number:"101", Image:"/Images/BFZ/TransgresstheMind.jpg"},
{Name:"Wasteland Strangler", Cost:"2B", Color:["B"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"BFZ", Number:"102", Image:"/Images/BFZ/WastelandStrangler.jpg"},
{Name:"Altar's Reap", Cost:"1B", Color:["B"], Rarity:"C", Type:["I"], Rating:"2", Sort:"1", Set:"BFZ", Number:"103", Image:"/Images/BFZ/AltarsReap.jpg"},
{Name:"Bloodbond Vampire", Cost:"2BB", Color:["B"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"BFZ", Number:"104", Image:"/Images/BFZ/BloodbondVampire.jpg"},
{Name:"Bone Splinters", Cost:"0B", Color:["B"], Rarity:"C", Type:["S"], Rating:"3", Sort:"1", Set:"BFZ", Number:"105", Image:"/Images/BFZ/BoneSplinters.jpg"},
{Name:"Carrier Thrall", Cost:"1B", Color:["B"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"BFZ", Number:"106", Image:"/Images/BFZ/CarrierThrall.jpg"},
{Name:"Defiant Bloodlord", Cost:"5BB", Color:["B"], Rarity:"R", Type:["C"], Rating:"6", Sort:"1", Set:"BFZ", Number:"107", Image:"/Images/BFZ/DefiantBloodlord.jpg"},
{Name:"Demon's Grasp", Cost:"4B", Color:["B"], Rarity:"C", Type:["S"], Rating:"4", Sort:"1", Set:"BFZ", Number:"108", Image:"/Images/BFZ/DemonsGrasp.jpg"},
{Name:"Drana, Liberator of Malakir", Cost:"1BB", Color:["B"], Rarity:"M", Type:["C"], Rating:"8", Sort:"1", Set:"BFZ", Number:"109", Image:"/Images/BFZ/Drana--LiberatorofMalakir.jpg"},
{Name:"Dutiful Return", Cost:"3B", Color:["B"], Rarity:"C", Type:["S"], Rating:"2", Sort:"1", Set:"BFZ", Number:"110", Image:"/Images/BFZ/DutifulReturn.jpg"},
{Name:"Geyserfield Stalker", Cost:"4B", Color:["B"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"BFZ", Number:"111", Image:"/Images/BFZ/GeyserfieldStalker.jpg"},
{Name:"Guul Draz Overseer", Cost:"4BB", Color:["B"], Rarity:"R", Type:["C"], Rating:"6", Sort:"1", Set:"BFZ", Number:"112", Image:"/Images/BFZ/GuulDrazOverseer.jpg"},
{Name:"Hagra Sharpshooter", Cost:"2B", Color:["B"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"BFZ", Number:"113", Image:"/Images/BFZ/HagraSharpshooter.jpg"},
{Name:"Kalastria Healer", Cost:"1B", Color:["B"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"BFZ", Number:"114", Image:"/Images/BFZ/KalastriaHealer.jpg"},
{Name:"Kalastria Nightwatch", Cost:"4B", Color:["B"], Rarity:"C", Type:["C"], Rating:"2", Sort:"1", Set:"BFZ", Number:"115", Image:"/Images/BFZ/KalastriaNightwatch.jpg"},
{Name:"Malakir Familiar", Cost:"2B", Color:["B"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"BFZ", Number:"116", Image:"/Images/BFZ/MalakirFamiliar.jpg"},
{Name:"Mire's Malice", Cost:"3B", Color:["B"], Rarity:"C", Type:["S"], Rating:"3", Sort:"1", Set:"BFZ", Number:"117", Image:"/Images/BFZ/MiresMalice.jpg"},
{Name:"Nirkana Assassin", Cost:"2B", Color:["B"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"BFZ", Number:"118", Image:"/Images/BFZ/NirkanaAssassin.jpg"},
{Name:"Ob Nixilis Reignited", Cost:"3BB", Color:["B"], Rarity:"M", Type:["P"], Rating:"9", Sort:"1", Set:"BFZ", Number:"119", Image:"/Images/BFZ/ObNixilisReignited.jpg"},
{Name:"Painful Truths", Cost:"2B", Color:["B"], Rarity:"R", Type:["S"], Rating:"5", Sort:"1", Set:"BFZ", Number:"120", Image:"/Images/BFZ/PainfulTruths.jpg"},
{Name:"Retreat to Hagra", Cost:"2B", Color:["B"], Rarity:"U", Type:["E"], Rating:"6", Sort:"1", Set:"BFZ", Number:"121", Image:"/Images/BFZ/RetreattoHagra.jpg"},
{Name:"Rising Miasma", Cost:"3B", Color:["B"], Rarity:"U", Type:["S"], Rating:"6", Sort:"1", Set:"BFZ", Number:"122", Image:"/Images/BFZ/RisingMiasma.jpg"},
{Name:"Ruinous Path", Cost:"1BB", Color:["B"], Rarity:"R", Type:["S"], Rating:"9", Sort:"1", Set:"BFZ", Number:"123", Image:"/Images/BFZ/RuinousPath.jpg"},
{Name:"Vampiric Rites", Cost:"0B", Color:["B"], Rarity:"U", Type:["E"], Rating:"6", Sort:"1", Set:"BFZ", Number:"124", Image:"/Images/BFZ/VampiricRites.jpg"},
{Name:"Voracious Null", Cost:"2B", Color:["B"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"BFZ", Number:"125", Image:"/Images/BFZ/VoraciousNull.jpg"},
{Name:"Zulaport Cutthroat", Cost:"1B", Color:["B"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"BFZ", Number:"126", Image:"/Images/BFZ/ZulaportCutthroat.jpg"},
{Name:"Barrage Tyrant", Cost:"4R", Color:["R"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"BFZ", Number:"127", Image:"/Images/BFZ/BarrageTyrant.jpg"},
{Name:"Crumble to Dust", Cost:"3R", Color:["R"], Rarity:"U", Type:["S"], Rating:"4", Sort:"1", Set:"BFZ", Number:"128", Image:"/Images/BFZ/CrumbletoDust.jpg"},
{Name:"Kozilek's Sentinel", Cost:"1R", Color:["R"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"BFZ", Number:"129", Image:"/Images/BFZ/KozileksSentinel.jpg"},
{Name:"Molten Nursery", Cost:"2R", Color:["R"], Rarity:"U", Type:["E"], Rating:"5", Sort:"1", Set:"BFZ", Number:"130", Image:"/Images/BFZ/MoltenNursery.jpg"},
{Name:"Nettle Drone", Cost:"2R", Color:["R"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"BFZ", Number:"131", Image:"/Images/BFZ/NettleDrone.jpg"},
{Name:"Processor Assault", Cost:"1R", Color:["R"], Rarity:"U", Type:["S"], Rating:"6", Sort:"1", Set:"BFZ", Number:"132", Image:"/Images/BFZ/ProcessorAssault.jpg"},
{Name:"Serpentine Spike", Cost:"5RR", Color:["R"], Rarity:"R", Type:["S"], Rating:"5", Sort:"1", Set:"BFZ", Number:"133", Image:"/Images/BFZ/SerpentineSpike.jpg"},
{Name:"Touch of the Void", Cost:"2R", Color:["R"], Rarity:"C", Type:["S"], Rating:"4", Sort:"1", Set:"BFZ", Number:"134", Image:"/Images/BFZ/TouchoftheVoid.jpg"},
{Name:"Turn Against", Cost:"4R", Color:["R"], Rarity:"U", Type:["I"], Rating:"4", Sort:"1", Set:"BFZ", Number:"135", Image:"/Images/BFZ/TurnAgainst.jpg"},
{Name:"Vestige of Emrakul", Cost:"3R", Color:["R"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"BFZ", Number:"136", Image:"/Images/BFZ/VestigeofEmrakul.jpg"},
{Name:"Vile Aggregate", Cost:"2R", Color:["R"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"BFZ", Number:"137", Image:"/Images/BFZ/VileAggregate.jpg"},
{Name:"Akoum Firebird", Cost:"2RR", Color:["R"], Rarity:"M", Type:["C"], Rating:"10", Sort:"1", Set:"BFZ", Number:"138", Image:"/Images/BFZ/AkoumFirebird.jpg"},
{Name:"Akoum Hellkite", Cost:"4RR", Color:["R"], Rarity:"R", Type:["C"], Rating:"6", Sort:"1", Set:"BFZ", Number:"139", Image:"/Images/BFZ/AkoumHellkite.jpg"},
{Name:"Akoum Stonewaker", Cost:"1R", Color:["R"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"BFZ", Number:"140", Image:"/Images/BFZ/AkoumStonewaker.jpg"},
{Name:"Belligerent Whiptail", Cost:"3R", Color:["R"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"BFZ", Number:"141", Image:"/Images/BFZ/BelligerentWhiptail.jpg"},
{Name:"Boiling Earth", Cost:"1R", Color:["R"], Rarity:"C", Type:["S"], Rating:"3", Sort:"1", Set:"BFZ", Number:"142", Image:"/Images/BFZ/BoilingEarth.jpg"},
{Name:"Chasm Guide", Cost:"3R", Color:["R"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"BFZ", Number:"143", Image:"/Images/BFZ/ChasmGuide.jpg"},
{Name:"Dragonmaster Outcast", Cost:"0R", Color:["R"], Rarity:"M", Type:["C"], Rating:"10", Sort:"1", Set:"BFZ", Number:"144", Image:"/Images/BFZ/DragonmasterOutcast.jpg"},
{Name:"Firemantle Mage", Cost:"2R", Color:["R"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"BFZ", Number:"145", Image:"/Images/BFZ/FiremantleMage.jpg"},
{Name:"Goblin War Paint", Cost:"1R", Color:["R"], Rarity:"C", Type:["E"], Rating:"2", Sort:"1", Set:"BFZ", Number:"146", Image:"/Images/BFZ/GoblinWarPaint.jpg"},
{Name:"Lavastep Raider", Cost:"0R", Color:["R"], Rarity:"C", Type:["C"], Rating:"2", Sort:"1", Set:"BFZ", Number:"147", Image:"/Images/BFZ/LavastepRaider.jpg"},
{Name:"Makindi Sliderunner", Cost:"1R", Color:["R"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"BFZ", Number:"148", Image:"/Images/BFZ/MakindiSliderunner.jpg"},
{Name:"Ondu Champion", Cost:"2RR", Color:["R"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"BFZ", Number:"149", Image:"/Images/BFZ/OnduChampion.jpg"},
{Name:"Outnumber", Cost:"0R", Color:["R"], Rarity:"C", Type:["I"], Rating:"2", Sort:"1", Set:"BFZ", Number:"150", Image:"/Images/BFZ/Outnumber.jpg"},
{Name:"Radiant Flames", Cost:"2R", Color:["R"], Rarity:"R", Type:["C"], Rating:"5", Sort:"1", Set:"BFZ", Number:"151", Image:"/Images/BFZ/RadiantFlames.jpg"},
{Name:"Reckless Cohort", Cost:"1R", Color:["R"], Rarity:"C", Type:["C"], Rating:"2", Sort:"1", Set:"BFZ", Number:"152", Image:"/Images/BFZ/RecklessCohort.jpg"},
{Name:"Retreat to Valakut", Cost:"2R", Color:["R"], Rarity:"U", Type:["E"], Rating:"5", Sort:"1", Set:"BFZ", Number:"153", Image:"/Images/BFZ/RetreattoValakut.jpg"},
{Name:"Rolling Thunder", Cost:"0RR", Color:["R"], Rarity:"U", Type:["S"], Rating:"7", Sort:"1", Set:"BFZ", Number:"154", Image:"/Images/BFZ/RollingThunder.jpg"},
{Name:"Shatterskull Recruit", Cost:"3RR", Color:["R"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"BFZ", Number:"155", Image:"/Images/BFZ/ShatterskullRecruit.jpg"},
{Name:"Stonefury", Cost:"3RR", Color:["R"], Rarity:"C", Type:["I"], Rating:"3", Sort:"1", Set:"BFZ", Number:"156", Image:"/Images/BFZ/Stonefury.jpg"},
{Name:"Sure Strike", Cost:"1R", Color:["R"], Rarity:"C", Type:["I"], Rating:"2", Sort:"1", Set:"BFZ", Number:"157", Image:"/Images/BFZ/SureStrike.jpg"},
{Name:"Tunneling Geopede", Cost:"2R", Color:["R"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"BFZ", Number:"158", Image:"/Images/BFZ/TunnelingGeopede.jpg"},
{Name:"Valakut Invoker", Cost:"2R", Color:["R"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"BFZ", Number:"159", Image:"/Images/BFZ/ValakutInvoker.jpg"},
{Name:"Valakut Predator", Cost:"2R", Color:["R"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"BFZ", Number:"160", Image:"/Images/BFZ/ValakutPredator.jpg"},
{Name:"Volcanic Upheaval", Cost:"3R", Color:["R"], Rarity:"C", Type:["I"], Rating:"3", Sort:"1", Set:"BFZ", Number:"161", Image:"/Images/BFZ/VolcanicUpheaval.jpg"},
{Name:"Zada, Hedron Grinder", Cost:"3R", Color:["R"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"BFZ", Number:"162", Image:"/Images/BFZ/Zada--HedronGrinder.jpg"},
{Name:"Blisterpod", Cost:"0G", Color:["G"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"BFZ", Number:"163", Image:"/Images/BFZ/Blisterpod.jpg"},
{Name:"Brood Monitor", Cost:"4GG", Color:["G"], Rarity:"U", Type:["C"], Rating:"7", Sort:"1", Set:"BFZ", Number:"164", Image:"/Images/BFZ/BroodMonitor.jpg"},
{Name:"Call the Scions", Cost:"2G", Color:["G"], Rarity:"C", Type:["S"], Rating:"4", Sort:"1", Set:"BFZ", Number:"165", Image:"/Images/BFZ/CalltheScions.jpg"},
{Name:"Eyeless Watcher", Cost:"3G", Color:["G"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"BFZ", Number:"166", Image:"/Images/BFZ/EyelessWatcher.jpg"},
{Name:"From Beyond", Cost:"3G", Color:["G"], Rarity:"R", Type:["E"], Rating:"8", Sort:"1", Set:"BFZ", Number:"167", Image:"/Images/BFZ/FromBeyond.jpg"},
{Name:"Unnatural Aggression", Cost:"2G", Color:["G"], Rarity:"C", Type:["I"], Rating:"3", Sort:"1", Set:"BFZ", Number:"168", Image:"/Images/BFZ/UnnaturalAggression.jpg"},
{Name:"Void Attendant", Cost:"2G", Color:["G"], Rarity:"U", Type:["C"], Rating:"7", Sort:"1", Set:"BFZ", Number:"169", Image:"/Images/BFZ/VoidAttendant.jpg"},
{Name:"Beastcaller Savant", Cost:"1G", Color:["G"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"BFZ", Number:"170", Image:"/Images/BFZ/BeastcallerSavant.jpg"},
{Name:"Broodhunter Wurm", Cost:"3G", Color:["G"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"BFZ", Number:"171", Image:"/Images/BFZ/BroodhunterWurm.jpg"},
{Name:"Earthen Arms", Cost:"1G", Color:["G"], Rarity:"C", Type:["S"], Rating:"2", Sort:"1", Set:"BFZ", Number:"172", Image:"/Images/BFZ/EarthenArms.jpg"},
{Name:"Giant Mantis", Cost:"3G", Color:["G"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"BFZ", Number:"173", Image:"/Images/BFZ/GiantMantis.jpg"},
{Name:"Greenwarden of Murasa", Cost:"4GG", Color:["G"], Rarity:"M", Type:["C"], Rating:"8", Sort:"1", Set:"BFZ", Number:"174", Image:"/Images/BFZ/GreenwardenofMurasa.jpg"},
{Name:"Infuse with the Elements", Cost:"3G", Color:["G"], Rarity:"U", Type:["I"], Rating:"3", Sort:"1", Set:"BFZ", Number:"175", Image:"/Images/BFZ/InfusewiththeElements.jpg"},
{Name:"Jaddi Offshoot", Cost:"0G", Color:["G"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"BFZ", Number:"176", Image:"/Images/BFZ/JaddiOffshoot.jpg"},
{Name:"Lifespring Druid", Cost:"2G", Color:["G"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"BFZ", Number:"177", Image:"/Images/BFZ/LifespringDruid.jpg"},
{Name:"Murasa Ranger", Cost:"3G", Color:["G"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"BFZ", Number:"178", Image:"/Images/BFZ/MurasaRanger.jpg"},
{Name:"Natural Connection", Cost:"2G", Color:["G"], Rarity:"C", Type:["I"], Rating:"5", Sort:"1", Set:"BFZ", Number:"179", Image:"/Images/BFZ/NaturalConnection.jpg"},
{Name:"Nissa's Renewal", Cost:"5G", Color:["G"], Rarity:"R", Type:["S"], Rating:"8", Sort:"1", Set:"BFZ", Number:"180", Image:"/Images/BFZ/NissasRenewal.jpg"},
{Name:"Oran-Rief Hydra", Cost:"4GG", Color:["G"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"BFZ", Number:"181", Image:"/Images/BFZ/Oran-RiefHydra.jpg"},
{Name:"Oran-Rief Invoker", Cost:"1G", Color:["G"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"BFZ", Number:"182", Image:"/Images/BFZ/Oran-RiefInvoker.jpg"},
{Name:"Plated Crusher", Cost:"4GGG", Color:["G"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"BFZ", Number:"183", Image:"/Images/BFZ/PlatedCrusher.jpg"},
{Name:"Plummet", Cost:"1G", Color:["G"], Rarity:"C", Type:["I"], Rating:"2", Sort:"1", Set:"BFZ", Number:"184", Image:"/Images/BFZ/Plummet.jpg"},
{Name:"Reclaiming Vines", Cost:"2GG", Color:["G"], Rarity:"C", Type:["S"], Rating:"3", Sort:"1", Set:"BFZ", Number:"185", Image:"/Images/BFZ/ReclaimingVines.jpg"},
{Name:"Retreat to Kazandu", Cost:"2G", Color:["G"], Rarity:"U", Type:["E"], Rating:"6", Sort:"1", Set:"BFZ", Number:"186", Image:"/Images/BFZ/RetreattoKazandu.jpg"},
{Name:"Rot Shambler", Cost:"2G", Color:["G"], Rarity:"U", Type:["E"], Rating:"7", Sort:"1", Set:"BFZ", Number:"187", Image:"/Images/BFZ/RotShambler.jpg"},
{Name:"Scythe Leopard", Cost:"0G", Color:["G"], Rarity:"U", Type:["C"], Rating:"7", Sort:"1", Set:"BFZ", Number:"188", Image:"/Images/BFZ/ScytheLeopard.jpg"},
{Name:"Seek the Wilds", Cost:"1G", Color:["G"], Rarity:"C", Type:["S"], Rating:"3", Sort:"1", Set:"BFZ", Number:"189", Image:"/Images/BFZ/SeektheWilds.jpg"},
{Name:"Snapping Gnarlid", Cost:"1G", Color:["G"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"BFZ", Number:"190", Image:"/Images/BFZ/SnappingGnarlid.jpg"},
{Name:"Swell of Growth", Cost:"1G", Color:["G"], Rarity:"C", Type:["I"], Rating:"3", Sort:"1", Set:"BFZ", Number:"191", Image:"/Images/BFZ/SwellofGrowth.jpg"},
{Name:"Sylvan Scrying", Cost:"1G", Color:["G"], Rarity:"U", Type:["S"], Rating:"7", Sort:"1", Set:"BFZ", Number:"192", Image:"/Images/BFZ/SylvanScrying.jpg"},
{Name:"Tajuru Beastmaster", Cost:"5G", Color:["G"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"BFZ", Number:"193", Image:"/Images/BFZ/TajuruBeastmaster.jpg"},
{Name:"Tajuru Stalwart", Cost:"2G", Color:["G"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"BFZ", Number:"194", Image:"/Images/BFZ/TajuruStalwart.jpg"},
{Name:"Tajuru Warcaller", Cost:"3GG", Color:["G"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"BFZ", Number:"195", Image:"/Images/BFZ/TajuruWarcaller.jpg"},
{Name:"Territorial Baloth", Cost:"4G", Color:["G"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"BFZ", Number:"196", Image:"/Images/BFZ/TerritorialBaloth.jpg"},
{Name:"Undergrowth Champion", Cost:"1GG", Color:["G"], Rarity:"M", Type:["C"], Rating:"10", Sort:"1", Set:"BFZ", Number:"197", Image:"/Images/BFZ/UndergrowthChampion.jpg"},
{Name:"Woodland Wanderer", Cost:"3G", Color:["G"], Rarity:"R", Type:["C"], Rating:"6", Sort:"1", Set:"BFZ", Number:"198", Image:"/Images/BFZ/WoodlandWanderer.jpg"},
{Name:"Brood Butcher", Cost:"3BG", Color:["B","G"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"BFZ", Number:"199", Image:"/Images/BFZ/BroodButcher.jpg"},
{Name:"Brutal Expulsion", Cost:"2UR", Color:["U","R"], Rarity:"R", Type:["I"], Rating:"8", Sort:"1", Set:"BFZ", Number:"200", Image:"/Images/BFZ/BrutalExpulsion.jpg"},
{Name:"Catacomb Sifter", Cost:"1BG", Color:["B","G"], Rarity:"U", Type:["C"], Rating:"7", Sort:"1", Set:"BFZ", Number:"201", Image:"/Images/BFZ/CatacombSifter.jpg"},
{Name:"Dust Stalker", Cost:"2BR", Color:["B","R"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"BFZ", Number:"202", Image:"/Images/BFZ/DustStalker.jpg"},
{Name:"Fathom Feeder", Cost:"0UB", Color:["U","B"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"BFZ", Number:"203", Image:"/Images/BFZ/FathomFeeder.jpg"},
{Name:"Forerunner of Slaughter", Cost:"0BR", Color:["B","R"], Rarity:"U", Type:["C"], Rating:"7", Sort:"1", Set:"BFZ", Number:"204", Image:"/Images/BFZ/ForerunnerofSlaughter.jpg"},
{Name:"Herald of Kozilek", Cost:"1UR", Color:["U","R"], Rarity:"U", Type:["C"], Rating:"7", Sort:"1", Set:"BFZ", Number:"205", Image:"/Images/BFZ/HeraldofKozilek.jpg"},
{Name:"Sire of Stagnation", Cost:"4UB", Color:["U","B"], Rarity:"M", Type:["C"], Rating:"10", Sort:"1", Set:"BFZ", Number:"206", Image:"/Images/BFZ/SireofStagnation.jpg"},
{Name:"Ulamog's Nullifier", Cost:"2UB", Color:["U","B"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"BFZ", Number:"207", Image:"/Images/BFZ/UlamogsNullifier.jpg"},
{Name:"Angelic Captain", Cost:"3WR", Color:["W","R"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"BFZ", Number:"208", Image:"/Images/BFZ/AngelicCaptain.jpg"},
{Name:"Bring to Light", Cost:"3UG", Color:["U","G"], Rarity:"R", Type:["S"], Rating:"7", Sort:"1", Set:"BFZ", Number:"209", Image:"/Images/BFZ/BringtoLight.jpg"},
{Name:"Drana's Emissary", Cost:"1WB", Color:["W","B"], Rarity:"U", Type:["C"], Rating:"8", Sort:"1", Set:"BFZ", Number:"210", Image:"/Images/BFZ/DranasEmissary.jpg"},
{Name:"Grove Rumbler", Cost:"2RG", Color:["R","G"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"BFZ", Number:"211", Image:"/Images/BFZ/GroveRumbler.jpg"},
{Name:"Grovetender Druids", Cost:"2WG", Color:["W","G"], Rarity:"U", Type:["C"], Rating:"7", Sort:"1", Set:"BFZ", Number:"212", Image:"/Images/BFZ/GrovetenderDruids.jpg"},
{Name:"Kiora, Master of the Depths", Cost:"2UG", Color:["U","G"], Rarity:"M", Type:["P"], Rating:"9", Sort:"1", Set:"BFZ", Number:"213", Image:"/Images/BFZ/Kiora--MasteroftheDepths.jpg"},
{Name:"March from the Tomb", Cost:"3WB", Color:["W","B"], Rarity:"R", Type:["S"], Rating:"7", Sort:"1", Set:"BFZ", Number:"214", Image:"/Images/BFZ/MarchfromtheTomb.jpg"},
{Name:"Munda, Ambush Leader", Cost:"2RW", Color:["R","W"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"BFZ", Number:"215", Image:"/Images/BFZ/Munda--AmbushLeader.jpg"},
{Name:"Noyan Dar, Roil Shaper", Cost:"3WU", Color:["W","U"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"BFZ", Number:"216", Image:"/Images/BFZ/NoyanDar--RoilShaper.jpg"},
{Name:"Omnath, Locus of Rage", Cost:"3RRGG", Color:["R","G"], Rarity:"M", Type:["C"], Rating:"9", Sort:"1", Set:"BFZ", Number:"217", Image:"/Images/BFZ/Omnath--LocusofRage.jpg"},
{Name:"Resolute Blademaster", Cost:"3WR", Color:["W","R"], Rarity:"U", Type:["C"], Rating:"7", Sort:"1", Set:"BFZ", Number:"218", Image:"/Images/BFZ/ResoluteBlademaster.jpg"},
{Name:"Roil Spout", Cost:"1WU", Color:["W","U"], Rarity:"U", Type:["S"], Rating:"7", Sort:"1", Set:"BFZ", Number:"219", Image:"/Images/BFZ/RoilSpout.jpg"},
{Name:"Skyrider Elf", Cost:"0UG", Color:["U","G"], Rarity:"U", Type:["C"], Rating:"7", Sort:"1", Set:"BFZ", Number:"220", Image:"/Images/BFZ/SkyriderElf.jpg"},
{Name:"Veteran Warleader", Cost:"1WG", Color:["W","G"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"BFZ", Number:"221", Image:"/Images/BFZ/VeteranWarleader.jpg"},
{Name:"Aligned Hedron Network", Cost:"4", Color:["C"], Rarity:"R", Type:["A"], Rating:"8", Sort:"1", Set:"BFZ", Number:"222", Image:"/Images/BFZ/AlignedHedronNetwork.jpg"},
{Name:"Hedron Archive", Cost:"4", Color:["C"], Rarity:"U", Type:["A"], Rating:"6", Sort:"1", Set:"BFZ", Number:"223", Image:"/Images/BFZ/HedronArchive.jpg"},
{Name:"Hedron Blade", Cost:"1", Color:["C"], Rarity:"C", Type:["A"], Rating:"3", Sort:"1", Set:"BFZ", Number:"224", Image:"/Images/BFZ/HedronBlade.jpg"},
{Name:"Pathway Arrows", Cost:"1", Color:["C"], Rarity:"U", Type:["A"], Rating:"4", Sort:"1", Set:"BFZ", Number:"225", Image:"/Images/BFZ/PathwayArrows.jpg"},
{Name:"Pilgrim's Eye", Cost:"3", Color:["C"], Rarity:"U", Type:["C"], Rating:"7", Sort:"1", Set:"BFZ", Number:"226", Image:"/Images/BFZ/PilgrimsEye.jpg"},
{Name:"Slab Hammer", Cost:"2", Color:["C"], Rarity:"U", Type:["A"], Rating:"5", Sort:"1", Set:"BFZ", Number:"227", Image:"/Images/BFZ/SlabHammer.jpg"},
{Name:"Ally Encampment", Cost:"0", Color:["C"], Rarity:"R", Type:["L"], Rating:"6", Sort:"1", Set:"BFZ", Number:"228", Image:"/Images/BFZ/AllyEncampment.jpg"},
{Name:"Blighted Cataract", Cost:"0", Color:["U"], Rarity:"U", Type:["L"], Rating:"3", Sort:"1", Set:"BFZ", Number:"229", Image:"/Images/BFZ/BlightedCataract.jpg"},
{Name:"Blighted Fen", Cost:"0", Color:["B"], Rarity:"U", Type:["L"], Rating:"6", Sort:"1", Set:"BFZ", Number:"230", Image:"/Images/BFZ/BlightedFen.jpg"},
{Name:"Blighted Gorge", Cost:"0", Color:["R"], Rarity:"U", Type:["L"], Rating:"4", Sort:"1", Set:"BFZ", Number:"231", Image:"/Images/BFZ/BlightedGorge.jpg"},
{Name:"Blighted Steppe", Cost:"0", Color:["W"], Rarity:"U", Type:["L"], Rating:"3", Sort:"1", Set:"BFZ", Number:"232", Image:"/Images/BFZ/BlightedSteppe.jpg"},
{Name:"Blighted Woodland", Cost:"0", Color:["G"], Rarity:"U", Type:["L"], Rating:"7", Sort:"1", Set:"BFZ", Number:"233", Image:"/Images/BFZ/BlightedWoodland.jpg"},
{Name:"Canopy Vista", Cost:"0", Color:["W","G"], Rarity:"R", Type:["L"], Rating:"7", Sort:"1", Set:"BFZ", Number:"234", Image:"/Images/BFZ/CanopyVista.jpg"},
{Name:"Cinder Glade", Cost:"0", Color:["R","G"], Rarity:"R", Type:["L"], Rating:"7", Sort:"1", Set:"BFZ", Number:"235", Image:"/Images/BFZ/CinderGlade.jpg"},
{Name:"Evolving Wilds", Cost:"0", Color:["C"], Rarity:"C", Type:["L"], Rating:"3", Sort:"1", Set:"BFZ", Number:"236", Image:"/Images/BFZ/EvolvingWilds.jpg"},
{Name:"Fertile Thicket", Cost:"0", Color:["G"], Rarity:"C", Type:["L"], Rating:"4", Sort:"1", Set:"BFZ", Number:"237", Image:"/Images/BFZ/FertileThicket.jpg"},
{Name:"Looming Spires", Cost:"0", Color:["R"], Rarity:"C", Type:["L"], Rating:"3", Sort:"1", Set:"BFZ", Number:"238", Image:"/Images/BFZ/LoomingSpires.jpg"},
{Name:"Lumbering Falls", Cost:"0", Color:["U","G"], Rarity:"R", Type:["L"], Rating:"7", Sort:"1", Set:"BFZ", Number:"239", Image:"/Images/BFZ/LumberingFalls.jpg"},
{Name:"Mortuary Mire", Cost:"0", Color:["B"], Rarity:"C", Type:["L"], Rating:"3", Sort:"1", Set:"BFZ", Number:"240", Image:"/Images/BFZ/MortuaryMire.jpg"},
{Name:"Prairie Stream", Cost:"0", Color:["W","U"], Rarity:"R", Type:["L"], Rating:"6", Sort:"1", Set:"BFZ", Number:"241", Image:"/Images/BFZ/PrairieStream.jpg"},
{Name:"Sanctum of Ugin", Cost:"0", Color:["C"], Rarity:"R", Type:["L"], Rating:"6", Sort:"1", Set:"BFZ", Number:"242", Image:"/Images/BFZ/SanctumofUgin.jpg"},
{Name:"Sandstone Bridge", Cost:"0", Color:["W"], Rarity:"C", Type:["L"], Rating:"3", Sort:"1", Set:"BFZ", Number:"243", Image:"/Images/BFZ/SandstoneBridge.jpg"},
{Name:"Shambling Vent", Cost:"0", Color:["W","B"], Rarity:"R", Type:["L"], Rating:"7", Sort:"1", Set:"BFZ", Number:"244", Image:"/Images/BFZ/ShamblingVent.jpg"},
{Name:"Shrine of the Forsaken Gods", Cost:"0", Color:["C"], Rarity:"R", Type:["L"], Rating:"6", Sort:"1", Set:"BFZ", Number:"245", Image:"/Images/BFZ/ShrineoftheForsakenGods.jpg"},
{Name:"Skyline Cascade", Cost:"0", Color:["U"], Rarity:"C", Type:["L"], Rating:"3", Sort:"1", Set:"BFZ", Number:"246", Image:"/Images/BFZ/SkylineCascade.jpg"},
{Name:"Smoldering Marsh", Cost:"0", Color:["B","R"], Rarity:"R", Type:["L"], Rating:"7", Sort:"1", Set:"BFZ", Number:"247", Image:"/Images/BFZ/SmolderingMarsh.jpg"},
{Name:"Spawning Bed", Cost:"0", Color:["C"], Rarity:"U", Type:["L"], Rating:"5", Sort:"1", Set:"BFZ", Number:"248", Image:"/Images/BFZ/SpawningBed.jpg"},
{Name:"Sunken Hollow", Cost:"0", Color:["U","B"], Rarity:"R", Type:["L"], Rating:"7", Sort:"1", Set:"BFZ", Number:"249", Image:"/Images/BFZ/SunkenHollow.jpg"},
];