var EMN = [
{Name:"Blessed Alliance", Cost:"1W", Color:["W"], Rarity:"U", Type:["I"], Rating:"7", Sort:"1", Set:"EMN", Number:"1", Image:"/Images/EMN/BlessedAlliance.jpg", },
{Name:"Borrowed Grace", Cost:"2W", Color:["W"], Rarity:"C", Type:["I"], Rating:"2", Sort:"1", Set:"EMN", Number:"2", Image:"/Images/EMN/BorrowedGrace.jpg", },
{Name:"Choking Restraints", Cost:"2W", Color:["W"], Rarity:"C", Type:["E"], Rating:"5", Sort:"1", Set:"EMN", Number:"3", Image:"/Images/EMN/ChokingRestraints.jpg", },
{Name:"Collective Effort", Cost:"1WW", Color:["W"], Rarity:"R", Type:["S"], Rating:"7", Sort:"1", Set:"EMN", Number:"4", Image:"/Images/EMN/CollectiveEffort.jpg", },
{Name:"Courageous Outrider", Cost:"3W", Color:["W"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"EMN", Number:"5", Image:"/Images/EMN/CourageousOutrider.jpg", },
{Name:"Dawn Gryff", Cost:"2W", Color:["W"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"EMN", Number:"6", Image:"/Images/EMN/DawnGryff.jpg", },
{Name:"Deploy the Gatewatch", Cost:"4WW", Color:["W"], Rarity:"M", Type:["S"], Rating:"5", Sort:"1", Set:"EMN", Number:"7", Image:"/Images/EMN/DeploytheGatewatch.jpg", },
{Name:"Desperate Sentry", Cost:"2W", Color:["W"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"EMN", Number:"8", Image:"/Images/EMN/DesperateSentry.jpg", },
{Name:"Drogskol Shieldmate", Cost:"2W", Color:["W"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"EMN", Number:"9", Image:"/Images/EMN/DrogskolShieldmate.jpg", },
{Name:"Faith Unbroken", Cost:"3W", Color:["W"], Rarity:"U", Type:["E"], Rating:"6", Sort:"1", Set:"EMN", Number:"10", Image:"/Images/EMN/FaithUnbroken.jpg", },
{Name:"Faithbearer Paladin", Cost:"4W", Color:["W"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"EMN", Number:"11", Image:"/Images/EMN/FaithbearerPaladin.jpg", },
{Name:"Fiend Binder", Cost:"3W", Color:["W"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"EMN", Number:"12", Image:"/Images/EMN/FiendBinder.jpg", },
{Name:"Geist of the Lonely Vigil", Cost:"1W", Color:["W"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"EMN", Number:"13", Image:"/Images/EMN/GeistoftheLonelyVigil.jpg", },
{Name:"Give No Ground", Cost:"3W", Color:["W"], Rarity:"U", Type:["I"], Rating:"3", Sort:"1", Set:"EMN", Number:"14", Image:"/Images/EMN/GiveNoGround.jpg", },
{Name:"Guardian of Pilgrims", Cost:"1W", Color:["W"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"EMN", Number:"15", Image:"/Images/EMN/GuardianofPilgrims.jpg", },
{Name:"Ironclad Slayer", Cost:"2W", Color:["W"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"EMN", Number:"16", Image:"/Images/EMN/IroncladSlayer.jpg", },
{Name:"Ironwright's Cleansing", Cost:"2W", Color:["W"], Rarity:"C", Type:["S"], Rating:"2", Sort:"1", Set:"EMN", Number:"17", Image:"/Images/EMN/IronwrightsCleansing.jpg", },
{Name:"Long Road Home", Cost:"1W", Color:["W"], Rarity:"U", Type:["I"], Rating:"5", Sort:"1", Set:"EMN", Number:"18", Image:"/Images/EMN/LongRoadHome.jpg", },
{Name:"Lunarch Mantle", Cost:"1W", Color:["W"], Rarity:"C", Type:["E"], Rating:"2", Sort:"1", Set:"EMN", Number:"19", Image:"/Images/EMN/LunarchMantle.jpg", },
{Name:"Peace of Mind", Cost:"1W", Color:["W"], Rarity:"U", Type:["E"], Rating:"1", Sort:"1", Set:"EMN", Number:"20", Image:"/Images/EMN/PeaceofMind.jpg", },
{Name:"Providence", Cost:"5WW", Color:["W"], Rarity:"R", Type:["S"], Rating:"5", Sort:"1", Set:"EMN", Number:"21", Image:"/Images/EMN/Providence.jpg", },
{Name:"Repel the Abominable", Cost:"1W", Color:["W"], Rarity:"U", Type:["I"], Rating:"4", Sort:"1", Set:"EMN", Number:"22", Image:"/Images/EMN/RepeltheAbominable.jpg", },
{Name:"Sanctifier of Souls", Cost:"3W", Color:["W"], Rarity:"R", Type:["C"], Rating:"6", Sort:"1", Set:"EMN", Number:"23", Image:"/Images/EMN/SanctifierofSouls.jpg", },
{Name:"Selfless Spirit", Cost:"1W", Color:["W"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"EMN", Number:"24", Image:"/Images/EMN/SelflessSpirit.jpg", },
{Name:"Sigarda's Aid", Cost:"0W", Color:["W"], Rarity:"R", Type:["E"], Rating:"5", Sort:"1", Set:"EMN", Number:"25", Image:"/Images/EMN/SigardasAid.jpg", },
{Name:"Sigardian Priest", Cost:"1W", Color:["W"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"EMN", Number:"26", Image:"/Images/EMN/SigardianPriest.jpg", },
{Name:"Spectral Reserves", Cost:"3W", Color:["W"], Rarity:"C", Type:["S"], Rating:"3", Sort:"1", Set:"EMN", Number:"27", Image:"/Images/EMN/SpectralReserves.jpg", },
{Name:"Steadfast Cathar", Cost:"1W", Color:["W"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"EMN", Number:"28", Image:"/Images/EMN/SteadfastCathar.jpg", },
{Name:"Subjugator Angel", Cost:"4WW", Color:["W"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"EMN", Number:"29", Image:"/Images/EMN/SubjugatorAngel.jpg", },
{Name:"Thalia, Heretic Cathar", Cost:"2W", Color:["W"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"EMN", Number:"30", Image:"/Images/EMN/Thalia--HereticCathar.jpg", },
{Name:"Thalia's Lancers", Cost:"3WW", Color:["W"], Rarity:"R", Type:["C"], Rating:"6", Sort:"1", Set:"EMN", Number:"31", Image:"/Images/EMN/ThaliasLancers.jpg", },
{Name:"Thraben Standard Bearer", Cost:"0W", Color:["W"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"EMN", Number:"32", Image:"/Images/EMN/ThrabenStandardBearer.jpg", },
{Name:"Advanced Stitchwing", Cost:"3UU", Color:["U"], Rarity:"U", Type:["C"], Rating:"7", Sort:"1", Set:"EMN", Number:"33", Image:"/Images/EMN/AdvancedStitchwing.jpg", },
{Name:"Chilling Grasp", Cost:"2U", Color:["U"], Rarity:"U", Type:["I"], Rating:"3", Sort:"1", Set:"EMN", Number:"34", Image:"/Images/EMN/ChillingGrasp.jpg", },
{Name:"Coax from the Blind Eternities", Cost:"2U", Color:["U"], Rarity:"R", Type:["S"], Rating:"5", Sort:"1", Set:"EMN", Number:"35", Image:"/Images/EMN/CoaxfromtheBlindEternities.jpg", },
{Name:"Contingency Plan", Cost:"1U", Color:["U"], Rarity:"C", Type:["S"], Rating:"3", Sort:"1", Set:"EMN", Number:"36", Image:"/Images/EMN/ContingencyPlan.jpg", },
{Name:"Convolute", Cost:"2U", Color:["U"], Rarity:"C", Type:["I"], Rating:"3", Sort:"1", Set:"EMN", Number:"37", Image:"/Images/EMN/Convolute.jpg", },
{Name:"Displace", Cost:"2U", Color:["U"], Rarity:"C", Type:["I"], Rating:"2", Sort:"1", Set:"EMN", Number:"38", Image:"/Images/EMN/Displace.jpg", },
{Name:"Drag Under", Cost:"2U", Color:["U"], Rarity:"C", Type:["S"], Rating:"3", Sort:"1", Set:"EMN", Number:"39", Image:"/Images/EMN/DragUnder.jpg", },
{Name:"Enlightened Maniac", Cost:"3U", Color:["U"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"EMN", Number:"40", Image:"/Images/EMN/EnlightenedManiac.jpg", },
{Name:"Exultant Cultist", Cost:"2U", Color:["U"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"EMN", Number:"41", Image:"/Images/EMN/ExultantCultist.jpg", },
{Name:"Fogwalker", Cost:"1U", Color:["U"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"EMN", Number:"42", Image:"/Images/EMN/Fogwalker.jpg", },
{Name:"Fortune's Favor", Cost:"2U", Color:["U"], Rarity:"U", Type:["I"], Rating:"5", Sort:"1", Set:"EMN", Number:"43", Image:"/Images/EMN/FortunesFavor.jpg", },
{Name:"Geist of the Archives", Cost:"2U", Color:["U"], Rarity:"U", Type:["C"], Rating:"7", Sort:"1", Set:"EMN", Number:"44", Image:"/Images/EMN/GeistoftheArchives.jpg", },
{Name:"Identity Thief", Cost:"2UU", Color:["U"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"EMN", Number:"45", Image:"/Images/EMN/IdentityThief.jpg", },
{Name:"Imprisoned in the Moon", Cost:"2U", Color:["U"], Rarity:"R", Type:["E"], Rating:"8", Sort:"1", Set:"EMN", Number:"46", Image:"/Images/EMN/ImprisonedintheMoon.jpg", },
{Name:"Ingenious Skaab", Cost:"2U", Color:["U"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"EMN", Number:"47", Image:"/Images/EMN/IngeniousSkaab.jpg", },
{Name:"Laboratory Brute", Cost:"3U", Color:["U"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"EMN", Number:"48", Image:"/Images/EMN/LaboratoryBrute.jpg", },
{Name:"Lunar Force", Cost:"2U", Color:["U"], Rarity:"U", Type:["E"], Rating:"5", Sort:"1", Set:"EMN", Number:"49", Image:"/Images/EMN/LunarForce.jpg", },
{Name:"Mausoleum Wanderer", Cost:"0U", Color:["U"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"EMN", Number:"50", Image:"/Images/EMN/MausoleumWanderer.jpg", },
{Name:"Mind's Dilation", Cost:"5UU", Color:["U"], Rarity:"M", Type:["E"], Rating:"7", Sort:"1", Set:"EMN", Number:"51", Image:"/Images/EMN/MindsDilation.jpg", },
{Name:"Nebelgast Herald", Cost:"2U", Color:["U"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"EMN", Number:"52", Image:"/Images/EMN/NebelgastHerald.jpg", },
{Name:"Niblis of Frost", Cost:"2UU", Color:["U"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"EMN", Number:"53", Image:"/Images/EMN/NiblisofFrost.jpg", },
{Name:"Scour the Laboratory", Cost:"4UU", Color:["U"], Rarity:"U", Type:["I"], Rating:"4", Sort:"1", Set:"EMN", Number:"54", Image:"/Images/EMN/ScourtheLaboratory.jpg", },
{Name:"Spontaneous Mutation", Cost:"0U", Color:["U"], Rarity:"C", Type:["E"], Rating:"3", Sort:"1", Set:"EMN", Number:"55", Image:"/Images/EMN/SpontaneousMutation.jpg", },
{Name:"Summary Dismissal", Cost:"2UU", Color:["U"], Rarity:"R", Type:["I"], Rating:"6", Sort:"1", Set:"EMN", Number:"56", Image:"/Images/EMN/SummaryDismissal.jpg", },
{Name:"Take Inventory", Cost:"1U", Color:["U"], Rarity:"C", Type:["S"], Rating:"4", Sort:"1", Set:"EMN", Number:"57", Image:"/Images/EMN/TakeInventory.jpg", },
{Name:"Tattered Haunter", Cost:"1U", Color:["U"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"EMN", Number:"58", Image:"/Images/EMN/TatteredHaunter.jpg", },
{Name:"Turn Aside", Cost:"0U", Color:["U"], Rarity:"C", Type:["I"], Rating:"3", Sort:"1", Set:"EMN", Number:"59", Image:"/Images/EMN/TurnAside.jpg", },
{Name:"Unsubstantiate", Cost:"1U", Color:["U"], Rarity:"U", Type:["I"], Rating:"5", Sort:"1", Set:"EMN", Number:"60", Image:"/Images/EMN/Unsubstantiate.jpg", },
{Name:"Wharf Infiltrator", Cost:"1U", Color:["U"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"EMN", Number:"61", Image:"/Images/EMN/WharfInfiltrator.jpg", },
{Name:"Boon of Emrakul", Cost:"2B", Color:["B"], Rarity:"C", Type:["E"], Rating:"3", Sort:"1", Set:"EMN", Number:"62", Image:"/Images/EMN/BoonofEmrakul.jpg", },
{Name:"Borrowed Malevolence", Cost:"0B", Color:["B"], Rarity:"C", Type:["I"], Rating:"2", Sort:"1", Set:"EMN", Number:"63", Image:"/Images/EMN/BorrowedMalevolence.jpg", },
{Name:"Cemetery Recruitment", Cost:"1B", Color:["B"], Rarity:"C", Type:["S"], Rating:"2", Sort:"1", Set:"EMN", Number:"64", Image:"/Images/EMN/CemeteryRecruitment.jpg", },
{Name:"Certain Death", Cost:"5B", Color:["B"], Rarity:"C", Type:["S"], Rating:"3", Sort:"1", Set:"EMN", Number:"65", Image:"/Images/EMN/CertainDeath.jpg", },
{Name:"Collective Brutality", Cost:"1B", Color:["B"], Rarity:"R", Type:["S"], Rating:"6", Sort:"1", Set:"EMN", Number:"66", Image:"/Images/EMN/CollectiveBrutality.jpg", },
{Name:"Cryptbreaker", Cost:"0B", Color:["B"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"EMN", Number:"67", Image:"/Images/EMN/Cryptbreaker.jpg", },
{Name:"Dark Salvation", Cost:"0B", Color:["B"], Rarity:"R", Type:["S"], Rating:"7", Sort:"1", Set:"EMN", Number:"68", Image:"/Images/EMN/DarkSalvation.jpg", },
{Name:"Dusk Feaster", Cost:"5BB", Color:["B"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"EMN", Number:"69", Image:"/Images/EMN/DuskFeaster.jpg", },
{Name:"Gavony Unhallowed", Cost:"3B", Color:["B"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"EMN", Number:"70", Image:"/Images/EMN/GavonyUnhallowed.jpg", },
{Name:"Graf Harvest", Cost:"0B", Color:["B"], Rarity:"U", Type:["E"], Rating:"4", Sort:"1", Set:"EMN", Number:"71", Image:"/Images/EMN/GrafHarvest.jpg", },
{Name:"Haunted Dead", Cost:"3B", Color:["B"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"EMN", Number:"72", Image:"/Images/EMN/HauntedDead.jpg", },
{Name:"Liliana, the Last Hope", Cost:"1BB", Color:["B"], Rarity:"M", Type:["P"], Rating:"9", Sort:"1", Set:"EMN", Number:"73", Image:"/Images/EMN/Liliana--theLastHope.jpg", },
{Name:"Liliana's Elite", Cost:"2B", Color:["B"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"EMN", Number:"74", Image:"/Images/EMN/LilianasElite.jpg", },
{Name:"Markov Crusader", Cost:"4B", Color:["B"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"EMN", Number:"75", Image:"/Images/EMN/MarkovCrusader.jpg", },
{Name:"Murder", Cost:"1BB", Color:["B"], Rarity:"U", Type:["I"], Rating:"7", Sort:"1", Set:"EMN", Number:"76", Image:"/Images/EMN/Murder.jpg", },
{Name:"Noosegraf Mob", Cost:"4BB", Color:["B"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"EMN", Number:"77", Image:"/Images/EMN/NoosegrafMob.jpg", },
{Name:"Oath of Liliana", Cost:"2B", Color:["B"], Rarity:"R", Type:["E"], Rating:"7", Sort:"1", Set:"EMN", Number:"78", Image:"/Images/EMN/OathofLiliana.jpg", },
{Name:"Olivia's Dragoon", Cost:"1B", Color:["B"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"EMN", Number:"79", Image:"/Images/EMN/OliviasDragoon.jpg", },
{Name:"Prying Questions", Cost:"2B", Color:["B"], Rarity:"U", Type:["S"], Rating:"5", Sort:"1", Set:"EMN", Number:"80", Image:"/Images/EMN/PryingQuestions.jpg", },
{Name:"Rise from the Grave", Cost:"4B", Color:["B"], Rarity:"U", Type:["S"], Rating:"4", Sort:"1", Set:"EMN", Number:"81", Image:"/Images/EMN/RisefromtheGrave.jpg", },
{Name:"Ruthless Disposal", Cost:"4B", Color:["B"], Rarity:"U", Type:["S"], Rating:"6", Sort:"1", Set:"EMN", Number:"82", Image:"/Images/EMN/RuthlessDisposal.jpg", },
{Name:"Skirsdag Supplicant", Cost:"2B", Color:["B"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"EMN", Number:"83", Image:"/Images/EMN/SkirsdagSupplicant.jpg", },
{Name:"Strange Augmentation", Cost:"0B", Color:["B"], Rarity:"C", Type:["E"], Rating:"2", Sort:"1", Set:"EMN", Number:"84", Image:"/Images/EMN/StrangeAugmentation.jpg", },
{Name:"Stromkirk Condemned", Cost:"0BB", Color:["B"], Rarity:"R", Type:["C"], Rating:"6", Sort:"1", Set:"EMN", Number:"85", Image:"/Images/EMN/StromkirkCondemned.jpg", },
{Name:"Succumb to Temptation", Cost:"1BB", Color:["B"], Rarity:"C", Type:["I"], Rating:"4", Sort:"1", Set:"EMN", Number:"86", Image:"/Images/EMN/SuccumbtoTemptation.jpg", },
{Name:"Thraben Foulbloods", Cost:"2B", Color:["B"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"EMN", Number:"87", Image:"/Images/EMN/ThrabenFoulbloods.jpg", },
{Name:"Tree of Perdition", Cost:"3B", Color:["B"], Rarity:"M", Type:["C"], Rating:"8", Sort:"1", Set:"EMN", Number:"88", Image:"/Images/EMN/TreeofPerdition.jpg", },
{Name:"Vampire Cutthroat", Cost:"0B", Color:["B"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"EMN", Number:"89", Image:"/Images/EMN/VampireCutthroat.jpg", },
{Name:"Wailing Ghoul", Cost:"1B", Color:["B"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"EMN", Number:"90", Image:"/Images/EMN/WailingGhoul.jpg", },
{Name:"Weirded Vampire", Cost:"3B", Color:["B"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"EMN", Number:"91", Image:"/Images/EMN/WeirdedVampire.jpg", },
{Name:"Whispers of Emrakul", Cost:"1B", Color:["B"], Rarity:"U", Type:["S"], Rating:"7", Sort:"1", Set:"EMN", Number:"92", Image:"/Images/EMN/WhispersofEmrakul.jpg", },
{Name:"Abandon Reason", Cost:"2R", Color:["R"], Rarity:"U", Type:["I"], Rating:"3", Sort:"1", Set:"EMN", Number:"93", Image:"/Images/EMN/AbandonReason.jpg", },
{Name:"Alchemist's Greeting", Cost:"4R", Color:["R"], Rarity:"C", Type:["S"], Rating:"3", Sort:"1", Set:"EMN", Number:"94", Image:"/Images/EMN/AlchemistsGreeting.jpg", },
{Name:"Assembled Alphas", Cost:"5R", Color:["R"], Rarity:"R", Type:["C"], Rating:"6", Sort:"1", Set:"EMN", Number:"95", Image:"/Images/EMN/AssembledAlphas.jpg", },
{Name:"Bedlam Reveler", Cost:"6RR", Color:["R"], Rarity:"R", Type:["C"], Rating:"6", Sort:"1", Set:"EMN", Number:"96", Image:"/Images/EMN/BedlamReveler.jpg", },
{Name:"Blood Mist", Cost:"3R", Color:["R"], Rarity:"U", Type:["E"], Rating:"5", Sort:"1", Set:"EMN", Number:"97", Image:"/Images/EMN/BloodMist.jpg", },
{Name:"Bold Impaler", Cost:"0R", Color:["R"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"EMN", Number:"98", Image:"/Images/EMN/BoldImpaler.jpg", },
{Name:"Borrowed Hostility", Cost:"0R", Color:["R"], Rarity:"C", Type:["I"], Rating:"3", Sort:"1", Set:"EMN", Number:"99", Image:"/Images/EMN/BorrowedHostility.jpg", },
{Name:"Brazen Wolves", Cost:"2R", Color:["R"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"EMN", Number:"100", Image:"/Images/EMN/BrazenWolves.jpg", },
{Name:"Collective Defiance", Cost:"1RR", Color:["R"], Rarity:"R", Type:["S"], Rating:"7", Sort:"1", Set:"EMN", Number:"101", Image:"/Images/EMN/CollectiveDefiance.jpg", },
{Name:"Deranged Whelp", Cost:"1R", Color:["R"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"EMN", Number:"102", Image:"/Images/EMN/DerangedWhelp.jpg", },
{Name:"Distemper of the Blood", Cost:"1R", Color:["R"], Rarity:"C", Type:["S"], Rating:"2", Sort:"1", Set:"EMN", Number:"103", Image:"/Images/EMN/DistemperoftheBlood.jpg", },
{Name:"Falkenrath Reaver", Cost:"1R", Color:["R"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"EMN", Number:"104", Image:"/Images/EMN/FalkenrathReaver.jpg", },
{Name:"Furyblade Vampire", Cost:"1R", Color:["R"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"EMN", Number:"105", Image:"/Images/EMN/FurybladeVampire.jpg", },
{Name:"Galvanic Bombardment", Cost:"0R", Color:["R"], Rarity:"C", Type:["I"], Rating:"4", Sort:"1", Set:"EMN", Number:"106", Image:"/Images/EMN/GalvanicBombardment.jpg", },
{Name:"Harmless Offering", Cost:"2R", Color:["R"], Rarity:"R", Type:["S"], Rating:"5", Sort:"1", Set:"EMN", Number:"107", Image:"/Images/EMN/HarmlessOffering.jpg", },
{Name:"Impetuous Devils", Cost:"2RR", Color:["R"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"EMN", Number:"108", Image:"/Images/EMN/ImpetuousDevils.jpg", },
{Name:"Incendiary Flow", Cost:"1R", Color:["R"], Rarity:"U", Type:["S"], Rating:"5", Sort:"1", Set:"EMN", Number:"109", Image:"/Images/EMN/IncendiaryFlow.jpg", },
{Name:"Insatiable Gorgers", Cost:"2RR", Color:["R"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"EMN", Number:"110", Image:"/Images/EMN/InsatiableGorgers.jpg", },
{Name:"Make Mischief", Cost:"2R", Color:["R"], Rarity:"C", Type:["S"], Rating:"3", Sort:"1", Set:"EMN", Number:"111", Image:"/Images/EMN/MakeMischief.jpg", },
{Name:"Mirrorwing Dragon", Cost:"3RR", Color:["R"], Rarity:"M", Type:["C"], Rating:"8", Sort:"1", Set:"EMN", Number:"112", Image:"/Images/EMN/MirrorwingDragon.jpg", },
{Name:"Nahiri's Wrath", Cost:"2R", Color:["R"], Rarity:"M", Type:["S"], Rating:"7", Sort:"1", Set:"EMN", Number:"113", Image:"/Images/EMN/NahirisWrath.jpg", },
{Name:"Otherworldly Outburst", Cost:"0R", Color:["R"], Rarity:"C", Type:["I"], Rating:"4", Sort:"1", Set:"EMN", Number:"114", Image:"/Images/EMN/OtherworldlyOutburst.jpg", },
{Name:"Prophetic Ravings", Cost:"0R", Color:["R"], Rarity:"C", Type:["E"], Rating:"3", Sort:"1", Set:"EMN", Number:"115", Image:"/Images/EMN/PropheticRavings.jpg", },
{Name:"Savage Alliance", Cost:"2R", Color:["R"], Rarity:"U", Type:["I"], Rating:"5", Sort:"1", Set:"EMN", Number:"116", Image:"/Images/EMN/SavageAlliance.jpg", },
{Name:"Shreds of Sanity", Cost:"2R", Color:["R"], Rarity:"U", Type:["S"], Rating:"3", Sort:"1", Set:"EMN", Number:"117", Image:"/Images/EMN/ShredsofSanity.jpg", },
{Name:"Spreading Flames", Cost:"6R", Color:["R"], Rarity:"U", Type:["I"], Rating:"4", Sort:"1", Set:"EMN", Number:"118", Image:"/Images/EMN/SpreadingFlames.jpg", },
{Name:"Stensia Banquet", Cost:"2R", Color:["R"], Rarity:"C", Type:["S"], Rating:"2", Sort:"1", Set:"EMN", Number:"119", Image:"/Images/EMN/StensiaBanquet.jpg", },
{Name:"Stensia Innkeeper", Cost:"3R", Color:["R"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"EMN", Number:"120", Image:"/Images/EMN/StensiaInnkeeper.jpg", },
{Name:"Stromkirk Occultist", Cost:"2R", Color:["R"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"EMN", Number:"121", Image:"/Images/EMN/StromkirkOccultist.jpg", },
{Name:"Thermo-Alchemist", Cost:"1R", Color:["R"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"EMN", Number:"122", Image:"/Images/EMN/Thermo-Alchemist.jpg", },
{Name:"Weaver of Lightning", Cost:"2R", Color:["R"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"EMN", Number:"123", Image:"/Images/EMN/WeaverofLightning.jpg", },
{Name:"Backwoods Survivalists", Cost:"3G", Color:["G"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"EMN", Number:"124", Image:"/Images/EMN/BackwoodsSurvivalists.jpg", },
{Name:"Bloodbriar", Cost:"2G", Color:["G"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"EMN", Number:"125", Image:"/Images/EMN/Bloodbriar.jpg", },
{Name:"Clear Shot", Cost:"2G", Color:["G"], Rarity:"U", Type:["I"], Rating:"4", Sort:"1", Set:"EMN", Number:"126", Image:"/Images/EMN/ClearShot.jpg", },
{Name:"Crop Sigil", Cost:"0G", Color:["G"], Rarity:"U", Type:["E"], Rating:"6", Sort:"1", Set:"EMN", Number:"127", Image:"/Images/EMN/CropSigil.jpg", },
{Name:"Crossroads Consecrator", Cost:"0G", Color:["G"], Rarity:"C", Type:["C"], Rating:"2", Sort:"1", Set:"EMN", Number:"128", Image:"/Images/EMN/CrossroadsConsecrator.jpg", },
{Name:"Eldritch Evolution", Cost:"1GG", Color:["G"], Rarity:"R", Type:["S"], Rating:"8", Sort:"1", Set:"EMN", Number:"129", Image:"/Images/EMN/EldritchEvolution.jpg", },
{Name:"Emrakul's Evangel", Cost:"2G", Color:["G"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"EMN", Number:"130", Image:"/Images/EMN/EmrakulsEvangel.jpg", },
{Name:"Emrakul's Influence", Cost:"2GG", Color:["G"], Rarity:"U", Type:["E"], Rating:"3", Sort:"1", Set:"EMN", Number:"131", Image:"/Images/EMN/EmrakulsInfluence.jpg", },
{Name:"Foul Emissary", Cost:"2G", Color:["G"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"EMN", Number:"132", Image:"/Images/EMN/FoulEmissary.jpg", },
{Name:"Gnarlwood Dryad", Cost:"0G", Color:["G"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"EMN", Number:"133", Image:"/Images/EMN/GnarlwoodDryad.jpg", },
{Name:"Grapple with the Past", Cost:"1G", Color:["G"], Rarity:"C", Type:["I"], Rating:"3", Sort:"1", Set:"EMN", Number:"134", Image:"/Images/EMN/GrapplewiththePast.jpg", },
{Name:"Hamlet Captain", Cost:"1G", Color:["G"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"EMN", Number:"135", Image:"/Images/EMN/HamletCaptain.jpg", },
{Name:"Ishkanah, Grafwidow", Cost:"4G", Color:["G"], Rarity:"M", Type:["C"], Rating:"7", Sort:"1", Set:"EMN", Number:"136", Image:"/Images/EMN/Ishkanah--Grafwidow.jpg", },
{Name:"Noose Constrictor", Cost:"1G", Color:["G"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"EMN", Number:"137", Image:"/Images/EMN/NooseConstrictor.jpg", },
{Name:"Permeating Mass", Cost:"0G", Color:["G"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"EMN", Number:"138", Image:"/Images/EMN/PermeatingMass.jpg", },
{Name:"Prey Upon", Cost:"0G", Color:["G"], Rarity:"C", Type:["S"], Rating:"4", Sort:"1", Set:"EMN", Number:"139", Image:"/Images/EMN/PreyUpon.jpg", },
{Name:"Primal Druid", Cost:"1G", Color:["G"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"EMN", Number:"140", Image:"/Images/EMN/PrimalDruid.jpg", },
{Name:"Somberwald Stag", Cost:"3GG", Color:["G"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"EMN", Number:"141", Image:"/Images/EMN/SomberwaldStag.jpg", },
{Name:"Spirit of the Hunt", Cost:"1GG", Color:["G"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"EMN", Number:"142", Image:"/Images/EMN/SpiritoftheHunt.jpg", },
{Name:"Splendid Reclamation", Cost:"3G", Color:["G"], Rarity:"R", Type:["S"], Rating:"6", Sort:"1", Set:"EMN", Number:"143", Image:"/Images/EMN/SplendidReclamation.jpg", },
{Name:"Springsage Ritual", Cost:"3G", Color:["G"], Rarity:"C", Type:["I"], Rating:"2", Sort:"1", Set:"EMN", Number:"144", Image:"/Images/EMN/SpringsageRitual.jpg", },
{Name:"Swift Spinner", Cost:"3G", Color:["G"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"EMN", Number:"145", Image:"/Images/EMN/SwiftSpinner.jpg", },
{Name:"Ulvenwald Observer", Cost:"4GG", Color:["G"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"EMN", Number:"146", Image:"/Images/EMN/UlvenwaldObserver.jpg", },
{Name:"Waxing Moon", Cost:"1G", Color:["G"], Rarity:"C", Type:["I"], Rating:"2", Sort:"1", Set:"EMN", Number:"147", Image:"/Images/EMN/WaxingMoon.jpg", },
{Name:"Wolfkin Bond", Cost:"4G", Color:["G"], Rarity:"C", Type:["E"], Rating:"3", Sort:"1", Set:"EMN", Number:"148", Image:"/Images/EMN/WolfkinBond.jpg", },
{Name:"Woodcutter's Grit", Cost:"2G", Color:["G"], Rarity:"C", Type:["I"], Rating:"3", Sort:"1", Set:"EMN", Number:"149", Image:"/Images/EMN/WoodcuttersGrit.jpg", },
{Name:"Woodland Patrol", Cost:"2G", Color:["G"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"EMN", Number:"150", Image:"/Images/EMN/WoodlandPatrol.jpg", },
{Name:"Bloodhall Priest", Cost:"2BR", Color:["B","R"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"EMN", Number:"151", Image:"/Images/EMN/BloodhallPriest.jpg", },
{Name:"Campaign of Vengeance", Cost:"3WB", Color:["W","B"], Rarity:"U", Type:["E"], Rating:"4", Sort:"1", Set:"EMN", Number:"152", Image:"/Images/EMN/CampaignofVengeance.jpg", },
{Name:"Gisa and Geralf", Cost:"2UB", Color:["U","B"], Rarity:"M", Type:["C"], Rating:"9", Sort:"1", Set:"EMN", Number:"153", Image:"/Images/EMN/GisaandGeralf.jpg", },
{Name:"Grim Flayer", Cost:"0BG", Color:["B","G"], Rarity:"M", Type:["C"], Rating:"9", Sort:"1", Set:"EMN", Number:"154", Image:"/Images/EMN/GrimFlayer.jpg", },
{Name:"Heron's Grace Champion", Cost:"2GW", Color:["G","W"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"EMN", Number:"155", Image:"/Images/EMN/HeronsGraceChampion.jpg", },
{Name:"Mercurial Geists", Cost:"2UR", Color:["U","R"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"EMN", Number:"156", Image:"/Images/EMN/MercurialGeists.jpg", },
{Name:"Mournwillow", Cost:"1BG", Color:["B","G"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"EMN", Number:"157", Image:"/Images/EMN/Mournwillow.jpg", },
{Name:"Ride Down", Cost:"0RW", Color:["R","W"], Rarity:"U", Type:["I"], Rating:"7", Sort:"1", Set:"EMN", Number:"158", Image:"/Images/EMN/RideDown.jpg", },
{Name:"Spell Queller", Cost:"1WU", Color:["W","U"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"EMN", Number:"159", Image:"/Images/EMN/SpellQueller.jpg", },
{Name:"Tamiyo, Field Researcher", Cost:"1GWB", Color:["G","W","B"], Rarity:"M", Type:["P"], Rating:"9", Sort:"1", Set:"EMN", Number:"160", Image:"/Images/EMN/Tamiyo--FieldResearcher.jpg", },
{Name:"Abundant Maw", Cost:"8", Color:["C"], Rarity:"U", Type:["C"], Rating:"3", Sort:"1", Set:"EMN", Number:"161", Image:"/Images/EMN/AbundantMaw.jpg", },
{Name:"Decimator of the Provinces", Cost:"10", Color:["C"], Rarity:"M", Type:["C"], Rating:"6", Sort:"1", Set:"EMN", Number:"162", Image:"/Images/EMN/DecimatoroftheProvinces.jpg", },
{Name:"Distended Mindbender", Cost:"8", Color:["C"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"EMN", Number:"163", Image:"/Images/EMN/DistendedMindbender.jpg", },
{Name:"Drownyard Behemoth", Cost:"9", Color:["C"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"EMN", Number:"164", Image:"/Images/EMN/DrownyardBehemoth.jpg", },
{Name:"Elder Deep-Fiend", Cost:"8", Color:["C"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"EMN", Number:"165", Image:"/Images/EMN/ElderDeep-Fiend.jpg", },
{Name:"Emrakul, the Promised End", Cost:"13", Color:["C"], Rarity:"M", Type:["C"], Rating:"8", Sort:"1", Set:"EMN", Number:"166", Image:"/Images/EMN/Emrakul--thePromisedEnd.jpg", },
{Name:"Eternal Scourge", Cost:"3", Color:["C"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"EMN", Number:"167", Image:"/Images/EMN/EternalScourge.jpg", },
{Name:"It of the Horrid Swarm", Cost:"8", Color:["C"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"EMN", Number:"168", Image:"/Images/EMN/ItoftheHorridSwarm.jpg", },
{Name:"Lashweed Lurker", Cost:"8", Color:["C"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"EMN", Number:"169", Image:"/Images/EMN/LashweedLurker.jpg", },
{Name:"Mockery of Nature", Cost:"9", Color:["C"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"EMN", Number:"170", Image:"/Images/EMN/MockeryofNature.jpg", },
{Name:"Vexing Scuttler", Cost:"8", Color:["C"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"EMN", Number:"171", Image:"/Images/EMN/VexingScuttler.jpg", },
{Name:"Wretched Gryff", Cost:"7", Color:["C"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"EMN", Number:"172", Image:"/Images/EMN/WretchedGryff.jpg", },
{Name:"Extricator of Sin", Cost:"2W", Color:["W"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"EMN", Number:"173", Image:"/Images/EMN/ExtricatorofSin.jpg", ReverseImage:"/Images/EMN/ExtricatorofFlesh.jpg"},
{Name:"Lone Rider", Cost:"1W", Color:["W"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"EMN", Number:"174", Image:"/Images/EMN/LoneRider.jpg", ReverseImage:"/Images/EMN/ItThatRidesasOne.jpg"},
{Name:"Curious Homunculus", Cost:"1U", Color:["U"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"EMN", Number:"175", Image:"/Images/EMN/CuriousHomunculus.jpg", ReverseImage:"/Images/EMN/VoraciousReader.jpg"},
{Name:"Docent of Perfection", Cost:"3UU", Color:["U"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"EMN", Number:"176", Image:"/Images/EMN/DocentofPerfection.jpg", ReverseImage:"/Images/EMN/FinalIteration.jpg"},
{Name:"Grizzled Angler", Cost:"2U", Color:["U"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"EMN", Number:"177", Image:"/Images/EMN/GrizzledAngler.jpg", ReverseImage:"/Images/EMN/GrislyAnglerfish.jpg"},
{Name:"Voldaren Pariah", Cost:"3BB", Color:["B"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"EMN", Number:"178", Image:"/Images/EMN/VoldarenPariah.jpg", ReverseImage:"/Images/EMN/AbolisherofBloodlines.jpg"},
{Name:"Conduit of Storms", Cost:"2R", Color:["R"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"EMN", Number:"179", Image:"/Images/EMN/ConduitofStorms.jpg", ReverseImage:"/Images/EMN/ConduitofEmrakul.jpg"},
{Name:"Smoldering Werewolf", Cost:"2RR", Color:["R"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"EMN", Number:"180", Image:"/Images/EMN/SmolderingWerewolf.jpg", ReverseImage:"/Images/EMN/EruptingDreadwolf.jpg"},
{Name:"Vildin-Pack Outcast", Cost:"4R", Color:["R"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"EMN", Number:"181", Image:"/Images/EMN/Vildin-PackOutcast.jpg", ReverseImage:"/Images/EMN/DronepackKindred.jpg"},
{Name:"Kessig Prowler", Cost:"1G", Color:["G"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"EMN", Number:"182", Image:"/Images/EMN/KessigProwler.jpg", ReverseImage:"/Images/EMN/SinuousPredator.jpg"},
{Name:"Shrill Howler", Cost:"2G", Color:["G"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"EMN", Number:"183", Image:"/Images/EMN/ShrillHowler.jpg", ReverseImage:"/Images/EMN/HowlingChorus.jpg"},
{Name:"Tangleclaw Werewolf", Cost:"2GG", Color:["G"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"EMN", Number:"184", Image:"/Images/EMN/TangleclawWerewolf.jpg", ReverseImage:"/Images/EMN/FibrousEntangler.jpg"},
{Name:"Ulvenwald Captive", Cost:"1G", Color:["G"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"EMN", Number:"185", Image:"/Images/EMN/UlvenwaldCaptive.jpg", ReverseImage:"/Images/EMN/UlvenwaldAbomination.jpg"},
{Name:"Ulrich of the Krallenhorde", Cost:"3RG", Color:["R","G"], Rarity:"M", Type:["C"], Rating:"9", Sort:"1", Set:"EMN", Number:"186", Image:"/Images/EMN/UlrichoftheKrallenhorde.jpg", ReverseImage:"/Images/EMN/Ulrich--UncontestedAlpha.jpg"},
{Name:"Cryptolith Fragment", Cost:"3", Color:["C"], Rarity:"U", Type:["A"], Rating:"7", Sort:"1", Set:"EMN", Number:"187", Image:"/Images/EMN/CryptolithFragment.jpg", ReverseImage:"/Images/EMN/AuroraofEmrakul.jpg"},
{Name:"Cathar's Shield", Cost:"3", Color:["C"], Rarity:"C", Type:["A"], Rating:"2", Sort:"1", Set:"EMN", Number:"188", Image:"/Images/EMN/CatharsShield.jpg", },
{Name:"Cultist's Staff", Cost:"0", Color:["C"], Rarity:"C", Type:["A"], Rating:"2", Sort:"1", Set:"EMN", Number:"189", Image:"/Images/EMN/CultistsStaff.jpg", },
{Name:"Field Creeper", Cost:"2", Color:["C"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"EMN", Number:"190", Image:"/Images/EMN/FieldCreeper.jpg", },
{Name:"Geist-Fueled Scarecrow", Cost:"4", Color:["C"], Rarity:"U", Type:["C"], Rating:"3", Sort:"1", Set:"EMN", Number:"191", Image:"/Images/EMN/Geist-FueledScarecrow.jpg", },
{Name:"Lupine Prototype", Cost:"2", Color:["C"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"EMN", Number:"192", Image:"/Images/EMN/LupinePrototype.jpg", },
{Name:"Slayer's Cleaver", Cost:"3", Color:["C"], Rarity:"U", Type:["A"], Rating:"2", Sort:"1", Set:"EMN", Number:"193", Image:"/Images/EMN/SlayersCleaver.jpg", },
{Name:"Soul Separator", Cost:"3", Color:["C"], Rarity:"R", Type:["A"], Rating:"8", Sort:"1", Set:"EMN", Number:"194", Image:"/Images/EMN/SoulSeparator.jpg", },
{Name:"Stitcher's Graft", Cost:"1", Color:["C"], Rarity:"R", Type:["A"], Rating:"6", Sort:"1", Set:"EMN", Number:"195", Image:"/Images/EMN/StitchersGraft.jpg", },
{Name:"Terrarion", Cost:"1", Color:["C"], Rarity:"C", Type:["A"], Rating:"2", Sort:"1", Set:"EMN", Number:"196", Image:"/Images/EMN/Terrarion.jpg", },
{Name:"Thirsting Axe", Cost:"3", Color:["C"], Rarity:"U", Type:["A"], Rating:"4", Sort:"1", Set:"EMN", Number:"197", Image:"/Images/EMN/ThirstingAxe.jpg", },
{Name:"Geier Reach Sanitarium", Cost:"0", Color:["C"], Rarity:"R", Type:["L"], Rating:"6", Sort:"1", Set:"EMN", Number:"198", Image:"/Images/EMN/GeierReachSanitarium.jpg", },
{Name:"Nephalia Academy", Cost:"0", Color:["C"], Rarity:"U", Type:["L"], Rating:"5", Sort:"1", Set:"EMN", Number:"199", Image:"/Images/EMN/NephaliaAcademy.jpg", },
{Name:"Gisela, the Broken Blade", Cost:"2WW", Color:["W"], Rarity:"M", Type:["C"], Rating:"9", Sort:"1", Set:"EMN", Number:"200", Image:"/Images/EMN/Gisela--theBrokenBlade.jpg", ReverseImage:"/Images/EMN/Brisela--VoiceofNightmares(Top).jpg"},
{Name:"Bruna, the Fading Light", Cost:"5WW", Color:["W"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"EMN", Number:"201", Image:"/Images/EMN/Bruna--theFadingLight.jpg", ReverseImage:"/Images/EMN/Brisela--VoiceofNightmares(Bottom).jpg"},
{Name:"Graf Rats", Cost:"1B", Color:["B"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"EMN", Number:"202", Image:"/Images/EMN/GrafRats.jpg", ReverseImage:"/Images/EMN/ChitteringHost(Top).jpg"},
{Name:"Midnight Scavengers", Cost:"4B", Color:["B"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"EMN", Number:"203", Image:"/Images/EMN/MidnightScavengers.jpg", ReverseImage:"/Images/EMN/ChitteringHost(Bottom).jpg"},
{Name:"Hanweir Battlements", Cost:"0", Color:["C"], Rarity:"R", Type:["L"], Rating:"6", Sort:"1", Set:"EMN", Number:"204", Image:"/Images/EMN/HanweirBattlements.jpg", ReverseImage:"/Images/EMN/Hanweir--theWrithingTownship(Top).jpg"},
{Name:"Hanweir Garrison", Cost:"0", Color:["C"], Rarity:"R", Type:["L"], Rating:"8", Sort:"1", Set:"EMN", Number:"205", Image:"/Images/EMN/HanweirGarrison.jpg", ReverseImage:"/Images/EMN/Hanweir--theWrithingTownship(Bottom).jpg"},
];
