var KLD = [
{Name:"Acrobatic Maneuver", Cost:"2W", Color:["W"], Rarity:"C", Type:["I"], Rating:"3", Sort:"1", Set:"KLD", Number:"1", Image:"/Images/KLD/AcrobaticManeuver.jpg", },
{Name:"Aerial Responder", Cost:"1WW", Color:["W"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"KLD", Number:"2", Image:"/Images/KLD/AerialResponder.jpg", },
{Name:"Aetherstorm Roc", Cost:"2WW", Color:["W"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"KLD", Number:"3", Image:"/Images/KLD/AetherstormRoc.jpg", },
{Name:"Angel of Invention", Cost:"3WW", Color:["W"], Rarity:"M", Type:["C"], Rating:"8", Sort:"1", Set:"KLD", Number:"4", Image:"/Images/KLD/AngelofInvention.jpg", },
{Name:"Authority of the Consuls", Cost:"0W", Color:["W"], Rarity:"R", Type:["E"], Rating:"7", Sort:"1", Set:"KLD", Number:"5", Image:"/Images/KLD/AuthorityoftheConsuls.jpg", },
{Name:"Aviary Mechanic", Cost:"1W", Color:["W"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"KLD", Number:"6", Image:"/Images/KLD/AviaryMechanic.jpg", },
{Name:"Built to Last", Cost:"0W", Color:["W"], Rarity:"C", Type:["I"], Rating:"2", Sort:"1", Set:"KLD", Number:"7", Image:"/Images/KLD/BuilttoLast.jpg", },
{Name:"Captured by the Consulate", Cost:"3W", Color:["W"], Rarity:"R", Type:["E"], Rating:"7", Sort:"1", Set:"KLD", Number:"8", Image:"/Images/KLD/CapturedbytheConsulate.jpg", },
{Name:"Cataclysmic Gearhulk", Cost:"3WW", Color:["W"], Rarity:"M", Type:["C"], Rating:"9", Sort:"1", Set:"KLD", Number:"9", Image:"/Images/KLD/CataclysmicGearhulk.jpg", },
{Name:"Consulate Surveillance", Cost:"3W", Color:["W"], Rarity:"U", Type:["E"], Rating:"4", Sort:"1", Set:"KLD", Number:"10", Image:"/Images/KLD/ConsulateSurveillance.jpg", },
{Name:"Consul's Shieldguard", Cost:"3W", Color:["W"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"KLD", Number:"11", Image:"/Images/KLD/ConsulsShieldguard.jpg", },
{Name:"Eddytrail Hawk", Cost:"1W", Color:["W"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"KLD", Number:"12", Image:"/Images/KLD/EddytrailHawk.jpg", },
{Name:"Fairgrounds Warden", Cost:"2W", Color:["W"], Rarity:"U", Type:["C"], Rating:"7", Sort:"1", Set:"KLD", Number:"13", Image:"/Images/KLD/FairgroundsWarden.jpg", },
{Name:"Fragmentize", Cost:"0W", Color:["W"], Rarity:"C", Type:["S"], Rating:"3", Sort:"1", Set:"KLD", Number:"14", Image:"/Images/KLD/Fragmentize.jpg", },
{Name:"Fumigate", Cost:"3WW", Color:["W"], Rarity:"R", Type:["S"], Rating:"8", Sort:"1", Set:"KLD", Number:"15", Image:"/Images/KLD/Fumigate.jpg", },
{Name:"Gearshift Ace", Cost:"1W", Color:["W"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"KLD", Number:"16", Image:"/Images/KLD/GearshiftAce.jpg", },
{Name:"Glint-Sleeve Artisan", Cost:"2W", Color:["W"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"KLD", Number:"17", Image:"/Images/KLD/Glint-SleeveArtisan.jpg", },
{Name:"Herald of the Fair", Cost:"2W", Color:["W"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"KLD", Number:"18", Image:"/Images/KLD/HeraldoftheFair.jpg", },
{Name:"Impeccable Timing", Cost:"1W", Color:["W"], Rarity:"C", Type:["I"], Rating:"3", Sort:"1", Set:"KLD", Number:"19", Image:"/Images/KLD/ImpeccableTiming.jpg", },
{Name:"Inspired Charge", Cost:"2WW", Color:["W"], Rarity:"C", Type:["I"], Rating:"2", Sort:"1", Set:"KLD", Number:"20", Image:"/Images/KLD/InspiredCharge.jpg", },
{Name:"Master Trinketeer", Cost:"2W", Color:["W"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"KLD", Number:"21", Image:"/Images/KLD/MasterTrinketeer.jpg", },
{Name:"Ninth Bridge Patrol", Cost:"1W", Color:["W"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"KLD", Number:"22", Image:"/Images/KLD/NinthBridgePatrol.jpg", },
{Name:"Pressure Point", Cost:"1W", Color:["W"], Rarity:"C", Type:["I"], Rating:"3", Sort:"1", Set:"KLD", Number:"23", Image:"/Images/KLD/PressurePoint.jpg", },
{Name:"Propeller Pioneer", Cost:"3W", Color:["W"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"KLD", Number:"24", Image:"/Images/KLD/PropellerPioneer.jpg", },
{Name:"Refurbish", Cost:"3W", Color:["W"], Rarity:"U", Type:["S"], Rating:"3", Sort:"1", Set:"KLD", Number:"25", Image:"/Images/KLD/Refurbish.jpg", },
{Name:"Revoke Privileges", Cost:"2W", Color:["W"], Rarity:"C", Type:["E"], Rating:"4", Sort:"1", Set:"KLD", Number:"26", Image:"/Images/KLD/RevokePrivileges.jpg", },
{Name:"Servo Exhibition", Cost:"1W", Color:["W"], Rarity:"U", Type:["S"], Rating:"4", Sort:"1", Set:"KLD", Number:"27", Image:"/Images/KLD/ServoExhibition.jpg", },
{Name:"Skyswirl Harrier", Cost:"4W", Color:["W"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"KLD", Number:"28", Image:"/Images/KLD/SkyswirlHarrier.jpg", },
{Name:"Skywhaler's Shot", Cost:"2W", Color:["W"], Rarity:"U", Type:["I"], Rating:"7", Sort:"1", Set:"KLD", Number:"29", Image:"/Images/KLD/SkywhalersShot.jpg", },
{Name:"Tasseled Dromedary", Cost:"0W", Color:["W"], Rarity:"C", Type:["C"], Rating:"2", Sort:"1", Set:"KLD", Number:"30", Image:"/Images/KLD/TasseledDromedary.jpg", },
{Name:"Thriving Ibex", Cost:"3W", Color:["W"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"KLD", Number:"31", Image:"/Images/KLD/ThrivingIbex.jpg", },
{Name:"Toolcraft Exemplar", Cost:"0W", Color:["W"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"KLD", Number:"32", Image:"/Images/KLD/ToolcraftExemplar.jpg", },
{Name:"Trusty Companion", Cost:"1W", Color:["W"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"KLD", Number:"33", Image:"/Images/KLD/TrustyCompanion.jpg", },
{Name:"Visionary Augmenter", Cost:"2WW", Color:["W"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"KLD", Number:"34", Image:"/Images/KLD/VisionaryAugmenter.jpg", },
{Name:"Wispweaver Angel", Cost:"4WW", Color:["W"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"KLD", Number:"35", Image:"/Images/KLD/WispweaverAngel.jpg", },
{Name:"Aether Meltdown", Cost:"1U", Color:["U"], Rarity:"U", Type:["E"], Rating:"4", Sort:"1", Set:"KLD", Number:"36", Image:"/Images/KLD/AetherMeltdown.jpg", },
{Name:"Aether Theorist", Cost:"1U", Color:["U"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"KLD", Number:"37", Image:"/Images/KLD/AetherTheorist.jpg", },
{Name:"Aether Tradewinds", Cost:"2U", Color:["U"], Rarity:"C", Type:["I"], Rating:"2", Sort:"1", Set:"KLD", Number:"38", Image:"/Images/KLD/AetherTradewinds.jpg", },
{Name:"Aethersquall Ancient", Cost:"5UU", Color:["U"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"KLD", Number:"39", Image:"/Images/KLD/AethersquallAncient.jpg", },
{Name:"Ceremonious Rejection", Cost:"0U", Color:["U"], Rarity:"U", Type:["I"], Rating:"3", Sort:"1", Set:"KLD", Number:"40", Image:"/Images/KLD/CeremoniousRejection.jpg", },
{Name:"Confiscation Coup", Cost:"3UU", Color:["U"], Rarity:"R", Type:["S"], Rating:"7", Sort:"1", Set:"KLD", Number:"41", Image:"/Images/KLD/ConfiscationCoup.jpg", },
{Name:"Curio Vendor", Cost:"1U", Color:["U"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"KLD", Number:"42", Image:"/Images/KLD/CurioVendor.jpg", },
{Name:"Disappearing Act", Cost:"1UU", Color:["U"], Rarity:"U", Type:["I"], Rating:"4", Sort:"1", Set:"KLD", Number:"43", Image:"/Images/KLD/DisappearingAct.jpg", },
{Name:"Dramatic Reversal", Cost:"1U", Color:["U"], Rarity:"C", Type:["I"], Rating:"2", Sort:"1", Set:"KLD", Number:"44", Image:"/Images/KLD/DramaticReversal.jpg", },
{Name:"Era of Innovation", Cost:"1U", Color:["U"], Rarity:"U", Type:["E"], Rating:"4", Sort:"1", Set:"KLD", Number:"45", Image:"/Images/KLD/EraofInnovation.jpg", },
{Name:"Experimental Aviator", Cost:"3UU", Color:["U"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"KLD", Number:"46", Image:"/Images/KLD/ExperimentalAviator.jpg", },
{Name:"Failed Inspection", Cost:"2UU", Color:["U"], Rarity:"C", Type:["I"], Rating:"3", Sort:"1", Set:"KLD", Number:"47", Image:"/Images/KLD/FailedInspection.jpg", },
{Name:"Gearseeker Serpent", Cost:"5UU", Color:["U"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"KLD", Number:"48", Image:"/Images/KLD/GearseekerSerpent.jpg", },
{Name:"Glimmer of Genius", Cost:"3U", Color:["U"], Rarity:"U", Type:["I"], Rating:"5", Sort:"1", Set:"KLD", Number:"49", Image:"/Images/KLD/GlimmerofGenius.jpg", },
{Name:"Glint-Nest Crane", Cost:"1U", Color:["U"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"KLD", Number:"50", Image:"/Images/KLD/Glint-NestCrane.jpg", },
{Name:"Hightide Hermit", Cost:"4U", Color:["U"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"KLD", Number:"51", Image:"/Images/KLD/HightideHermit.jpg", },
{Name:"Insidious Will", Cost:"2UU", Color:["U"], Rarity:"R", Type:["I"], Rating:"7", Sort:"1", Set:"KLD", Number:"52", Image:"/Images/KLD/InsidiousWill.jpg", },
{Name:"Janjeet Sentry", Cost:"2U", Color:["U"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"KLD", Number:"53", Image:"/Images/KLD/JanjeetSentry.jpg", },
{Name:"Long-Finned Skywhale", Cost:"2UU", Color:["U"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"KLD", Number:"54", Image:"/Images/KLD/Long-FinnedSkywhale.jpg", },
{Name:"Malfunction", Cost:"3U", Color:["U"], Rarity:"C", Type:["E"], Rating:"4", Sort:"1", Set:"KLD", Number:"55", Image:"/Images/KLD/Malfunction.jpg", },
{Name:"Metallurgic Summonings", Cost:"3UU", Color:["U"], Rarity:"M", Type:["E"], Rating:"9", Sort:"1", Set:"KLD", Number:"56", Image:"/Images/KLD/MetallurgicSummonings.jpg", },
{Name:"Minister of Inquiries", Cost:"0U", Color:["U"], Rarity:"U", Type:["C"], Rating:"3", Sort:"1", Set:"KLD", Number:"57", Image:"/Images/KLD/MinisterofInquiries.jpg", },
{Name:"Nimble Innovator", Cost:"3U", Color:["U"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"KLD", Number:"58", Image:"/Images/KLD/NimbleInnovator.jpg", },
{Name:"Padeem, Consul of Innovation", Cost:"3U", Color:["U"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"KLD", Number:"59", Image:"/Images/KLD/Padeem--ConsulofInnovation.jpg", },
{Name:"Paradoxical Outcome", Cost:"3U", Color:["U"], Rarity:"R", Type:["I"], Rating:"6", Sort:"1", Set:"KLD", Number:"60", Image:"/Images/KLD/ParadoxicalOutcome.jpg", },
{Name:"Revolutionary Rebuff", Cost:"1U", Color:["U"], Rarity:"C", Type:["I"], Rating:"3", Sort:"1", Set:"KLD", Number:"61", Image:"/Images/KLD/RevolutionaryRebuff.jpg", },
{Name:"Saheeli's Artistry", Cost:"4UU", Color:["U"], Rarity:"R", Type:["S"], Rating:"6", Sort:"1", Set:"KLD", Number:"62", Image:"/Images/KLD/SaheelisArtistry.jpg", },
{Name:"Select for Inspection", Cost:"0U", Color:["U"], Rarity:"C", Type:["I"], Rating:"3", Sort:"1", Set:"KLD", Number:"63", Image:"/Images/KLD/SelectforInspection.jpg", },
{Name:"Shrewd Negotiation", Cost:"4U", Color:["U"], Rarity:"U", Type:["S"], Rating:"3", Sort:"1", Set:"KLD", Number:"64", Image:"/Images/KLD/ShrewdNegotiation.jpg", },
{Name:"Tezzeret's Ambition", Cost:"3UU", Color:["U"], Rarity:"C", Type:["S"], Rating:"3", Sort:"1", Set:"KLD", Number:"65", Image:"/Images/KLD/TezzeretsAmbition.jpg", },
{Name:"Thriving Turtle", Cost:"0U", Color:["U"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"KLD", Number:"66", Image:"/Images/KLD/ThrivingTurtle.jpg", },
{Name:"Torrential Gearhulk", Cost:"4UU", Color:["U"], Rarity:"M", Type:["C"], Rating:"9", Sort:"1", Set:"KLD", Number:"67", Image:"/Images/KLD/TorrentialGearhulk.jpg", },
{Name:"Vedalken Blademaster", Cost:"2U", Color:["U"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"KLD", Number:"68", Image:"/Images/KLD/VedalkenBlademaster.jpg", },
{Name:"Weldfast Wingsmith", Cost:"3U", Color:["U"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"KLD", Number:"69", Image:"/Images/KLD/WeldfastWingsmith.jpg", },
{Name:"Wind Drake", Cost:"2U", Color:["U"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"KLD", Number:"70", Image:"/Images/KLD/WindDrake.jpg", },
{Name:"Aetherborn Marauder", Cost:"3B", Color:["B"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"KLD", Number:"71", Image:"/Images/KLD/AetherbornMarauder.jpg", },
{Name:"Ambitious Aetherborn", Cost:"4B", Color:["B"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"KLD", Number:"72", Image:"/Images/KLD/AmbitiousAetherborn.jpg", },
{Name:"Demon of Dark Schemes", Cost:"3BBB", Color:["B"], Rarity:"M", Type:["C"], Rating:"9", Sort:"1", Set:"KLD", Number:"73", Image:"/Images/KLD/DemonofDarkSchemes.jpg", },
{Name:"Dhund Operative", Cost:"1B", Color:["B"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"KLD", Number:"74", Image:"/Images/KLD/DhundOperative.jpg", },
{Name:"Diabolic Tutor", Cost:"2BB", Color:["B"], Rarity:"U", Type:["S"], Rating:"5", Sort:"1", Set:"KLD", Number:"75", Image:"/Images/KLD/DiabolicTutor.jpg", },
{Name:"Die Young", Cost:"1B", Color:["B"], Rarity:"C", Type:["S"], Rating:"3", Sort:"1", Set:"KLD", Number:"76", Image:"/Images/KLD/DieYoung.jpg", },
{Name:"Dukhara Scavenger", Cost:"5B", Color:["B"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"KLD", Number:"77", Image:"/Images/KLD/DukharaScavenger.jpg", },
{Name:"Eliminate the Competition", Cost:"4B", Color:["B"], Rarity:"R", Type:["S"], Rating:"7", Sort:"1", Set:"KLD", Number:"78", Image:"/Images/KLD/EliminatetheCompetition.jpg", },
{Name:"Embraal Bruiser", Cost:"1B", Color:["B"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"KLD", Number:"79", Image:"/Images/KLD/EmbraalBruiser.jpg", },
{Name:"Essence Extraction", Cost:"1BB", Color:["B"], Rarity:"U", Type:["I"], Rating:"4", Sort:"1", Set:"KLD", Number:"80", Image:"/Images/KLD/EssenceExtraction.jpg", },
{Name:"Fortuitous Find", Cost:"2B", Color:["B"], Rarity:"C", Type:["S"], Rating:"2", Sort:"1", Set:"KLD", Number:"81", Image:"/Images/KLD/FortuitousFind.jpg", },
{Name:"Foundry Screecher", Cost:"2B", Color:["B"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"KLD", Number:"82", Image:"/Images/KLD/FoundryScreecher.jpg", },
{Name:"Fretwork Colony", Cost:"1B", Color:["B"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"KLD", Number:"83", Image:"/Images/KLD/FretworkColony.jpg", },
{Name:"Gonti, Lord of Luxury", Cost:"2BB", Color:["B"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"KLD", Number:"84", Image:"/Images/KLD/Gonti--LordofLuxury.jpg", },
{Name:"Harsh Scrutiny", Cost:"0B", Color:["B"], Rarity:"U", Type:["S"], Rating:"5", Sort:"1", Set:"KLD", Number:"85", Image:"/Images/KLD/HarshScrutiny.jpg", },
{Name:"Lawless Broker", Cost:"2B", Color:["B"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"KLD", Number:"86", Image:"/Images/KLD/LawlessBroker.jpg", },
{Name:"Live Fast", Cost:"2B", Color:["B"], Rarity:"C", Type:["S"], Rating:"4", Sort:"1", Set:"KLD", Number:"87", Image:"/Images/KLD/LiveFast.jpg", },
{Name:"Lost Legacy", Cost:"1BB", Color:["B"], Rarity:"R", Type:["S"], Rating:"7", Sort:"1", Set:"KLD", Number:"88", Image:"/Images/KLD/LostLegacy.jpg", },
{Name:"Make Obsolete", Cost:"2B", Color:["B"], Rarity:"U", Type:["I"], Rating:"4", Sort:"1", Set:"KLD", Number:"89", Image:"/Images/KLD/MakeObsolete.jpg", },
{Name:"Marionette Master", Cost:"4BB", Color:["B"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"KLD", Number:"90", Image:"/Images/KLD/MarionetteMaster.jpg", },
{Name:"Maulfist Squad", Cost:"3B", Color:["B"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"KLD", Number:"91", Image:"/Images/KLD/MaulfistSquad.jpg", },
{Name:"Midnight Oil", Cost:"2BB", Color:["B"], Rarity:"R", Type:["E"], Rating:"8", Sort:"1", Set:"KLD", Number:"92", Image:"/Images/KLD/MidnightOil.jpg", },
{Name:"Mind Rot", Cost:"2B", Color:["B"], Rarity:"C", Type:["S"], Rating:"2", Sort:"1", Set:"KLD", Number:"93", Image:"/Images/KLD/MindRot.jpg", },
{Name:"Morbid Curiosity", Cost:"1BB", Color:["B"], Rarity:"U", Type:["S"], Rating:"4", Sort:"1", Set:"KLD", Number:"94", Image:"/Images/KLD/MorbidCuriosity.jpg", },
{Name:"Night Market Lookout", Cost:"0B", Color:["B"], Rarity:"C", Type:["C"], Rating:"2", Sort:"1", Set:"KLD", Number:"95", Image:"/Images/KLD/NightMarketLookout.jpg", },
{Name:"Noxious Gearhulk", Cost:"4BB", Color:["B"], Rarity:"M", Type:["C"], Rating:"9", Sort:"1", Set:"KLD", Number:"96", Image:"/Images/KLD/NoxiousGearhulk.jpg", },
{Name:"Ovalchase Daredevil", Cost:"3B", Color:["B"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"KLD", Number:"97", Image:"/Images/KLD/OvalchaseDaredevil.jpg", },
{Name:"Prakhata Club Security", Cost:"3B", Color:["B"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"KLD", Number:"98", Image:"/Images/KLD/PrakhataClubSecurity.jpg", },
{Name:"Rush of Vitality", Cost:"1B", Color:["B"], Rarity:"C", Type:["I"], Rating:"3", Sort:"1", Set:"KLD", Number:"99", Image:"/Images/KLD/RushofVitality.jpg", },
{Name:"Subtle Strike", Cost:"1B", Color:["B"], Rarity:"C", Type:["I"], Rating:"3", Sort:"1", Set:"KLD", Number:"100", Image:"/Images/KLD/SubtleStrike.jpg", },
{Name:"Syndicate Trafficker", Cost:"1B", Color:["B"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"KLD", Number:"101", Image:"/Images/KLD/SyndicateTrafficker.jpg", },
{Name:"Thriving Rats", Cost:"1B", Color:["B"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"KLD", Number:"102", Image:"/Images/KLD/ThrivingRats.jpg", },
{Name:"Tidy Conclusion", Cost:"3BB", Color:["B"], Rarity:"C", Type:["I"], Rating:"4", Sort:"1", Set:"KLD", Number:"103", Image:"/Images/KLD/TidyConclusion.jpg", },
{Name:"Underhanded Designs", Cost:"1B", Color:["B"], Rarity:"U", Type:["E"], Rating:"5", Sort:"1", Set:"KLD", Number:"104", Image:"/Images/KLD/UnderhandedDesigns.jpg", },
{Name:"Weaponcraft Enthusiast", Cost:"2B", Color:["B"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"KLD", Number:"105", Image:"/Images/KLD/WeaponcraftEnthusiast.jpg", },
{Name:"Aethertorch Renegade", Cost:"2R", Color:["R"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"KLD", Number:"106", Image:"/Images/KLD/AethertorchRenegade.jpg", },
{Name:"Brazen Scourge", Cost:"1RR", Color:["R"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"KLD", Number:"107", Image:"/Images/KLD/BrazenScourge.jpg", },
{Name:"Built to Smash", Cost:"0R", Color:["R"], Rarity:"C", Type:["I"], Rating:"2", Sort:"1", Set:"KLD", Number:"108", Image:"/Images/KLD/BuilttoSmash.jpg", },
{Name:"Cathartic Reunion", Cost:"1R", Color:["R"], Rarity:"C", Type:["S"], Rating:"3", Sort:"1", Set:"KLD", Number:"109", Image:"/Images/KLD/CatharticReunion.jpg", },
{Name:"Chandra, Torch of Defiance", Cost:"2RR", Color:["R"], Rarity:"M", Type:["P"], Rating:"9", Sort:"1", Set:"KLD", Number:"110", Image:"/Images/KLD/Chandra--TorchofDefiance.jpg", },
{Name:"Chandra's Pyrohelix", Cost:"1R", Color:["R"], Rarity:"C", Type:["I"], Rating:"4", Sort:"1", Set:"KLD", Number:"111", Image:"/Images/KLD/ChandrasPyrohelix.jpg", },
{Name:"Combustible Gearhulk", Cost:"4RR", Color:["R"], Rarity:"M", Type:["C"], Rating:"9", Sort:"1", Set:"KLD", Number:"112", Image:"/Images/KLD/CombustibleGearhulk.jpg", },
{Name:"Demolish", Cost:"3R", Color:["R"], Rarity:"C", Type:["S"], Rating:"2", Sort:"1", Set:"KLD", Number:"113", Image:"/Images/KLD/Demolish.jpg", },
{Name:"Fateful Showdown", Cost:"2RR", Color:["R"], Rarity:"R", Type:["I"], Rating:"8", Sort:"1", Set:"KLD", Number:"114", Image:"/Images/KLD/FatefulShowdown.jpg", },
{Name:"Furious Reprisal", Cost:"3R", Color:["R"], Rarity:"U", Type:["S"], Rating:"4", Sort:"1", Set:"KLD", Number:"115", Image:"/Images/KLD/FuriousReprisal.jpg", },
{Name:"Giant Spectacle", Cost:"1R", Color:["R"], Rarity:"C", Type:["E"], Rating:"2", Sort:"1", Set:"KLD", Number:"116", Image:"/Images/KLD/GiantSpectacle.jpg", },
{Name:"Harnessed Lightning", Cost:"1R", Color:["R"], Rarity:"U", Type:["I"], Rating:"5", Sort:"1", Set:"KLD", Number:"117", Image:"/Images/KLD/HarnessedLightning.jpg", },
{Name:"Hijack", Cost:"1RR", Color:["R"], Rarity:"C", Type:["S"], Rating:"2", Sort:"1", Set:"KLD", Number:"118", Image:"/Images/KLD/Hijack.jpg", },
{Name:"Incendiary Sabotage", Cost:"2RR", Color:["R"], Rarity:"U", Type:["I"], Rating:"4", Sort:"1", Set:"KLD", Number:"119", Image:"/Images/KLD/IncendiarySabotage.jpg", },
{Name:"Inventor's Apprentice", Cost:"0R", Color:["R"], Rarity:"U", Type:["C"], Rating:"3", Sort:"1", Set:"KLD", Number:"120", Image:"/Images/KLD/InventorsApprentice.jpg", },
{Name:"Lathnu Hellion", Cost:"2R", Color:["R"], Rarity:"R", Type:["C"], Rating:"6", Sort:"1", Set:"KLD", Number:"121", Image:"/Images/KLD/LathnuHellion.jpg", },
{Name:"Madcap Experiment", Cost:"3R", Color:["R"], Rarity:"R", Type:["S"], Rating:"6", Sort:"1", Set:"KLD", Number:"122", Image:"/Images/KLD/MadcapExperiment.jpg", },
{Name:"Maulfist Doorbuster", Cost:"3R", Color:["R"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"KLD", Number:"123", Image:"/Images/KLD/MaulfistDoorbuster.jpg", },
{Name:"Pia Nalaar", Cost:"2R", Color:["R"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"KLD", Number:"124", Image:"/Images/KLD/PiaNalaar.jpg", },
{Name:"Quicksmith Genius", Cost:"2R", Color:["R"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"KLD", Number:"125", Image:"/Images/KLD/QuicksmithGenius.jpg", },
{Name:"Reckless Fireweaver", Cost:"1R", Color:["R"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"KLD", Number:"126", Image:"/Images/KLD/RecklessFireweaver.jpg", },
{Name:"Renegade Tactics", Cost:"0R", Color:["R"], Rarity:"C", Type:["S"], Rating:"3", Sort:"1", Set:"KLD", Number:"127", Image:"/Images/KLD/RenegadeTactics.jpg", },
{Name:"Ruinous Gremlin", Cost:"0R", Color:["R"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"KLD", Number:"128", Image:"/Images/KLD/RuinousGremlin.jpg", },
{Name:"Salivating Gremlins", Cost:"2R", Color:["R"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"KLD", Number:"129", Image:"/Images/KLD/SalivatingGremlins.jpg", },
{Name:"Skyship Stalker", Cost:"2RR", Color:["R"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"KLD", Number:"130", Image:"/Images/KLD/SkyshipStalker.jpg", },
{Name:"Spark of Creativity", Cost:"0R", Color:["R"], Rarity:"U", Type:["S"], Rating:"5", Sort:"1", Set:"KLD", Number:"131", Image:"/Images/KLD/SparkofCreativity.jpg", },
{Name:"Speedway Fanatic", Cost:"1R", Color:["R"], Rarity:"U", Type:["C"], Rating:"3", Sort:"1", Set:"KLD", Number:"132", Image:"/Images/KLD/SpeedwayFanatic.jpg", },
{Name:"Spireside Infiltrator", Cost:"2R", Color:["R"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"KLD", Number:"133", Image:"/Images/KLD/SpiresideInfiltrator.jpg", },
{Name:"Spontaneous Artist", Cost:"3R", Color:["R"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"KLD", Number:"134", Image:"/Images/KLD/SpontaneousArtist.jpg", },
{Name:"Start Your Engines", Cost:"3R", Color:["R"], Rarity:"U", Type:["S"], Rating:"3", Sort:"1", Set:"KLD", Number:"135", Image:"/Images/KLD/StartYourEngines.jpg", },
{Name:"Territorial Gorger", Cost:"3R", Color:["R"], Rarity:"R", Type:["C"], Rating:"5", Sort:"1", Set:"KLD", Number:"136", Image:"/Images/KLD/TerritorialGorger.jpg", },
{Name:"Terror of the Fairgrounds", Cost:"3R", Color:["R"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"KLD", Number:"137", Image:"/Images/KLD/TerroroftheFairgrounds.jpg", },
{Name:"Thriving Grubs", Cost:"1R", Color:["R"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"KLD", Number:"138", Image:"/Images/KLD/ThrivingGrubs.jpg", },
{Name:"Wayward Giant", Cost:"4R", Color:["R"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"KLD", Number:"139", Image:"/Images/KLD/WaywardGiant.jpg", },
{Name:"Welding Sparks", Cost:"2R", Color:["R"], Rarity:"C", Type:["I"], Rating:"3", Sort:"1", Set:"KLD", Number:"140", Image:"/Images/KLD/WeldingSparks.jpg", },
{Name:"Appetite for the Unnatural", Cost:"2G", Color:["G"], Rarity:"C", Type:["I"], Rating:"3", Sort:"1", Set:"KLD", Number:"141", Image:"/Images/KLD/AppetitefortheUnnatural.jpg", },
{Name:"Arborback Stomper", Cost:"3GG", Color:["G"], Rarity:"U", Type:["C"], Rating:"3", Sort:"1", Set:"KLD", Number:"142", Image:"/Images/KLD/ArborbackStomper.jpg", },
{Name:"Architect of the Untamed", Cost:"2G", Color:["G"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"KLD", Number:"143", Image:"/Images/KLD/ArchitectoftheUntamed.jpg", },
{Name:"Armorcraft Judge", Cost:"3G", Color:["G"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"KLD", Number:"144", Image:"/Images/KLD/ArmorcraftJudge.jpg", },
{Name:"Attune with Aether", Cost:"0G", Color:["G"], Rarity:"C", Type:["S"], Rating:"4", Sort:"1", Set:"KLD", Number:"145", Image:"/Images/KLD/AttunewithAether.jpg", },
{Name:"Blossoming Defense", Cost:"0G", Color:["G"], Rarity:"U", Type:["I"], Rating:"4", Sort:"1", Set:"KLD", Number:"146", Image:"/Images/KLD/BlossomingDefense.jpg", },
{Name:"Bristling Hydra", Cost:"2GG", Color:["G"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"KLD", Number:"147", Image:"/Images/KLD/BristlingHydra.jpg", },
{Name:"Commencement of Festivities", Cost:"1G", Color:["G"], Rarity:"C", Type:["I"], Rating:"1", Sort:"1", Set:"KLD", Number:"148", Image:"/Images/KLD/CommencementofFestivities.jpg", },
{Name:"Cowl Prowler", Cost:"4GG", Color:["G"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"KLD", Number:"149", Image:"/Images/KLD/CowlProwler.jpg", },
{Name:"Creeping Mold", Cost:"2GG", Color:["G"], Rarity:"U", Type:["S"], Rating:"4", Sort:"1", Set:"KLD", Number:"150", Image:"/Images/KLD/CreepingMold.jpg", },
{Name:"Cultivator of Blades", Cost:"3GG", Color:["G"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"KLD", Number:"151", Image:"/Images/KLD/CultivatorofBlades.jpg", },
{Name:"Dubious Challenge", Cost:"3G", Color:["G"], Rarity:"R", Type:["S"], Rating:"6", Sort:"1", Set:"KLD", Number:"152", Image:"/Images/KLD/DubiousChallenge.jpg", },
{Name:"Durable Handicraft", Cost:"1G", Color:["G"], Rarity:"U", Type:["E"], Rating:"5", Sort:"1", Set:"KLD", Number:"153", Image:"/Images/KLD/DurableHandicraft.jpg", },
{Name:"Elegant Edgecrafters", Cost:"4GG", Color:["G"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"KLD", Number:"154", Image:"/Images/KLD/ElegantEdgecrafters.jpg", },
{Name:"Fairgrounds Trumpeter", Cost:"2G", Color:["G"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"KLD", Number:"155", Image:"/Images/KLD/FairgroundsTrumpeter.jpg", },
{Name:"Ghirapur Guide", Cost:"2G", Color:["G"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"KLD", Number:"156", Image:"/Images/KLD/GhirapurGuide.jpg", },
{Name:"Highspire Artisan", Cost:"2G", Color:["G"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"KLD", Number:"157", Image:"/Images/KLD/HighspireArtisan.jpg", },
{Name:"Hunt the Weak", Cost:"3G", Color:["G"], Rarity:"C", Type:["S"], Rating:"3", Sort:"1", Set:"KLD", Number:"158", Image:"/Images/KLD/HunttheWeak.jpg", },
{Name:"Kujar Seedsculptor", Cost:"1G", Color:["G"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"KLD", Number:"159", Image:"/Images/KLD/KujarSeedsculptor.jpg", },
{Name:"Larger Than Life", Cost:"1G", Color:["G"], Rarity:"C", Type:["S"], Rating:"2", Sort:"1", Set:"KLD", Number:"160", Image:"/Images/KLD/LargerThanLife.jpg", },
{Name:"Longtusk Cub", Cost:"1G", Color:["G"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"KLD", Number:"161", Image:"/Images/KLD/LongtuskCub.jpg", },
{Name:"Nature's Way", Cost:"1G", Color:["G"], Rarity:"U", Type:["S"], Rating:"5", Sort:"1", Set:"KLD", Number:"162", Image:"/Images/KLD/NaturesWay.jpg", },
{Name:"Nissa, Vital Force", Cost:"3GG", Color:["G"], Rarity:"M", Type:["P"], Rating:"9", Sort:"1", Set:"KLD", Number:"163", Image:"/Images/KLD/Nissa--VitalForce.jpg", },
{Name:"Ornamental Courage", Cost:"0G", Color:["G"], Rarity:"C", Type:["I"], Rating:"2", Sort:"1", Set:"KLD", Number:"164", Image:"/Images/KLD/OrnamentalCourage.jpg", },
{Name:"Oviya Pashiri, Sage Lifecrafter", Cost:"0G", Color:["G"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"KLD", Number:"165", Image:"/Images/KLD/OviyaPashiri--SageLifecrafter.jpg", },
{Name:"Peema Outrider", Cost:"2GG", Color:["G"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"KLD", Number:"166", Image:"/Images/KLD/PeemaOutrider.jpg", },
{Name:"Riparian Tiger", Cost:"3GG", Color:["G"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"KLD", Number:"167", Image:"/Images/KLD/RiparianTiger.jpg", },
{Name:"Sage of Shaila's Claim", Cost:"1G", Color:["G"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"KLD", Number:"168", Image:"/Images/KLD/SageofShailasClaim.jpg", },
{Name:"Servant of the Conduit", Cost:"1G", Color:["G"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"KLD", Number:"169", Image:"/Images/KLD/ServantoftheConduit.jpg", },
{Name:"Take Down", Cost:"0G", Color:["G"], Rarity:"C", Type:["S"], Rating:"2", Sort:"1", Set:"KLD", Number:"170", Image:"/Images/KLD/TakeDown.jpg", },
{Name:"Thriving Rhino", Cost:"2G", Color:["G"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"KLD", Number:"171", Image:"/Images/KLD/ThrivingRhino.jpg", },
{Name:"Verdurous Gearhulk", Cost:"3GG", Color:["G"], Rarity:"M", Type:["C"], Rating:"9", Sort:"1", Set:"KLD", Number:"172", Image:"/Images/KLD/VerdurousGearhulk.jpg", },
{Name:"Wild Wanderer", Cost:"3G", Color:["G"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"KLD", Number:"173", Image:"/Images/KLD/WildWanderer.jpg", },
{Name:"Wildest Dreams", Cost:"0G", Color:["G"], Rarity:"R", Type:["S"], Rating:"5", Sort:"1", Set:"KLD", Number:"174", Image:"/Images/KLD/WildestDreams.jpg", },
{Name:"Wily Bandar", Cost:"0G", Color:["G"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"KLD", Number:"175", Image:"/Images/KLD/WilyBandar.jpg", },
{Name:"Cloudblazer", Cost:"3WU", Color:["W","U"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"KLD", Number:"176", Image:"/Images/KLD/Cloudblazer.jpg", },
{Name:"Contraband Kingpin", Cost:"0UB", Color:["U","B"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"KLD", Number:"177", Image:"/Images/KLD/ContrabandKingpin.jpg", },
{Name:"Depala, Pilot Exemplar", Cost:"1RW", Color:["R","W"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"KLD", Number:"178", Image:"/Images/KLD/Depala--PilotExemplar.jpg", },
{Name:"Dovin Baan", Cost:"2WU", Color:["W","U"], Rarity:"M", Type:["P"], Rating:"9", Sort:"1", Set:"KLD", Number:"179", Image:"/Images/KLD/DovinBaan.jpg", },
{Name:"Empyreal Voyager", Cost:"1GU", Color:["U","G"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"KLD", Number:"180", Image:"/Images/KLD/EmpyrealVoyager.jpg", },
{Name:"Engineered Might", Cost:"3WG", Color:["G","W"], Rarity:"U", Type:["S"], Rating:"3", Sort:"1", Set:"KLD", Number:"181", Image:"/Images/KLD/EngineeredMight.jpg", },
{Name:"Hazardous Conditions", Cost:"2BG", Color:["G","B"], Rarity:"U", Type:["S"], Rating:"4", Sort:"1", Set:"KLD", Number:"182", Image:"/Images/KLD/HazardousConditions.jpg", },
{Name:"Kambal, Consul of Allocation", Cost:"1WB", Color:["W","B"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"KLD", Number:"183", Image:"/Images/KLD/Kambal--ConsulofAllocation.jpg", },
{Name:"Rashmi, Eternities Crafter", Cost:"2GU", Color:["G","U"], Rarity:"M", Type:["C"], Rating:"10", Sort:"1", Set:"KLD", Number:"184", Image:"/Images/KLD/Rashmi--EternitiesCrafter.jpg", },
{Name:"Restoration Gearsmith", Cost:"2WB", Color:["W","B"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"KLD", Number:"185", Image:"/Images/KLD/RestorationGearsmith.jpg", },
{Name:"Saheeli Rai", Cost:"1UR", Color:["U","R"], Rarity:"M", Type:["P"], Rating:"9", Sort:"1", Set:"KLD", Number:"186", Image:"/Images/KLD/SaheeliRai.jpg", },
{Name:"Unlicensed Disintegration", Cost:"1BR", Color:["B","R"], Rarity:"U", Type:["I"], Rating:"7", Sort:"1", Set:"KLD", Number:"187", Image:"/Images/KLD/UnlicensedDisintegration.jpg", },
{Name:"Veteran Motorist", Cost:"0RW", Color:["R","W"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"KLD", Number:"188", Image:"/Images/KLD/VeteranMotorist.jpg", },
{Name:"Voltaic Brawler", Cost:"0RG", Color:["R","G"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"KLD", Number:"189", Image:"/Images/KLD/VoltaicBrawler.jpg", },
{Name:"Whirler Virtuoso", Cost:"1UR", Color:["U","R"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"KLD", Number:"190", Image:"/Images/KLD/WhirlerVirtuoso.jpg", },
{Name:"Accomplished Automaton", Cost:"7", Color:["C"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"KLD", Number:"191", Image:"/Images/KLD/AccomplishedAutomaton.jpg", },
{Name:"Aetherflux Reservoir", Cost:"4", Color:["C"], Rarity:"R", Type:["A"], Rating:"4", Sort:"1", Set:"KLD", Number:"192", Image:"/Images/KLD/AetherfluxReservoir.jpg", },
{Name:"Aetherworks Marvel", Cost:"4", Color:["C"], Rarity:"M", Type:["A"], Rating:"9", Sort:"1", Set:"KLD", Number:"193", Image:"/Images/KLD/AetherworksMarvel.jpg", },
{Name:"Animation Module", Cost:"1", Color:["C"], Rarity:"R", Type:["A"], Rating:"7", Sort:"1", Set:"KLD", Number:"194", Image:"/Images/KLD/AnimationModule.jpg", },
{Name:"Aradara Express", Cost:"5", Color:["C"], Rarity:"C", Type:["A"], Rating:"3", Sort:"1", Set:"KLD", Number:"195", Image:"/Images/KLD/AradaraExpress.jpg", },
{Name:"Ballista Charger", Cost:"5", Color:["C"], Rarity:"U", Type:["A"], Rating:"4", Sort:"1", Set:"KLD", Number:"196", Image:"/Images/KLD/BallistaCharger.jpg", },
{Name:"Bastion Mastodon", Cost:"5", Color:["C"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"KLD", Number:"197", Image:"/Images/KLD/BastionMastodon.jpg", },
{Name:"Bomat Bazaar Barge", Cost:"4", Color:["R"], Rarity:"U", Type:["A"], Rating:"4", Sort:"1", Set:"KLD", Number:"198", Image:"/Images/KLD/BomatBazaarBarge.jpg", },
{Name:"Bomat Courier", Cost:"1", Color:["C"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"KLD", Number:"199", Image:"/Images/KLD/BomatCourier.jpg", },
{Name:"Chief of the Foundry", Cost:"3", Color:["C"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"KLD", Number:"200", Image:"/Images/KLD/ChiefoftheFoundry.jpg", },
{Name:"Cogworker's Puzzleknot", Cost:"2", Color:["W"], Rarity:"C", Type:["A"], Rating:"3", Sort:"1", Set:"KLD", Number:"201", Image:"/Images/KLD/CogworkersPuzzleknot.jpg", },
{Name:"Consulate Skygate", Cost:"2", Color:["C"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"KLD", Number:"202", Image:"/Images/KLD/ConsulateSkygate.jpg", },
{Name:"Cultivator's Caravan", Cost:"3", Color:["C"], Rarity:"R", Type:["A"], Rating:"7", Sort:"1", Set:"KLD", Number:"203", Image:"/Images/KLD/CultivatorsCaravan.jpg", },
{Name:"Deadlock Trap", Cost:"3", Color:["C"], Rarity:"R", Type:["A"], Rating:"7", Sort:"1", Set:"KLD", Number:"204", Image:"/Images/KLD/DeadlockTrap.jpg", },
{Name:"Decoction Module", Cost:"2", Color:["C"], Rarity:"U", Type:["A"], Rating:"4", Sort:"1", Set:"KLD", Number:"205", Image:"/Images/KLD/DecoctionModule.jpg", },
{Name:"Demolition Stomper", Cost:"6", Color:["C"], Rarity:"U", Type:["A"], Rating:"5", Sort:"1", Set:"KLD", Number:"206", Image:"/Images/KLD/DemolitionStomper.jpg", },
{Name:"Dukhara Peafowl", Cost:"4", Color:["U"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"KLD", Number:"207", Image:"/Images/KLD/DukharaPeafowl.jpg", },
{Name:"Dynavolt Tower", Cost:"3", Color:["C"], Rarity:"R", Type:["A"], Rating:"7", Sort:"1", Set:"KLD", Number:"208", Image:"/Images/KLD/DynavoltTower.jpg", },
{Name:"Eager Construct", Cost:"2", Color:["C"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"KLD", Number:"209", Image:"/Images/KLD/EagerConstruct.jpg", },
{Name:"Electrostatic Pummeler", Cost:"3", Color:["C"], Rarity:"R", Type:["C"], Rating:"6", Sort:"1", Set:"KLD", Number:"210", Image:"/Images/KLD/ElectrostaticPummeler.jpg", },
{Name:"Fabrication Module", Cost:"3", Color:["C"], Rarity:"U", Type:["A"], Rating:"5", Sort:"1", Set:"KLD", Number:"211", Image:"/Images/KLD/FabricationModule.jpg", },
{Name:"Filigree Familiar", Cost:"3", Color:["C"], Rarity:"U", Type:["C"], Rating:"3", Sort:"1", Set:"KLD", Number:"212", Image:"/Images/KLD/FiligreeFamiliar.jpg", },
{Name:"Fireforger's Puzzleknot", Cost:"2", Color:["R"], Rarity:"C", Type:["A"], Rating:"3", Sort:"1", Set:"KLD", Number:"213", Image:"/Images/KLD/FireforgersPuzzleknot.jpg", },
{Name:"Fleetwheel Cruiser", Cost:"4", Color:["C"], Rarity:"R", Type:["A"], Rating:"7", Sort:"1", Set:"KLD", Number:"214", Image:"/Images/KLD/FleetwheelCruiser.jpg", },
{Name:"Foundry Inspector", Cost:"3", Color:["C"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"KLD", Number:"215", Image:"/Images/KLD/FoundryInspector.jpg", },
{Name:"Ghirapur Orrery", Cost:"4", Color:["C"], Rarity:"R", Type:["A"], Rating:"5", Sort:"1", Set:"KLD", Number:"216", Image:"/Images/KLD/GhirapurOrrery.jpg", },
{Name:"Glassblower's Puzzleknot", Cost:"2", Color:["U"], Rarity:"C", Type:["A"], Rating:"3", Sort:"1", Set:"KLD", Number:"217", Image:"/Images/KLD/GlassblowersPuzzleknot.jpg", },
{Name:"Inventor's Goggles", Cost:"1", Color:["C"], Rarity:"C", Type:["A"], Rating:"3", Sort:"1", Set:"KLD", Number:"218", Image:"/Images/KLD/InventorsGoggles.jpg", },
{Name:"Iron League Steed", Cost:"4", Color:["C"], Rarity:"U", Type:["C"], Rating:"3", Sort:"1", Set:"KLD", Number:"219", Image:"/Images/KLD/IronLeagueSteed.jpg", },
{Name:"Key to the City", Cost:"2", Color:["C"], Rarity:"R", Type:["A"], Rating:"7", Sort:"1", Set:"KLD", Number:"220", Image:"/Images/KLD/KeytotheCity.jpg", },
{Name:"Metalspinner's Puzzleknot", Cost:"2", Color:["B"], Rarity:"C", Type:["A"], Rating:"4", Sort:"1", Set:"KLD", Number:"221", Image:"/Images/KLD/MetalspinnersPuzzleknot.jpg", },
{Name:"Metalwork Colossus", Cost:"11", Color:["C"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"KLD", Number:"222", Image:"/Images/KLD/MetalworkColossus.jpg", },
{Name:"Multiform Wonder", Cost:"5", Color:["C"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"KLD", Number:"223", Image:"/Images/KLD/MultiformWonder.jpg", },
{Name:"Narnam Cobra", Cost:"2", Color:["G"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"KLD", Number:"224", Image:"/Images/KLD/NarnamCobra.jpg", },
{Name:"Ovalchase Dragster", Cost:"4", Color:["C"], Rarity:"U", Type:["A"], Rating:"4", Sort:"1", Set:"KLD", Number:"225", Image:"/Images/KLD/OvalchaseDragster.jpg", },
{Name:"Panharmonicon", Cost:"4", Color:["C"], Rarity:"R", Type:["A"], Rating:"5", Sort:"1", Set:"KLD", Number:"226", Image:"/Images/KLD/Panharmonicon.jpg", },
{Name:"Perpetual Timepiece", Cost:"2", Color:["C"], Rarity:"U", Type:["A"], Rating:"2", Sort:"1", Set:"KLD", Number:"227", Image:"/Images/KLD/PerpetualTimepiece.jpg", },
{Name:"Prakhata Pillar-Bug", Cost:"3", Color:["B"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"KLD", Number:"228", Image:"/Images/KLD/PrakhataPillar-Bug.jpg", },
{Name:"Prophetic Prism", Cost:"2", Color:["C"], Rarity:"C", Type:["A"], Rating:"3", Sort:"1", Set:"KLD", Number:"229", Image:"/Images/KLD/PropheticPrism.jpg", },
{Name:"Renegade Freighter", Cost:"3", Color:["C"], Rarity:"C", Type:["A"], Rating:"3", Sort:"1", Set:"KLD", Number:"230", Image:"/Images/KLD/RenegadeFreighter.jpg", },
{Name:"Scrapheap Scrounger", Cost:"2", Color:["C"], Rarity:"R", Type:["C"], Rating:"6", Sort:"1", Set:"KLD", Number:"231", Image:"/Images/KLD/ScrapheapScrounger.jpg", },
{Name:"Self-Assembler", Cost:"5", Color:["C"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"KLD", Number:"232", Image:"/Images/KLD/Self-Assembler.jpg", },
{Name:"Sky Skiff", Cost:"2", Color:["C"], Rarity:"C", Type:["A"], Rating:"3", Sort:"1", Set:"KLD", Number:"233", Image:"/Images/KLD/SkySkiff.jpg", },
{Name:"Skysovereign, Consul Flagship", Cost:"5", Color:["C"], Rarity:"M", Type:["A"], Rating:"9", Sort:"1", Set:"KLD", Number:"234", Image:"/Images/KLD/Skysovereign--ConsulFlagship.jpg", },
{Name:"Smuggler's Copter", Cost:"2", Color:["C"], Rarity:"R", Type:["A"], Rating:"7", Sort:"1", Set:"KLD", Number:"235", Image:"/Images/KLD/SmugglersCopter.jpg", },
{Name:"Snare Thopter", Cost:"4", Color:["C"], Rarity:"U", Type:["C"], Rating:"3", Sort:"1", Set:"KLD", Number:"236", Image:"/Images/KLD/SnareThopter.jpg", },
{Name:"Torch Gauntlet", Cost:"2", Color:["C"], Rarity:"C", Type:["A"], Rating:"2", Sort:"1", Set:"KLD", Number:"237", Image:"/Images/KLD/TorchGauntlet.jpg", },
{Name:"Weldfast Monitor", Cost:"3", Color:["C"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"KLD", Number:"238", Image:"/Images/KLD/WeldfastMonitor.jpg", },
{Name:"Whirlermaker", Cost:"3", Color:["C"], Rarity:"U", Type:["A"], Rating:"4", Sort:"1", Set:"KLD", Number:"239", Image:"/Images/KLD/Whirlermaker.jpg", },
{Name:"Woodweaver's Puzzleknot", Cost:"2", Color:["G"], Rarity:"C", Type:["A"], Rating:"3", Sort:"1", Set:"KLD", Number:"240", Image:"/Images/KLD/WoodweaversPuzzleknot.jpg", },
{Name:"Workshop Assistant", Cost:"3", Color:["C"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"KLD", Number:"241", Image:"/Images/KLD/WorkshopAssistant.jpg", },
{Name:"Aether Hub", Cost:"0", Color:["C"], Rarity:"U", Type:["L"], Rating:"5", Sort:"1", Set:"KLD", Number:"242", Image:"/Images/KLD/AetherHub.jpg", },
{Name:"Blooming Marsh", Cost:"0", Color:["B","G"], Rarity:"R", Type:["L"], Rating:"6", Sort:"1", Set:"KLD", Number:"243", Image:"/Images/KLD/BloomingMarsh.jpg", },
{Name:"Botanical Sanctum", Cost:"0", Color:["U","G"], Rarity:"R", Type:["L"], Rating:"6", Sort:"1", Set:"KLD", Number:"244", Image:"/Images/KLD/BotanicalSanctum.jpg", },
{Name:"Concealed Courtyard", Cost:"0", Color:["W","B"], Rarity:"R", Type:["L"], Rating:"6", Sort:"1", Set:"KLD", Number:"245", Image:"/Images/KLD/ConcealedCourtyard.jpg", },
{Name:"Inspiring Vantage", Cost:"0", Color:["W","R"], Rarity:"R", Type:["L"], Rating:"6", Sort:"1", Set:"KLD", Number:"246", Image:"/Images/KLD/InspiringVantage.jpg", },
{Name:"Inventors' Fair", Cost:"0", Color:["C"], Rarity:"R", Type:["L"], Rating:"7", Sort:"1", Set:"KLD", Number:"247", Image:"/Images/KLD/InventorsFair.jpg", },
{Name:"Sequestered Stash", Cost:"0", Color:["C"], Rarity:"U", Type:["L"], Rating:"4", Sort:"1", Set:"KLD", Number:"248", Image:"/Images/KLD/SequesteredStash.jpg", },
{Name:"Spirebluff Canal", Cost:"0", Color:["U","R"], Rarity:"R", Type:["L"], Rating:"6", Sort:"1", Set:"KLD", Number:"249", Image:"/Images/KLD/SpirebluffCanal.jpg"}
];