var FRF = [
{Name:"Ugin, the Spirit Dragon", Cost:"8", Color:["C"], Rarity:"M", Type:["P"], Rating:"10", Sort:"1", Set:"FRF", Number:"1", Image:"/Images/FRF/Ugin--theSpiritDragon.jpg"},
{Name:"Abzan Advantage", Cost:"1W", Color:["W"], Rarity:"C", Type:["I"], Rating:"2", Sort:"1", Set:"FRF", Number:"2", Image:"/Images/FRF/AbzanAdvantage.jpg"},
{Name:"Abzan Runemark", Cost:"2W", Color:["W"], Rarity:"C", Type:["E"], Rating:"2", Sort:"1", Set:"FRF", Number:"3", Image:"/Images/FRF/AbzanRunemark.jpg"},
{Name:"Abzan Skycaptain", Cost:"3W", Color:["W"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"FRF", Number:"4", Image:"/Images/FRF/AbzanSkycaptain.jpg"},
{Name:"Arashin Cleric", Cost:"1W", Color:["W"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"FRF", Number:"5", Image:"/Images/FRF/ArashinCleric.jpg"},
{Name:"Aven Skirmisher", Cost:"0W", Color:["W"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"FRF", Number:"6", Image:"/Images/FRF/AvenSkirmisher.jpg"},
{Name:"Channel Harm", Cost:"5W", Color:["W"], Rarity:"U", Type:["I"], Rating:"5", Sort:"1", Set:"FRF", Number:"7", Image:"/Images/FRF/ChannelHarm.jpg"},
{Name:"Citadel Siege", Cost:"2WW", Color:["W"], Rarity:"R", Type:["E"], Rating:"8", Sort:"1", Set:"FRF", Number:"8", Image:"/Images/FRF/CitadelSiege.jpg"},
{Name:"Daghatar the Adamant", Cost:"3W", Color:["W"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"FRF", Number:"9", Image:"/Images/FRF/DaghatartheAdamant.jpg"},
{Name:"Dragon Bell Monk", Cost:"2W", Color:["W"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"FRF", Number:"10", Image:"/Images/FRF/DragonBellMonk.jpg"},
{Name:"Dragonscale General", Cost:"3W", Color:["W"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"FRF", Number:"11", Image:"/Images/FRF/DragonscaleGeneral.jpg"},
{Name:"Elite Scaleguard", Cost:"4W", Color:["W"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"FRF", Number:"12", Image:"/Images/FRF/EliteScaleguard.jpg"},
{Name:"Great-Horn Krushok", Cost:"4W", Color:["W"], Rarity:"C", Type:["C"], Rating:"5", Sort:"1", Set:"FRF", Number:"13", Image:"/Images/FRF/Great-HornKrushok.jpg"},
{Name:"Honor's Reward", Cost:"2W", Color:["W"], Rarity:"U", Type:["I"], Rating:"4", Sort:"1", Set:"FRF", Number:"14", Image:"/Images/FRF/HonorsReward.jpg"},
{Name:"Jeskai Barricade", Cost:"1W", Color:["W"], Rarity:"U", Type:["C"], Rating:"7", Sort:"1", Set:"FRF", Number:"15", Image:"/Images/FRF/JeskaiBarricade.jpg"},
{Name:"Lightform", Cost:"1WW", Color:["W"], Rarity:"U", Type:["E"], Rating:"7", Sort:"1", Set:"FRF", Number:"16", Image:"/Images/FRF/Lightform.jpg"},
{Name:"Lotus-Eye Mystics", Cost:"3W", Color:["W"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"FRF", Number:"17", Image:"/Images/FRF/Lotus-EyeMystics.jpg"},
{Name:"Mardu Woe-Reaper", Cost:"0W", Color:["W"], Rarity:"U", Type:["C"], Rating:"7", Sort:"1", Set:"FRF", Number:"18", Image:"/Images/FRF/MarduWoe-Reaper.jpg"},
{Name:"Mastery of the Unseen", Cost:"1W", Color:["W"], Rarity:"R", Type:["E"], Rating:"8", Sort:"1", Set:"FRF", Number:"19", Image:"/Images/FRF/MasteryoftheUnseen.jpg"},
{Name:"Monastery Mentor", Cost:"2W", Color:["W"], Rarity:"M", Type:["C"], Rating:"9", Sort:"1", Set:"FRF", Number:"20", Image:"/Images/FRF/MonasteryMentor.jpg"},
{Name:"Pressure Point", Cost:"1W", Color:["W"], Rarity:"C", Type:["I"], Rating:"5", Sort:"1", Set:"FRF", Number:"21", Image:"/Images/FRF/PressurePoint.jpg"},
{Name:"Rally the Ancestors", Cost:"0WW", Color:["W"], Rarity:"R", Type:["I"], Rating:"6", Sort:"1", Set:"FRF", Number:"22", Image:"/Images/FRF/RallytheAncestors.jpg"},
{Name:"Sage's Reverie", Cost:"3W", Color:["W"], Rarity:"U", Type:["E"], Rating:"6", Sort:"1", Set:"FRF", Number:"23", Image:"/Images/FRF/SagesReverie.jpg"},
{Name:"Sandblast", Cost:"2W", Color:["W"], Rarity:"C", Type:["I"], Rating:"4", Sort:"1", Set:"FRF", Number:"24", Image:"/Images/FRF/Sandblast.jpg"},
{Name:"Sandsteppe Outcast", Cost:"2W", Color:["W"], Rarity:"C", Type:["C"], Rating:"6", Sort:"1", Set:"FRF", Number:"25", Image:"/Images/FRF/SandsteppeOutcast.jpg"},
{Name:"Soul Summons", Cost:"1W", Color:["W"], Rarity:"C", Type:["S"], Rating:"5", Sort:"1", Set:"FRF", Number:"26", Image:"/Images/FRF/SoulSummons.jpg"},
{Name:"Soulfire Grand Master", Cost:"1W", Color:["W"], Rarity:"M", Type:["C"], Rating:"9", Sort:"1", Set:"FRF", Number:"27", Image:"/Images/FRF/SoulfireGrandMaster.jpg"},
{Name:"Valorous Stance", Cost:"1W", Color:["W"], Rarity:"U", Type:["I"], Rating:"8", Sort:"1", Set:"FRF", Number:"28", Image:"/Images/FRF/ValorousStance.jpg"},
{Name:"Wandering Champion", Cost:"1W", Color:["W"], Rarity:"U", Type:["C"], Rating:"7", Sort:"1", Set:"FRF", Number:"29", Image:"/Images/FRF/WanderingChampion.jpg"},
{Name:"Wardscale Dragon", Cost:"4WW", Color:["W"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"FRF", Number:"30", Image:"/Images/FRF/WardscaleDragon.jpg"},
{Name:"Aven Surveyor", Cost:"3UU", Color:["U"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"FRF", Number:"31", Image:"/Images/FRF/AvenSurveyor.jpg"},
{Name:"Cloudform", Cost:"1UU", Color:["U"], Rarity:"U", Type:["E"], Rating:"8", Sort:"1", Set:"FRF", Number:"32", Image:"/Images/FRF/Cloudform.jpg"},
{Name:"Enhanced Awareness", Cost:"4U", Color:["U"], Rarity:"C", Type:["I"], Rating:"5", Sort:"1", Set:"FRF", Number:"33", Image:"/Images/FRF/EnhancedAwareness.jpg"},
{Name:"Fascination", Cost:"0UU", Color:["U"], Rarity:"U", Type:["S"], Rating:"2", Sort:"1", Set:"FRF", Number:"34", Image:"/Images/FRF/Fascination.jpg"},
{Name:"Frost Walker", Cost:"1U", Color:["U"], Rarity:"U", Type:["C"], Rating:"7", Sort:"1", Set:"FRF", Number:"35", Image:"/Images/FRF/FrostWalker.jpg"},
{Name:"Jeskai Infiltrator", Cost:"2U", Color:["U"], Rarity:"R", Type:["C"], Rating:"9", Sort:"1", Set:"FRF", Number:"36", Image:"/Images/FRF/JeskaiInfiltrator.jpg"},
{Name:"Jeskai Runemark", Cost:"2U", Color:["U"], Rarity:"C", Type:["E"], Rating:"4", Sort:"1", Set:"FRF", Number:"37", Image:"/Images/FRF/JeskaiRunemark.jpg"},
{Name:"Jeskai Sage", Cost:"1U", Color:["U"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"FRF", Number:"38", Image:"/Images/FRF/JeskaiSage.jpg"},
{Name:"Lotus Path Djinn", Cost:"3U", Color:["U"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"FRF", Number:"39", Image:"/Images/FRF/LotusPathDjinn.jpg"},
{Name:"Marang River Prowler", Cost:"2U", Color:["U"], Rarity:"U", Type:["C"], Rating:"8", Sort:"1", Set:"FRF", Number:"40", Image:"/Images/FRF/MarangRiverProwler.jpg"},
{Name:"Mindscour Dragon", Cost:"4UU", Color:["U"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"FRF", Number:"41", Image:"/Images/FRF/MindscourDragon.jpg"},
{Name:"Mistfire Adept", Cost:"3U", Color:["U"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"FRF", Number:"42", Image:"/Images/FRF/MistfireAdept.jpg"},
{Name:"Monastery Siege", Cost:"2U", Color:["U"], Rarity:"R", Type:["E"], Rating:"7", Sort:"1", Set:"FRF", Number:"43", Image:"/Images/FRF/MonasterySiege.jpg"},
{Name:"Neutralizing Blast", Cost:"1U", Color:["U"], Rarity:"U", Type:["I"], Rating:"5", Sort:"1", Set:"FRF", Number:"44", Image:"/Images/FRF/NeutralizingBlast.jpg"},
{Name:"Rakshasa's Disdain", Cost:"2U", Color:["U"], Rarity:"C", Type:["I"], Rating:"3", Sort:"1", Set:"FRF", Number:"45", Image:"/Images/FRF/RakshasasDisdain.jpg"},
{Name:"Reality Shift", Cost:"1U", Color:["U"], Rarity:"U", Type:["I"], Rating:"7", Sort:"1", Set:"FRF", Number:"46", Image:"/Images/FRF/RealityShift.jpg"},
{Name:"Refocus", Cost:"1U", Color:["U"], Rarity:"C", Type:["I"], Rating:"3", Sort:"1", Set:"FRF", Number:"47", Image:"/Images/FRF/Refocus.jpg"},
{Name:"Renowned Weaponsmith", Cost:"1U", Color:["U"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"FRF", Number:"48", Image:"/Images/FRF/RenownedWeaponsmith.jpg"},
{Name:"Rite of Undoing", Cost:"4U", Color:["U"], Rarity:"U", Type:["I"], Rating:"3", Sort:"1", Set:"FRF", Number:"49", Image:"/Images/FRF/RiteofUndoing.jpg"},
{Name:"Sage-Eye Avengers", Cost:"4UU", Color:["U"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"FRF", Number:"50", Image:"/Images/FRF/Sage-EyeAvengers.jpg"},
{Name:"Shifting Loyalties", Cost:"5U", Color:["U"], Rarity:"U", Type:["S"], Rating:"7", Sort:"1", Set:"FRF", Number:"51", Image:"/Images/FRF/ShiftingLoyalties.jpg"},
{Name:"Shu Yun, the Silent Tempest", Cost:"2U", Color:["U"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"FRF", Number:"52", Image:"/Images/FRF/ShuYun--theSilentTempest.jpg"},
{Name:"Sultai Skullkeeper", Cost:"1U", Color:["U"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"FRF", Number:"53", Image:"/Images/FRF/SultaiSkullkeeper.jpg"},
{Name:"Supplant Form", Cost:"4UU", Color:["U"], Rarity:"R", Type:["I"], Rating:"7", Sort:"1", Set:"FRF", Number:"54", Image:"/Images/FRF/SupplantForm.jpg"},
{Name:"Temporal Trespass", Cost:"8UUU", Color:["U"], Rarity:"M", Type:["S"], Rating:"9", Sort:"1", Set:"FRF", Number:"55", Image:"/Images/FRF/TemporalTrespass.jpg"},
{Name:"Torrent Elemental", Cost:"3UU", Color:["U"], Rarity:"M", Type:["C"], Rating:"9", Sort:"1", Set:"FRF", Number:"56", Image:"/Images/FRF/TorrentElemental.jpg"},
{Name:"Whisk Away", Cost:"2U", Color:["U"], Rarity:"C", Type:["I"], Rating:"6", Sort:"1", Set:"FRF", Number:"57", Image:"/Images/FRF/WhiskAway.jpg"},
{Name:"Will of the Naga", Cost:"4UU", Color:["U"], Rarity:"C", Type:["I"], Rating:"3", Sort:"1", Set:"FRF", Number:"58", Image:"/Images/FRF/WilloftheNaga.jpg"},
{Name:"Write into Being", Cost:"2U", Color:["U"], Rarity:"C", Type:["S"], Rating:"6", Sort:"1", Set:"FRF", Number:"59", Image:"/Images/FRF/WriteintoBeing.jpg"},
{Name:"Alesha's Vanguard", Cost:"3B", Color:["B"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"FRF", Number:"60", Image:"/Images/FRF/AleshasVanguard.jpg"},
{Name:"Ancestral Vengeance", Cost:"0BB", Color:["B"], Rarity:"C", Type:["E"], Rating:"4", Sort:"1", Set:"FRF", Number:"61", Image:"/Images/FRF/AncestralVengeance.jpg"},
{Name:"Archfiend of Depravity", Cost:"3BB", Color:["B"], Rarity:"R", Type:["C"], Rating:"9", Sort:"1", Set:"FRF", Number:"62", Image:"/Images/FRF/ArchfiendofDepravity.jpg"},
{Name:"Battle Brawler", Cost:"1B", Color:["B"], Rarity:"U", Type:["C"], Rating:"8", Sort:"1", Set:"FRF", Number:"63", Image:"/Images/FRF/BattleBrawler.jpg"},
{Name:"Brutal Hordechief", Cost:"3B", Color:["B"], Rarity:"M", Type:["C"], Rating:"8", Sort:"1", Set:"FRF", Number:"64", Image:"/Images/FRF/BrutalHordechief.jpg"},
{Name:"Crux of Fate", Cost:"3BB", Color:["B"], Rarity:"R", Type:["S"], Rating:"8", Sort:"1", Set:"FRF", Number:"65", Image:"/Images/FRF/CruxofFate.jpg"},
{Name:"Dark Deal", Cost:"2B", Color:["B"], Rarity:"U", Type:["S"], Rating:"2", Sort:"1", Set:"FRF", Number:"66", Image:"/Images/FRF/DarkDeal.jpg"},
{Name:"Diplomacy of the Wastes", Cost:"2B", Color:["B"], Rarity:"U", Type:["S"], Rating:"6", Sort:"1", Set:"FRF", Number:"67", Image:"/Images/FRF/DiplomacyoftheWastes.jpg"},
{Name:"Douse in Gloom", Cost:"2B", Color:["B"], Rarity:"C", Type:["I"], Rating:"4", Sort:"1", Set:"FRF", Number:"68", Image:"/Images/FRF/DouseinGloom.jpg"},
{Name:"Fearsome Awakening", Cost:"4B", Color:["B"], Rarity:"U", Type:["S"], Rating:"3", Sort:"1", Set:"FRF", Number:"69", Image:"/Images/FRF/FearsomeAwakening.jpg"},
{Name:"Ghastly Conscription", Cost:"5BB", Color:["B"], Rarity:"M", Type:["S"], Rating:"6", Sort:"1", Set:"FRF", Number:"70", Image:"/Images/FRF/GhastlyConscription.jpg"},
{Name:"Grave Strength", Cost:"1B", Color:["B"], Rarity:"U", Type:["S"], Rating:"4", Sort:"1", Set:"FRF", Number:"71", Image:"/Images/FRF/GraveStrength.jpg"},
{Name:"Gurmag Angler", Cost:"6B", Color:["B"], Rarity:"C", Type:["C"], Rating:"6", Sort:"1", Set:"FRF", Number:"72", Image:"/Images/FRF/GurmagAngler.jpg"},
{Name:"Hooded Assassin", Cost:"3B", Color:["B"], Rarity:"C", Type:["C"], Rating:"6", Sort:"1", Set:"FRF", Number:"73", Image:"/Images/FRF/HoodedAssassin.jpg"},
{Name:"Mardu Shadowspear", Cost:"0B", Color:["B"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"FRF", Number:"74", Image:"/Images/FRF/MarduShadowspear.jpg"},
{Name:"Mardu Strike Leader", Cost:"2B", Color:["B"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"FRF", Number:"75", Image:"/Images/FRF/MarduStrikeLeader.jpg"},
{Name:"Merciless Executioner", Cost:"2B", Color:["B"], Rarity:"U", Type:["C"], Rating:"7", Sort:"1", Set:"FRF", Number:"76", Image:"/Images/FRF/MercilessExecutioner.jpg"},
{Name:"Noxious Dragon", Cost:"4BB", Color:["B"], Rarity:"U", Type:["C"], Rating:"7", Sort:"1", Set:"FRF", Number:"77", Image:"/Images/FRF/NoxiousDragon.jpg"},
{Name:"Orc Sureshot", Cost:"3B", Color:["B"], Rarity:"U", Type:["C"], Rating:"7", Sort:"1", Set:"FRF", Number:"78", Image:"/Images/FRF/OrcSureshot.jpg"},
{Name:"Palace Siege", Cost:"3BB", Color:["B"], Rarity:"R", Type:["E"], Rating:"7", Sort:"1", Set:"FRF", Number:"79", Image:"/Images/FRF/PalaceSiege.jpg"},
{Name:"Qarsi High Priest", Cost:"0B", Color:["B"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"FRF", Number:"80", Image:"/Images/FRF/QarsiHighPriest.jpg"},
{Name:"Reach of Shadows", Cost:"4B", Color:["B"], Rarity:"C", Type:["I"], Rating:"6", Sort:"1", Set:"FRF", Number:"81", Image:"/Images/FRF/ReachofShadows.jpg"},
{Name:"Sibsig Host", Cost:"4B", Color:["B"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"FRF", Number:"82", Image:"/Images/FRF/SibsigHost.jpg"},
{Name:"Sibsig Muckdraggers", Cost:"8B", Color:["B"], Rarity:"U", Type:["C"], Rating:"7", Sort:"1", Set:"FRF", Number:"83", Image:"/Images/FRF/SibsigMuckdraggers.jpg"},
{Name:"Soulflayer", Cost:"4BB", Color:["B"], Rarity:"R", Type:["C"], Rating:"9", Sort:"1", Set:"FRF", Number:"84", Image:"/Images/FRF/Soulflayer.jpg"},
{Name:"Sultai Emissary", Cost:"1B", Color:["B"], Rarity:"C", Type:["C"], Rating:"5", Sort:"1", Set:"FRF", Number:"85", Image:"/Images/FRF/SultaiEmissary.jpg"},
{Name:"Sultai Runemark", Cost:"2B", Color:["B"], Rarity:"C", Type:["E"], Rating:"3", Sort:"1", Set:"FRF", Number:"86", Image:"/Images/FRF/SultaiRunemark.jpg"},
{Name:"Tasigur, the Golden Fang", Cost:"5B", Color:["B"], Rarity:"R", Type:["C"], Rating:"9", Sort:"1", Set:"FRF", Number:"87", Image:"/Images/FRF/Tasigur--theGoldenFang.jpg"},
{Name:"Tasigur's Cruelty", Cost:"5B", Color:["B"], Rarity:"C", Type:["S"], Rating:"4", Sort:"1", Set:"FRF", Number:"88", Image:"/Images/FRF/TasigursCruelty.jpg"},
{Name:"Typhoid Rats", Cost:"0B", Color:["B"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"FRF", Number:"89", Image:"/Images/FRF/TyphoidRats.jpg"},
{Name:"Alesha, Who Smiles at Death", Cost:"2R", Color:["R"], Rarity:"R", Type:["C"], Rating:"9", Sort:"1", Set:"FRF", Number:"90", Image:"/Images/FRF/Alesha--WhoSmilesatDeath.jpg"},
{Name:"Arcbond", Cost:"2R", Color:["R"], Rarity:"R", Type:["I"], Rating:"5", Sort:"1", Set:"FRF", Number:"91", Image:"/Images/FRF/Arcbond.jpg"},
{Name:"Bathe in Dragonfire", Cost:"2R", Color:["R"], Rarity:"C", Type:["S"], Rating:"6", Sort:"1", Set:"FRF", Number:"92", Image:"/Images/FRF/BatheinDragonfire.jpg"},
{Name:"Bloodfire Enforcers", Cost:"3R", Color:["R"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"FRF", Number:"93", Image:"/Images/FRF/BloodfireEnforcers.jpg"},
{Name:"Break Through the Line", Cost:"1R", Color:["R"], Rarity:"U", Type:["E"], Rating:"7", Sort:"1", Set:"FRF", Number:"94", Image:"/Images/FRF/BreakThroughtheLine.jpg"},
{Name:"Collateral Damage", Cost:"0R", Color:["R"], Rarity:"C", Type:["I"], Rating:"2", Sort:"1", Set:"FRF", Number:"95", Image:"/Images/FRF/CollateralDamage.jpg"},
{Name:"Defiant Ogre", Cost:"5R", Color:["R"], Rarity:"C", Type:["C"], Rating:"2", Sort:"1", Set:"FRF", Number:"96", Image:"/Images/FRF/DefiantOgre.jpg"},
{Name:"Dragonrage", Cost:"2R", Color:["R"], Rarity:"U", Type:["I"], Rating:"3", Sort:"1", Set:"FRF", Number:"97", Image:"/Images/FRF/Dragonrage.jpg"},
{Name:"Fierce Invocation", Cost:"4R", Color:["R"], Rarity:"C", Type:["S"], Rating:"3", Sort:"1", Set:"FRF", Number:"98", Image:"/Images/FRF/FierceInvocation.jpg"},
{Name:"Flamerush Rider", Cost:"4R", Color:["R"], Rarity:"R", Type:["C"], Rating:"9", Sort:"1", Set:"FRF", Number:"99", Image:"/Images/FRF/FlamerushRider.jpg"},
{Name:"Flamewake Phoenix", Cost:"1RR", Color:["R"], Rarity:"R", Type:["C"], Rating:"9", Sort:"1", Set:"FRF", Number:"100", Image:"/Images/FRF/FlamewakePhoenix.jpg"},
{Name:"Friendly Fire", Cost:"3R", Color:["R"], Rarity:"U", Type:["I"], Rating:"1", Sort:"1", Set:"FRF", Number:"101", Image:"/Images/FRF/FriendlyFire.jpg"},
{Name:"Goblin Heelcutter", Cost:"3R", Color:["R"], Rarity:"C", Type:["C"], Rating:"6", Sort:"1", Set:"FRF", Number:"102", Image:"/Images/FRF/GoblinHeelcutter.jpg"},
{Name:"Gore Swine", Cost:"2R", Color:["R"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"FRF", Number:"103", Image:"/Images/FRF/GoreSwine.jpg"},
{Name:"Humble Defector", Cost:"1R", Color:["R"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"FRF", Number:"104", Image:"/Images/FRF/HumbleDefector.jpg"},
{Name:"Hungering Yeti", Cost:"4R", Color:["R"], Rarity:"U", Type:["C"], Rating:"7", Sort:"1", Set:"FRF", Number:"105", Image:"/Images/FRF/HungeringYeti.jpg"},
{Name:"Lightning Shrieker", Cost:"4R", Color:["R"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"FRF", Number:"106", Image:"/Images/FRF/LightningShrieker.jpg"},
{Name:"Mardu Runemark", Cost:"2R", Color:["R"], Rarity:"C", Type:["E"], Rating:"3", Sort:"1", Set:"FRF", Number:"107", Image:"/Images/FRF/MarduRunemark.jpg"},
{Name:"Mardu Scout", Cost:"0RR", Color:["R"], Rarity:"C", Type:["C"], Rating:"6", Sort:"1", Set:"FRF", Number:"108", Image:"/Images/FRF/MarduScout.jpg"},
{Name:"Mob Rule", Cost:"4RR", Color:["R"], Rarity:"R", Type:["S"], Rating:"9", Sort:"1", Set:"FRF", Number:"109", Image:"/Images/FRF/MobRule.jpg"},
{Name:"Outpost Siege", Cost:"3R", Color:["R"], Rarity:"R", Type:["E"], Rating:"9", Sort:"1", Set:"FRF", Number:"110", Image:"/Images/FRF/OutpostSiege.jpg"},
{Name:"Pyrotechnics", Cost:"4R", Color:["R"], Rarity:"U", Type:["S"], Rating:"7", Sort:"1", Set:"FRF", Number:"111", Image:"/Images/FRF/Pyrotechnics.jpg"},
{Name:"Rageform", Cost:"2RR", Color:["R"], Rarity:"U", Type:["E"], Rating:"7", Sort:"1", Set:"FRF", Number:"112", Image:"/Images/FRF/Rageform.jpg"},
{Name:"Shaman of the Great Hunt", Cost:"3R", Color:["R"], Rarity:"M", Type:["C"], Rating:"8", Sort:"1", Set:"FRF", Number:"113", Image:"/Images/FRF/ShamanoftheGreatHunt.jpg"},
{Name:"Shockmaw Dragon", Cost:"4RR", Color:["R"], Rarity:"U", Type:["C"], Rating:"7", Sort:"1", Set:"FRF", Number:"114", Image:"/Images/FRF/ShockmawDragon.jpg"},
{Name:"Smoldering Efreet", Cost:"1R", Color:["R"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"FRF", Number:"115", Image:"/Images/FRF/SmolderingEfreet.jpg"},
{Name:"Temur Battle Rage", Cost:"1R", Color:["R"], Rarity:"C", Type:["I"], Rating:"5", Sort:"1", Set:"FRF", Number:"116", Image:"/Images/FRF/TemurBattleRage.jpg"},
{Name:"Vaultbreaker", Cost:"3R", Color:["R"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"FRF", Number:"117", Image:"/Images/FRF/Vaultbreaker.jpg"},
{Name:"Wild Slash", Cost:"0R", Color:["R"], Rarity:"U", Type:["I"], Rating:"6", Sort:"1", Set:"FRF", Number:"118", Image:"/Images/FRF/WildSlash.jpg"},
{Name:"Abzan Beastmaster", Cost:"2G", Color:["G"], Rarity:"U", Type:["C"], Rating:"8", Sort:"1", Set:"FRF", Number:"119", Image:"/Images/FRF/AbzanBeastmaster.jpg"},
{Name:"Abzan Kin-Guard", Cost:"3G", Color:["G"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"FRF", Number:"120", Image:"/Images/FRF/AbzanKin-Guard.jpg"},
{Name:"Ainok Guide", Cost:"1G", Color:["G"], Rarity:"C", Type:["C"], Rating:"5", Sort:"1", Set:"FRF", Number:"121", Image:"/Images/FRF/AinokGuide.jpg"},
{Name:"Ambush Krotiq", Cost:"5G", Color:["G"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"FRF", Number:"122", Image:"/Images/FRF/AmbushKrotiq.jpg"},
{Name:"Arashin War Beast", Cost:"5GG", Color:["G"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"FRF", Number:"123", Image:"/Images/FRF/ArashinWarBeast.jpg"},
{Name:"Archers of Qarsi", Cost:"3G", Color:["G"], Rarity:"C", Type:["C"], Rating:"2", Sort:"1", Set:"FRF", Number:"124", Image:"/Images/FRF/ArchersofQarsi.jpg"},
{Name:"Battlefront Krushok", Cost:"4G", Color:["G"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"FRF", Number:"125", Image:"/Images/FRF/BattlefrontKrushok.jpg"},
{Name:"Cached Defenses", Cost:"2G", Color:["G"], Rarity:"U", Type:["S"], Rating:"3", Sort:"1", Set:"FRF", Number:"126", Image:"/Images/FRF/CachedDefenses.jpg"},
{Name:"Destructor Dragon", Cost:"4GG", Color:["G"], Rarity:"U", Type:["C"], Rating:"7", Sort:"1", Set:"FRF", Number:"127", Image:"/Images/FRF/DestructorDragon.jpg"},
{Name:"Feral Krushok", Cost:"4G", Color:["G"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"FRF", Number:"128", Image:"/Images/FRF/FeralKrushok.jpg"},
{Name:"Formless Nurturing", Cost:"3G", Color:["G"], Rarity:"C", Type:["S"], Rating:"5", Sort:"1", Set:"FRF", Number:"129", Image:"/Images/FRF/FormlessNurturing.jpg"},
{Name:"Frontier Mastodon", Cost:"2G", Color:["G"], Rarity:"C", Type:["C"], Rating:"6", Sort:"1", Set:"FRF", Number:"130", Image:"/Images/FRF/FrontierMastodon.jpg"},
{Name:"Frontier Siege", Cost:"3G", Color:["G"], Rarity:"R", Type:["E"], Rating:"8", Sort:"1", Set:"FRF", Number:"131", Image:"/Images/FRF/FrontierSiege.jpg"},
{Name:"Fruit of the First Tree", Cost:"3G", Color:["G"], Rarity:"U", Type:["E"], Rating:"5", Sort:"1", Set:"FRF", Number:"132", Image:"/Images/FRF/FruitoftheFirstTree.jpg"},
{Name:"Hunt the Weak", Cost:"3G", Color:["G"], Rarity:"C", Type:["S"], Rating:"5", Sort:"1", Set:"FRF", Number:"133", Image:"/Images/FRF/HunttheWeak.jpg"},
{Name:"Map the Wastes", Cost:"2G", Color:["G"], Rarity:"C", Type:["S"], Rating:"5", Sort:"1", Set:"FRF", Number:"134", Image:"/Images/FRF/MaptheWastes.jpg"},
{Name:"Return to the Earth", Cost:"3G", Color:["G"], Rarity:"C", Type:["I"], Rating:"3", Sort:"1", Set:"FRF", Number:"135", Image:"/Images/FRF/ReturntotheEarth.jpg"},
{Name:"Ruthless Instincts", Cost:"2G", Color:["G"], Rarity:"U", Type:["I"], Rating:"5", Sort:"1", Set:"FRF", Number:"136", Image:"/Images/FRF/RuthlessInstincts.jpg"},
{Name:"Sandsteppe Mastodon", Cost:"5GG", Color:["G"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"FRF", Number:"137", Image:"/Images/FRF/SandsteppeMastodon.jpg"},
{Name:"Shamanic Revelation", Cost:"3GG", Color:["G"], Rarity:"R", Type:["S"], Rating:"7", Sort:"1", Set:"FRF", Number:"138", Image:"/Images/FRF/ShamanicRevelation.jpg"},
{Name:"Sudden Reclamation", Cost:"3G", Color:["G"], Rarity:"U", Type:["I"], Rating:"6", Sort:"1", Set:"FRF", Number:"139", Image:"/Images/FRF/SuddenReclamation.jpg"},
{Name:"Temur Runemark", Cost:"2G", Color:["G"], Rarity:"C", Type:["E"], Rating:"2", Sort:"1", Set:"FRF", Number:"140", Image:"/Images/FRF/TemurRunemark.jpg"},
{Name:"Temur Sabertooth", Cost:"2GG", Color:["G"], Rarity:"U", Type:["C"], Rating:"7", Sort:"1", Set:"FRF", Number:"141", Image:"/Images/FRF/TemurSabertooth.jpg"},
{Name:"Temur War Shaman", Cost:"4GG", Color:["G"], Rarity:"R", Type:["C"], Rating:"9", Sort:"1", Set:"FRF", Number:"142", Image:"/Images/FRF/TemurWarShaman.jpg"},
{Name:"Warden of the First Tree", Cost:"0G", Color:["G"], Rarity:"M", Type:["C"], Rating:"9", Sort:"1", Set:"FRF", Number:"143", Image:"/Images/FRF/WardenoftheFirstTree.jpg"},
{Name:"Whisperer of the Wilds", Cost:"1G", Color:["G"], Rarity:"C", Type:["C"], Rating:"6", Sort:"1", Set:"FRF", Number:"144", Image:"/Images/FRF/WhispereroftheWilds.jpg"},
{Name:"Whisperwood Elemental", Cost:"3GG", Color:["G"], Rarity:"M", Type:["C"], Rating:"10", Sort:"1", Set:"FRF", Number:"145", Image:"/Images/FRF/WhisperwoodElemental.jpg"},
{Name:"Wildcall", Cost:"0GG", Color:["G"], Rarity:"R", Type:["S"], Rating:"8", Sort:"1", Set:"FRF", Number:"146", Image:"/Images/FRF/Wildcall.jpg"},
{Name:"Winds of Qal Sisma", Cost:"1G", Color:["G"], Rarity:"U", Type:["I"], Rating:"4", Sort:"1", Set:"FRF", Number:"147", Image:"/Images/FRF/WindsofQalSisma.jpg"},
{Name:"Yasova Dragonclaw", Cost:"2G", Color:["G"], Rarity:"R", Type:["C"], Rating:"9", Sort:"1", Set:"FRF", Number:"148", Image:"/Images/FRF/YasovaDragonclaw.jpg"},
{Name:"Atarka, World Render", Cost:"5RG", Color:["R","G"], Rarity:"R", Type:["C"], Rating:"9", Sort:"1", Set:"FRF", Number:"149", Image:"/Images/FRF/Atarka--WorldRender.jpg"},
{Name:"Cunning Strike", Cost:"3UR", Color:["U","R"], Rarity:"C", Type:["I"], Rating:"4", Sort:"1", Set:"FRF", Number:"150", Image:"/Images/FRF/CunningStrike.jpg"},
{Name:"Dromoka, the Eternal", Cost:"3WG", Color:["W","G"], Rarity:"R", Type:["C"], Rating:"9", Sort:"1", Set:"FRF", Number:"151", Image:"/Images/FRF/Dromoka--theEternal.jpg"},
{Name:"Ethereal Ambush", Cost:"3GU", Color:["G","U"], Rarity:"C", Type:["I"], Rating:"4", Sort:"1", Set:"FRF", Number:"152", Image:"/Images/FRF/EtherealAmbush.jpg"},
{Name:"Grim Contest", Cost:"1BG", Color:["B","G"], Rarity:"C", Type:["I"], Rating:"5", Sort:"1", Set:"FRF", Number:"153", Image:"/Images/FRF/GrimContest.jpg"},
{Name:"Harsh Sustenance", Cost:"1WB", Color:["W","B"], Rarity:"C", Type:["I"], Rating:"4", Sort:"1", Set:"FRF", Number:"154", Image:"/Images/FRF/HarshSustenance.jpg"},
{Name:"Kolaghan, the Storm's Fury", Cost:"3BR", Color:["B","R"], Rarity:"R", Type:["C"], Rating:"9", Sort:"1", Set:"FRF", Number:"155", Image:"/Images/FRF/Kolaghan--theStormsFury.jpg"},
{Name:"Ojutai, Soul of Winter", Cost:"5WU", Color:["W","U"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"FRF", Number:"156", Image:"/Images/FRF/Ojutai--SoulofWinter.jpg"},
{Name:"Silumgar, the Drifting Death", Cost:"4UB", Color:["U","B"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"FRF", Number:"157", Image:"/Images/FRF/Silumgar--theDriftingDeath.jpg"},
{Name:"War Flare", Cost:"2RW", Color:["R","W"], Rarity:"C", Type:["I"], Rating:"3", Sort:"1", Set:"FRF", Number:"158", Image:"/Images/FRF/WarFlare.jpg"},
{Name:"Goblin Boom Keg", Cost:"4", Color:["C"], Rarity:"U", Type:["A"], Rating:"4", Sort:"1", Set:"FRF", Number:"159", Image:"/Images/FRF/GoblinBoomKeg.jpg"},
{Name:"Hero's Blade", Cost:"2", Color:["C"], Rarity:"U", Type:["A"], Rating:"3", Sort:"1", Set:"FRF", Number:"160", Image:"/Images/FRF/HerosBlade.jpg"},
{Name:"Hewed Stone Retainers", Cost:"3", Color:["C"], Rarity:"U", Type:["A"], Rating:"3", Sort:"1", Set:"FRF", Number:"161", Image:"/Images/FRF/HewedStoneRetainers.jpg"},
{Name:"Pilgrim of the Fires", Cost:"7", Color:["C"], Rarity:"U", Type:["A"], Rating:"4", Sort:"1", Set:"FRF", Number:"162", Image:"/Images/FRF/PilgrimoftheFires.jpg"},
{Name:"Scroll of the Masters", Cost:"2", Color:["C"], Rarity:"R", Type:["A"], Rating:"5", Sort:"1", Set:"FRF", Number:"163", Image:"/Images/FRF/ScrolloftheMasters.jpg"},
{Name:"Ugin's Construct", Cost:"4", Color:["C"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"FRF", Number:"163", Image:"/Images/FRF/UginsConstruct.jpg"},
{Name:"Crucible of the Spirit Dragon", Cost:"0", Color:["C"], Rarity:"R", Type:["L"], Rating:"5", Sort:"1", Set:"FRF", Number:"164", Image:"/Images/FRF/CrucibleoftheSpiritDragon.jpg"},
];