var SOI = [
{Name:"Always Watching", Cost:"1WW", Color:["W"], Rarity:"R", Type:["E"], Rating:"6", Sort:"1", Set:"SOI", Number:"1", Image:"/Images/SOI/AlwaysWatching.jpg", },
{Name:"Angel of Deliverance", Cost:"6WW", Color:["W"], Rarity:"R", Type:["C"], Rating:"6", Sort:"1", Set:"SOI", Number:"2", Image:"/Images/SOI/AngelofDeliverance.jpg", },
{Name:"Angelic Purge", Cost:"2W", Color:["W"], Rarity:"C", Type:["S"], Rating:"5", Sort:"1", Set:"SOI", Number:"3", Image:"/Images/SOI/AngelicPurge.jpg", },
{Name:"Apothecary Geist", Cost:"3W", Color:["W"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"SOI", Number:"4", Image:"/Images/SOI/ApothecaryGeist.jpg", },
{Name:"Archangel Avacyn", Cost:"3WW", Color:["W"], Rarity:"M", Type:["C"], Rating:"9", Sort:"1", Set:"SOI", Number:"5", Image:"/Images/SOI/ArchangelAvacyn.jpg", ReverseImage:"/Images/SOI/Avacyn--ThePurifier.jpg"},
{Name:"Avacynian Missionaries", Cost:"3W", Color:["W"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"SOI", Number:"6", Image:"/Images/SOI/AvacynianMissionaries.jpg", ReverseImage:"/Images/SOI/LunarchInquisitors.jpg"},
{Name:"Bound by Moonsilver", Cost:"2W", Color:["W"], Rarity:"U", Type:["E"], Rating:"5", Sort:"1", Set:"SOI", Number:"7", Image:"/Images/SOI/BoundbyMoonsilver.jpg", },
{Name:"Bygone Bishop", Cost:"2W", Color:["W"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"SOI", Number:"8", Image:"/Images/SOI/BygoneBishop.jpg", },
{Name:"Cathar's Companion", Cost:"2W", Color:["W"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"SOI", Number:"9", Image:"/Images/SOI/CatharsCompanion.jpg", },
{Name:"Chaplain's Blessing", Cost:"0W", Color:["W"], Rarity:"C", Type:["S"], Rating:"1", Sort:"1", Set:"SOI", Number:"10", Image:"/Images/SOI/ChaplainsBlessing.jpg", },
{Name:"Dauntless Cathar", Cost:"2W", Color:["W"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"SOI", Number:"11", Image:"/Images/SOI/DauntlessCathar.jpg", },
{Name:"Declaration in Stone", Cost:"1W", Color:["W"], Rarity:"R", Type:["S"], Rating:"8", Sort:"1", Set:"SOI", Number:"12", Image:"/Images/SOI/DeclarationinStone.jpg", },
{Name:"Descend upon the Sinful", Cost:"4WW", Color:["W"], Rarity:"M", Type:["S"], Rating:"9", Sort:"1", Set:"SOI", Number:"13", Image:"/Images/SOI/DescendupontheSinful.jpg", },
{Name:"Devilthorn Fox", Cost:"1W", Color:["W"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"SOI", Number:"14", Image:"/Images/SOI/DevilthornFox.jpg", },
{Name:"Drogskol Cavalry", Cost:"5WW", Color:["W"], Rarity:"R", Type:["C"], Rating:"6", Sort:"1", Set:"SOI", Number:"15", Image:"/Images/SOI/DrogskolCavalry.jpg", },
{Name:"Eerie Interlude", Cost:"2W", Color:["W"], Rarity:"R", Type:["I"], Rating:"6", Sort:"1", Set:"SOI", Number:"16", Image:"/Images/SOI/EerieInterlude.jpg", },
{Name:"Emissary of the Sleepless", Cost:"4W", Color:["W"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"SOI", Number:"17", Image:"/Images/SOI/EmissaryoftheSleepless.jpg", },
{Name:"Ethereal Guidance", Cost:"2W", Color:["W"], Rarity:"C", Type:["S"], Rating:"2", Sort:"1", Set:"SOI", Number:"18", Image:"/Images/SOI/EtherealGuidance.jpg", },
{Name:"Expose Evil", Cost:"1W", Color:["W"], Rarity:"C", Type:["I"], Rating:"3", Sort:"1", Set:"SOI", Number:"19", Image:"/Images/SOI/ExposeEvil.jpg", },
{Name:"Gryff's Boon", Cost:"0W", Color:["W"], Rarity:"U", Type:["E"], Rating:"3", Sort:"1", Set:"SOI", Number:"20", Image:"/Images/SOI/GryffsBoon.jpg"},
{Name:"Hanweir Militia Captain", Cost:"1W", Color:["W"], Rarity:"R", Type:["R"], Rating:"7", Sort:"1", Set:"SOI", Number:"21", Image:"/Images/SOI/HanweirMilitiaCaptain.jpg", ReverseImage:"/Images/SOI/WestvaleCultLeader.jpg"},
{Name:"Hope Against Hope", Cost:"2W", Color:["W"], Rarity:"U", Type:["E"], Rating:"3", Sort:"1", Set:"SOI", Number:"22", Image:"/Images/SOI/HopeAgainstHope.jpg", },
{Name:"Humble the Brute", Cost:"4W", Color:["W"], Rarity:"U", Type:["I"], Rating:"5", Sort:"1", Set:"SOI", Number:"23", Image:"/Images/SOI/HumbletheBrute.jpg", },
{Name:"Inquisitor's Ox", Cost:"3W", Color:["W"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"SOI", Number:"24", Image:"/Images/SOI/InquisitorsOx.jpg", },
{Name:"Inspiring Captain", Cost:"3W", Color:["W"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"SOI", Number:"25", Image:"/Images/SOI/InspiringCaptain.jpg", },
{Name:"Militant Inquisitor", Cost:"2W", Color:["W"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"SOI", Number:"26", Image:"/Images/SOI/MilitantInquisitor.jpg", },
{Name:"Moorland Drifter", Cost:"1W", Color:["W"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"SOI", Number:"27", Image:"/Images/SOI/MoorlandDrifter.jpg", },
{Name:"Nahiri's Machinations", Cost:"1W", Color:["W"], Rarity:"U", Type:["E"], Rating:"6", Sort:"1", Set:"SOI", Number:"28", Image:"/Images/SOI/NahirisMachinations.jpg", },
{Name:"Nearheath Chaplain", Cost:"3W", Color:["W"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"SOI", Number:"29", Image:"/Images/SOI/NearheathChaplain.jpg", },
{Name:"Not Forgotten", Cost:"1W", Color:["W"], Rarity:"U", Type:["S"], Rating:"5", Sort:"1", Set:"SOI", Number:"30", Image:"/Images/SOI/NotForgotten.jpg", },
{Name:"Odric, Lunarch Marshal", Cost:"3W", Color:["W"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"SOI", Number:"31", Image:"/Images/SOI/Odric--LunarchMarshal.jpg", },
{Name:"Open the Armory", Cost:"1W", Color:["W"], Rarity:"U", Type:["S"], Rating:"4", Sort:"1", Set:"SOI", Number:"32", Image:"/Images/SOI/OpentheArmory.jpg", },
{Name:"Paranoid Parish-Blade", Cost:"2W", Color:["W"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"SOI", Number:"33", Image:"/Images/SOI/ParanoidParish-Blade.jpg", },
{Name:"Pious Evangel", Cost:"2W", Color:["W"], Rarity:"U", Type:["C"], Rating:"3", Sort:"1", Set:"SOI", Number:"34", Image:"/Images/SOI/PiousEvangel.jpg", ReverseImage:"/Images/SOI/WaywardDisciple.jpg"},
{Name:"Puncturing Light", Cost:"1W", Color:["W"], Rarity:"C", Type:["I"], Rating:"3", Sort:"1", Set:"SOI", Number:"35", Image:"/Images/SOI/PuncturingLight.jpg", },
{Name:"Reaper of Flight Moonsilver", Cost:"3WW", Color:["W"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"SOI", Number:"36", Image:"/Images/SOI/ReaperofFlightMoonsilver.jpg", },
{Name:"Silverstrike", Cost:"3W", Color:["W"], Rarity:"U", Type:["I"], Rating:"7", Sort:"1", Set:"SOI", Number:"37", Image:"/Images/SOI/Silverstrike.jpg", },
{Name:"Spectral Shepherd", Cost:"2W", Color:["W"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"SOI", Number:"38", Image:"/Images/SOI/SpectralShepherd.jpg", },
{Name:"Stern Constable", Cost:"0W", Color:["W"], Rarity:"C", Type:["C"], Rating:"2", Sort:"1", Set:"SOI", Number:"39", Image:"/Images/SOI/SternConstable.jpg", },
{Name:"Strength of Arms", Cost:"0W", Color:["W"], Rarity:"C", Type:["I"], Rating:"2", Sort:"1", Set:"SOI", Number:"40", Image:"/Images/SOI/StrengthofArms.jpg", },
{Name:"Survive the Night", Cost:"2W", Color:["W"], Rarity:"C", Type:["I"], Rating:"3", Sort:"1", Set:"SOI", Number:"41", Image:"/Images/SOI/SurvivetheNight.jpg", },
{Name:"Tenacity", Cost:"3W", Color:["W"], Rarity:"U", Type:["I"], Rating:"4", Sort:"1", Set:"SOI", Number:"42", Image:"/Images/SOI/Tenacity.jpg", },
{Name:"Thalia's Lieutenant", Cost:"1W", Color:["W"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"SOI", Number:"43", Image:"/Images/SOI/ThaliasLieutenant.jpg", },
{Name:"Thraben Inspector", Cost:"0W", Color:["W"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"SOI", Number:"44", Image:"/Images/SOI/ThrabenInspector.jpg", },
{Name:"Topplegeist", Cost:"0W", Color:["W"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"SOI", Number:"45", Image:"/Images/SOI/Topplegeist.jpg", },
{Name:"Town Gossipmonger", Cost:"0W", Color:["W"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"SOI", Number:"46", Image:"/Images/SOI/TownGossipmonger.jpg", ReverseImage:"/Images/SOI/IncitedRabble.jpg"},
{Name:"Unruly Mob", Cost:"1W", Color:["W"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"SOI", Number:"47", Image:"/Images/SOI/UnrulyMob.jpg", },
{Name:"Vessel of Ephemera", Cost:"1W", Color:["W"], Rarity:"C", Type:["E"], Rating:"3", Sort:"1", Set:"SOI", Number:"48", Image:"/Images/SOI/VesselofEphemera.jpg", },
{Name:"Aberrant Researcher", Cost:"3U", Color:["U"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"SOI", Number:"49", Image:"/Images/SOI/AberrantResearcher.jpg", ReverseImage:"/Images/SOI/PerfectedForm.jpg"},
{Name:"Broken Concentration", Cost:"1UU", Color:["U"], Rarity:"U", Type:["I"], Rating:"4", Sort:"1", Set:"SOI", Number:"50", Image:"/Images/SOI/BrokenConcentration.jpg", },
{Name:"Catalog", Cost:"2U", Color:["U"], Rarity:"C", Type:["I"], Rating:"3", Sort:"1", Set:"SOI", Number:"51", Image:"/Images/SOI/Catalog.jpg", },
{Name:"Compelling Deterrence", Cost:"1U", Color:["U"], Rarity:"U", Type:["I"], Rating:"5", Sort:"1", Set:"SOI", Number:"52", Image:"/Images/SOI/CompellingDeterrence.jpg", },
{Name:"Confirm Suspicions", Cost:"3UU", Color:["U"], Rarity:"R", Type:["I"], Rating:"6", Sort:"1", Set:"SOI", Number:"53", Image:"/Images/SOI/ConfirmSuspicions.jpg", },
{Name:"Daring Sleuth", Cost:"1U", Color:["U"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"SOI", Number:"54", Image:"/Images/SOI/DaringSleuth.jpg", ReverseImage:"/Images/SOI/BearerOfOverwhelmingTruths.jpg"},
{Name:"Deny Existence", Cost:"2U", Color:["U"], Rarity:"C", Type:["I"], Rating:"4", Sort:"1", Set:"SOI", Number:"55", Image:"/Images/SOI/DenyExistence.jpg", },
{Name:"Drownyard Explorers", Cost:"3U", Color:["U"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"SOI", Number:"56", Image:"/Images/SOI/DrownyardExplorers.jpg", },
{Name:"Drunau Corpse Trawler", Cost:"3U", Color:["U"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"SOI", Number:"57", Image:"/Images/SOI/DrunauCorpseTrawler.jpg", },
{Name:"Engulf the Shore", Cost:"3U", Color:["U"], Rarity:"R", Type:["I"], Rating:"8", Sort:"1", Set:"SOI", Number:"58", Image:"/Images/SOI/EngulftheShore.jpg", },
{Name:"Epiphany at the Drownyard", Cost:"0U", Color:["U"], Rarity:"R", Type:["I"], Rating:"8", Sort:"1", Set:"SOI", Number:"59", Image:"/Images/SOI/EpiphanyattheDrownyard.jpg", },
{Name:"Erdwal Illuminator", Cost:"1U", Color:["U"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"SOI", Number:"60", Image:"/Images/SOI/ErdwalIlluminator.jpg", },
{Name:"Essence Flux", Cost:"0U", Color:["U"], Rarity:"U", Type:["I"], Rating:"4", Sort:"1", Set:"SOI", Number:"61", Image:"/Images/SOI/EssenceFlux.jpg", },
{Name:"Fleeting Memories", Cost:"2U", Color:["U"], Rarity:"U", Type:["E"], Rating:"3", Sort:"1", Set:"SOI", Number:"62", Image:"/Images/SOI/FleetingMemories.jpg", },
{Name:"Forgotten Creation", Cost:"3U", Color:["U"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"SOI", Number:"63", Image:"/Images/SOI/ForgottenCreation.jpg", },
{Name:"Furtive Homunculus", Cost:"1U", Color:["U"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"SOI", Number:"64", Image:"/Images/SOI/FurtiveHomunculus.jpg", },
{Name:"Geralf's Masterpiece", Cost:"3UU", Color:["U"], Rarity:"M", Type:["C"], Rating:"9", Sort:"1", Set:"SOI", Number:"65", Image:"/Images/SOI/GeralfsMasterpiece.jpg", },
{Name:"Ghostly Wings", Cost:"1U", Color:["U"], Rarity:"C", Type:["E"], Rating:"2", Sort:"1", Set:"SOI", Number:"66", Image:"/Images/SOI/GhostlyWings.jpg", },
{Name:"Gone Missing", Cost:"4U", Color:["U"], Rarity:"C", Type:["S"], Rating:"3", Sort:"1", Set:"SOI", Number:"67", Image:"/Images/SOI/GoneMissing.jpg", },
{Name:"Invasive Surgery", Cost:"0U", Color:["U"], Rarity:"U", Type:["I"], Rating:"3", Sort:"1", Set:"SOI", Number:"68", Image:"/Images/SOI/InvasiveSurgery.jpg", },
{Name:"Jace, Unraveler of Secrets", Cost:"3UU", Color:["U"], Rarity:"M", Type:["P"], Rating:"9", Sort:"1", Set:"SOI", Number:"69", Image:"/Images/SOI/Jace--UnravelerofSecrets.jpg", },
{Name:"Jace's Scrutiny", Cost:"1U", Color:["U"], Rarity:"C", Type:["I"], Rating:"3", Sort:"1", Set:"SOI", Number:"70", Image:"/Images/SOI/JacesScrutiny.jpg", },
{Name:"Just the Wind", Cost:"1U", Color:["U"], Rarity:"C", Type:["I"], Rating:"2", Sort:"1", Set:"SOI", Number:"71", Image:"/Images/SOI/JusttheWind.jpg", },
{Name:"Lamplighter of Selhoff", Cost:"4U", Color:["U"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"SOI", Number:"72", Image:"/Images/SOI/LamplighterofSelhoff.jpg", },
{Name:"Manic Scribe", Cost:"1U", Color:["U"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"SOI", Number:"73", Image:"/Images/SOI/ManicScribe.jpg", },
{Name:"Nagging Thoughts", Cost:"1U", Color:["U"], Rarity:"C", Type:["S"], Rating:"3", Sort:"1", Set:"SOI", Number:"74", Image:"/Images/SOI/NaggingThoughts.jpg", },
{Name:"Nephalia Moondrakes", Cost:"5UU", Color:["U"], Rarity:"R", Type:["C"], Rating:"6", Sort:"1", Set:"SOI", Number:"75", Image:"/Images/SOI/NephaliaMoondrakes.jpg", },
{Name:"Niblis of Dusk", Cost:"2U", Color:["U"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"SOI", Number:"76", Image:"/Images/SOI/NiblisofDusk.jpg", },
{Name:"Ongoing Investigation", Cost:"1U", Color:["U"], Rarity:"U", Type:["E"], Rating:"5", Sort:"1", Set:"SOI", Number:"77", Image:"/Images/SOI/OngoingInvestigation.jpg", },
{Name:"Pieces of the Puzzle", Cost:"2U", Color:["U"], Rarity:"C", Type:["S"], Rating:"2", Sort:"1", Set:"SOI", Number:"78", Image:"/Images/SOI/PiecesofthePuzzle.jpg", },
{Name:"Pore Over the Pages", Cost:"3UU", Color:["U"], Rarity:"U", Type:["S"], Rating:"5", Sort:"1", Set:"SOI", Number:"79", Image:"/Images/SOI/PoreOverthePages.jpg", },
{Name:"Press for Answers", Cost:"1U", Color:["U"], Rarity:"C", Type:["S"], Rating:"3", Sort:"1", Set:"SOI", Number:"80", Image:"/Images/SOI/PressforAnswers.jpg", },
{Name:"Rattlechains", Cost:"1U", Color:["U"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"SOI", Number:"81", Image:"/Images/SOI/Rattlechains.jpg", },
{Name:"Reckless Scholar", Cost:"2U", Color:["U"], Rarity:"U", Type:["C"], Rating:"3", Sort:"1", Set:"SOI", Number:"82", Image:"/Images/SOI/RecklessScholar.jpg", },
{Name:"Rise from the Tides", Cost:"5U", Color:["U"], Rarity:"U", Type:["S"], Rating:"3", Sort:"1", Set:"SOI", Number:"83", Image:"/Images/SOI/RisefromtheTides.jpg", },
{Name:"Seagraf Skaab", Cost:"1U", Color:["U"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"SOI", Number:"84", Image:"/Images/SOI/SeagrafSkaab.jpg", },
{Name:"Silburlind Snapper", Cost:"5U", Color:["U"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"SOI", Number:"85", Image:"/Images/SOI/SilburlindSnapper.jpg"},
{Name:"Silent Observer", Cost:"3U", Color:["U"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"SOI", Number:"86", Image:"/Images/SOI/SilentObserver.jpg", },
{Name:"Sleep Paralysis", Cost:"3U", Color:["U"], Rarity:"C", Type:["E"], Rating:"4", Sort:"1", Set:"SOI", Number:"87", Image:"/Images/SOI/SleepParalysis.jpg", },
{Name:"Startled Awake", Cost:"2UU", Color:["U"], Rarity:"M", Type:["S"], Rating:"9", Sort:"1", Set:"SOI", Number:"88", Image:"/Images/SOI/StartledAwake.jpg", ReverseImage:"/Images/SOI/PersistentNightmare.jpg"},
{Name:"Stitched Mangler", Cost:"2U", Color:["U"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"SOI", Number:"89", Image:"/Images/SOI/StitchedMangler.jpg", },
{Name:"Stitchwing Skaab", Cost:"3U", Color:["U"], Rarity:"U", Type:["U"], Rating:"6", Sort:"1", Set:"SOI", Number:"90", Image:"/Images/SOI/StitchwingSkaab.jpg", },
{Name:"Stormrider Spirit", Cost:"4U", Color:["U"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"SOI", Number:"91", Image:"/Images/SOI/StormriderSpirit.jpg", },
{Name:"Thing in the Ice", Cost:"1U", Color:["U"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"SOI", Number:"92", Image:"/Images/SOI/ThingintheIce.jpg", ReverseImage:"/Images/SOI/AwokenHorror.jpg"},
{Name:"Trail of Evidence", Cost:"2U", Color:["U"], Rarity:"U", Type:["E"], Rating:"4", Sort:"1", Set:"SOI", Number:"93", Image:"/Images/SOI/TrailofEvidence.jpg", },
{Name:"Uninvited Geist", Cost:"2U", Color:["U"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"SOI", Number:"94", Image:"/Images/SOI/UninvitedGeist.jpg", ReverseImage:"/Images/SOI/UnimpededTrespasser.jpg"},
{Name:"Vessel of Paramnesia", Cost:"1U", Color:["U"], Rarity:"C", Type:["E"], Rating:"2", Sort:"1", Set:"SOI", Number:"95", Image:"/Images/SOI/VesselofParamnesia.jpg", },
{Name:"Welcome to the Fold", Cost:"2UU", Color:["U"], Rarity:"R", Type:["U"], Rating:"5", Sort:"1", Set:"SOI", Number:"96", Image:"/Images/SOI/WelcometotheFold.jpg", },
{Name:"Accursed Witch", Cost:"3B", Color:["B"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"SOI", Number:"97", Image:"/Images/SOI/AccursedWitch.jpg", ReverseImage:"/Images/SOI/InfectiousCurse.jpg"},
{Name:"Alms of the Vein", Cost:"2B", Color:["B"], Rarity:"C", Type:["S"], Rating:"1", Sort:"1", Set:"SOI", Number:"98", Image:"/Images/SOI/AlmsoftheVein.jpg", },
{Name:"Asylum Visitor", Cost:"1B", Color:["B"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"SOI", Number:"99", Image:"/Images/SOI/AsylumVisitor.jpg", },
{Name:"Behind the Scenes", Cost:"2B", Color:["B"], Rarity:"U", Type:["E"], Rating:"4", Sort:"1", Set:"SOI", Number:"100", Image:"/Images/SOI/BehindtheScenes.jpg", },
{Name:"Behold the Beyond", Cost:"5BB", Color:["B"], Rarity:"M", Type:["S"], Rating:"6", Sort:"1", Set:"SOI", Number:"101", Image:"/Images/SOI/BeholdtheBeyond.jpg", },
{Name:"Biting Rain", Cost:"2BB", Color:["B"], Rarity:"U", Type:["S"], Rating:"5", Sort:"1", Set:"SOI", Number:"102", Image:"/Images/SOI/BitingRain.jpg", },
{Name:"Call the Bloodline", Cost:"1B", Color:["B"], Rarity:"U", Type:["E"], Rating:"3", Sort:"1", Set:"SOI", Number:"103", Image:"/Images/SOI/CalltheBloodline.jpg", },
{Name:"Creeping Dread", Cost:"3B", Color:["B"], Rarity:"U", Type:["E"], Rating:"3", Sort:"1", Set:"SOI", Number:"104", Image:"/Images/SOI/CreepingDread.jpg", },
{Name:"Crow of Dark Tidings", Cost:"2B", Color:["B"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"SOI", Number:"105", Image:"/Images/SOI/CrowofDarkTidings.jpg", },
{Name:"Dead Weight", Cost:"0B", Color:["B"], Rarity:"C", Type:["E"], Rating:"4", Sort:"1", Set:"SOI", Number:"106", Image:"/Images/SOI/DeadWeight.jpg", },
{Name:"Diregraf Colossus", Cost:"2B", Color:["B"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"SOI", Number:"107", Image:"/Images/SOI/DiregrafColossus.jpg", },
{Name:"Elusive Tormentor", Cost:"2BB", Color:["B"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"SOI", Number:"108", Image:"/Images/SOI/ElusiveTormentor.jpg", ReverseImage:"/Images/SOI/InsidiousMist.jpg"},
{Name:"Ever After", Cost:"4BB", Color:["B"], Rarity:"R", Type:["S"], Rating:"6", Sort:"1", Set:"SOI", Number:"109", Image:"/Images/SOI/EverAfter.jpg", },
{Name:"Farbog Revenant", Cost:"2B", Color:["B"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"SOI", Number:"110", Image:"/Images/SOI/FarbogRevenant.jpg", },
{Name:"From Under the Floorboards", Cost:"3BB", Color:["B"], Rarity:"R", Type:["S"], Rating:"6", Sort:"1", Set:"SOI", Number:"111", Image:"/Images/SOI/FromUndertheFloorboards.jpg", },
{Name:"Ghoulcaller's Accomplice", Cost:"1B", Color:["B"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"SOI", Number:"112", Image:"/Images/SOI/GhoulcallersAccomplice.jpg", },
{Name:"Ghoulsteed", Cost:"4B", Color:["B"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"SOI", Number:"113", Image:"/Images/SOI/Ghoulsteed.jpg", },
{Name:"Gisa's Bidding", Cost:"2BB", Color:["B"], Rarity:"U", Type:["S"], Rating:"5", Sort:"1", Set:"SOI", Number:"114", Image:"/Images/SOI/GisasBidding.jpg", },
{Name:"Grotesque Mutation", Cost:"1B", Color:["B"], Rarity:"C", Type:["I"], Rating:"2", Sort:"1", Set:"SOI", Number:"115", Image:"/Images/SOI/GrotesqueMutation.jpg", },
{Name:"Heir of Falkenrath", Cost:"1B", Color:["B"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"SOI", Number:"116", Image:"/Images/SOI/HeirofFalkenrath.jpg", ReverseImage:"/Images/SOI/HeirToTheNight.jpg"},
{Name:"Hound of the Farbogs", Cost:"4B", Color:["B"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"SOI", Number:"117", Image:"/Images/SOI/HoundoftheFarbogs.jpg", },
{Name:"Indulgent Aristocrat", Cost:"0B", Color:["B"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"SOI", Number:"118", Image:"/Images/SOI/IndulgentAristocrat.jpg", },
{Name:"Kindly Stranger", Cost:"2B", Color:["B"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"SOI", Number:"119", Image:"/Images/SOI/KindlyStranger.jpg", ReverseImage:"/Images/SOI/Demon-PossessedWitch.jpg"},
{Name:"Liliana's Indignation", Cost:"0B", Color:["B"], Rarity:"U", Type:["S"], Rating:"4", Sort:"1", Set:"SOI", Number:"120", Image:"/Images/SOI/LilianasIndignation.jpg", },
{Name:"Macabre Waltz", Cost:"1B", Color:["B"], Rarity:"C", Type:["S"], Rating:"1", Sort:"1", Set:"SOI", Number:"121", Image:"/Images/SOI/MacabreWaltz.jpg", },
{Name:"Markov Dreadknight", Cost:"3BB", Color:["B"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"SOI", Number:"122", Image:"/Images/SOI/MarkovDreadknight.jpg", },
{Name:"Merciless Resolve", Cost:"2B", Color:["B"], Rarity:"C", Type:["I"], Rating:"3", Sort:"1", Set:"SOI", Number:"123", Image:"/Images/SOI/MercilessResolve.jpg", },
{Name:"Mindwrack Demon", Cost:"2BB", Color:["B"], Rarity:"M", Type:["C"], Rating:"8", Sort:"1", Set:"SOI", Number:"124", Image:"/Images/SOI/MindwrackDemon.jpg", },
{Name:"Morkrut Necropod", Cost:"5B", Color:["B"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"SOI", Number:"125", Image:"/Images/SOI/MorkrutNecropod.jpg", },
{Name:"Murderous Compulsion", Cost:"1B", Color:["B"], Rarity:"C", Type:["S"], Rating:"5", Sort:"1", Set:"SOI", Number:"126", Image:"/Images/SOI/MurderousCompulsion.jpg", },
{Name:"Olivia's Bloodsworn", Cost:"1B", Color:["B"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"SOI", Number:"127", Image:"/Images/SOI/OliviasBloodsworn.jpg", },
{Name:"Pale Rider of Trostad", Cost:"1B", Color:["B"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"SOI", Number:"128", Image:"/Images/SOI/PaleRiderofTrostad.jpg", },
{Name:"Pick the Brain", Cost:"2B", Color:["B"], Rarity:"U", Type:["S"], Rating:"3", Sort:"1", Set:"SOI", Number:"129", Image:"/Images/SOI/PicktheBrain.jpg", },
{Name:"Rancid Rats", Cost:"1B", Color:["B"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"SOI", Number:"130", Image:"/Images/SOI/RancidRats.jpg", },
{Name:"Relentless Dead", Cost:"0BB", Color:["B"], Rarity:"M", Type:["C"], Rating:"9", Sort:"1", Set:"SOI", Number:"131", Image:"/Images/SOI/RelentlessDead.jpg", },
{Name:"Rottenheart Ghoul", Cost:"3B", Color:["B"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"SOI", Number:"132", Image:"/Images/SOI/RottenheartGhoul.jpg", },
{Name:"Sanitarium Skeleton", Cost:"0B", Color:["B"], Rarity:"C", Type:["C"], Rating:"2", Sort:"1", Set:"SOI", Number:"133", Image:"/Images/SOI/SanitariumSkeleton.jpg", },
{Name:"Shamble Back", Cost:"0B", Color:["B"], Rarity:"C", Type:["S"], Rating:"2", Sort:"1", Set:"SOI", Number:"134", Image:"/Images/SOI/ShambleBack.jpg", },
{Name:"Sinister Concoction", Cost:"0B", Color:["B"], Rarity:"U", Type:["E"], Rating:"4", Sort:"1", Set:"SOI", Number:"135", Image:"/Images/SOI/SinisterConcoction.jpg", },
{Name:"Stallion of Ashmouth", Cost:"3B", Color:["B"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"SOI", Number:"136", Image:"/Images/SOI/StallionofAshmouth.jpg", },
{Name:"Stromkirk Mentor", Cost:"3B", Color:["B"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"SOI", Number:"137", Image:"/Images/SOI/StromkirkMentor.jpg", },
{Name:"Throttle", Cost:"4B", Color:["B"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"SOI", Number:"138", Image:"/Images/SOI/Throttle.jpg", },
{Name:"To the Slaughter", Cost:"2B", Color:["B"], Rarity:"R", Type:["I"], Rating:"8", Sort:"1", Set:"SOI", Number:"139", Image:"/Images/SOI/TotheSlaughter.jpg", },
{Name:"Tooth Collector", Cost:"2B", Color:["B"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"SOI", Number:"140", Image:"/Images/SOI/ToothCollector.jpg", },
{Name:"Triskaidekaphobia", Cost:"3B", Color:["B"], Rarity:"R", Type:["E"], Rating:"5", Sort:"1", Set:"SOI", Number:"141", Image:"/Images/SOI/Triskaidekaphobia.jpg", },
{Name:"Twins of Maurer Estate", Cost:"4B", Color:["B"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"SOI", Number:"142", Image:"/Images/SOI/TwinsofMaurerEstate.jpg", },
{Name:"Vampire Noble", Cost:"2B", Color:["B"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"SOI", Number:"143", Image:"/Images/SOI/VampireNoble.jpg", },
{Name:"Vessel of Malignity", Cost:"1B", Color:["B"], Rarity:"C", Type:["E"], Rating:"3", Sort:"1", Set:"SOI", Number:"144", Image:"/Images/SOI/VesselofMalignity.jpg", },
{Name:"Avacyn's Judgment", Cost:"1R", Color:["R"], Rarity:"R", Type:["S"], Rating:"7", Sort:"1", Set:"SOI", Number:"145", Image:"/Images/SOI/AvacynsJudgment.jpg", },
{Name:"Bloodmad Vampire", Cost:"2R", Color:["R"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"SOI", Number:"146", Image:"/Images/SOI/BloodmadVampire.jpg", },
{Name:"Breakneck Rider", Cost:"1RR", Color:["R"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"SOI", Number:"147", Image:"/Images/SOI/BreakneckRider.jpg", ReverseImage:"/Images/SOI/NeckBreaker.jpg"},
{Name:"Burn from Within", Cost:"0R", Color:["R"], Rarity:"R", Type:["S"], Rating:"7", Sort:"1", Set:"SOI", Number:"148", Image:"/Images/SOI/BurnfromWithin.jpg", },
{Name:"Convicted Killer", Cost:"2R", Color:["R"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"SOI", Number:"149", Image:"/Images/SOI/ConvictedKiller.jpg", ReverseImage:"/Images/SOI/BrandedHowler.jpg"},
{Name:"Dance with Devils", Cost:"3R", Color:["R"], Rarity:"U", Type:["S"], Rating:"4", Sort:"1", Set:"SOI", Number:"150", Image:"/Images/SOI/DancewithDevils.jpg", },
{Name:"Devils' Playground", Cost:"4RR", Color:["R"], Rarity:"R", Type:["S"], Rating:"6", Sort:"1", Set:"SOI", Number:"151", Image:"/Images/SOI/DevilsPlayground.jpg", },
{Name:"Dissension in the Ranks", Cost:"3RR", Color:["R"], Rarity:"U", Type:["I"], Rating:"5", Sort:"1", Set:"SOI", Number:"152", Image:"/Images/SOI/DissensionintheRanks.jpg", },
{Name:"Dual Shot", Cost:"0R", Color:["R"], Rarity:"C", Type:["I"], Rating:"3", Sort:"1", Set:"SOI", Number:"153", Image:"/Images/SOI/DualShot.jpg", },
{Name:"Ember-Eye Wolf", Cost:"1R", Color:["R"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"SOI", Number:"154", Image:"/Images/SOI/Ember-EyeWolf.jpg", },
{Name:"Falkenrath Gorger", Cost:"0R", Color:["R"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"SOI", Number:"155", Image:"/Images/SOI/FalkenrathGorger.jpg", },
{Name:"Fiery Temper", Cost:"1RR", Color:["R"], Rarity:"C", Type:["I"], Rating:"4", Sort:"1", Set:"SOI", Number:"156", Image:"/Images/SOI/FieryTemper.jpg", },
{Name:"Flameblade Angel", Cost:"4RR", Color:["R"], Rarity:"R", Type:["C"], Rating:"6", Sort:"1", Set:"SOI", Number:"157", Image:"/Images/SOI/FlamebladeAngel.jpg", },
{Name:"Gatstaf Arsonists", Cost:"4R", Color:["R"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"SOI", Number:"158", Image:"/Images/SOI/GatstafArsonists.jpg", ReverseImage:"/Images/SOI/GatstafRavagers.jpg"},
{Name:"Geier Reach Bandit", Cost:"2R", Color:["R"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"SOI", Number:"159", Image:"/Images/SOI/GeierReachBandit.jpg", ReverseImage:"/Images/SOI/Vildin-PackAlpha.jpg"},
{Name:"Geistblast", Cost:"2R", Color:["R"], Rarity:"U", Type:["I"], Rating:"4", Sort:"1", Set:"SOI", Number:"160", Image:"/Images/SOI/Geistblast.jpg", },
{Name:"Gibbering Fiend", Cost:"1R", Color:["R"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"SOI", Number:"161", Image:"/Images/SOI/GibberingFiend.jpg", },
{Name:"Goldnight Castigator", Cost:"2RR", Color:["R"], Rarity:"M", Type:["C"], Rating:"8", Sort:"1", Set:"SOI", Number:"162", Image:"/Images/SOI/GoldnightCastigator.jpg", },
{Name:"Harness the Storm", Cost:"2R", Color:["R"], Rarity:"R", Type:["E"], Rating:"5", Sort:"1", Set:"SOI", Number:"163", Image:"/Images/SOI/HarnesstheStorm.jpg", },
{Name:"Howlpack Wolf", Cost:"2R", Color:["R"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"SOI", Number:"164", Image:"/Images/SOI/HowlpackWolf.jpg", },
{Name:"Hulking Devil", Cost:"3R", Color:["R"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"SOI", Number:"165", Image:"/Images/SOI/HulkingDevil.jpg", },
{Name:"Incorrigible Youths", Cost:"3RR", Color:["R"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"SOI", Number:"166", Image:"/Images/SOI/IncorrigibleYouths.jpg", },
{Name:"Inner Struggle", Cost:"3R", Color:["R"], Rarity:"U", Type:["I"], Rating:"7", Sort:"1", Set:"SOI", Number:"167", Image:"/Images/SOI/InnerStruggle.jpg", },
{Name:"Insolent Neonate", Cost:"0R", Color:["R"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"SOI", Number:"168", Image:"/Images/SOI/InsolentNeonate.jpg", },
{Name:"Kessig Forgemaster", Cost:"1R", Color:["R"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"SOI", Number:"169", Image:"/Images/SOI/KessigForgemaster.jpg", ReverseImage:"/Images/SOI/FlameheartWerewolf.jpg"},
{Name:"Lightning Axe", Cost:"0R", Color:["R"], Rarity:"U", Type:["I"], Rating:"5", Sort:"1", Set:"SOI", Number:"170", Image:"/Images/SOI/LightningAxe.jpg", },
{Name:"Mad Prophet", Cost:"3R", Color:["R"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"SOI", Number:"171", Image:"/Images/SOI/MadProphet.jpg", },
{Name:"Magmatic Chasm", Cost:"1R", Color:["R"], Rarity:"C", Type:["S"], Rating:"2", Sort:"1", Set:"SOI", Number:"172", Image:"/Images/SOI/MagmaticChasm.jpg", },
{Name:"Malevolent Whispers", Cost:"3R", Color:["R"], Rarity:"U", Type:["S"], Rating:"4", Sort:"1", Set:"SOI", Number:"173", Image:"/Images/SOI/MalevolentWhispers.jpg", },
{Name:"Pyre Hound", Cost:"3R", Color:["R"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"SOI", Number:"174", Image:"/Images/SOI/PyreHound.jpg", },
{Name:"Ravenous Bloodseeker", Cost:"1R", Color:["R"], Rarity:"U", Type:["C"], Rating:"3", Sort:"1", Set:"SOI", Number:"175", Image:"/Images/SOI/RavenousBloodseeker.jpg", },
{Name:"Reduce to Ashes", Cost:"4R", Color:["R"], Rarity:"C", Type:["S"], Rating:"4", Sort:"1", Set:"SOI", Number:"176", Image:"/Images/SOI/ReducetoAshes.jpg", },
{Name:"Rush of Adrenaline", Cost:"0R", Color:["R"], Rarity:"C", Type:["I"], Rating:"2", Sort:"1", Set:"SOI", Number:"177", Image:"/Images/SOI/RushofAdrenaline.jpg", },
{Name:"Sanguinary Mage", Cost:"1R", Color:["R"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"SOI", Number:"178", Image:"/Images/SOI/SanguinaryMage.jpg", },
{Name:"Scourge Wolf", Cost:"0RR", Color:["R"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"SOI", Number:"179", Image:"/Images/SOI/ScourgeWolf.jpg", },
{Name:"Senseless Rage", Cost:"1R", Color:["R"], Rarity:"C", Type:["E"], Rating:"2", Sort:"1", Set:"SOI", Number:"180", Image:"/Images/SOI/SenselessRage.jpg", },
{Name:"Sin Prodder", Cost:"2R", Color:["R"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"SOI", Number:"181", Image:"/Images/SOI/SinProdder.jpg", },
{Name:"Skin Invasion", Cost:"0R", Color:["R"], Rarity:"U", Type:["E"], Rating:"6", Sort:"1", Set:"SOI", Number:"182", Image:"/Images/SOI/SkinInvasion.jpg", ReverseImage:"/Images/SOI/SkinShedder.jpg"},
{Name:"Spiteful Motives", Cost:"3R", Color:["R"], Rarity:"U", Type:["E"], Rating:"5", Sort:"1", Set:"SOI", Number:"183", Image:"/Images/SOI/SpitefulMotives.jpg", },
{Name:"Stensia Masquerade", Cost:"2R", Color:["R"], Rarity:"U", Type:["E"], Rating:"4", Sort:"1", Set:"SOI", Number:"184", Image:"/Images/SOI/StensiaMasquerade.jpg", },
{Name:"Structural Distortion", Cost:"3R", Color:["R"], Rarity:"C", Type:["S"], Rating:"3", Sort:"1", Set:"SOI", Number:"185", Image:"/Images/SOI/StructuralDistortion.jpg", },
{Name:"Tormenting Voice", Cost:"1R", Color:["R"], Rarity:"C", Type:["S"], Rating:"3", Sort:"1", Set:"SOI", Number:"186", Image:"/Images/SOI/TormentingVoice.jpg", },
{Name:"Ulrich's Kindred", Cost:"2R", Color:["R"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"SOI", Number:"187", Image:"/Images/SOI/UlrichsKindred.jpg", },
{Name:"Uncaged Fury", Cost:"2R", Color:["R"], Rarity:"C", Type:["I"], Rating:"2", Sort:"1", Set:"SOI", Number:"188", Image:"/Images/SOI/UncagedFury.jpg", },
{Name:"Vessel of Volatility", Cost:"1R", Color:["R"], Rarity:"C", Type:["E"], Rating:"3", Sort:"1", Set:"SOI", Number:"189", Image:"/Images/SOI/VesselofVolatility.jpg", },
{Name:"Village Messenger", Cost:"0R", Color:["R"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"SOI", Number:"190", Image:"/Images/SOI/VillageMessenger.jpg", ReverseImage:"/Images/SOI/MoonriseIntruder.jpg"},
{Name:"Voldaren Duelist", Cost:"3R", Color:["R"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"SOI", Number:"191", Image:"/Images/SOI/VoldarenDuelist.jpg", },
{Name:"Wolf of Devil's Breach", Cost:"3RR", Color:["R"], Rarity:"M", Type:["C"], Rating:"8", Sort:"1", Set:"SOI", Number:"192", Image:"/Images/SOI/WolfofDevilsBreach.jpg", },
{Name:"Aim High", Cost:"1G", Color:["G"], Rarity:"C", Type:["I"], Rating:"2", Sort:"1", Set:"SOI", Number:"193", Image:"/Images/SOI/AimHigh.jpg", },
{Name:"Autumnal Gloom", Cost:"2G", Color:["G"], Rarity:"U", Type:["E"], Rating:"6", Sort:"1", Set:"SOI", Number:"194", Image:"/Images/SOI/AutumnalGloom.jpg", ReverseImage:"/Images/SOI/AncientOfTheEquinox.jpg"},
{Name:"Briarbridge Patrol", Cost:"3G", Color:["G"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"SOI", Number:"195", Image:"/Images/SOI/BriarbridgePatrol.jpg", },
{Name:"Byway Courier", Cost:"2G", Color:["G"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"SOI", Number:"196", Image:"/Images/SOI/BywayCourier.jpg", },
{Name:"Clip Wings", Cost:"1G", Color:["G"], Rarity:"C", Type:["I"], Rating:"2", Sort:"1", Set:"SOI", Number:"197", Image:"/Images/SOI/ClipWings.jpg", },
{Name:"Confront the Unknown", Cost:"0G", Color:["G"], Rarity:"C", Type:["I"], Rating:"3", Sort:"1", Set:"SOI", Number:"198", Image:"/Images/SOI/ConfronttheUnknown.jpg", },
{Name:"Crawling Sensation", Cost:"2G", Color:["G"], Rarity:"U", Type:["E"], Rating:"5", Sort:"1", Set:"SOI", Number:"199", Image:"/Images/SOI/CrawlingSensation.jpg", },
{Name:"Cryptolith Rite", Cost:"1G", Color:["G"], Rarity:"R", Type:["E"], Rating:"8", Sort:"1", Set:"SOI", Number:"200", Image:"/Images/SOI/CryptolithRite.jpg", },
{Name:"Cult of the Waxing Moon", Cost:"4G", Color:["G"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"SOI", Number:"201", Image:"/Images/SOI/CultoftheWaxingMoon.jpg", },
{Name:"Deathcap Cultivator", Cost:"1G", Color:["G"], Rarity:"R", Type:["C"], Rating:"6", Sort:"1", Set:"SOI", Number:"202", Image:"/Images/SOI/DeathcapCultivator.jpg", },
{Name:"Duskwatch Recruiter", Cost:"1G", Color:["G"], Rarity:"U", Type:["C"], Rating:"7", Sort:"1", Set:"SOI", Number:"203", Image:"/Images/SOI/DuskwatchRecruiter.jpg", ReverseImage:"/Images/SOI/KrallenhordeHowler.jpg"},
{Name:"Equestrian Skill", Cost:"3G", Color:["G"], Rarity:"C", Type:["E"], Rating:"2", Sort:"1", Set:"SOI", Number:"204", Image:"/Images/SOI/EquestrianSkill.jpg", },
{Name:"Fork in the Road", Cost:"1G", Color:["G"], Rarity:"C", Type:["S"], Rating:"3", Sort:"1", Set:"SOI", Number:"205", Image:"/Images/SOI/ForkintheRoad.jpg", },
{Name:"Gloomwidow", Cost:"2G", Color:["G"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"SOI", Number:"206", Image:"/Images/SOI/Gloomwidow.jpg", },
{Name:"Graf Mole", Cost:"2G", Color:["G"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"SOI", Number:"207", Image:"/Images/SOI/GrafMole.jpg", },
{Name:"Groundskeeper", Cost:"0G", Color:["G"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"SOI", Number:"208", Image:"/Images/SOI/Groundskeeper.jpg", },
{Name:"Hermit of the Natterknolls", Cost:"2G", Color:["G"], Rarity:"U", Type:["C"], Rating:"7", Sort:"1", Set:"SOI", Number:"209", Image:"/Images/SOI/HermitoftheNatterknolls.jpg", ReverseImage:"/Images/SOI/LoneWolfOfTheNatterknolls.jpg"},
{Name:"Hinterland Logger", Cost:"1G", Color:["G"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"SOI", Number:"210", Image:"/Images/SOI/HinterlandLogger.jpg", ReverseImage:"/Images/SOI/TimberShredder.jpg"},
{Name:"Howlpack Resurgence", Cost:"2G", Color:["G"], Rarity:"U", Type:["E"], Rating:"5", Sort:"1", Set:"SOI", Number:"211", Image:"/Images/SOI/HowlpackResurgence.jpg", },
{Name:"Inexorable Blob", Cost:"2G", Color:["G"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"SOI", Number:"212", Image:"/Images/SOI/InexorableBlob.jpg", },
{Name:"Intrepid Provisioner", Cost:"3G", Color:["G"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"SOI", Number:"213", Image:"/Images/SOI/IntrepidProvisioner.jpg", },
{Name:"Kessig Dire Swine", Cost:"4GG", Color:["G"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"SOI", Number:"214", Image:"/Images/SOI/KessigDireSwine.jpg", },
{Name:"Lambholt Pacifist", Cost:"1G", Color:["G"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"SOI", Number:"215", Image:"/Images/SOI/LambholtPacifist.jpg", ReverseImage:"/Images/SOI/LambholtButcher.jpg"},
{Name:"Loam Dryad", Cost:"0G", Color:["G"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"SOI", Number:"216", Image:"/Images/SOI/LoamDryad.jpg", },
{Name:"Might Beyond Reason", Cost:"3G", Color:["G"], Rarity:"C", Type:["I"], Rating:"2", Sort:"1", Set:"SOI", Number:"217", Image:"/Images/SOI/MightBeyondReason.jpg", },
{Name:"Moldgraf Scavenger", Cost:"1G", Color:["G"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"SOI", Number:"218", Image:"/Images/SOI/MoldgrafScavenger.jpg", },
{Name:"Moonlight Hunt", Cost:"1G", Color:["G"], Rarity:"U", Type:["I"], Rating:"3", Sort:"1", Set:"SOI", Number:"219", Image:"/Images/SOI/MoonlightHunt.jpg", },
{Name:"Obsessive Skinner", Cost:"1G", Color:["G"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"SOI", Number:"220", Image:"/Images/SOI/ObsessiveSkinner.jpg", },
{Name:"Pack Guardian", Cost:"2GG", Color:["G"], Rarity:"U", Type:["C"], Rating:"7", Sort:"1", Set:"SOI", Number:"221", Image:"/Images/SOI/PackGuardian.jpg", },
{Name:"Quilled Wolf", Cost:"1G", Color:["G"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"SOI", Number:"222", Image:"/Images/SOI/QuilledWolf.jpg", },
{Name:"Rabid Bite", Cost:"1G", Color:["G"], Rarity:"C", Type:["S"], Rating:"2", Sort:"1", Set:"SOI", Number:"223", Image:"/Images/SOI/RabidBite.jpg", },
{Name:"Root Out", Cost:"2G", Color:["G"], Rarity:"C", Type:["S"], Rating:"1", Sort:"1", Set:"SOI", Number:"224", Image:"/Images/SOI/RootOut.jpg", },
{Name:"Sage of Ancient Lore", Cost:"4G", Color:["G"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"SOI", Number:"225", Image:"/Images/SOI/SageofAncientLore.jpg", ReverseImage:"/Images/SOI/WerewolfofAncientHunger.jpg"},
{Name:"Seasons Past", Cost:"4GG", Color:["G"], Rarity:"M", Type:["S"], Rating:"6", Sort:"1", Set:"SOI", Number:"226", Image:"/Images/SOI/SeasonsPast.jpg", },
{Name:"Second Harvest", Cost:"2GG", Color:["G"], Rarity:"R", Type:["I"], Rating:"5", Sort:"1", Set:"SOI", Number:"227", Image:"/Images/SOI/SecondHarvest.jpg", },
{Name:"Silverfur Partisan", Cost:"2G", Color:["G"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"SOI", Number:"228", Image:"/Images/SOI/SilverfurPartisan.jpg", },
{Name:"Solitary Hunter", Cost:"3G", Color:["G"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"SOI", Number:"229", Image:"/Images/SOI/SolitaryHunter.jpg", ReverseImage:"/Images/SOI/OneOfThePack.jpg"},
{Name:"Soul Swallower", Cost:"2GG", Color:["G"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"SOI", Number:"230", Image:"/Images/SOI/SoulSwallower.jpg", },
{Name:"Stoic Builder", Cost:"2G", Color:["G"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"SOI", Number:"231", Image:"/Images/SOI/StoicBuilder.jpg", },
{Name:"Thornhide Wolves", Cost:"4G", Color:["G"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"SOI", Number:"232", Image:"/Images/SOI/ThornhideWolves.jpg", },
{Name:"Tireless Tracker", Cost:"2G", Color:["G"], Rarity:"R", Type:["C"], Rating:"9", Sort:"1", Set:"SOI", Number:"233", Image:"/Images/SOI/TirelessTracker.jpg", },
{Name:"Traverse the Ulvenwald", Cost:"0G", Color:["G"], Rarity:"R", Type:["S"], Rating:"7", Sort:"1", Set:"SOI", Number:"234", Image:"/Images/SOI/TraversetheUlvenwald.jpg", },
{Name:"Ulvenwald Hydra", Cost:"4GG", Color:["G"], Rarity:"M", Type:["C"], Rating:"9", Sort:"1", Set:"SOI", Number:"235", Image:"/Images/SOI/UlvenwaldHydra.jpg", },
{Name:"Ulvenwald Mysteries", Cost:"2G", Color:["G"], Rarity:"U", Type:["E"], Rating:"5", Sort:"1", Set:"SOI", Number:"236", Image:"/Images/SOI/UlvenwaldMysteries.jpg", },
{Name:"Vessel of Nascency", Cost:"0G", Color:["G"], Rarity:"C", Type:["E"], Rating:"3", Sort:"1", Set:"SOI", Number:"237", Image:"/Images/SOI/VesselofNascency.jpg", },
{Name:"Veteran Cathar", Cost:"1G", Color:["G"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"SOI", Number:"238", Image:"/Images/SOI/VeteranCathar.jpg", },
{Name:"Watcher in the Web", Cost:"4G", Color:["G"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"SOI", Number:"239", Image:"/Images/SOI/WatcherintheWeb.jpg", },
{Name:"Weirding Wood", Cost:"2G", Color:["G"], Rarity:"U", Type:["E"], Rating:"6", Sort:"1", Set:"SOI", Number:"240", Image:"/Images/SOI/WeirdingWood.jpg", },
{Name:"Altered Ego", Cost:"2GU", Color:["G","U"], Rarity:"R", Type:["C"], Rating:"9", Sort:"1", Set:"SOI", Number:"241", Image:"/Images/SOI/AlteredEgo.jpg", },
{Name:"Anguished Unmaking", Cost:"1WB", Color:["W","B"], Rarity:"R", Type:["I"], Rating:"9", Sort:"1", Set:"SOI", Number:"242", Image:"/Images/SOI/AnguishedUnmaking.jpg", },
{Name:"Arlinn Kord", Cost:"2RG", Color:["R","G"], Rarity:"M", Type:["P"], Rating:"9", Sort:"1", Set:"SOI", Number:"243", Image:"/Images/SOI/ArlinnKord.jpg", ReverseImage:"/Images/SOI/Arlinn--EmbracedbytheMoon.jpg"},
{Name:"Fevered Visions", Cost:"1UR", Color:["U","R"], Rarity:"R", Type:["E"], Rating:"6", Sort:"1", Set:"SOI", Number:"244", Image:"/Images/SOI/FeveredVisions.jpg", },
{Name:"The Gitrog Monster", Cost:"3BG", Color:["B","G"], Rarity:"M", Type:["C"], Rating:"9", Sort:"1", Set:"SOI", Number:"245", Image:"/Images/SOI/TheGitrogMonster.jpg"},
{Name:"Invocation of Saint Traft", Cost:"1WU", Color:["W","U"], Rarity:"R", Type:["E"], Rating:"7", Sort:"1", Set:"SOI", Number:"246", Image:"/Images/SOI/InvocationofSaintTraft.jpg", },
{Name:"Nahiri, the Harbinger", Cost:"2RW", Color:["R","W"], Rarity:"M", Type:["P"], Rating:"9", Sort:"1", Set:"SOI", Number:"247", Image:"/Images/SOI/Nahiri--theHarbinger.jpg", },
{Name:"Olivia, Mobilized for War", Cost:"1BR", Color:["B","R"], Rarity:"M", Type:["C"], Rating:"8", Sort:"1", Set:"SOI", Number:"248", Image:"/Images/SOI/Olivia--MobilizedforWar.jpg", },
{Name:"Prized Amalgam", Cost:"1UB", Color:["U","B"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"SOI", Number:"249", Image:"/Images/SOI/PrizedAmalgam.jpg", },
{Name:"Sigarda, Heron's Grace", Cost:"3WG", Color:["W","G"], Rarity:"M", Type:["C"], Rating:"9", Sort:"1", Set:"SOI", Number:"250", Image:"/Images/SOI/Sigarda--HeronsGrace.jpg", },
{Name:"Sorin, Grim Nemesis", Cost:"4WB", Color:["W","B"], Rarity:"M", Type:["P"], Rating:"9", Sort:"1", Set:"SOI", Number:"251", Image:"/Images/SOI/Sorin--GrimNemesis.jpg", },
{Name:"Brain in a Jar", Cost:"2", Color:["C"], Rarity:"R", Type:["A"], Rating:"8", Sort:"1", Set:"SOI", Number:"252", Image:"/Images/SOI/BraininaJar.jpg", },
{Name:"Corrupted Grafstone", Cost:"2", Color:["C"], Rarity:"R", Type:["A"], Rating:"7", Sort:"1", Set:"SOI", Number:"253", Image:"/Images/SOI/CorruptedGrafstone.jpg", },
{Name:"Epitaph Golem", Cost:"5", Color:["C"], Rarity:"U", Type:["C"], Rating:"3", Sort:"1", Set:"SOI", Number:"254", Image:"/Images/SOI/EpitaphGolem.jpg", },
{Name:"Explosive Apparatus", Cost:"1", Color:["C"], Rarity:"C", Type:["A"], Rating:"2", Sort:"1", Set:"SOI", Number:"255", Image:"/Images/SOI/ExplosiveApparatus.jpg", },
{Name:"Harvest Hand", Cost:"3", Color:["C"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"SOI", Number:"256", Image:"/Images/SOI/HarvestHand.jpg", ReverseImage:"/Images/SOI/ScroungedScythe.jpg"},
{Name:"Haunted Cloak", Cost:"3", Color:["C"], Rarity:"U", Type:["A"], Rating:"3", Sort:"1", Set:"SOI", Number:"257", Image:"/Images/SOI/HauntedCloak.jpg", },
{Name:"Magnifying Glass", Cost:"3", Color:["C"], Rarity:"U", Type:["A"], Rating:"4", Sort:"1", Set:"SOI", Number:"258", Image:"/Images/SOI/MagnifyingGlass.jpg", },
{Name:"Murderer's Axe", Cost:"4", Color:["C"], Rarity:"U", Type:["A"], Rating:"3", Sort:"1", Set:"SOI", Number:"259", Image:"/Images/SOI/MurderersAxe.jpg", },
{Name:"Neglected Heirloom", Cost:"1", Color:["C"], Rarity:"U", Type:["A"], Rating:"4", Sort:"1", Set:"SOI", Number:"260", Image:"/Images/SOI/NeglectedHeirloom.jpg", ReverseImage:"/Images/SOI/AshmouthBlade.jpg"},
{Name:"Runaway Carriage", Cost:"4", Color:["C"], Rarity:"U", Type:["A"], Rating:"2", Sort:"1", Set:"SOI", Number:"261", Image:"/Images/SOI/RunawayCarriage.jpg", },
{Name:"Shard of Broken Glass", Cost:"1", Color:["C"], Rarity:"C", Type:["A"], Rating:"2", Sort:"1", Set:"SOI", Number:"262", Image:"/Images/SOI/ShardofBrokenGlass.jpg", },
{Name:"Skeleton Key", Cost:"1", Color:["C"], Rarity:"U", Type:["A"], Rating:"3", Sort:"1", Set:"SOI", Number:"263", Image:"/Images/SOI/SkeletonKey.jpg", },
{Name:"Slayer's Plate", Cost:"3", Color:["C"], Rarity:"R", Type:["A"], Rating:"6", Sort:"1", Set:"SOI", Number:"264", Image:"/Images/SOI/SlayersPlate.jpg", },
{Name:"Tamiyo's Journal", Cost:"5", Color:["C"], Rarity:"R", Type:["A"], Rating:"7", Sort:"1", Set:"SOI", Number:"265", Image:"/Images/SOI/TamiyosJournal.jpg", },
{Name:"Thraben Gargoyle", Cost:"1", Color:["C"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"SOI", Number:"266", Image:"/Images/SOI/ThrabenGargoyle.jpg", ReverseImage:"/Images/SOI/StonewingAntagonizer.jpg"},
{Name:"True-Faith Censer", Cost:"2", Color:["C"], Rarity:"C", Type:["A"], Rating:"1", Sort:"1", Set:"SOI", Number:"267", Image:"/Images/SOI/True-FaithCenser.jpg", },
{Name:"Wicker Witch", Cost:"3", Color:["C"], Rarity:"C", Type:["A"], Rating:"2", Sort:"1", Set:"SOI", Number:"268", Image:"/Images/SOI/WickerWitch.jpg", },
{Name:"Wild-Field Scarecrow", Cost:"3", Color:["C"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"SOI", Number:"269", Image:"/Images/SOI/Wild-FieldScarecrow.jpg", },
{Name:"Choked Estuary", Cost:"0", Color:["U","B"], Rarity:"R", Type:["L"], Rating:"6", Sort:"1", Set:"SOI", Number:"270", Image:"/Images/SOI/ChokedEstuary.jpg", },
{Name:"Drownyard Temple", Cost:"0", Color:["C"], Rarity:"R", Type:["L"], Rating:"6", Sort:"1", Set:"SOI", Number:"271", Image:"/Images/SOI/DrownyardTemple.jpg", },
{Name:"Foreboding Ruins", Cost:"0", Color:["B","R"], Rarity:"R", Type:["L"], Rating:"6", Sort:"1", Set:"SOI", Number:"272", Image:"/Images/SOI/ForebodingRuins.jpg", },
{Name:"Forsaken Sanctuary", Cost:"0", Color:["W","B"], Rarity:"U", Type:["L"], Rating:"4", Sort:"1", Set:"SOI", Number:"272", Image:"/Images/SOI/ForsakenSanctuary.jpg", },
{Name:"Fortified Village", Cost:"0", Color:["W","G"], Rarity:"R", Type:["L"], Rating:"6", Sort:"1", Set:"SOI", Number:"272", Image:"/Images/SOI/FortifiedVillage.jpg", },
{Name:"Foul Orchard", Cost:"0", Color:["B","G"], Rarity:"U", Type:["L"], Rating:"4", Sort:"1", Set:"SOI", Number:"272", Image:"/Images/SOI/FoulOrchard.jpg", },
{Name:"Game Trail", Cost:"0", Color:["R","G"], Rarity:"R", Type:["L"], Rating:"6", Sort:"1", Set:"SOI", Number:"272", Image:"/Images/SOI/GameTrail.jpg", },
{Name:"Highland Lake", Cost:"0", Color:["U","R"], Rarity:"U", Type:["L"], Rating:"4", Sort:"1", Set:"SOI", Number:"272", Image:"/Images/SOI/HighlandLake.jpg", },
{Name:"Port Town", Cost:"0", Color:["W","U"], Rarity:"R", Type:["L"], Rating:"6", Sort:"1", Set:"SOI", Number:"272", Image:"/Images/SOI/PortTown.jpg", },
{Name:"Stone Quarry", Cost:"0", Color:["W","R"], Rarity:"U", Type:["L"], Rating:"4", Sort:"1", Set:"SOI", Number:"272", Image:"/Images/SOI/StoneQuarry.jpg", },
{Name:"Warped Landscape", Cost:"0", Color:["C"], Rarity:"C", Type:["L"], Rating:"1", Sort:"1", Set:"SOI", Number:"272", Image:"/Images/SOI/WarpedLandscape.jpg", },
{Name:"Westvale Abbey", Cost:"0", Color:["C"], Rarity:"R", Type:["L"], Rating:"7", Sort:"1", Set:"SOI", Number:"272", Image:"/Images/SOI/WestvaleAbbey.jpg", ReverseImage:"/Images/SOI/Ormendahl--ProfanePrince.jpg"},
{Name:"Woodland Stream", Cost:"0", Color:["U","B"], Rarity:"U", Type:["L"], Rating:"4", Sort:"1", Set:"SOI", Number:"272", Image:"/Images/SOI/WoodlandStream.jpg", },
];
