var THS = [
{Name:"Battlewise Valor", Cost:"2", Color:["W"], Rarity:"C", Type:["I"], Rating:"5", Sort:"1", Set:"THS", Number:"1", Image:"/Images/THS/1.jpg"},
{Name:"Cavalry Pegasus", Cost:"2", Color:["W"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"THS", Number:"2", Image:"/Images/THS/2.jpg"},
{Name:"Celestial Archon", Cost:"5", Color:["W"], Rarity:"R", Type:["E","C"], Rating:"9", Sort:"1", Set:"THS", Number:"3", Image:"/Images/THS/3.jpg"},
{Name:"Chained to the Rocks", Cost:"1", Color:["W"], Rarity:"R", Type:["E"], Rating:"7", Sort:"1", Set:"THS", Number:"4", Image:"/Images/THS/4.jpg"},
{Name:"Chosen by Heliod", Cost:"2", Color:["W"], Rarity:"C", Type:["E"], Rating:"5", Sort:"1", Set:"THS", Number:"5", Image:"/Images/THS/5.jpg"},
{Name:"Dauntless Onslaught", Cost:"3", Color:["W"], Rarity:"U", Type:["I"], Rating:"6", Sort:"1", Set:"THS", Number:"6", Image:"/Images/THS/6.jpg"},
{Name:"Decorated Griffin", Cost:"5", Color:["W"], Rarity:"U", Type:["C"], Rating:"3", Sort:"1", Set:"THS", Number:"7", Image:"/Images/THS/7.jpg"},
{Name:"Divine Verdict", Cost:"4", Color:["W"], Rarity:"C", Type:["I"], Rating:"6", Sort:"1", Set:"THS", Number:"8", Image:"/Images/THS/8.jpg"},
{Name:"Elspeth, Sun's Champion", Cost:"6", Color:["W"], Rarity:"M", Type:["P"], Rating:"9", Sort:"1", Set:"THS", Number:"9", Image:"/Images/THS/9.jpg"},
{Name:"Ephara's Warden", Cost:"4", Color:["W"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"THS", Number:"10", Image:"/Images/THS/10.jpg"},
{Name:"Evangel of Heliod", Cost:"6", Color:["W"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"THS", Number:"11", Image:"/Images/THS/11.jpg"},
{Name:"Fabled Hero", Cost:"3", Color:["W"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"THS", Number:"12", Image:"/Images/THS/12.jpg"},
{Name:"Favored Hoplite", Cost:"1", Color:["W"], Rarity:"U", Type:["C"], Rating:"2", Sort:"1", Set:"THS", Number:"13", Image:"/Images/THS/13.jpg"},
{Name:"Gift of Immortality", Cost:"3", Color:["W"], Rarity:"R", Type:["E"], Rating:"3", Sort:"1", Set:"THS", Number:"14", Image:"/Images/THS/14.jpg"},
{Name:"Glare of Heresy", Cost:"2", Color:["W"], Rarity:"U", Type:["S"], Rating:"1", Sort:"1", Set:"THS", Number:"15", Image:"/Images/THS/15.jpg"},
{Name:"Gods Willing", Cost:"1", Color:["W"], Rarity:"C", Type:["I"], Rating:"7", Sort:"1", Set:"THS", Number:"16", Image:"/Images/THS/16.jpg"},
{Name:"Heliod, God of the Sun", Cost:"4", Color:["W"], Rarity:"M", Type:["E","C"], Rating:"9", Sort:"1", Set:"THS", Number:"17", Image:"/Images/THS/17.jpg"},
{Name:"Heliod's Emissary", Cost:"4", Color:["W"], Rarity:"U", Type:["E","C"], Rating:"7", Sort:"1", Set:"THS", Number:"18", Image:"/Images/THS/18.jpg"},
{Name:"Hopeful Eidolon", Cost:"1", Color:["W"], Rarity:"C", Type:["E","C"], Rating:"6", Sort:"1", Set:"THS", Number:"19", Image:"/Images/THS/19.jpg"},
{Name:"Hundred-Handed One", Cost:"4", Color:["W"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"THS", Number:"20", Image:"/Images/THS/20.jpg"},
{Name:"Lagonna-Band Elder", Cost:"3", Color:["W"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"THS", Number:"21", Image:"/Images/THS/21.jpg"},
{Name:"Last Breath", Cost:"2", Color:["W"], Rarity:"C", Type:["I"], Rating:"5", Sort:"1", Set:"THS", Number:"22", Image:"/Images/THS/22.jpg"},
{Name:"Leonin Snarecaster", Cost:"2", Color:["W"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"THS", Number:"23", Image:"/Images/THS/23.jpg"},
{Name:"Observant Alseid", Cost:"3", Color:["W"], Rarity:"C", Type:["E","C"], Rating:"6", Sort:"1", Set:"THS", Number:"24", Image:"/Images/THS/24.jpg"},
{Name:"Ordeal of Heliod", Cost:"2", Color:["W"], Rarity:"U", Type:["E"], Rating:"2", Sort:"1", Set:"THS", Number:"25", Image:"/Images/THS/25.jpg"},
{Name:"Phalanx Leader", Cost:"2", Color:["W"], Rarity:"U", Type:["C"], Rating:"7", Sort:"1", Set:"THS", Number:"26", Image:"/Images/THS/26.jpg"},
{Name:"Ray of Dissolution", Cost:"3", Color:["W"], Rarity:"C", Type:["I"], Rating:"5", Sort:"1", Set:"THS", Number:"27", Image:"/Images/THS/27.jpg"},
{Name:"Scholar of Athreos", Cost:"3", Color:["W"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"THS", Number:"28", Image:"/Images/THS/28.jpg"},
{Name:"Setessan Battle Priest", Cost:"2", Color:["W"], Rarity:"C", Type:["C"], Rating:"2", Sort:"1", Set:"THS", Number:"29", Image:"/Images/THS/29.jpg"},
{Name:"Setessan Griffin", Cost:"5", Color:["W"], Rarity:"C", Type:["C"], Rating:"5", Sort:"1", Set:"THS", Number:"30", Image:"/Images/THS/30.jpg"},
{Name:"Silent Artisan", Cost:"5", Color:["W"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"THS", Number:"31", Image:"/Images/THS/31.jpg"},
{Name:"Soldier of the Pantheon", Cost:"1", Color:["W"], Rarity:"R", Type:["C"], Rating:"5", Sort:"1", Set:"THS", Number:"32", Image:"/Images/THS/32.jpg"},
{Name:"Spear of Heliod", Cost:"3", Color:["W"], Rarity:"R", Type:["E","A"], Rating:"9", Sort:"1", Set:"THS", Number:"33", Image:"/Images/THS/33.jpg"},
{Name:"Traveling Philosopher", Cost:"2", Color:["W"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"THS", Number:"34", Image:"/Images/THS/34.jpg"},
{Name:"Vanquish the Foul", Cost:"6", Color:["W"], Rarity:"U", Type:["S"], Rating:"6", Sort:"1", Set:"THS", Number:"35", Image:"/Images/THS/35.jpg"},
{Name:"Wingsteed Rider", Cost:"3", Color:["W"], Rarity:"C", Type:["C"], Rating:"6", Sort:"1", Set:"THS", Number:"36", Image:"/Images/THS/36.jpg"},
{Name:"Yoked Ox", Cost:"1", Color:["W"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"THS", Number:"37", Image:"/Images/THS/37.jpg"},
{Name:"Annul", Cost:"1", Color:["U"], Rarity:"C", Type:["I"], Rating:"6", Sort:"1", Set:"THS", Number:"38", Image:"/Images/THS/38.jpg"},
{Name:"Aqueous Form", Cost:"1", Color:["U"], Rarity:"C", Type:["E"], Rating:"2", Sort:"1", Set:"THS", Number:"39", Image:"/Images/THS/39.jpg"},
{Name:"Artisan of Forms", Cost:"2", Color:["U"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"THS", Number:"40", Image:"/Images/THS/40.jpg"},
{Name:"Benthic Giant", Cost:"6", Color:["U"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"THS", Number:"41", Image:"/Images/THS/41.jpg"},
{Name:"Bident of Thassa", Cost:"4", Color:["U"], Rarity:"R", Type:["E","A"], Rating:"8", Sort:"1", Set:"THS", Number:"42", Image:"/Images/THS/42.jpg"},
{Name:"Breaching Hippocamp", Cost:"4", Color:["U"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"THS", Number:"43", Image:"/Images/THS/43.jpg"},
{Name:"Coastline Chimera", Cost:"4", Color:["U"], Rarity:"C", Type:["C"], Rating:"6", Sort:"1", Set:"THS", Number:"44", Image:"/Images/THS/44.jpg"},
{Name:"Crackling Triton", Cost:"3", Color:["U"], Rarity:"C", Type:["C"], Rating:"5", Sort:"1", Set:"THS", Number:"45", Image:"/Images/THS/45.jpg"},
{Name:"Curse of the Swine", Cost:"2", Color:["U"], Rarity:"R", Type:["S"], Rating:"7", Sort:"1", Set:"THS", Number:"46", Image:"/Images/THS/46.jpg"},
{Name:"Dissolve", Cost:"3", Color:["U"], Rarity:"U", Type:["I"], Rating:"7", Sort:"1", Set:"THS", Number:"47", Image:"/Images/THS/47.jpg"},
{Name:"Fate Foretold", Cost:"2", Color:["U"], Rarity:"C", Type:["E"], Rating:"6", Sort:"1", Set:"THS", Number:"48", Image:"/Images/THS/48.jpg"},
{Name:"Gainsay", Cost:"2", Color:["U"], Rarity:"U", Type:["I"], Rating:"1", Sort:"1", Set:"THS", Number:"49", Image:"/Images/THS/49.jpg"},
{Name:"Griptide", Cost:"4", Color:["U"], Rarity:"C", Type:["I"], Rating:"6", Sort:"1", Set:"THS", Number:"50", Image:"/Images/THS/50.jpg"},
{Name:"Horizon Scholar", Cost:"6", Color:["U"], Rarity:"U", Type:["C"], Rating:"7", Sort:"1", Set:"THS", Number:"51", Image:"/Images/THS/51.jpg"},
{Name:"Lost in a Labyrinth", Cost:"1", Color:["U"], Rarity:"C", Type:["I"], Rating:"5", Sort:"1", Set:"THS", Number:"52", Image:"/Images/THS/52.jpg"},
{Name:"Master of Waves", Cost:"4", Color:["U"], Rarity:"M", Type:["C"], Rating:"8", Sort:"1", Set:"THS", Number:"53", Image:"/Images/THS/53.jpg"},
{Name:"Meletis Charlatan", Cost:"3", Color:["U"], Rarity:"R", Type:["C"], Rating:"5", Sort:"1", Set:"THS", Number:"54", Image:"/Images/THS/54.jpg"},
{Name:"Mnemonic Wall", Cost:"5", Color:["U"], Rarity:"C", Type:["C"], Rating:"5", Sort:"1", Set:"THS", Number:"55", Image:"/Images/THS/55.jpg"},
{Name:"Nimbus Naiad", Cost:"3", Color:["U"], Rarity:"C", Type:["E","C"], Rating:"7", Sort:"1", Set:"THS", Number:"56", Image:"/Images/THS/56.jpg"},
{Name:"Omenspeaker", Cost:"2", Color:["U"], Rarity:"C", Type:["C"], Rating:"5", Sort:"1", Set:"THS", Number:"57", Image:"/Images/THS/57.jpg"},
{Name:"Ordeal of Thassa", Cost:"2", Color:["U"], Rarity:"U", Type:["E"], Rating:"3", Sort:"1", Set:"THS", Number:"58", Image:"/Images/THS/58.jpg"},
{Name:"Prescient Chimera", Cost:"5", Color:["U"], Rarity:"C", Type:["C"], Rating:"7", Sort:"1", Set:"THS", Number:"59", Image:"/Images/THS/59.jpg"},
{Name:"Prognostic Sphinx", Cost:"5", Color:["U"], Rarity:"R", Type:["C"], Rating:"9", Sort:"1", Set:"THS", Number:"60", Image:"/Images/THS/60.jpg"},
{Name:"Sea God's Revenge", Cost:"6", Color:["U"], Rarity:"U", Type:["S"], Rating:"7", Sort:"1", Set:"THS", Number:"61", Image:"/Images/THS/61.jpg"},
{Name:"Sealock Monster", Cost:"5", Color:["U"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"THS", Number:"62", Image:"/Images/THS/62.jpg"},
{Name:"Shipbreaker Kraken", Cost:"6", Color:["U"], Rarity:"R", Type:["C"], Rating:"9", Sort:"1", Set:"THS", Number:"63", Image:"/Images/THS/63.jpg"},
{Name:"Stymied Hopes", Cost:"2", Color:["U"], Rarity:"C", Type:["I"], Rating:"4", Sort:"1", Set:"THS", Number:"64", Image:"/Images/THS/64.jpg"},
{Name:"Swan Song", Cost:"1", Color:["U"], Rarity:"R", Type:["I"], Rating:"1", Sort:"1", Set:"THS", Number:"65", Image:"/Images/THS/65.jpg"},
{Name:"Thassa, God of the Sea", Cost:"3", Color:["U"], Rarity:"M", Type:["E","C"], Rating:"8", Sort:"1", Set:"THS", Number:"66", Image:"/Images/THS/66.jpg"},
{Name:"Thassa's Bounty", Cost:"6", Color:["U"], Rarity:"C", Type:["S"], Rating:"5", Sort:"1", Set:"THS", Number:"67", Image:"/Images/THS/67.jpg"},
{Name:"Thassa's Emissary", Cost:"4", Color:["U"], Rarity:"U", Type:["E","C"], Rating:"7", Sort:"1", Set:"THS", Number:"68", Image:"/Images/THS/68.jpg"},
{Name:"Triton Fortune Hunter", Cost:"3", Color:["U"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"THS", Number:"69", Image:"/Images/THS/69.jpg"},
{Name:"Triton Shorethief", Cost:"1", Color:["U"], Rarity:"C", Type:["C"], Rating:"1", Sort:"1", Set:"THS", Number:"70", Image:"/Images/THS/70.jpg"},
{Name:"Triton Tactics", Cost:"1", Color:["U"], Rarity:"U", Type:["I"], Rating:"6", Sort:"1", Set:"THS", Number:"71", Image:"/Images/THS/71.jpg"},
{Name:"Vaporkin", Cost:"2", Color:["U"], Rarity:"C", Type:["C"], Rating:"6", Sort:"1", Set:"THS", Number:"72", Image:"/Images/THS/72.jpg"},
{Name:"Voyage's End", Cost:"2", Color:["U"], Rarity:"C", Type:["I"], Rating:"7", Sort:"1", Set:"THS", Number:"73", Image:"/Images/THS/73.jpg"},
{Name:"Wavecrash Triton", Cost:"3", Color:["U"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"THS", Number:"74", Image:"/Images/THS/74.jpg"},
{Name:"Abhorrent Overlord", Cost:"7", Color:["B"], Rarity:"R", Type:["C"], Rating:"9", Sort:"1", Set:"THS", Number:"75", Image:"/Images/THS/75.jpg"},
{Name:"Agent of the Fates", Cost:"3", Color:["B"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"THS", Number:"76", Image:"/Images/THS/76.jpg"},
{Name:"Asphodel Wanderer", Cost:"1", Color:["B"], Rarity:"C", Type:["C"], Rating:"2", Sort:"1", Set:"THS", Number:"77", Image:"/Images/THS/77.jpg"},
{Name:"Baleful Eidolon", Cost:"2", Color:["B"], Rarity:"C", Type:["E","C"], Rating:"6", Sort:"1", Set:"THS", Number:"78", Image:"/Images/THS/78.jpg"},
{Name:"Blood-Toll Harpy", Cost:"3", Color:["B"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"THS", Number:"79", Image:"/Images/THS/79.jpg"},
{Name:"Boon of Erebos", Cost:"1", Color:["B"], Rarity:"C", Type:["I"], Rating:"5", Sort:"1", Set:"THS", Number:"80", Image:"/Images/THS/80.jpg"},
{Name:"Cavern Lampad", Cost:"4", Color:["B"], Rarity:"C", Type:["E","C"], Rating:"7", Sort:"1", Set:"THS", Number:"81", Image:"/Images/THS/81.jpg"},
{Name:"Cutthroat Maneuver", Cost:"4", Color:["B"], Rarity:"U", Type:["I"], Rating:"4", Sort:"1", Set:"THS", Number:"82", Image:"/Images/THS/82.jpg"},
{Name:"Dark Betrayal", Cost:"1", Color:["B"], Rarity:"U", Type:["I"], Rating:"5", Sort:"1", Set:"THS", Number:"83", Image:"/Images/THS/83.jpg"},
{Name:"Disciple of Phenax", Cost:"4", Color:["B"], Rarity:"C", Type:["C"], Rating:"7", Sort:"1", Set:"THS", Number:"84", Image:"/Images/THS/84.jpg"},
{Name:"Erebos, God of the Dead", Cost:"4", Color:["B"], Rarity:"M", Type:["E","C"], Rating:"6", Sort:"1", Set:"THS", Number:"85", Image:"/Images/THS/85.jpg"},
{Name:"Erebos's Emissary", Cost:"4", Color:["B"], Rarity:"U", Type:["E","C"], Rating:"7", Sort:"1", Set:"THS", Number:"86", Image:"/Images/THS/86.jpg"},
{Name:"Felhide Minotaur", Cost:"3", Color:["B"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"THS", Number:"87", Image:"/Images/THS/87.jpg"},
{Name:"Fleshmad Steed", Cost:"2", Color:["B"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"THS", Number:"88", Image:"/Images/THS/88.jpg"},
{Name:"Gray Merchant of Asphodel", Cost:"5", Color:["B"], Rarity:"C", Type:["C"], Rating:"7", Sort:"1", Set:"THS", Number:"89", Image:"/Images/THS/89.jpg"},
{Name:"Hero's Downfall", Cost:"3", Color:["B"], Rarity:"R", Type:["I"], Rating:"8", Sort:"1", Set:"THS", Number:"90", Image:"/Images/THS/90.jpg"},
{Name:"Hythonia the Cruel", Cost:"6", Color:["B"], Rarity:"M", Type:["C"], Rating:"9", Sort:"1", Set:"THS", Number:"91", Image:"/Images/THS/91.jpg"},
{Name:"Insatiable Harpy", Cost:"4", Color:["B"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"THS", Number:"92", Image:"/Images/THS/92.jpg"},
{Name:"Keepsake Gorgon", Cost:"5", Color:["B"], Rarity:"U", Type:["C"], Rating:"8", Sort:"1", Set:"THS", Number:"93", Image:"/Images/THS/93.jpg"},
{Name:"Lash of the Whip", Cost:"5", Color:["B"], Rarity:"C", Type:["I"], Rating:"6", Sort:"1", Set:"THS", Number:"94", Image:"/Images/THS/94.jpg"},
{Name:"Loathsome Catoblepas", Cost:"6", Color:["B"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"THS", Number:"95", Image:"/Images/THS/95.jpg"},
{Name:"March of the Returned", Cost:"4", Color:["B"], Rarity:"C", Type:["S"], Rating:"4", Sort:"1", Set:"THS", Number:"96", Image:"/Images/THS/96.jpg"},
{Name:"Mogis's Marauder", Cost:"3", Color:["B"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"THS", Number:"97", Image:"/Images/THS/97.jpg"},
{Name:"Nighthowler", Cost:"3", Color:["B"], Rarity:"R", Type:["E","C"], Rating:"7", Sort:"1", Set:"THS", Number:"98", Image:"/Images/THS/98.jpg"},
{Name:"Ordeal of Erebos", Cost:"2", Color:["B"], Rarity:"U", Type:["E"], Rating:"2", Sort:"1", Set:"THS", Number:"99", Image:"/Images/THS/99.jpg"},
{Name:"Pharika's Cure", Cost:"2", Color:["B"], Rarity:"C", Type:["I"], Rating:"6", Sort:"1", Set:"THS", Number:"100", Image:"/Images/THS/100.jpg"},
{Name:"Read the Bones", Cost:"3", Color:["B"], Rarity:"C", Type:["S"], Rating:"6", Sort:"1", Set:"THS", Number:"101", Image:"/Images/THS/101.jpg"},
{Name:"Rescue from the Underworld", Cost:"5", Color:["B"], Rarity:"U", Type:["I"], Rating:"5", Sort:"1", Set:"THS", Number:"102", Image:"/Images/THS/102.jpg"},
{Name:"Returned Centaur", Cost:"4", Color:["B"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"THS", Number:"103", Image:"/Images/THS/103.jpg"},
{Name:"Returned Phalanx", Cost:"2", Color:["B"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"THS", Number:"104", Image:"/Images/THS/104.jpg"},
{Name:"Scourgemark", Cost:"2", Color:["B"], Rarity:"C", Type:["E"], Rating:"5", Sort:"1", Set:"THS", Number:"105", Image:"/Images/THS/105.jpg"},
{Name:"Sip of Hemlock", Cost:"6", Color:["B"], Rarity:"C", Type:["S"], Rating:"7", Sort:"1", Set:"THS", Number:"106", Image:"/Images/THS/106.jpg"},
{Name:"Thoughtseize", Cost:"1", Color:["B"], Rarity:"R", Type:["S"], Rating:"6", Sort:"1", Set:"THS", Number:"107", Image:"/Images/THS/107.jpg"},
{Name:"Tormented Hero", Cost:"1", Color:["B"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"THS", Number:"108", Image:"/Images/THS/108.jpg"},
{Name:"Viper's Kiss", Cost:"1", Color:["B"], Rarity:"C", Type:["E"], Rating:"4", Sort:"1", Set:"THS", Number:"109", Image:"/Images/THS/109.jpg"},
{Name:"Whip of Erebos", Cost:"4", Color:["B"], Rarity:"R", Type:["E","A"], Rating:"8", Sort:"1", Set:"THS", Number:"110", Image:"/Images/THS/110.jpg"},
{Name:"Akroan Crusader", Cost:"1", Color:["R"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"THS", Number:"111", Image:"/Images/THS/111.jpg"},
{Name:"Anger of the Gods", Cost:"3", Color:["R"], Rarity:"R", Type:["S"], Rating:"8", Sort:"1", Set:"THS", Number:"112", Image:"/Images/THS/112.jpg"},
{Name:"Arena Athlete", Cost:"2", Color:["R"], Rarity:"U", Type:["C"], Rating:"7", Sort:"1", Set:"THS", Number:"113", Image:"/Images/THS/113.jpg"},
{Name:"Borderland Minotaur", Cost:"4", Color:["R"], Rarity:"C", Type:["C"], Rating:"6", Sort:"1", Set:"THS", Number:"114", Image:"/Images/THS/114.jpg"},
{Name:"Boulderfall", Cost:"8", Color:["R"], Rarity:"C", Type:["I"], Rating:"3", Sort:"1", Set:"THS", Number:"115", Image:"/Images/THS/115.jpg"},
{Name:"Coordinated Assault", Cost:"1", Color:["R"], Rarity:"U", Type:["I"], Rating:"6", Sort:"1", Set:"THS", Number:"116", Image:"/Images/THS/116.jpg"},
{Name:"Deathbellow Raider", Cost:"2", Color:["R"], Rarity:"C", Type:["C"], Rating:"5", Sort:"1", Set:"THS", Number:"117", Image:"/Images/THS/117.jpg"},
{Name:"Demolish", Cost:"4", Color:["R"], Rarity:"C", Type:["S"], Rating:"1", Sort:"1", Set:"THS", Number:"118", Image:"/Images/THS/118.jpg"},
{Name:"Dragon Mantle", Cost:"1", Color:["R"], Rarity:"C", Type:["E"], Rating:"5", Sort:"1", Set:"THS", Number:"119", Image:"/Images/THS/119.jpg"},
{Name:"Ember Swallower", Cost:"4", Color:["R"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"THS", Number:"120", Image:"/Images/THS/120.jpg"},
{Name:"Fanatic of Mogis", Cost:"4", Color:["R"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"THS", Number:"121", Image:"/Images/THS/121.jpg"},
{Name:"Firedrinker Satyr", Cost:"1", Color:["R"], Rarity:"R", Type:["C"], Rating:"5", Sort:"1", Set:"THS", Number:"122", Image:"/Images/THS/122.jpg"},
{Name:"Flamespeaker Adept", Cost:"3", Color:["R"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"THS", Number:"123", Image:"/Images/THS/123.jpg"},
{Name:"Hammer of Purphoros", Cost:"3", Color:["R"], Rarity:"R", Type:["E","A"], Rating:"8", Sort:"1", Set:"THS", Number:"124", Image:"/Images/THS/124.jpg"},
{Name:"Ill-Tempered Cyclops", Cost:"4", Color:["R"], Rarity:"C", Type:["C"], Rating:"6", Sort:"1", Set:"THS", Number:"125", Image:"/Images/THS/125.jpg"},
{Name:"Labyrinth Champion", Cost:"4", Color:["R"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"THS", Number:"126", Image:"/Images/THS/126.jpg"},
{Name:"Lightning Strike", Cost:"2", Color:["R"], Rarity:"C", Type:["I"], Rating:"7", Sort:"1", Set:"THS", Number:"127", Image:"/Images/THS/127.jpg"},
{Name:"Magma Jet", Cost:"2", Color:["R"], Rarity:"U", Type:["I"], Rating:"7", Sort:"1", Set:"THS", Number:"128", Image:"/Images/THS/128.jpg"},
{Name:"Messenger's Speed", Cost:"1", Color:["R"], Rarity:"C", Type:["E"], Rating:"2", Sort:"1", Set:"THS", Number:"129", Image:"/Images/THS/129.jpg"},
{Name:"Minotaur Skullcleaver", Cost:"3", Color:["R"], Rarity:"C", Type:["C"], Rating:"5", Sort:"1", Set:"THS", Number:"130", Image:"/Images/THS/130.jpg"},
{Name:"Ordeal of Purphoros", Cost:"2", Color:["R"], Rarity:"U", Type:["E"], Rating:"4", Sort:"1", Set:"THS", Number:"131", Image:"/Images/THS/131.jpg"},
{Name:"Peak Eruption", Cost:"3", Color:["R"], Rarity:"U", Type:["S"], Rating:"1", Sort:"1", Set:"THS", Number:"132", Image:"/Images/THS/132.jpg"},
{Name:"Portent of Betrayal", Cost:"4", Color:["R"], Rarity:"C", Type:["S"], Rating:"4", Sort:"1", Set:"THS", Number:"133", Image:"/Images/THS/133.jpg"},
{Name:"Priest of Iroas", Cost:"1", Color:["R"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"THS", Number:"134", Image:"/Images/THS/134.jpg"},
{Name:"Purphoros, God of the Forge", Cost:"4", Color:["R"], Rarity:"M", Type:["E","C"], Rating:"8", Sort:"1", Set:"THS", Number:"135", Image:"/Images/THS/135.jpg"},
{Name:"Purphoros's Emissary", Cost:"4", Color:["R"], Rarity:"U", Type:["E","C"], Rating:"6", Sort:"1", Set:"THS", Number:"136", Image:"/Images/THS/136.jpg"},
{Name:"Rage of Purphoros", Cost:"5", Color:["R"], Rarity:"C", Type:["S"], Rating:"6", Sort:"1", Set:"THS", Number:"137", Image:"/Images/THS/137.jpg"},
{Name:"Rageblood Shaman", Cost:"3", Color:["R"], Rarity:"R", Type:["C"], Rating:"5", Sort:"1", Set:"THS", Number:"138", Image:"/Images/THS/138.jpg"},
{Name:"Satyr Rambler", Cost:"2", Color:["R"], Rarity:"C", Type:["C"], Rating:"5", Sort:"1", Set:"THS", Number:"139", Image:"/Images/THS/139.jpg"},
{Name:"Spark Jolt", Cost:"1", Color:["R"], Rarity:"C", Type:["I"], Rating:"6", Sort:"1", Set:"THS", Number:"140", Image:"/Images/THS/140.jpg"},
{Name:"Spearpoint Oread", Cost:"3", Color:["R"], Rarity:"C", Type:["E","C"], Rating:"7", Sort:"1", Set:"THS", Number:"141", Image:"/Images/THS/141.jpg"},
{Name:"Stoneshock Giant", Cost:"5", Color:["R"], Rarity:"U", Type:["C"], Rating:"7", Sort:"1", Set:"THS", Number:"142", Image:"/Images/THS/142.jpg"},
{Name:"Stormbreath Dragon", Cost:"5", Color:["R"], Rarity:"M", Type:["C"], Rating:"8", Sort:"1", Set:"THS", Number:"143", Image:"/Images/THS/143.jpg"},
{Name:"Titan of Eternal Fire", Cost:"6", Color:["R"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"THS", Number:"144", Image:"/Images/THS/144.jpg"},
{Name:"Titan's Strength", Cost:"1", Color:["R"], Rarity:"C", Type:["I"], Rating:"6", Sort:"1", Set:"THS", Number:"145", Image:"/Images/THS/145.jpg"},
{Name:"Two-Headed Cerberus", Cost:"3", Color:["R"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"THS", Number:"146", Image:"/Images/THS/146.jpg"},
{Name:"Wild Celebrants", Cost:"5", Color:["R"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"THS", Number:"147", Image:"/Images/THS/147.jpg"},
{Name:"Agent of Horizons", Cost:"3", Color:["G"], Rarity:"C", Type:["C"], Rating:"5", Sort:"1", Set:"THS", Number:"148", Image:"/Images/THS/148.jpg"},
{Name:"Anthousa, Setessan Hero", Cost:"5", Color:["G"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"THS", Number:"149", Image:"/Images/THS/149.jpg"},
{Name:"Arbor Colossus", Cost:"5", Color:["G"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"THS", Number:"150", Image:"/Images/THS/150.jpg"},
{Name:"Artisan's Sorrow", Cost:"4", Color:["G"], Rarity:"U", Type:["I"], Rating:"3", Sort:"1", Set:"THS", Number:"151", Image:"/Images/THS/151.jpg"},
{Name:"Boon Satyr", Cost:"3", Color:["G"], Rarity:"R", Type:["E","C"], Rating:"8", Sort:"1", Set:"THS", Number:"152", Image:"/Images/THS/152.jpg"},
{Name:"Bow of Nylea", Cost:"3", Color:["G"], Rarity:"R", Type:["E","A"], Rating:"8", Sort:"1", Set:"THS", Number:"153", Image:"/Images/THS/153.jpg"},
{Name:"Centaur Battlemaster", Cost:"5", Color:["G"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"THS", Number:"154", Image:"/Images/THS/154.jpg"},
{Name:"Commune with the Gods", Cost:"2", Color:["G"], Rarity:"C", Type:["S"], Rating:"2", Sort:"1", Set:"THS", Number:"155", Image:"/Images/THS/155.jpg"},
{Name:"Defend the Hearth", Cost:"2", Color:["G"], Rarity:"C", Type:["I"], Rating:"1", Sort:"1", Set:"THS", Number:"156", Image:"/Images/THS/156.jpg"},
{Name:"Fade into Antiquity", Cost:"3", Color:["G"], Rarity:"C", Type:["S"], Rating:"3", Sort:"1", Set:"THS", Number:"157", Image:"/Images/THS/157.jpg"},
{Name:"Feral Invocation", Cost:"3", Color:["G"], Rarity:"C", Type:["E"], Rating:"5", Sort:"1", Set:"THS", Number:"158", Image:"/Images/THS/158.jpg"},
{Name:"Hunt the Hunter", Cost:"1", Color:["G"], Rarity:"U", Type:["S"], Rating:"1", Sort:"1", Set:"THS", Number:"159", Image:"/Images/THS/159.jpg"},
{Name:"Karametra's Acolyte", Cost:"4", Color:["G"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"THS", Number:"160", Image:"/Images/THS/160.jpg"},
{Name:"Leafcrown Dryad", Cost:"2", Color:["G"], Rarity:"C", Type:["E","C"], Rating:"6", Sort:"1", Set:"THS", Number:"161", Image:"/Images/THS/161.jpg"},
{Name:"Mistcutter Hydra", Cost:"1", Color:["G"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"THS", Number:"162", Image:"/Images/THS/162.jpg"},
{Name:"Nemesis of Mortals", Cost:"6", Color:["G"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"THS", Number:"163", Image:"/Images/THS/163.jpg"},
{Name:"Nessian Asp", Cost:"5", Color:["G"], Rarity:"C", Type:["C"], Rating:"7", Sort:"1", Set:"THS", Number:"164", Image:"/Images/THS/164.jpg"},
{Name:"Nessian Courser", Cost:"3", Color:["G"], Rarity:"C", Type:["C"], Rating:"6", Sort:"1", Set:"THS", Number:"165", Image:"/Images/THS/165.jpg"},
{Name:"Nylea, God of the Hunt", Cost:"4", Color:["G"], Rarity:"M", Type:["E","C"], Rating:"8", Sort:"1", Set:"THS", Number:"166", Image:"/Images/THS/166.jpg"},
{Name:"Nylea's Disciple", Cost:"4", Color:["G"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"THS", Number:"167", Image:"/Images/THS/167.jpg"},
{Name:"Nylea's Emissary", Cost:"4", Color:["G"], Rarity:"U", Type:["E","C"], Rating:"7", Sort:"1", Set:"THS", Number:"168", Image:"/Images/THS/168.jpg"},
{Name:"Nylea's Presence", Cost:"2", Color:["G"], Rarity:"C", Type:["E"], Rating:"3", Sort:"1", Set:"THS", Number:"169", Image:"/Images/THS/169.jpg"},
{Name:"Ordeal of Nylea", Cost:"2", Color:["G"], Rarity:"U", Type:["E"], Rating:"2", Sort:"1", Set:"THS", Number:"170", Image:"/Images/THS/170.jpg"},
{Name:"Pheres-Band Centaurs", Cost:"5", Color:["G"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"THS", Number:"171", Image:"/Images/THS/171.jpg"},
{Name:"Polukranos, World Eater", Cost:"4", Color:["G"], Rarity:"M", Type:["C"], Rating:"9", Sort:"1", Set:"THS", Number:"172", Image:"/Images/THS/172.jpg"},
{Name:"Reverent Hunter", Cost:"3", Color:["G"], Rarity:"R", Type:["C"], Rating:"6", Sort:"1", Set:"THS", Number:"173", Image:"/Images/THS/173.jpg"},
{Name:"Satyr Hedonist", Cost:"2", Color:["G"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"THS", Number:"174", Image:"/Images/THS/174.jpg"},
{Name:"Satyr Piper", Cost:"3", Color:["G"], Rarity:"U", Type:["C"], Rating:"3", Sort:"1", Set:"THS", Number:"175", Image:"/Images/THS/175.jpg"},
{Name:"Savage Surge", Cost:"2", Color:["G"], Rarity:"C", Type:["I"], Rating:"5", Sort:"1", Set:"THS", Number:"176", Image:"/Images/THS/176.jpg"},
{Name:"Sedge Scorpion", Cost:"1", Color:["G"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"THS", Number:"177", Image:"/Images/THS/177.jpg"},
{Name:"Shredding Winds", Cost:"3", Color:["G"], Rarity:"C", Type:["I"], Rating:"1", Sort:"1", Set:"THS", Number:"178", Image:"/Images/THS/178.jpg"},
{Name:"Staunch-Hearted Warrior", Cost:"4", Color:["G"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"THS", Number:"179", Image:"/Images/THS/179.jpg"},
{Name:"Sylvan Caryatid", Cost:"2", Color:["G"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"THS", Number:"180", Image:"/Images/THS/180.jpg"},
{Name:"Time to Feed", Cost:"3", Color:["G"], Rarity:"C", Type:["S"], Rating:"6", Sort:"1", Set:"THS", Number:"181", Image:"/Images/THS/181.jpg"},
{Name:"Voyaging Satyr", Cost:"2", Color:["G"], Rarity:"C", Type:["C"], Rating:"7", Sort:"1", Set:"THS", Number:"182", Image:"/Images/THS/182.jpg"},
{Name:"Vulpine Goliath", Cost:"6", Color:["G"], Rarity:"C", Type:["C"], Rating:"5", Sort:"1", Set:"THS", Number:"183", Image:"/Images/THS/183.jpg"},
{Name:"Warriors' Lesson", Cost:"1", Color:["G"], Rarity:"U", Type:["I"], Rating:"5", Sort:"1", Set:"THS", Number:"184", Image:"/Images/THS/184.jpg"},
{Name:"Akroan Hoplite", Cost:"2", Color:["W","R"], Rarity:"U", Type:["C"], Rating:"2", Sort:"1", Set:"THS", Number:"185", Image:"/Images/THS/185.jpg"},
{Name:"Anax and Cymede", Cost:"3", Color:["W","R"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"THS", Number:"186", Image:"/Images/THS/186.jpg"},
{Name:"Ashen Rider", Cost:"8", Color:["W","B"], Rarity:"M", Type:["C"], Rating:"4", Sort:"1", Set:"THS", Number:"187", Image:"/Images/THS/187.jpg"},
{Name:"Ashiok, Nightmare Weaver", Cost:"3", Color:["U","B"], Rarity:"M", Type:["P"], Rating:"8", Sort:"1", Set:"THS", Number:"188", Image:"/Images/THS/188.jpg"},
{Name:"Battlewise Hoplite", Cost:"2", Color:["W","U"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"THS", Number:"189", Image:"/Images/THS/189.jpg"},
{Name:"Chronicler of Heroes", Cost:"3", Color:["W","G"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"THS", Number:"190", Image:"/Images/THS/190.jpg"},
{Name:"Daxos of Meletis", Cost:"3", Color:["W","U"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"THS", Number:"191", Image:"/Images/THS/191.jpg"},
{Name:"Destructive Revelry", Cost:"2", Color:["R","G"], Rarity:"U", Type:["I"], Rating:"5", Sort:"1", Set:"THS", Number:"192", Image:"/Images/THS/192.jpg"},
{Name:"Fleecemane Lion", Cost:"2", Color:["W","G"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"THS", Number:"193", Image:"/Images/THS/193.jpg"},
{Name:"Horizon Chimera", Cost:"4", Color:["U","G"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"THS", Number:"194", Image:"/Images/THS/194.jpg"},
{Name:"Kragma Warcaller", Cost:"5", Color:["B","R"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"THS", Number:"195", Image:"/Images/THS/195.jpg"},
{Name:"Medomai the Ageless", Cost:"6", Color:["W","U"], Rarity:"M", Type:["C"], Rating:"7", Sort:"1", Set:"THS", Number:"196", Image:"/Images/THS/196.jpg"},
{Name:"Pharika's Mender", Cost:"5", Color:["B","G"], Rarity:"U", Type:["C"], Rating:"7", Sort:"1", Set:"THS", Number:"197", Image:"/Images/THS/197.jpg"},
{Name:"Polis Crusher", Cost:"4", Color:["R","G"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"THS", Number:"198", Image:"/Images/THS/198.jpg"},
{Name:"Prophet of Kruphix", Cost:"5", Color:["U","G"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"THS", Number:"199", Image:"/Images/THS/199.jpg"},
{Name:"Psychic Intrusion", Cost:"5", Color:["U","B"], Rarity:"R", Type:["S"], Rating:"3", Sort:"1", Set:"THS", Number:"200", Image:"/Images/THS/200.jpg"},
{Name:"Reaper of the Wilds", Cost:"4", Color:["B","G"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"THS", Number:"201", Image:"/Images/THS/201.jpg"},
{Name:"Sentry of the Underworld", Cost:"5", Color:["W","B"], Rarity:"U", Type:["C"], Rating:"7", Sort:"1", Set:"THS", Number:"202", Image:"/Images/THS/202.jpg"},
{Name:"Shipwreck Singer", Cost:"2", Color:["U","B"], Rarity:"U", Type:["C"], Rating:"7", Sort:"1", Set:"THS", Number:"203", Image:"/Images/THS/203.jpg"},
{Name:"Spellheart Chimera", Cost:"3", Color:["U","R"], Rarity:"U", Type:["C"], Rating:"3", Sort:"1", Set:"THS", Number:"204", Image:"/Images/THS/204.jpg"},
{Name:"Steam Augury", Cost:"4", Color:["U","R"], Rarity:"R", Type:["I"], Rating:"5", Sort:"1", Set:"THS", Number:"205", Image:"/Images/THS/205.jpg"},
{Name:"Triad of Fates", Cost:"4", Color:["W","B"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"THS", Number:"206", Image:"/Images/THS/206.jpg"},
{Name:"Tymaret, the Murder King", Cost:"2", Color:["B","R"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"THS", Number:"207", Image:"/Images/THS/207.jpg"},
{Name:"Underworld Cerberus", Cost:"5", Color:["B","R"], Rarity:"M", Type:["C"], Rating:"8", Sort:"1", Set:"THS", Number:"208", Image:"/Images/THS/208.jpg"},
{Name:"Xenagos, the Reveler", Cost:"4", Color:["R","G"], Rarity:"M", Type:["P"], Rating:"8", Sort:"1", Set:"THS", Number:"209", Image:"/Images/THS/209.jpg"},
{Name:"Akroan Horse", Cost:"4", Color:["C"], Rarity:"R", Type:["A","C"], Rating:"5", Sort:"1", Set:"THS", Number:"210", Image:"/Images/THS/210.jpg"},
{Name:"Anvilwrought Raptor", Cost:"4", Color:["C"], Rarity:"U", Type:["A","C"], Rating:"3", Sort:"1", Set:"THS", Number:"211", Image:"/Images/THS/211.jpg"},
{Name:"Bronze Sable", Cost:"2", Color:["C"], Rarity:"C", Type:["A","C"], Rating:"3", Sort:"1", Set:"THS", Number:"212", Image:"/Images/THS/212.jpg"},
{Name:"Burnished Hart", Cost:"3", Color:["C"], Rarity:"U", Type:["A","C"], Rating:"6", Sort:"1", Set:"THS", Number:"213", Image:"/Images/THS/213.jpg"},
{Name:"Colossus of Akros", Cost:"8", Color:["C"], Rarity:"R", Type:["A","C"], Rating:"3", Sort:"1", Set:"THS", Number:"214", Image:"/Images/THS/214.jpg"},
{Name:"Flamecast Wheel", Cost:"1", Color:["C"], Rarity:"U", Type:["A"], Rating:"3", Sort:"1", Set:"THS", Number:"215", Image:"/Images/THS/215.jpg"},
{Name:"Fleetfeather Sandals", Cost:"2", Color:["C"], Rarity:"C", Type:["A"], Rating:"3", Sort:"1", Set:"THS", Number:"216", Image:"/Images/THS/216.jpg"},
{Name:"Guardians of Meletis", Cost:"3", Color:["C"], Rarity:"C", Type:["A","C"], Rating:"3", Sort:"1", Set:"THS", Number:"217", Image:"/Images/THS/217.jpg"},
{Name:"Opaline Unicorn", Cost:"3", Color:["C"], Rarity:"C", Type:["A","C"], Rating:"4", Sort:"1", Set:"THS", Number:"218", Image:"/Images/THS/218.jpg"},
{Name:"Prowler's Helm", Cost:"2", Color:["C"], Rarity:"U", Type:["A"], Rating:"2", Sort:"1", Set:"THS", Number:"219", Image:"/Images/THS/219.jpg"},
{Name:"Pyxis of Pandemonium", Cost:"1", Color:["C"], Rarity:"R", Type:["A"], Rating:"1", Sort:"1", Set:"THS", Number:"220", Image:"/Images/THS/220.jpg"},
{Name:"Traveler's Amulet", Cost:"1", Color:["C"], Rarity:"C", Type:["A"], Rating:"4", Sort:"1", Set:"THS", Number:"221", Image:"/Images/THS/221.jpg"},
{Name:"Witches' Eye", Cost:"1", Color:["C"], Rarity:"U", Type:["A"], Rating:"1", Sort:"1", Set:"THS", Number:"222", Image:"/Images/THS/222.jpg"},
{Name:"Nykthos, Shrine to Nyx", Cost:"0", Color:["C"], Rarity:"R", Type:["L"], Rating:"5", Sort:"1", Set:"THS", Number:"223", Image:"/Images/THS/223.jpg"},
{Name:"Temple of Abandon", Cost:"0", Color:["G","R"], Rarity:"R", Type:["L"], Rating:"6", Sort:"1", Set:"THS", Number:"224", Image:"/Images/THS/224.jpg"},
{Name:"Temple of Deceit", Cost:"0", Color:["U","B"], Rarity:"R", Type:["L"], Rating:"6", Sort:"1", Set:"THS", Number:"225", Image:"/Images/THS/225.jpg"},
{Name:"Temple of Mystery", Cost:"0", Color:["U","G"], Rarity:"R", Type:["L"], Rating:"6", Sort:"1", Set:"THS", Number:"226", Image:"/Images/THS/226.jpg"},
{Name:"Temple of Silence", Cost:"0", Color:["W","B"], Rarity:"R", Type:["L"], Rating:"6", Sort:"1", Set:"THS", Number:"227", Image:"/Images/THS/227.jpg"},
{Name:"Temple of Triumph", Cost:"0", Color:["W","R"], Rarity:"R", Type:["L"], Rating:"6", Sort:"1", Set:"THS", Number:"228", Image:"/Images/THS/228.jpg"},
{Name:"Unknown Shores", Cost:"0", Color:["C"], Rarity:"C", Type:["L"], Rating:"4", Sort:"1", Set:"THS", Number:"229", Image:"/Images/THS/229.jpg"},
];