var KTK = [
{Name:"Abzan Battle Priest", Cost:"3W", Color:["W"], Rarity:"U", Type:["C"], Rating:"7", Sort:"1", Set:"KTK", Number:"1", Image:"/Images/KTK/AbzanBattlePriest.jpg"},
{Name:"Abzan Falconer", Cost:"2W", Color:["W"], Rarity:"U", Type:["C"], Rating:"8", Sort:"1", Set:"KTK", Number:"2", Image:"/Images/KTK/AbzanFalconer.jpg"},
{Name:"Ainok Bond-Kin", Cost:"1W", Color:["W"], Rarity:"C", Type:["C"], Rating:"6", Sort:"1", Set:"KTK", Number:"3", Image:"/Images/KTK/AinokBond-Kin.jpg"},
{Name:"Alabaster Kirin", Cost:"3W", Color:["W"], Rarity:"C", Type:["C"], Rating:"5", Sort:"1", Set:"KTK", Number:"4", Image:"/Images/KTK/AlabasterKirin.jpg"},
{Name:"Brave the Sands", Cost:"1W", Color:["W"], Rarity:"U", Type:["E"], Rating:"3", Sort:"1", Set:"KTK", Number:"5", Image:"/Images/KTK/BravetheSands.jpg"},
{Name:"Dazzling Ramparts", Cost:"4W", Color:["W"], Rarity:"U", Type:["C"], Rating:"3", Sort:"1", Set:"KTK", Number:"6", Image:"/Images/KTK/DazzlingRamparts.jpg"},
{Name:"Defiant Strike", Cost:"0W", Color:["W"], Rarity:"C", Type:["I"], Rating:"5", Sort:"1", Set:"KTK", Number:"7", Image:"/Images/KTK/DefiantStrike.jpg"},
{Name:"End Hostilities", Cost:"5WW", Color:["W"], Rarity:"R", Type:["S"], Rating:"8", Sort:"1", Set:"KTK", Number:"8", Image:"/Images/KTK/EndHostilities.jpg"},
{Name:"Erase", Cost:"0W", Color:["W"], Rarity:"C", Type:["I"], Rating:"3", Sort:"1", Set:"KTK", Number:"9", Image:"/Images/KTK/Erase.jpg"},
{Name:"Feat of Resistance", Cost:"1W", Color:["W"], Rarity:"C", Type:["I"], Rating:"5", Sort:"1", Set:"KTK", Number:"10", Image:"/Images/KTK/FeatofResistance.jpg"},
{Name:"Firehoof Cavalry", Cost:"0W", Color:["W"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"KTK", Number:"11", Image:"/Images/KTK/FirehoofCavalry.jpg"},
{Name:"Herald of Anafenza", Cost:"0W", Color:["W"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"KTK", Number:"12", Image:"/Images/KTK/HeraldofAnafenza.jpg"},
{Name:"High Sentinels of Arashin", Cost:"3W", Color:["W"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"KTK", Number:"13", Image:"/Images/KTK/HighSentinelsofArashin.jpg"},
{Name:"Jeskai Student", Cost:"1W", Color:["W"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"KTK", Number:"14", Image:"/Images/KTK/JeskaiStudent.jpg"},
{Name:"Kill Shot", Cost:"2W", Color:["W"], Rarity:"C", Type:["I"], Rating:"6", Sort:"1", Set:"KTK", Number:"15", Image:"/Images/KTK/KillShot.jpg"},
{Name:"Mardu Hateblade", Cost:"0W", Color:["W"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"KTK", Number:"16", Image:"/Images/KTK/MarduHateblade.jpg"},
{Name:"Mardu Hordechief", Cost:"2W", Color:["W"], Rarity:"C", Type:["C"], Rating:"5", Sort:"1", Set:"KTK", Number:"17", Image:"/Images/KTK/MarduHordechief.jpg"},
{Name:"Master of Pearls", Cost:"1W", Color:["W"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"KTK", Number:"18", Image:"/Images/KTK/MasterofPearls.jpg"},
{Name:"Rush of Battle", Cost:"3W", Color:["W"], Rarity:"C", Type:["S"], Rating:"3", Sort:"1", Set:"KTK", Number:"19", Image:"/Images/KTK/RushofBattle.jpg"},
{Name:"Sage-Eye Harrier", Cost:"4W", Color:["W"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"KTK", Number:"20", Image:"/Images/KTK/Sage-EyeHarrier.jpg"},
{Name:"Salt Road Patrol", Cost:"3W", Color:["W"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"KTK", Number:"21", Image:"/Images/KTK/SaltRoadPatrol.jpg"},
{Name:"Seeker of the Way", Cost:"1W", Color:["W"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"KTK", Number:"22", Image:"/Images/KTK/SeekeroftheWay.jpg"},
{Name:"Siegecraft", Cost:"3W", Color:["W"], Rarity:"C", Type:["E"], Rating:"1", Sort:"1", Set:"KTK", Number:"23", Image:"/Images/KTK/Siegecraft.jpg"},
{Name:"Smite the Monstrous", Cost:"3W", Color:["W"], Rarity:"C", Type:["I"], Rating:"5", Sort:"1", Set:"KTK", Number:"24", Image:"/Images/KTK/SmitetheMonstrous.jpg"},
{Name:"Suspension Field", Cost:"1W", Color:["W"], Rarity:"U", Type:["E"], Rating:"8", Sort:"1", Set:"KTK", Number:"25", Image:"/Images/KTK/SuspensionField.jpg"},
{Name:"Take Up Arms", Cost:"4W", Color:["W"], Rarity:"U", Type:["I"], Rating:"5", Sort:"1", Set:"KTK", Number:"26", Image:"/Images/KTK/TakeUpArms.jpg"},
{Name:"Timely Hordemate", Cost:"3W", Color:["W"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"KTK", Number:"27", Image:"/Images/KTK/TimelyHordemate.jpg"},
{Name:"Venerable Lammasu", Cost:"6W", Color:["W"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"KTK", Number:"28", Image:"/Images/KTK/VenerableLammasu.jpg"},
{Name:"War Behemoth", Cost:"5W", Color:["W"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"KTK", Number:"29", Image:"/Images/KTK/WarBehemoth.jpg"},
{Name:"Watcher of the Roost", Cost:"2W", Color:["W"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"KTK", Number:"30", Image:"/Images/KTK/WatcheroftheRoost.jpg"},
{Name:"Wingmate Roc", Cost:"3WW", Color:["W"], Rarity:"M", Type:["C"], Rating:"9", Sort:"1", Set:"KTK", Number:"31", Image:"/Images/KTK/WingmateRoc.jpg"},
{Name:"Blinding Spray", Cost:"4U", Color:["U"], Rarity:"U", Type:["I"], Rating:"6", Sort:"1", Set:"KTK", Number:"32", Image:"/Images/KTK/BlindingSpray.jpg"},
{Name:"Cancel", Cost:"1UU", Color:["U"], Rarity:"C", Type:["I"], Rating:"4", Sort:"1", Set:"KTK", Number:"33", Image:"/Images/KTK/Cancel.jpg"},
{Name:"Clever Impersonator", Cost:"2UU", Color:["U"], Rarity:"M", Type:["C"], Rating:"8", Sort:"1", Set:"KTK", Number:"34", Image:"/Images/KTK/CleverImpersonator.jpg"},
{Name:"Crippling Chill", Cost:"2U", Color:["U"], Rarity:"C", Type:["I"], Rating:"5", Sort:"1", Set:"KTK", Number:"35", Image:"/Images/KTK/CripplingChill.jpg"},
{Name:"Dig Through Time", Cost:"6UU", Color:["U"], Rarity:"R", Type:["I"], Rating:"9", Sort:"1", Set:"KTK", Number:"36", Image:"/Images/KTK/DigThroughTime.jpg"},
{Name:"Disdainful Stroke", Cost:"1U", Color:["U"], Rarity:"C", Type:["I"], Rating:"5", Sort:"1", Set:"KTK", Number:"37", Image:"/Images/KTK/DisdainfulStroke.jpg"},
{Name:"Dragon's Eye Savants", Cost:"1U", Color:["U"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"KTK", Number:"38", Image:"/Images/KTK/DragonsEyeSavants.jpg"},
{Name:"Embodiment of Spring", Cost:"0U", Color:["U"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"KTK", Number:"39", Image:"/Images/KTK/EmbodimentofSpring.jpg"},
{Name:"Force Away", Cost:"1U", Color:["U"], Rarity:"C", Type:["I"], Rating:"3", Sort:"1", Set:"KTK", Number:"40", Image:"/Images/KTK/ForceAway.jpg"},
{Name:"Glacial Stalker", Cost:"5U", Color:["U"], Rarity:"C", Type:["C"], Rating:"5", Sort:"1", Set:"KTK", Number:"41", Image:"/Images/KTK/GlacialStalker.jpg"},
{Name:"Icy Blast", Cost:"0U", Color:["U"], Rarity:"R", Type:["I"], Rating:"8", Sort:"1", Set:"KTK", Number:"42", Image:"/Images/KTK/IcyBlast.jpg"},
{Name:"Jeskai Elder", Cost:"1U", Color:["U"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"KTK", Number:"43", Image:"/Images/KTK/JeskaiElder.jpg"},
{Name:"Jeskai Windscout", Cost:"2U", Color:["U"], Rarity:"C", Type:["C"], Rating:"6", Sort:"1", Set:"KTK", Number:"44", Image:"/Images/KTK/JeskaiWindscout.jpg"},
{Name:"Kheru Spellsnatcher", Cost:"4UU", Color:["U"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"KTK", Number:"45", Image:"/Images/KTK/KheruSpellsnatcher.jpg"},
{Name:"Mistfire Weaver", Cost:"3U", Color:["U"], Rarity:"U", Type:["C"], Rating:"8", Sort:"1", Set:"KTK", Number:"46", Image:"/Images/KTK/MistfireWeaver.jpg"},
{Name:"Monastery Flock", Cost:"2U", Color:["U"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"KTK", Number:"47", Image:"/Images/KTK/MonasteryFlock.jpg"},
{Name:"Mystic of the Hidden Way", Cost:"4U", Color:["U"], Rarity:"C", Type:["C"], Rating:"6", Sort:"1", Set:"KTK", Number:"48", Image:"/Images/KTK/MysticoftheHiddenWay.jpg"},
{Name:"Pearl Lake Ancient", Cost:"5UU", Color:["U"], Rarity:"M", Type:["C"], Rating:"8", Sort:"1", Set:"KTK", Number:"49", Image:"/Images/KTK/PearlLakeAncient.jpg"},
{Name:"Quiet Contemplation", Cost:"2U", Color:["U"], Rarity:"U", Type:["E"], Rating:"3", Sort:"1", Set:"KTK", Number:"50", Image:"/Images/KTK/QuietContemplation.jpg"},
{Name:"Riverwheel Aerialists", Cost:"5U", Color:["U"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"KTK", Number:"51", Image:"/Images/KTK/RiverwheelAerialists.jpg"},
{Name:"Scaldkin", Cost:"3U", Color:["U"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"KTK", Number:"52", Image:"/Images/KTK/Scaldkin.jpg"},
{Name:"Scion of Glaciers", Cost:"2UU", Color:["U"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"KTK", Number:"53", Image:"/Images/KTK/ScionofGlaciers.jpg"},
{Name:"Set Adrift", Cost:"5U", Color:["U"], Rarity:"U", Type:["S"], Rating:"5", Sort:"1", Set:"KTK", Number:"54", Image:"/Images/KTK/SetAdrift.jpg"},
{Name:"Singing Bell Strike", Cost:"1U", Color:["U"], Rarity:"C", Type:["E"], Rating:"6", Sort:"1", Set:"KTK", Number:"55", Image:"/Images/KTK/SingingBellStrike.jpg"},
{Name:"Stubborn Denial", Cost:"0U", Color:["U"], Rarity:"U", Type:["I"], Rating:"6", Sort:"1", Set:"KTK", Number:"56", Image:"/Images/KTK/StubbornDenial.jpg"},
{Name:"Taigam's Scheming", Cost:"1U", Color:["U"], Rarity:"C", Type:["S"], Rating:"6", Sort:"1", Set:"KTK", Number:"57", Image:"/Images/KTK/TaigamsScheming.jpg"},
{Name:"Thousand Winds", Cost:"4UU", Color:["U"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"KTK", Number:"58", Image:"/Images/KTK/ThousandWinds.jpg"},
{Name:"Treasure Cruise", Cost:"7U", Color:["U"], Rarity:"C", Type:["S"], Rating:"6", Sort:"1", Set:"KTK", Number:"59", Image:"/Images/KTK/TreasureCruise.jpg"},
{Name:"Waterwhirl", Cost:"4UU", Color:["U"], Rarity:"U", Type:["I"], Rating:"4", Sort:"1", Set:"KTK", Number:"60", Image:"/Images/KTK/Waterwhirl.jpg"},
{Name:"Weave Fate", Cost:"3U", Color:["U"], Rarity:"C", Type:["I"], Rating:"5", Sort:"1", Set:"KTK", Number:"61", Image:"/Images/KTK/WeaveFate.jpg"},
{Name:"Wetland Sambar", Cost:"1U", Color:["U"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"KTK", Number:"62", Image:"/Images/KTK/WetlandSambar.jpg"},
{Name:"Whirlwind Adept", Cost:"4U", Color:["U"], Rarity:"C", Type:["C"], Rating:"5", Sort:"1", Set:"KTK", Number:"63", Image:"/Images/KTK/WhirlwindAdept.jpg"},
{Name:"Bellowing Saddlebrute", Cost:"3B", Color:["B"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"KTK", Number:"64", Image:"/Images/KTK/BellowingSaddlebrute.jpg"},
{Name:"Bitter Revelation", Cost:"3B", Color:["B"], Rarity:"C", Type:["S"], Rating:"7", Sort:"1", Set:"KTK", Number:"65", Image:"/Images/KTK/BitterRevelation.jpg"},
{Name:"Bloodsoaked Champion", Cost:"0B", Color:["B"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"KTK", Number:"66", Image:"/Images/KTK/BloodsoakedChampion.jpg"},
{Name:"Dead Drop", Cost:"9B", Color:["B"], Rarity:"U", Type:["S"], Rating:"8", Sort:"1", Set:"KTK", Number:"67", Image:"/Images/KTK/DeadDrop.jpg"},
{Name:"Debilitating Injury", Cost:"1B", Color:["B"], Rarity:"C", Type:["E"], Rating:"3", Sort:"1", Set:"KTK", Number:"68", Image:"/Images/KTK/DebilitatingInjury.jpg"},
{Name:"Despise", Cost:"0B", Color:["B"], Rarity:"U", Type:["S"], Rating:"8", Sort:"1", Set:"KTK", Number:"69", Image:"/Images/KTK/Despise.jpg"},
{Name:"Disowned Ancestor", Cost:"0B", Color:["B"], Rarity:"C", Type:["C"], Rating:"6", Sort:"1", Set:"KTK", Number:"70", Image:"/Images/KTK/DisownedAncestor.jpg"},
{Name:"Dutiful Return", Cost:"3B", Color:["B"], Rarity:"C", Type:["S"], Rating:"4", Sort:"1", Set:"KTK", Number:"71", Image:"/Images/KTK/DutifulReturn.jpg"},
{Name:"Empty the Pits", Cost:"0BBBB", Color:["B"], Rarity:"M", Type:["I"], Rating:"9", Sort:"1", Set:"KTK", Number:"72", Image:"/Images/KTK/EmptythePits.jpg"},
{Name:"Grim Haruspex", Cost:"2B", Color:["B"], Rarity:"R", Type:["C"], Rating:"10", Sort:"1", Set:"KTK", Number:"73", Image:"/Images/KTK/GrimHaruspex.jpg"},
{Name:"Gurmag Swiftwing", Cost:"1B", Color:["B"], Rarity:"U", Type:["C"], Rating:"8", Sort:"1", Set:"KTK", Number:"74", Image:"/Images/KTK/GurmagSwiftwing.jpg"},
{Name:"Kheru Bloodsucker", Cost:"2B", Color:["B"], Rarity:"U", Type:["C"], Rating:"7", Sort:"1", Set:"KTK", Number:"75", Image:"/Images/KTK/KheruBloodsucker.jpg"},
{Name:"Kheru Dreadmaw", Cost:"4B", Color:["B"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"KTK", Number:"76", Image:"/Images/KTK/KheruDreadmaw.jpg"},
{Name:"Krumar Bond-Kin", Cost:"3BB", Color:["B"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"KTK", Number:"77", Image:"/Images/KTK/KrumarBond-Kin.jpg"},
{Name:"Mardu Skullhunter", Cost:"1B", Color:["B"], Rarity:"C", Type:["C"], Rating:"7", Sort:"1", Set:"KTK", Number:"78", Image:"/Images/KTK/MarduSkullhunter.jpg"},
{Name:"Mer-Ek Nightblade", Cost:"3B", Color:["B"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"KTK", Number:"79", Image:"/Images/KTK/Mer-EkNightblade.jpg"},
{Name:"Molting Snakeskin", Cost:"0B", Color:["B"], Rarity:"C", Type:["E"], Rating:"4", Sort:"1", Set:"KTK", Number:"80", Image:"/Images/KTK/MoltingSnakeskin.jpg"},
{Name:"Murderous Cut", Cost:"4B", Color:["B"], Rarity:"U", Type:["I"], Rating:"9", Sort:"1", Set:"KTK", Number:"81", Image:"/Images/KTK/MurderousCut.jpg"},
{Name:"Necropolis Fiend", Cost:"7BB", Color:["B"], Rarity:"R", Type:["C"], Rating:"9", Sort:"1", Set:"KTK", Number:"82", Image:"/Images/KTK/NecropolisFiend.jpg"},
{Name:"Raider's Spoils", Cost:"3B", Color:["B"], Rarity:"U", Type:["E"], Rating:"3", Sort:"1", Set:"KTK", Number:"83", Image:"/Images/KTK/RaidersSpoils.jpg"},
{Name:"Rakshasa's Secret", Cost:"2B", Color:["B"], Rarity:"C", Type:["S"], Rating:"4", Sort:"1", Set:"KTK", Number:"84", Image:"/Images/KTK/RakshasasSecret.jpg"},
{Name:"Retribution of the Ancients", Cost:"0B", Color:["B"], Rarity:"R", Type:["E"], Rating:"7", Sort:"1", Set:"KTK", Number:"85", Image:"/Images/KTK/RetributionoftheAncients.jpg"},
{Name:"Rite of the Serpent", Cost:"4BB", Color:["B"], Rarity:"C", Type:["S"], Rating:"4", Sort:"1", Set:"KTK", Number:"86", Image:"/Images/KTK/RiteoftheSerpent.jpg"},
{Name:"Rotting Mastodon", Cost:"4B", Color:["B"], Rarity:"C", Type:["C"], Rating:"2", Sort:"1", Set:"KTK", Number:"87", Image:"/Images/KTK/RottingMastodon.jpg"},
{Name:"Ruthless Ripper", Cost:"0B", Color:["B"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"KTK", Number:"88", Image:"/Images/KTK/RuthlessRipper.jpg"},
{Name:"Shambling Attendants", Cost:"7B", Color:["B"], Rarity:"C", Type:["C"], Rating:"5", Sort:"1", Set:"KTK", Number:"89", Image:"/Images/KTK/ShamblingAttendants.jpg"},
{Name:"Sidisi's Pet", Cost:"3B", Color:["B"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"KTK", Number:"90", Image:"/Images/KTK/SidisisPet.jpg"},
{Name:"Sultai Scavenger", Cost:"5B", Color:["B"], Rarity:"C", Type:["C"], Rating:"6", Sort:"1", Set:"KTK", Number:"91", Image:"/Images/KTK/SultaiScavenger.jpg"},
{Name:"Swarm of Bloodflies", Cost:"4B", Color:["B"], Rarity:"U", Type:["C"], Rating:"8", Sort:"1", Set:"KTK", Number:"92", Image:"/Images/KTK/SwarmofBloodflies.jpg"},
{Name:"Throttle", Cost:"4B", Color:["B"], Rarity:"C", Type:["I"], Rating:"5", Sort:"1", Set:"KTK", Number:"93", Image:"/Images/KTK/Throttle.jpg"},
{Name:"Unyielding Krumar", Cost:"3B", Color:["B"], Rarity:"C", Type:["C"], Rating:"5", Sort:"1", Set:"KTK", Number:"94", Image:"/Images/KTK/UnyieldingKrumar.jpg"},
{Name:"Act of Treason", Cost:"2R", Color:["R"], Rarity:"C", Type:["S"], Rating:"3", Sort:"1", Set:"KTK", Number:"95", Image:"/Images/KTK/ActofTreason.jpg"},
{Name:"Ainok Tracker", Cost:"5R", Color:["R"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"KTK", Number:"96", Image:"/Images/KTK/AinokTracker.jpg"},
{Name:"Arc Lightning", Cost:"2R", Color:["R"], Rarity:"U", Type:["S"], Rating:"8", Sort:"1", Set:"KTK", Number:"97", Image:"/Images/KTK/ArcLightning.jpg"},
{Name:"Arrow Storm", Cost:"3RR", Color:["R"], Rarity:"C", Type:["S"], Rating:"4", Sort:"1", Set:"KTK", Number:"98", Image:"/Images/KTK/ArrowStorm.jpg"},
{Name:"Ashcloud Phoenix", Cost:"2RR", Color:["R"], Rarity:"M", Type:["C"], Rating:"9", Sort:"1", Set:"KTK", Number:"99", Image:"/Images/KTK/AshcloudPhoenix.jpg"},
{Name:"Barrage of Boulders", Cost:"2R", Color:["R"], Rarity:"C", Type:["S"], Rating:"5", Sort:"1", Set:"KTK", Number:"100", Image:"/Images/KTK/BarrageofBoulders.jpg"},
{Name:"Bloodfire Expert", Cost:"2R", Color:["R"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"KTK", Number:"101", Image:"/Images/KTK/BloodfireExpert.jpg"},
{Name:"Bloodfire Mentor", Cost:"2R", Color:["R"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"KTK", Number:"102", Image:"/Images/KTK/BloodfireMentor.jpg"},
{Name:"Bring Low", Cost:"3R", Color:["R"], Rarity:"C", Type:["I"], Rating:"3", Sort:"1", Set:"KTK", Number:"103", Image:"/Images/KTK/BringLow.jpg"},
{Name:"Burn Away", Cost:"4R", Color:["R"], Rarity:"U", Type:["I"], Rating:"7", Sort:"1", Set:"KTK", Number:"104", Image:"/Images/KTK/BurnAway.jpg"},
{Name:"Canyon Lurkers", Cost:"4R", Color:["R"], Rarity:"C", Type:["C"], Rating:"6", Sort:"1", Set:"KTK", Number:"105", Image:"/Images/KTK/CanyonLurkers.jpg"},
{Name:"Crater's Claws", Cost:"0R", Color:["R"], Rarity:"R", Type:["S"], Rating:"8", Sort:"1", Set:"KTK", Number:"106", Image:"/Images/KTK/CratersClaws.jpg"},
{Name:"Dragon Grip", Cost:"2R", Color:["R"], Rarity:"U", Type:["E"], Rating:"6", Sort:"1", Set:"KTK", Number:"107", Image:"/Images/KTK/DragonGrip.jpg"},
{Name:"Dragon-Style Twins", Cost:"3RR", Color:["R"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"KTK", Number:"108", Image:"/Images/KTK/Dragon-StyleTwins.jpg"},
{Name:"Goblinslide", Cost:"2R", Color:["R"], Rarity:"U", Type:["E"], Rating:"3", Sort:"1", Set:"KTK", Number:"109", Image:"/Images/KTK/Goblinslide.jpg"},
{Name:"Horde Ambusher", Cost:"1R", Color:["R"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"KTK", Number:"110", Image:"/Images/KTK/HordeAmbusher.jpg"},
{Name:"Hordeling Outburst", Cost:"1RR", Color:["R"], Rarity:"U", Type:["S"], Rating:"3", Sort:"1", Set:"KTK", Number:"111", Image:"/Images/KTK/HordelingOutburst.jpg"},
{Name:"Howl of the Horde", Cost:"2R", Color:["R"], Rarity:"R", Type:["S"], Rating:"7", Sort:"1", Set:"KTK", Number:"112", Image:"/Images/KTK/HowloftheHorde.jpg"},
{Name:"Jeering Instigator", Cost:"1R", Color:["R"], Rarity:"R", Type:["C"], Rating:"9", Sort:"1", Set:"KTK", Number:"113", Image:"/Images/KTK/JeeringInstigator.jpg"},
{Name:"Leaping Master", Cost:"1R", Color:["R"], Rarity:"C", Type:["C"], Rating:"5", Sort:"1", Set:"KTK", Number:"114", Image:"/Images/KTK/LeapingMaster.jpg"},
{Name:"Mardu Blazebringer", Cost:"2R", Color:["R"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"KTK", Number:"115", Image:"/Images/KTK/MarduBlazebringer.jpg"},
{Name:"Mardu Heart-Piercer", Cost:"3R", Color:["R"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"KTK", Number:"116", Image:"/Images/KTK/MarduHeart-Piercer.jpg"},
{Name:"Mardu Warshrieker", Cost:"3R", Color:["R"], Rarity:"C", Type:["C"], Rating:"6", Sort:"1", Set:"KTK", Number:"117", Image:"/Images/KTK/MarduWarshrieker.jpg"},
{Name:"Monastery Swiftspear", Cost:"0R", Color:["R"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"KTK", Number:"118", Image:"/Images/KTK/MonasterySwiftspear.jpg"},
{Name:"Sarkhan, the Dragonspeaker", Cost:"3RR", Color:["R"], Rarity:"M", Type:["P"], Rating:"10", Sort:"1", Set:"KTK", Number:"119", Image:"/Images/KTK/Sarkhan--theDragonspeaker.jpg"},
{Name:"Shatter", Cost:"1R", Color:["R"], Rarity:"C", Type:["I"], Rating:"1", Sort:"1", Set:"KTK", Number:"120", Image:"/Images/KTK/Shatter.jpg"},
{Name:"Summit Prowler", Cost:"2RR", Color:["R"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"KTK", Number:"121", Image:"/Images/KTK/SummitProwler.jpg"},
{Name:"Swift Kick", Cost:"3R", Color:["R"], Rarity:"C", Type:["I"], Rating:"4", Sort:"1", Set:"KTK", Number:"122", Image:"/Images/KTK/SwiftKick.jpg"},
{Name:"Tormenting Voice", Cost:"1R", Color:["R"], Rarity:"C", Type:["S"], Rating:"5", Sort:"1", Set:"KTK", Number:"123", Image:"/Images/KTK/TormentingVoice.jpg"},
{Name:"Trumpet Blast", Cost:"2R", Color:["R"], Rarity:"C", Type:["I"], Rating:"3", Sort:"1", Set:"KTK", Number:"124", Image:"/Images/KTK/TrumpetBlast.jpg"},
{Name:"Valley Dasher", Cost:"1R", Color:["R"], Rarity:"C", Type:["C"], Rating:"5", Sort:"1", Set:"KTK", Number:"125", Image:"/Images/KTK/ValleyDasher.jpg"},
{Name:"War-Name Aspirant", Cost:"1R", Color:["R"], Rarity:"U", Type:["C"], Rating:"8", Sort:"1", Set:"KTK", Number:"126", Image:"/Images/KTK/War-NameAspirant.jpg"},
{Name:"Alpine Grizzly", Cost:"2G", Color:["G"], Rarity:"C", Type:["C"], Rating:"6", Sort:"1", Set:"KTK", Number:"127", Image:"/Images/KTK/AlpineGrizzly.jpg"},
{Name:"Archers' Parapet", Cost:"1G", Color:["G"], Rarity:"C", Type:["C"], Rating:"5", Sort:"1", Set:"KTK", Number:"128", Image:"/Images/KTK/ArchersParapet.jpg"},
{Name:"Awaken the Bear", Cost:"2G", Color:["G"], Rarity:"C", Type:["I"], Rating:"4", Sort:"1", Set:"KTK", Number:"129", Image:"/Images/KTK/AwakentheBear.jpg"},
{Name:"Become Immense", Cost:"5G", Color:["G"], Rarity:"U", Type:["I"], Rating:"5", Sort:"1", Set:"KTK", Number:"130", Image:"/Images/KTK/BecomeImmense.jpg"},
{Name:"Dragonscale Boon", Cost:"3G", Color:["G"], Rarity:"C", Type:["I"], Rating:"4", Sort:"1", Set:"KTK", Number:"131", Image:"/Images/KTK/DragonscaleBoon.jpg"},
{Name:"Feed the Clan", Cost:"1G", Color:["G"], Rarity:"C", Type:["I"], Rating:"1", Sort:"1", Set:"KTK", Number:"132", Image:"/Images/KTK/FeedtheClan.jpg"},
{Name:"Hardened Scales", Cost:"0G", Color:["G"], Rarity:"R", Type:["E"], Rating:"8", Sort:"1", Set:"KTK", Number:"133", Image:"/Images/KTK/HardenedScales.jpg"},
{Name:"Heir of the Wilds", Cost:"1G", Color:["G"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"KTK", Number:"134", Image:"/Images/KTK/HeiroftheWilds.jpg"},
{Name:"Highland Game", Cost:"1G", Color:["G"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"KTK", Number:"135", Image:"/Images/KTK/HighlandGame.jpg"},
{Name:"Hooded Hydra", Cost:"0GG", Color:["G"], Rarity:"M", Type:["C"], Rating:"9", Sort:"1", Set:"KTK", Number:"136", Image:"/Images/KTK/HoodedHydra.jpg"},
{Name:"Hooting Mandrills", Cost:"5G", Color:["G"], Rarity:"C", Type:["C"], Rating:"5", Sort:"1", Set:"KTK", Number:"137", Image:"/Images/KTK/HootingMandrills.jpg"},
{Name:"Incremental Growth", Cost:"3GG", Color:["G"], Rarity:"U", Type:["S"], Rating:"4", Sort:"1", Set:"KTK", Number:"138", Image:"/Images/KTK/IncrementalGrowth.jpg"},
{Name:"Kin-Tree Warden", Cost:"0G", Color:["G"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"KTK", Number:"139", Image:"/Images/KTK/Kin-TreeWarden.jpg"},
{Name:"Longshot Squad", Cost:"3G", Color:["G"], Rarity:"C", Type:["C"], Rating:"6", Sort:"1", Set:"KTK", Number:"140", Image:"/Images/KTK/LongshotSquad.jpg"},
{Name:"Meandering Towershell", Cost:"3GG", Color:["G"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"KTK", Number:"141", Image:"/Images/KTK/MeanderingTowershell.jpg"},
{Name:"Naturalize", Cost:"1G", Color:["G"], Rarity:"C", Type:["I"], Rating:"2", Sort:"1", Set:"KTK", Number:"142", Image:"/Images/KTK/Naturalize.jpg"},
{Name:"Pine Walker", Cost:"3GG", Color:["G"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"KTK", Number:"143", Image:"/Images/KTK/PineWalker.jpg"},
{Name:"Rattleclaw Mystic", Cost:"1G", Color:["G"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"KTK", Number:"144", Image:"/Images/KTK/RattleclawMystic.jpg"},
{Name:"Roar of Challenge", Cost:"2G", Color:["G"], Rarity:"U", Type:["S"], Rating:"5", Sort:"1", Set:"KTK", Number:"145", Image:"/Images/KTK/RoarofChallenge.jpg"},
{Name:"Sagu Archer", Cost:"4G", Color:["G"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"KTK", Number:"146", Image:"/Images/KTK/SaguArcher.jpg"},
{Name:"Savage Punch", Cost:"1G", Color:["G"], Rarity:"C", Type:["I"], Rating:"4", Sort:"1", Set:"KTK", Number:"147", Image:"/Images/KTK/SavagePunch.jpg"},
{Name:"Scout the Borders", Cost:"2G", Color:["G"], Rarity:"C", Type:["S"], Rating:"5", Sort:"1", Set:"KTK", Number:"148", Image:"/Images/KTK/ScouttheBorders.jpg"},
{Name:"See the Unwritten", Cost:"4GG", Color:["G"], Rarity:"M", Type:["S"], Rating:"8", Sort:"1", Set:"KTK", Number:"149", Image:"/Images/KTK/SeetheUnwritten.jpg"},
{Name:"Seek the Horizon", Cost:"3G", Color:["G"], Rarity:"U", Type:["S"], Rating:"4", Sort:"1", Set:"KTK", Number:"150", Image:"/Images/KTK/SeektheHorizon.jpg"},
{Name:"Smoke Teller", Cost:"1G", Color:["G"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"KTK", Number:"151", Image:"/Images/KTK/SmokeTeller.jpg"},
{Name:"Sultai Flayer", Cost:"3G", Color:["G"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"KTK", Number:"152", Image:"/Images/KTK/SultaiFlayer.jpg"},
{Name:"Temur Charger", Cost:"1G", Color:["G"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"KTK", Number:"153", Image:"/Images/KTK/TemurCharger.jpg"},
{Name:"Trail of Mystery", Cost:"1G", Color:["G"], Rarity:"R", Type:["E"], Rating:"8", Sort:"1", Set:"KTK", Number:"154", Image:"/Images/KTK/TrailofMystery.jpg"},
{Name:"Tusked Colossodon", Cost:"4GG", Color:["G"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"KTK", Number:"155", Image:"/Images/KTK/TuskedColossodon.jpg"},
{Name:"Tuskguard Captain", Cost:"2G", Color:["G"], Rarity:"U", Type:["C"], Rating:"7", Sort:"1", Set:"KTK", Number:"156", Image:"/Images/KTK/TuskguardCaptain.jpg"},
{Name:"Windstorm", Cost:"0G", Color:["G"], Rarity:"U", Type:["I"], Rating:"5", Sort:"1", Set:"KTK", Number:"157", Image:"/Images/KTK/Windstorm.jpg"},
{Name:"Woolly Loxodon", Cost:"5GG", Color:["G"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"KTK", Number:"158", Image:"/Images/KTK/WoollyLoxodon.jpg"},
{Name:"Abomination of Gudul", Cost:"3BGU", Color:["B","G","U"], Rarity:"C", Type:["C"], Rating:"5", Sort:"1", Set:"KTK", Number:"159", Image:"/Images/KTK/AbominationofGudul.jpg"},
{Name:"Abzan Ascendancy", Cost:"0WBG", Color:["W","B","G"], Rarity:"R", Type:["E"], Rating:"9", Sort:"1", Set:"KTK", Number:"160", Image:"/Images/KTK/AbzanAscendancy.jpg"},
{Name:"Abzan Charm", Cost:"0WBG", Color:["W","B","G"], Rarity:"U", Type:["I"], Rating:"8", Sort:"1", Set:"KTK", Number:"161", Image:"/Images/KTK/AbzanCharm.jpg"},
{Name:"Abzan Guide", Cost:"3WBG", Color:["W","B","G"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"KTK", Number:"162", Image:"/Images/KTK/AbzanGuide.jpg"},
{Name:"Anafenza, the Foremost", Cost:"0WBG", Color:["W","B","G"], Rarity:"M", Type:["C"], Rating:"9", Sort:"1", Set:"KTK", Number:"163", Image:"/Images/KTK/Anafenza--theForemost.jpg"},
{Name:"Ankle Shanker", Cost:"2RWB", Color:["R","W","B"], Rarity:"R", Type:["C"], Rating:"9", Sort:"1", Set:"KTK", Number:"164", Image:"/Images/KTK/AnkleShanker.jpg"},
{Name:"Armament Corps", Cost:"2WBG", Color:["W","B","G"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"KTK", Number:"165", Image:"/Images/KTK/ArmamentCorps.jpg"},
{Name:"Avalanche Tusker", Cost:"2GUR", Color:["G","U","R"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"KTK", Number:"166", Image:"/Images/KTK/AvalancheTusker.jpg"},
{Name:"Bear's Companion", Cost:"2GUR", Color:["G","U","R"], Rarity:"U", Type:["C"], Rating:"7", Sort:"1", Set:"KTK", Number:"167", Image:"/Images/KTK/BearsCompanion.jpg"},
{Name:"Butcher of the Horde", Cost:"1RWB", Color:["R","W","B"], Rarity:"R", Type:["C"], Rating:"9", Sort:"1", Set:"KTK", Number:"168", Image:"/Images/KTK/ButcheroftheHorde.jpg"},
{Name:"Chief of the Edge", Cost:"0WB", Color:["W","B"], Rarity:"U", Type:["C"], Rating:"8", Sort:"1", Set:"KTK", Number:"169", Image:"/Images/KTK/ChiefoftheEdge.jpg"},
{Name:"Chief of the Scale", Cost:"0WB", Color:["W","B"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"KTK", Number:"170", Image:"/Images/KTK/ChiefoftheScale.jpg"},
{Name:"Crackling Doom", Cost:"0RWB", Color:["R","W","B"], Rarity:"R", Type:["I"], Rating:"9", Sort:"1", Set:"KTK", Number:"171", Image:"/Images/KTK/CracklingDoom.jpg"},
{Name:"Death Frenzy", Cost:"3BG", Color:["B","G","U"], Rarity:"U", Type:["S"], Rating:"3", Sort:"1", Set:"KTK", Number:"172", Image:"/Images/KTK/DeathFrenzy.jpg"},
{Name:"Deflecting Palm", Cost:"0RW", Color:["R","W"], Rarity:"R", Type:["I"], Rating:"6", Sort:"1", Set:"KTK", Number:"173", Image:"/Images/KTK/DeflectingPalm.jpg"},
{Name:"Duneblast", Cost:"4WBG", Color:["W","B","G"], Rarity:"R", Type:["S"], Rating:"8", Sort:"1", Set:"KTK", Number:"174", Image:"/Images/KTK/Duneblast.jpg"},
{Name:"Efreet Weaponmaster", Cost:"3URW", Color:["U","R","W"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"KTK", Number:"175", Image:"/Images/KTK/EfreetWeaponmaster.jpg"},
{Name:"Flying Crane Technique", Cost:"3URW", Color:["U","R","W"], Rarity:"R", Type:["I"], Rating:"8", Sort:"1", Set:"KTK", Number:"176", Image:"/Images/KTK/FlyingCraneTechnique.jpg"},
{Name:"Highspire Mantis", Cost:"2RW", Color:["R","W"], Rarity:"U", Type:["C"], Rating:"7", Sort:"1", Set:"KTK", Number:"177", Image:"/Images/KTK/HighspireMantis.jpg"},
{Name:"Icefeather Aven", Cost:"0GU", Color:["G","U"], Rarity:"U", Type:["C"], Rating:"7", Sort:"1", Set:"KTK", Number:"178", Image:"/Images/KTK/IcefeatherAven.jpg"},
{Name:"Ivorytusk Fortress", Cost:"2WBG", Color:["W","B","G"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"KTK", Number:"179", Image:"/Images/KTK/IvorytuskFortress.jpg"},
{Name:"Jeskai Ascendancy", Cost:"0URW", Color:["U","R","W"], Rarity:"R", Type:["E"], Rating:"8", Sort:"1", Set:"KTK", Number:"180", Image:"/Images/KTK/JeskaiAscendancy.jpg"},
{Name:"Jeskai Charm", Cost:"0URW", Color:["U","R","W"], Rarity:"U", Type:["I"], Rating:"8", Sort:"1", Set:"KTK", Number:"181", Image:"/Images/KTK/JeskaiCharm.jpg"},
{Name:"Kheru Lich Lord", Cost:"3BGU", Color:["B","G","U"], Rarity:"R", Type:["C"], Rating:"9", Sort:"1", Set:"KTK", Number:"182", Image:"/Images/KTK/KheruLichLord.jpg"},
{Name:"Kin-Tree Invocation", Cost:"0BG", Color:["B","G"], Rarity:"U", Type:["S"], Rating:"6", Sort:"1", Set:"KTK", Number:"183", Image:"/Images/KTK/Kin-TreeInvocation.jpg"},
{Name:"Mantis Rider", Cost:"0URW", Color:["U","R","W"], Rarity:"R", Type:["C"], Rating:"9", Sort:"1", Set:"KTK", Number:"184", Image:"/Images/KTK/MantisRider.jpg"},
{Name:"Mardu Ascendancy", Cost:"0RWB", Color:["R","W","B"], Rarity:"R", Type:["E"], Rating:"9", Sort:"1", Set:"KTK", Number:"185", Image:"/Images/KTK/MarduAscendancy.jpg"},
{Name:"Mardu Charm", Cost:"0RWB", Color:["R","W","B"], Rarity:"U", Type:["I"], Rating:"8", Sort:"1", Set:"KTK", Number:"186", Image:"/Images/KTK/MarduCharm.jpg"},
{Name:"Mardu Roughrider", Cost:"2RWB", Color:["R","W","B"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"KTK", Number:"187", Image:"/Images/KTK/MarduRoughrider.jpg"},
{Name:"Master the Way", Cost:"3UR", Color:["U","R"], Rarity:"U", Type:["S"], Rating:"6", Sort:"1", Set:"KTK", Number:"188", Image:"/Images/KTK/MastertheWay.jpg"},
{Name:"Mindswipe", Cost:"0UR", Color:["U","R"], Rarity:"R", Type:["I"], Rating:"6", Sort:"1", Set:"KTK", Number:"189", Image:"/Images/KTK/Mindswipe.jpg"},
{Name:"Narset, Enlightened Master", Cost:"3URW", Color:["U","R","W"], Rarity:"M", Type:["C"], Rating:"9", Sort:"1", Set:"KTK", Number:"190", Image:"/Images/KTK/Narset--EnlightenedMaster.jpg"},
{Name:"Ponyback Brigade", Cost:"3RWB", Color:["R","W","B"], Rarity:"C", Type:["C"], Rating:"5", Sort:"1", Set:"KTK", Number:"191", Image:"/Images/KTK/PonybackBrigade.jpg"},
{Name:"Rakshasa Deathdealer", Cost:"0BG", Color:["B","G"], Rarity:"R", Type:["C"], Rating:"9", Sort:"1", Set:"KTK", Number:"192", Image:"/Images/KTK/RakshasaDeathdealer.jpg"},
{Name:"Rakshasa Vizier", Cost:"2BGU", Color:["B","G","U"], Rarity:"R", Type:["C"], Rating:"8", Sort:"", Set:"KTK", Number:"193", Image:"/Images/KTK/RakshasaVizier.jpg"},
{Name:"Ride Down", Cost:"0RW", Color:["R","W"], Rarity:"U", Type:["I"], Rating:"7", Sort:"1", Set:"KTK", Number:"194", Image:"/Images/KTK/RideDown.jpg"},
{Name:"Sage of the Inward Eye", Cost:"2URW", Color:["U","R","W"], Rarity:"R", Type:["C"], Rating:"9", Sort:"1", Set:"KTK", Number:"195", Image:"/Images/KTK/SageoftheInwardEye.jpg"},
{Name:"Sagu Mauler", Cost:"4GU", Color:["G","U"], Rarity:"R", Type:["C"], Rating:"9", Sort:"1", Set:"KTK", Number:"196", Image:"/Images/KTK/SaguMauler.jpg"},
{Name:"Savage Knuckleblade", Cost:"0GUR", Color:["G","U","R"], Rarity:"R", Type:["C"], Rating:"10", Sort:"1", Set:"KTK", Number:"197", Image:"/Images/KTK/SavageKnuckleblade.jpg"},
{Name:"Secret Plans", Cost:"0GU", Color:["G","U"], Rarity:"U", Type:["E"], Rating:"4", Sort:"1", Set:"KTK", Number:"198", Image:"/Images/KTK/SecretPlans.jpg"},
{Name:"Sidisi, Brood Tyrant", Cost:"1BGU", Color:["B","G","U"], Rarity:"M", Type:["C"], Rating:"10", Sort:"1", Set:"KTK", Number:"199", Image:"/Images/KTK/Sidisi--BroodTyrant.jpg"},
{Name:"Siege Rhino", Cost:"1WBG", Color:["W","B","G"], Rarity:"R", Type:["C"], Rating:"8", Sort:"1", Set:"KTK", Number:"200", Image:"/Images/KTK/SiegeRhino.jpg"},
{Name:"Snowhorn Rider", Cost:"3GUR", Color:["G","U","R"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"KTK", Number:"201", Image:"/Images/KTK/SnowhornRider.jpg"},
{Name:"Sorin, Solemn Visitor", Cost:"2WB", Color:["W","B"], Rarity:"M", Type:["P"], Rating:"10", Sort:"1", Set:"KTK", Number:"202", Image:"/Images/KTK/Sorin--SolemnVisitor.jpg"},
{Name:"Sultai Ascendancy", Cost:"0GBU", Color:["G","B","U"], Rarity:"R", Type:["E"], Rating:"9", Sort:"1", Set:"KTK", Number:"203", Image:"/Images/KTK/SultaiAscendancy.jpg"},
{Name:"Sultai Charm", Cost:"0BGU", Color:["B","G","U"], Rarity:"U", Type:["I"], Rating:"8", Sort:"1", Set:"KTK", Number:"204", Image:"/Images/KTK/SultaiCharm.jpg"},
{Name:"Sultai Soothsayer", Cost:"2BGU", Color:["B","G","U"], Rarity:"U", Type:["C"], Rating:"7", Sort:"1", Set:"KTK", Number:"205", Image:"/Images/KTK/SultaiSoothsayer.jpg"},
{Name:"Surrak Dragonclaw", Cost:"3GUR", Color:["G","U","R"], Rarity:"M", Type:["C"], Rating:"10", Sort:"1", Set:"KTK", Number:"206", Image:"/Images/KTK/SurrakDragonclaw.jpg"},
{Name:"Temur Ascendancy", Cost:"0GUR", Color:["G","U","R"], Rarity:"R", Type:["E"], Rating:"7", Sort:"1", Set:"KTK", Number:"207", Image:"/Images/KTK/TemurAscendancy.jpg"},
{Name:"Temur Charm", Cost:"0GUR", Color:["G","U","R"], Rarity:"U", Type:["I"], Rating:"8", Sort:"1", Set:"KTK", Number:"208", Image:"/Images/KTK/TemurCharm.jpg"},
{Name:"Trap Essence", Cost:"0GUR", Color:["G","U","R"], Rarity:"R", Type:["I"], Rating:"7", Sort:"1", Set:"KTK", Number:"209", Image:"/Images/KTK/TrapEssence.jpg"},
{Name:"Utter End", Cost:"2WB", Color:["W","B"], Rarity:"R", Type:["I"], Rating:"9", Sort:"1", Set:"KTK", Number:"210", Image:"/Images/KTK/UtterEnd.jpg"},
{Name:"Villainous Wealth", Cost:"0BGU", Color:["B","G","U"], Rarity:"R", Type:["S"], Rating:"8", Sort:"1", Set:"KTK", Number:"211", Image:"/Images/KTK/VillainousWealth.jpg"},
{Name:"Warden of the Eye", Cost:"2URW", Color:["U","R","W"], Rarity:"U", Type:["C"], Rating:"5", Sort:"1", Set:"KTK", Number:"212", Image:"/Images/KTK/WardenoftheEye.jpg"},
{Name:"Winterflame", Cost:"1UR", Color:["U","R"], Rarity:"U", Type:["I"], Rating:"7", Sort:"1", Set:"KTK", Number:"213", Image:"/Images/KTK/Winterflame.jpg"},
{Name:"Zurgo Helmsmasher", Cost:"2RWB", Color:["R","W","B"], Rarity:"M", Type:["C"], Rating:"10", Sort:"1", Set:"KTK", Number:"214", Image:"/Images/KTK/ZurgoHelmsmasher.jpg"},
{Name:"Abzan Banner", Cost:"3", Color:["W","B","G"], Rarity:"C", Type:["A"], Rating:"5", Sort:"1", Set:"KTK", Number:"215", Image:"/Images/KTK/AbzanBanner.jpg"},
{Name:"Altar of the Brood", Cost:"1", Color:["C"], Rarity:"R", Type:["A"], Rating:"5", Sort:"1", Set:"KTK", Number:"216", Image:"/Images/KTK/AltaroftheBrood.jpg"},
{Name:"Briber's Purse", Cost:"0", Color:["C"], Rarity:"U", Type:["A"], Rating:"4", Sort:"1", Set:"KTK", Number:"217", Image:"/Images/KTK/BribersPurse.jpg"},
{Name:"Cranial Archive", Cost:"2", Color:["C"], Rarity:"U", Type:["A"], Rating:"4", Sort:"1", Set:"KTK", Number:"218", Image:"/Images/KTK/CranialArchive.jpg"},
{Name:"Dragon Throne of Tarkir", Cost:"4", Color:["C"], Rarity:"R", Type:["A"], Rating:"6", Sort:"1", Set:"KTK", Number:"219", Image:"/Images/KTK/DragonThroneofTarkir.jpg"},
{Name:"Ghostfire Blade", Cost:"1", Color:["C"], Rarity:"R", Type:["E"], Rating:"8", Sort:"1", Set:"KTK", Number:"220", Image:"/Images/KTK/GhostfireBlade.jpg"},
{Name:"Heart-Piercer Bow", Cost:"2", Color:["C"], Rarity:"U", Type:["A"], Rating:"4", Sort:"1", Set:"KTK", Number:"221", Image:"/Images/KTK/Heart-PiercerBow.jpg"},
{Name:"Jeskai Banner", Cost:"3", Color:["U","R","W"], Rarity:"C", Type:["A"], Rating:"5", Sort:"1", Set:"KTK", Number:"222", Image:"/Images/KTK/JeskaiBanner.jpg"},
{Name:"Lens of Clarity", Cost:"1", Color:["C"], Rarity:"C", Type:["A"], Rating:"2", Sort:"1", Set:"KTK", Number:"223", Image:"/Images/KTK/LensofClarity.jpg"},
{Name:"Mardu Banner", Cost:"3", Color:["R","W","B"], Rarity:"C", Type:["A"], Rating:"5", Sort:"1", Set:"KTK", Number:"224", Image:"/Images/KTK/MarduBanner.jpg"},
{Name:"Sultai Banner", Cost:"3", Color:["B","G","U"], Rarity:"C", Type:["A"], Rating:"5", Sort:"1", Set:"KTK", Number:"225", Image:"/Images/KTK/SultaiBanner.jpg"},
{Name:"Temur Banner", Cost:"3", Color:["G","U","R"], Rarity:"C", Type:["A"], Rating:"5", Sort:"1", Set:"KTK", Number:"226", Image:"/Images/KTK/TemurBanner.jpg"},
{Name:"Ugin's Nexus", Cost:"5", Color:["C"], Rarity:"M", Type:["A"], Rating:"6", Sort:"1", Set:"KTK", Number:"227", Image:"/Images/KTK/UginsNexus.jpg"},
{Name:"Witness of the Ages", Cost:"6", Color:["C"], Rarity:"U", Type:["C","A"], Rating:"5", Sort:"1", Set:"KTK", Number:"228", Image:"/Images/KTK/WitnessoftheAges.jpg"},
{Name:"Bloodfell Caves", Cost:"0", Color:["B","R"], Rarity:"C", Type:["L"], Rating:"7", Sort:"1", Set:"KTK", Number:"229", Image:"/Images/KTK/BloodfellCaves.jpg"},
{Name:"Bloodstained Mire", Cost:"0", Color:["B","R"], Rarity:"R", Type:["L"], Rating:"9", Sort:"1", Set:"KTK", Number:"230", Image:"/Images/KTK/BloodstainedMire.jpg"},
{Name:"Blossoming Sands", Cost:"0", Color:["G","W"], Rarity:"C", Type:["L"], Rating:"7", Sort:"1", Set:"KTK", Number:"231", Image:"/Images/KTK/BlossomingSands.jpg"},
{Name:"Dismal Backwater", Cost:"0", Color:["B","U"], Rarity:"C", Type:["L"], Rating:"7", Sort:"1", Set:"KTK", Number:"232", Image:"/Images/KTK/DismalBackwater.jpg"},
{Name:"Flooded Strand", Cost:"0", Color:["W","U"], Rarity:"R", Type:["L"], Rating:"9", Sort:"1", Set:"KTK", Number:"233", Image:"/Images/KTK/FloodedStrand.jpg"},
{Name:"Frontier Bivouac", Cost:"0", Color:["G","U","R"], Rarity:"U", Type:["L"], Rating:"8", Sort:"1", Set:"KTK", Number:"234", Image:"/Images/KTK/FrontierBivouac.jpg"},
{Name:"Jungle Hollow", Cost:"0", Color:["B","G"], Rarity:"C", Type:["L"], Rating:"7", Sort:"1", Set:"KTK", Number:"235", Image:"/Images/KTK/JungleHollow.jpg"},
{Name:"Mystic Monastery", Cost:"0", Color:["U","R","W"], Rarity:"U", Type:["L"], Rating:"8", Sort:"1", Set:"KTK", Number:"236", Image:"/Images/KTK/MysticMonastery.jpg"},
{Name:"Nomad Outpost", Cost:"0", Color:["R","W","B"], Rarity:"U", Type:["L"], Rating:"8", Sort:"1", Set:"KTK", Number:"237", Image:"/Images/KTK/NomadOutpost.jpg"},
{Name:"Opulent Palace", Cost:"0", Color:["B","G","U"], Rarity:"U", Type:["L"], Rating:"8", Sort:"1", Set:"KTK", Number:"238", Image:"/Images/KTK/OpulentPalace.jpg"},
{Name:"Polluted Delta", Cost:"0", Color:["B","U"], Rarity:"R", Type:["L"], Rating:"9", Sort:"1", Set:"KTK", Number:"239", Image:"/Images/KTK/PollutedDelta.jpg"},
{Name:"Rugged Highlands", Cost:"0", Color:["R","G"], Rarity:"C", Type:["L"], Rating:"7", Sort:"1", Set:"KTK", Number:"240", Image:"/Images/KTK/RuggedHighlands.jpg"},
{Name:"Sandsteppe Citadel", Cost:"0", Color:["W","B","G"], Rarity:"U", Type:["L"], Rating:"8", Sort:"1", Set:"KTK", Number:"241", Image:"/Images/KTK/SandsteppeCitadel.jpg"},
{Name:"Scoured Barrens", Cost:"0", Color:["B","W"], Rarity:"C", Type:["L"], Rating:"7", Sort:"1", Set:"KTK", Number:"242", Image:"/Images/KTK/ScouredBarrens.jpg"},
{Name:"Swiftwater Cliffs", Cost:"0", Color:["R","U"], Rarity:"C", Type:["L"], Rating:"7", Sort:"1", Set:"KTK", Number:"243", Image:"/Images/KTK/SwiftwaterCliffs.jpg"},
{Name:"Thornwood Falls", Cost:"0", Color:["G","U"], Rarity:"C", Type:["L"], Rating:"7", Sort:"1", Set:"KTK", Number:"244", Image:"/Images/KTK/ThornwoodFalls.jpg"},
{Name:"Tomb of the Spirit Dragon", Cost:"0", Color:["C"], Rarity:"U", Type:["L"], Rating:"1", Sort:"1", Set:"KTK", Number:"245", Image:"/Images/KTK/TomboftheSpiritDragon.jpg"},
{Name:"Tranquil Cove", Cost:"0", Color:["W","U"], Rarity:"C", Type:["L"], Rating:"7", Sort:"1", Set:"KTK", Number:"246", Image:"/Images/KTK/TranquilCove.jpg"},
{Name:"Wind-Scarred Crag", Cost:"0", Color:["R","W"], Rarity:"C", Type:["L"], Rating:"7", Sort:"1", Set:"KTK", Number:"247", Image:"/Images/KTK/Wind-ScarredCrag.jpg"},
{Name:"Windswept Heath", Cost:"0", Color:["W","G"], Rarity:"R", Type:["L"], Rating:"9", Sort:"1", Set:"KTK", Number:"248", Image:"/Images/KTK/WindsweptHeath.jpg"},
{Name:"Wooded Foothills", Cost:"0", Color:["R","G"], Rarity:"R", Type:["L"], Rating:"9", Sort:"1", Set:"KTK", Number:"249", Image:"/Images/KTK/WoodedFoothills.jpg"},
];