var BNG = [
{Name:"Acolyte's Reward", Cost:"2", Color:["W"], Rarity:"U", Type:["I"], Rating:"7", Sort:"1", Set:"BNG", Number:"1", Image:"/Images/BNG/1.jpg"},
{Name:"Akroan Phalanx", Cost:"4", Color:["W"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"BNG", Number:"2", Image:"/Images/BNG/2.jpg"},
{Name:"Akroan Skyguard", Cost:"2", Color:["W"], Rarity:"C", Type:["C"], Rating:"5", Sort:"1", Set:"BNG", Number:"3", Image:"/Images/BNG/3.jpg"},
{Name:"Archetype of Courage ", Cost:"3", Color:["W"], Rarity:"U", Type:["C","E"], Rating:"6", Sort:"1", Set:"BNG", Number:"4", Image:"/Images/BNG/4.jpg"},
{Name:"Brimaz, King of Oreskos", Cost:"3", Color:["W"], Rarity:"M", Type:["C"], Rating:"8", Sort:"1", Set:"BNG", Number:"5", Image:"/Images/BNG/5.jpg"},
{Name:"Dawn to Dusk", Cost:"4", Color:["W"], Rarity:"U", Type:["S"], Rating:"3", Sort:"1", Set:"BNG", Number:"6", Image:"/Images/BNG/6.jpg"},
{Name:"Eidolon of Countless Battles", Cost:"3", Color:["W"], Rarity:"R", Type:["C","E"], Rating:"8", Sort:"1", Set:"BNG", Number:"7", Image:"/Images/BNG/7.jpg"},
{Name:"Elite Skirmisher", Cost:"3", Color:["W"], Rarity:"C", Type:["C"], Rating:"5", Sort:"1", Set:"BNG", Number:"8", Image:"/Images/BNG/8.jpg"},
{Name:"Ephara's Radiance", Cost:"1", Color:["W"], Rarity:"C", Type:["E"], Rating:"3", Sort:"1", Set:"BNG", Number:"9", Image:"/Images/BNG/9.jpg"},
{Name:"Excoriate", Cost:"4", Color:["W"], Rarity:"C", Type:["S"], Rating:"6", Sort:"1", Set:"BNG", Number:"10", Image:"/Images/BNG/10.jpg"},
{Name:"Fated Retribution", Cost:"7", Color:["W"], Rarity:"R", Type:["I"], Rating:"7", Sort:"1", Set:"BNG", Number:"11", Image:"/Images/BNG/11.jpg"},
{Name:"Ghostblade Eidolon", Cost:"3", Color:["W"], Rarity:"U", Type:["C","E"], Rating:"7", Sort:"1", Set:"BNG", Number:"12", Image:"/Images/BNG/12.jpg"},
{Name:"Glimpse the Sun God", Cost:"1", Color:["W"], Rarity:"U", Type:["I"], Rating:"5", Sort:"1", Set:"BNG", Number:"13", Image:"/Images/BNG/13.jpg"},
{Name:"God-Favored General ", Cost:"2", Color:["W"], Rarity:"U", Type:["C"], Rating:"3", Sort:"1", Set:"BNG", Number:"14", Image:"/Images/BNG/14.jpg"},
{Name:"Great Hart", Cost:"4", Color:["W"], Rarity:"C", Type:["C"], Rating:"2", Sort:"1", Set:"BNG", Number:"15", Image:"/Images/BNG/15.jpg"},
{Name:"Griffin Dreamfinder", Cost:"5", Color:["W"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"BNG", Number:"16", Image:"/Images/BNG/16.jpg"},
{Name:"Hero of Iroas", Cost:"2", Color:["W"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"BNG", Number:"17", Image:"/Images/BNG/17.jpg"},
{Name:"Hold at Bay", Cost:"", Color:["W"], Rarity:"C", Type:["C"], Rating:"2", Sort:"1", Set:"BNG", Number:"18", Image:"/Images/BNG/18.jpg"},
{Name:"Loyal Pegasus", Cost:"1", Color:["W"], Rarity:"C", Type:["C"], Rating:"3", Sort:"1", Set:"BNG", Number:"19", Image:"/Images/BNG/19.jpg"},
{Name:"Mortal's Ardor", Cost:"1", Color:["W"], Rarity:"C", Type:["I"], Rating:"5", Sort:"1", Set:"BNG", Number:"20", Image:"/Images/BNG/20.jpg"},
{Name:"Nyxborn Shieldmate", Cost:"1", Color:["W"], Rarity:"C", Type:["C","E"], Rating:"6", Sort:"1", Set:"BNG", Number:"21", Image:"/Images/BNG/21.jpg"},
{Name:"Oreskos Sun Guide", Cost:"2", Color:["W"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"BNG", Number:"22", Image:"/Images/BNG/22.jpg"},
{Name:"Ornitharch", Cost:"5", Color:["W"], Rarity:"U", Type:["C"], Rating:"8", Sort:"1", Set:"BNG", Number:"23", Image:"/Images/BNG/23.jpg"},
{Name:"Plea for Guidance", Cost:"6", Color:["W"], Rarity:"R", Type:["S"], Rating:"2", Sort:"1", Set:"BNG", Number:"24", Image:"/Images/BNG/24.jpg"},
{Name:"Revoke Existence", Cost:"2", Color:["W"], Rarity:"C", Type:["S"], Rating:"3", Sort:"1", Set:"BNG", Number:"25", Image:"/Images/BNG/25.jpg"},
{Name:"Silent Sentinel", Cost:"7", Color:["W"], Rarity:"R", Type:["C"], Rating:"7", Sort:"1", Set:"BNG", Number:"26", Image:"/Images/BNG/26.jpg"},
{Name:"Spirit of the Labyrinth", Cost:"2", Color:["W"], Rarity:"R", Type:["C","E"], Rating:"6", Sort:"1", Set:"BNG", Number:"27", Image:"/Images/BNG/27.jpg"},
{Name:"Sunbond", Cost:"4", Color:["W"], Rarity:"U", Type:["E"], Rating:"2", Sort:"1", Set:"BNG", Number:"28", Image:"/Images/BNG/28.jpg"},
{Name:"Vanguard of Brimaz", Cost:"2", Color:["W"], Rarity:"U", Type:["C"], Rating:"6", Sort:"1", Set:"BNG", Number:"29", Image:"/Images/BNG/29.jpg"},
{Name:"Aerie Worshippers", Cost:"4", Color:["U"], Rarity:"U", Type:["C"], Rating:"7", Sort:"2", Set:"BNG", Number:"30", Image:"/Images/BNG/30.jpg"},
{Name:"Arbiter of the Ideal", Cost:"6", Color:["U"], Rarity:"R", Type:["C"], Rating:"8", Sort:"2", Set:"BNG", Number:"31", Image:"/Images/BNG/31.jpg"},
{Name:"Archetype of Imagination", Cost:"6", Color:["U"], Rarity:"U", Type:["C","E"], Rating:"8", Sort:"2", Set:"BNG", Number:"32", Image:"/Images/BNG/32.jpg"},
{Name:"Chrous of the Tides", Cost:"4", Color:["U"], Rarity:"C", Type:["C"], Rating:"6", Sort:"2", Set:"BNG", Number:"33", Image:"/Images/BNG/33.jpg"},
{Name:"Crypsis", Cost:"2", Color:["U"], Rarity:"C", Type:["I"], Rating:"4", Sort:"2", Set:"BNG", Number:"34", Image:"/Images/BNG/34.jpg"},
{Name:"Deepwater Hypnotist", Cost:"2", Color:["U"], Rarity:"C", Type:["C"], Rating:"4", Sort:"2", Set:"BNG", Number:"35", Image:"/Images/BNG/35.jpg"},
{Name:"Divination", Cost:"3", Color:["U"], Rarity:"C", Type:["S"], Rating:"6", Sort:"2", Set:"BNG", Number:"36", Image:"/Images/BNG/36.jpg"},
{Name:"Eternity Snare", Cost:"6", Color:["U"], Rarity:"U", Type:["E"], Rating:"4", Sort:"2", Set:"BNG", Number:"37", Image:"/Images/BNG/37.jpg"},
{Name:"Evanescent Intellect ", Cost:"1", Color:["U"], Rarity:"C", Type:["E"], Rating:"3", Sort:"2", Set:"BNG", Number:"38", Image:"/Images/BNG/38.jpg"},
{Name:"Fated Infatuation", Cost:"3", Color:["U"], Rarity:"R", Type:["I"], Rating:"4", Sort:"2", Set:"BNG", Number:"39", Image:"/Images/BNG/39.jpg"},
{Name:"Flitterstep Eidolon ", Cost:"2", Color:["U"], Rarity:"U", Type:["C","E"], Rating:"6", Sort:"2", Set:"BNG", Number:"40", Image:"/Images/BNG/40.jpg"},
{Name:"Floodtide Serpent", Cost:"5", Color:["U"], Rarity:"C", Type:["C"], Rating:"4", Sort:"2", Set:"BNG", Number:"41", Image:"/Images/BNG/41.jpg"},
{Name:"Kraken of the Straits", Cost:"7", Color:["U"], Rarity:"U", Type:["C"], Rating:"5", Sort:"2", Set:"BNG", Number:"42", Image:"/Images/BNG/42.jpg"},
{Name:"Meletis Astronomer", Cost:"2", Color:["U"], Rarity:"U", Type:["C"], Rating:"4", Sort:"2", Set:"BNG", Number:"43", Image:"/Images/BNG/43.jpg"},
{Name:"Mindreaver", Cost:"2", Color:["U"], Rarity:"R", Type:["C"], Rating:"3", Sort:"2", Set:"BNG", Number:"44", Image:"/Images/BNG/44.jpg"},
{Name:"Nullify", Cost:"2", Color:["U"], Rarity:"C", Type:["I"], Rating:"5", Sort:"2", Set:"BNG", Number:"45", Image:"/Images/BNG/45.jpg"},
{Name:"Nyxborn Triton", Cost:"3", Color:["U"], Rarity:"C", Type:["C","E"], Rating:"6", Sort:"2", Set:"BNG", Number:"46", Image:"/Images/BNG/46.jpg"},
{Name:"Oracle’s Insight ", Cost:"4", Color:["U"], Rarity:"U", Type:["E"], Rating:"7", Sort:"2", Set:"BNG", Number:"47", Image:"/Images/BNG/47.jpg"},
{Name:"Perplexing Chimera", Cost:"5", Color:["U"], Rarity:"R", Type:["C","E"], Rating:"6", Sort:"2", Set:"BNG", Number:"48", Image:"/Images/BNG/48.jpg"},
{Name:"Retraction Helix ", Cost:"1", Color:["U"], Rarity:"C", Type:["I"], Rating:"7", Sort:"2", Set:"BNG", Number:"49", Image:"/Images/BNG/49.jpg"},
{Name:"Siren of the Fanged Coast ", Cost:"5", Color:["U"], Rarity:"U", Type:["C"], Rating:"6", Sort:"2", Set:"BNG", Number:"50", Image:"/Images/BNG/50.jpg"},
{Name:"Sphinx's Disciple", Cost:"5", Color:["U"], Rarity:"C", Type:["C"], Rating:"6", Sort:"2", Set:"BNG", Number:"51", Image:"/Images/BNG/51.jpg"},
{Name:"Stratus Walk", Cost:"2", Color:["U"], Rarity:"C", Type:["E"], Rating:"7", Sort:"2", Set:"BNG", Number:"52", Image:"/Images/BNG/52.jpg"},
{Name:"Sudden Storm", Cost:"4", Color:["U"], Rarity:"C", Type:["I"], Rating:"4", Sort:"2", Set:"BNG", Number:"53", Image:"/Images/BNG/53.jpg"},
{Name:"Thassa's Rebuff", Cost:"2", Color:["U"], Rarity:"U", Type:["I"], Rating:"3", Sort:"2", Set:"BNG", Number:"54", Image:"/Images/BNG/54.jpg"},
{Name:"Tromokratis", Cost:"7", Color:["U"], Rarity:"R", Type:["C"], Rating:"8", Sort:"2", Set:"BNG", Number:"55", Image:"/Images/BNG/55.jpg"},
{Name:"Vortex Elemental", Cost:"1", Color:["U"], Rarity:"U", Type:["C"], Rating:"7", Sort:"2", Set:"BNG", Number:"56", Image:"/Images/BNG/56.jpg"},
{Name:"Whelming Wave", Cost:"4", Color:["U"], Rarity:"R", Type:["S"], Rating:"4", Sort:"2", Set:"BNG", Number:"57", Image:"/Images/BNG/57.jpg"},
{Name:"Archetype of Finality ", Cost:"6", Color:["B"], Rarity:"U", Type:["C","E"], Rating:"5", Sort:"3", Set:"BNG", Number:"58", Image:"/Images/BNG/58.jpg"},
{Name:"Ashiok's Adept", Cost:"3", Color:["B"], Rarity:"U", Type:["C"], Rating:"3", Sort:"3", Set:"BNG", Number:"59", Image:"/Images/BNG/59.jpg"},
{Name:"Asphyxiate", Cost:"3", Color:["B"], Rarity:"C", Type:["S"], Rating:"6", Sort:"3", Set:"BNG", Number:"60", Image:"/Images/BNG/60.jpg"},
{Name:"Bile Blight", Cost:"2", Color:["B"], Rarity:"U", Type:["I"], Rating:"7", Sort:"3", Set:"BNG", Number:"61", Image:"/Images/BNG/61.jpg"},
{Name:"Black Oak of Odunos", Cost:"3", Color:["B"], Rarity:"U", Type:["C"], Rating:"4", Sort:"3", Set:"BNG", Number:"62", Image:"/Images/BNG/62.jpg"},
{Name:"Champion of Stray Souls", Cost:"6", Color:["B"], Rarity:"M", Type:["C"], Rating:"3", Sort:"3", Set:"BNG", Number:"63", Image:"/Images/BNG/63.jpg"},
{Name:"Claim of Erebos", Cost:"2", Color:["B"], Rarity:"C", Type:["E"], Rating:"2", Sort:"3", Set:"BNG", Number:"64", Image:"/Images/BNG/64.jpg"},
{Name:"Drown in Sorrow", Cost:"3", Color:["B"], Rarity:"U", Type:["S"], Rating:"6", Sort:"3", Set:"BNG", Number:"65", Image:"/Images/BNG/65.jpg"},
{Name:"Eater of Hope", Cost:"7", Color:["B"], Rarity:"R", Type:["C"], Rating:"7", Sort:"3", Set:"BNG", Number:"66", Image:"/Images/BNG/66.jpg"},
{Name:"Eye Gouge", Cost:"1", Color:["B"], Rarity:"C", Type:["I"], Rating:"3", Sort:"3", Set:"BNG", Number:"67", Image:"/Images/BNG/67.jpg"},
{Name:"Fate Unraveler", Cost:"4", Color:["B"], Rarity:"R", Type:["C","E"], Rating:"7", Sort:"3", Set:"BNG", Number:"68", Image:"/Images/BNG/68.jpg"},
{Name:"Fated Return", Cost:"7", Color:["B"], Rarity:"R", Type:["I"], Rating:"3", Sort:"3", Set:"BNG", Number:"69", Image:"/Images/BNG/69.jpg"},
{Name:"Felhide Brawler", Cost:"2", Color:["B"], Rarity:"C", Type:["C"], Rating:"3", Sort:"3", Set:"BNG", Number:"70", Image:"/Images/BNG/70.jpg"},
{Name:"Forlorn Pseudamma", Cost:"4", Color:["B"], Rarity:"U", Type:["C"], Rating:"6", Sort:"3", Set:"BNG", Number:"71", Image:"/Images/BNG/71.jpg"},
{Name:"Forsaken Drifters ", Cost:"4", Color:["B"], Rarity:"C", Type:["C"], Rating:"4", Sort:"3", Set:"BNG", Number:"72", Image:"/Images/BNG/72.jpg"},
{Name:"Gild", Cost:"4", Color:["B"], Rarity:"R", Type:["S"], Rating:"7", Sort:"3", Set:"BNG", Number:"73", Image:"/Images/BNG/73.jpg"},
{Name:"Grisly Transformation ", Cost:"3", Color:["B"], Rarity:"C", Type:["E"], Rating:"5", Sort:"3", Set:"BNG", Number:"74", Image:"/Images/BNG/74.jpg"},
{Name:"Herald of Torment", Cost:"3", Color:["B"], Rarity:"R", Type:["C","E"], Rating:"8", Sort:"3", Set:"BNG", Number:"75", Image:"/Images/BNG/75.jpg"},
{Name:"Marshmist Titan", Cost:"7", Color:["B"], Rarity:"C", Type:["C"], Rating:"4", Sort:"3", Set:"BNG", Number:"76", Image:"/Images/BNG/76.jpg"},
{Name:"Necrobite", Cost:"3", Color:["B"], Rarity:"C", Type:["I"], Rating:"4", Sort:"3", Set:"BNG", Number:"77", Image:"/Images/BNG/77.jpg"},
{Name:"Nyxborn Eidolon", Cost:"2", Color:["B"], Rarity:"C", Type:["C","E"], Rating:"6", Sort:"3", Set:"BNG", Number:"78", Image:"/Images/BNG/78.jpg"},
{Name:"Odunos River Trawler", Cost:"3", Color:["B"], Rarity:"U", Type:["C"], Rating:"4", Sort:"3", Set:"BNG", Number:"79", Image:"/Images/BNG/79.jpg"},
{Name:"Pain Seer", Cost:"2", Color:["B"], Rarity:"R", Type:["C"], Rating:"6", Sort:"3", Set:"BNG", Number:"80", Image:"/Images/BNG/80.jpg"},
{Name:"Sanguimancy ", Cost:"5", Color:["B"], Rarity:"U", Type:["S"], Rating:"3", Sort:"3", Set:"BNG", Number:"81", Image:"/Images/BNG/81.jpg"},
{Name:"Servant of Tymaret", Cost:"3", Color:["B"], Rarity:"C", Type:["C"], Rating:"5", Sort:"3", Set:"BNG", Number:"82", Image:"/Images/BNG/82.jpg"},
{Name:"Shrike Harpy", Cost:"5", Color:["B"], Rarity:"U", Type:["C"], Rating:"6", Sort:"3", Set:"BNG", Number:"83", Image:"/Images/BNG/83.jpg"},
{Name:"Spiteful Returned", Cost:"2", Color:["B"], Rarity:"U", Type:["C","E"], Rating:"4", Sort:"3", Set:"BNG", Number:"84", Image:"/Images/BNG/84.jpg"},
{Name:"Warchanter of Mogis", Cost:"5", Color:["B"], Rarity:"C", Type:["C"], Rating:"3", Sort:"3", Set:"BNG", Number:"85", Image:"/Images/BNG/85.jpg"},
{Name:"Weight of the Underwold", Cost:"4", Color:["B"], Rarity:"C", Type:["E"], Rating:"5", Sort:"3", Set:"BNG", Number:"86", Image:"/Images/BNG/86.jpg"},
{Name:"Akroan Conscriptor", Cost:"5", Color:["R"], Rarity:"U", Type:["C"], Rating:"5", Sort:"4", Set:"BNG", Number:"87", Image:"/Images/BNG/87.jpg"},
{Name:"Archetype of Aggression ", Cost:"3", Color:["R"], Rarity:"U", Type:["C","E"], Rating:"5", Sort:"4", Set:"BNG", Number:"88", Image:"/Images/BNG/88.jpg"},
{Name:"Bolt of Keranos", Cost:"3", Color:["R"], Rarity:"C", Type:["S"], Rating:"6", Sort:"4", Set:"BNG", Number:"89", Image:"/Images/BNG/89.jpg"},
{Name:"Cyclops of One-Eyed Pass", Cost:"4", Color:["R"], Rarity:"C", Type:["C"], Rating:"4", Sort:"4", Set:"BNG", Number:"90", Image:"/Images/BNG/90.jpg"},
{Name:"Epiphany Storm", Cost:"1", Color:["R"], Rarity:"C", Type:["E"], Rating:"4", Sort:"4", Set:"BNG", Number:"91", Image:"/Images/BNG/91.jpg"},
{Name:"Everflame Eidolon", Cost:"2", Color:["R"], Rarity:"U", Type:["C","E"], Rating:"6", Sort:"4", Set:"BNG", Number:"92", Image:"/Images/BNG/92.jpg"},
{Name:"Fall of the Hammer", Cost:"2", Color:["R"], Rarity:"C", Type:["I"], Rating:"6", Sort:"4", Set:"BNG", Number:"93", Image:"/Images/BNG/93.jpg"},
{Name:"Fated Conflagration", Cost:"4", Color:["R"], Rarity:"R", Type:["I"], Rating:"6", Sort:"4", Set:"BNG", Number:"94", Image:"/Images/BNG/94.jpg"},
{Name:"Fearsome Temper", Cost:"3", Color:["R"], Rarity:"C", Type:["E"], Rating:"4", Sort:"4", Set:"BNG", Number:"95", Image:"/Images/BNG/95.jpg"},
{Name:"Felhide Spiritbinder", Cost:"4", Color:["R"], Rarity:"R", Type:["C"], Rating:"8", Sort:"4", Set:"BNG", Number:"96", Image:"/Images/BNG/96.jpg"},
{Name:"Flame-Wreathed Phoenix", Cost:"4", Color:["R"], Rarity:"M", Type:["C"], Rating:"9", Sort:"4", Set:"BNG", Number:"97", Image:"/Images/BNG/97.jpg"},
{Name:"Forgestoker Dragon", Cost:"6", Color:["R"], Rarity:"R", Type:["C"], Rating:"8", Sort:"4", Set:"BNG", Number:"98", Image:"/Images/BNG/98.jpg"},
{Name:"Impetuous Sunchaser", Cost:"2", Color:["R"], Rarity:"C", Type:["C"], Rating:"4", Sort:"4", Set:"BNG", Number:"99", Image:"/Images/BNG/99.jpg"},
{Name:"Kragma Butcher ", Cost:"3", Color:["R"], Rarity:"C", Type:["C"], Rating:"6", Sort:"4", Set:"BNG", Number:"100", Image:"/Images/BNG/100.jpg"},
{Name:"Lightning Volley", Cost:"4", Color:["R"], Rarity:"U", Type:["I"], Rating:"4", Sort:"4", Set:"BNG", Number:"101", Image:"/Images/BNG/101.jpg"},
{Name:"Nyxborn Rollicker", Cost:"1", Color:["R"], Rarity:"C", Type:["C","E"], Rating:"5", Sort:"4", Set:"BNG", Number:"102", Image:"/Images/BNG/102.jpg"},
{Name:"Oracle of Bones", Cost:"4", Color:["R"], Rarity:"R", Type:["C"], Rating:"7", Sort:"4", Set:"BNG", Number:"103", Image:"/Images/BNG/103.jpg"},
{Name:"Pharagax Giant", Cost:"5", Color:["R"], Rarity:"C", Type:["C"], Rating:"4", Sort:"4", Set:"BNG", Number:"104", Image:"/Images/BNG/104.jpg"},
{Name:"Pinnacle of Rage", Cost:"6", Color:["R"], Rarity:"U", Type:["S"], Rating:"7", Sort:"4", Set:"BNG", Number:"105", Image:"/Images/BNG/105.jpg"},
{Name:"Reckless Reveler ", Cost:"2", Color:["R"], Rarity:"C", Type:["C"], Rating:"4", Sort:"4", Set:"BNG", Number:"106", Image:"/Images/BNG/106.jpg"},
{Name:"Rise to the Challenge ", Cost:"2", Color:["R"], Rarity:"C", Type:["I"], Rating:"3", Sort:"4", Set:"BNG", Number:"107", Image:"/Images/BNG/107.jpg"},
{Name:"Satyr Firedancer", Cost:"2", Color:["R"], Rarity:"R", Type:["E","C"], Rating:"2", Sort:"4", Set:"BNG", Number:"108", Image:"/Images/BNG/108.jpg"},
{Name:"Satyr Nyx-Smith", Cost:"3", Color:["R"], Rarity:"U", Type:["C"], Rating:"5", Sort:"4", Set:"BNG", Number:"109", Image:"/Images/BNG/109.jpg"},
{Name:"Scouring Sands ", Cost:"2", Color:["R"], Rarity:"C", Type:["S"], Rating:"3", Sort:"4", Set:"BNG", Number:"110", Image:"/Images/BNG/110.jpg"},
{Name:"Searing Blood", Cost:"2", Color:["R"], Rarity:"U", Type:["I"], Rating:"7", Sort:"4", Set:"BNG", Number:"111", Image:"/Images/BNG/111.jpg"},
{Name:"Stormcaller of Keranos ", Cost:"3", Color:["R"], Rarity:"U", Type:["C"], Rating:"3", Sort:"4", Set:"BNG", Number:"112", Image:"/Images/BNG/112.jpg"},
{Name:"Thunder Brute", Cost:"6", Color:["R"], Rarity:"U", Type:["C"], Rating:"7", Sort:"4", Set:"BNG", Number:"113", Image:"/Images/BNG/113.jpg"},
{Name:"Thunderous Might", Cost:"2", Color:["R"], Rarity:"U", Type:["E"], Rating:"2", Sort:"4", Set:"BNG", Number:"114", Image:"/Images/BNG/114.jpg"},
{Name:"Whims of the Fates", Cost:"6", Color:["R"], Rarity:"R", Type:["S"], Rating:"2", Sort:"4", Set:"BNG", Number:"115", Image:"/Images/BNG/115.jpg"},
{Name:"Archetype of Endurance", Cost:"8", Color:["G"], Rarity:"U", Type:["C","E"], Rating:"5", Sort:"5", Set:"BNG", Number:"116", Image:"/Images/BNG/116.jpg"},
{Name:"Aspect of Hydra", Cost:"1", Color:["G"], Rarity:"C", Type:["I"], Rating:"3", Sort:"5", Set:"BNG", Number:"117", Image:"/Images/BNG/117.jpg"},
{Name:"Charging Badger ", Cost:"1", Color:["G"], Rarity:"C", Type:["C"], Rating:"2", Sort:"5", Set:"BNG", Number:"118", Image:"/Images/BNG/118.jpg"},
{Name:"Courser of Kruphix", Cost:"3", Color:["G"], Rarity:"R", Type:["C","E"], Rating:"8", Sort:"5", Set:"BNG", Number:"119", Image:"/Images/BNG/119.jpg"},
{Name:"Culling Mark", Cost:"3", Color:["G"], Rarity:"C", Type:["S"], Rating:"2", Sort:"5", Set:"BNG", Number:"120", Image:"/Images/BNG/120.jpg"},
{Name:"Fated Intervention", Cost:"5", Color:["G"], Rarity:"R", Type:["I"], Rating:"7", Sort:"5", Set:"BNG", Number:"121", Image:"/Images/BNG/121.jpg"},
{Name:"Graverobber Spider", Cost:"4", Color:["G"], Rarity:"U", Type:["C"], Rating:"7", Sort:"5", Set:"BNG", Number:"122", Image:"/Images/BNG/122.jpg"},
{Name:"Hero of Leina Tower", Cost:"1", Color:["G"], Rarity:"R", Type:["C"], Rating:"8", Sort:"5", Set:"BNG", Number:"123", Image:"/Images/BNG/123.jpg"},
{Name:"Hunter's Prowess", Cost:"5", Color:["G"], Rarity:"R", Type:["S"], Rating:"7", Sort:"5", Set:"BNG", Number:"124", Image:"/Images/BNG/124.jpg"},
{Name:"Karametra’s Favor ", Cost:"2", Color:["G"], Rarity:"C", Type:["E"], Rating:"6", Sort:"5", Set:"BNG", Number:"125", Image:"/Images/BNG/125.jpg"},
{Name:"Mischief and Mayhem ", Cost:"5", Color:["G"], Rarity:"U", Type:["S"], Rating:"3", Sort:"5", Set:"BNG", Number:"126", Image:"/Images/BNG/126.jpg"},
{Name:"Mortal’s Resolve ", Cost:"2", Color:["G"], Rarity:"C", Type:["I"], Rating:"4", Sort:"5", Set:"BNG", Number:"127", Image:"/Images/BNG/127.jpg"},
{Name:"Nessian Demlock", Cost:"5", Color:["G"], Rarity:"U", Type:["C"], Rating:"7", Sort:"5", Set:"BNG", Number:"128", Image:"/Images/BNG/128.jpg"},
{Name:"Nessian Wilds Ravager", Cost:"6", Color:["G"], Rarity:"R", Type:["C"], Rating:"7", Sort:"5", Set:"BNG", Number:"129", Image:"/Images/BNG/129.jpg"},
{Name:"Noble Quarry ", Cost:"3", Color:["G"], Rarity:"U", Type:["C","E"], Rating:"5", Sort:"5", Set:"BNG", Number:"130", Image:"/Images/BNG/130.jpg"},
{Name:"Nyxborn Wolf", Cost:"3", Color:["G"], Rarity:"C", Type:["C","E"], Rating:"6", Sort:"5", Set:"BNG", Number:"131", Image:"/Images/BNG/131.jpg"},
{Name:"Peregrination", Cost:"4", Color:["G"], Rarity:"U", Type:["S"], Rating:"5", Sort:"5", Set:"BNG", Number:"132", Image:"/Images/BNG/132.jpg"},
{Name:"Pheres-Band Raiders ", Cost:"6", Color:["G"], Rarity:"U", Type:["C"], Rating:"6", Sort:"5", Set:"BNG", Number:"133", Image:"/Images/BNG/133.jpg"},
{Name:"Pheres-Band Tromper ", Cost:"4", Color:["G"], Rarity:"C", Type:["C"], Rating:"6", Sort:"5", Set:"BNG", Number:"134", Image:"/Images/BNG/134.jpg"},
{Name:"Raised by Wolves", Cost:"5", Color:["G"], Rarity:"U", Type:["E"], Rating:"7", Sort:"5", Set:"BNG", Number:"135", Image:"/Images/BNG/135.jpg"},
{Name:"Satyr Wayfinder ", Cost:"2", Color:["G"], Rarity:"C", Type:["C"], Rating:"6", Sort:"5", Set:"BNG", Number:"136", Image:"/Images/BNG/136.jpg"},
{Name:"Scourge of Skola Vale", Cost:"3", Color:["G"], Rarity:"R", Type:["C"], Rating:"7", Sort:"5", Set:"BNG", Number:"137", Image:"/Images/BNG/137.jpg"},
{Name:"Setessan Oathsworn ", Cost:"3", Color:["G"], Rarity:"C", Type:["C"], Rating:"4", Sort:"5", Set:"BNG", Number:"138", Image:"/Images/BNG/138.jpg"},
{Name:"Setessan Starbreaker ", Cost:"4", Color:["G"], Rarity:"C", Type:["C"], Rating:"5", Sort:"5", Set:"BNG", Number:"139", Image:"/Images/BNG/139.jpg"},
{Name:"Skyreaping", Cost:"2", Color:["G"], Rarity:"U", Type:["S"], Rating:"1", Sort:"5", Set:"BNG", Number:"140", Image:"/Images/BNG/140.jpg"},
{Name:"Snake of the Golden Grove", Cost:"5", Color:["G"], Rarity:"C", Type:["C"], Rating:"4", Sort:"5", Set:"BNG", Number:"141", Image:"/Images/BNG/141.jpg"},
{Name:"Swordwise Centaur ", Cost:"2", Color:["G"], Rarity:"C", Type:["C"], Rating:"5", Sort:"5", Set:"BNG", Number:"142", Image:"/Images/BNG/142.jpg"},
{Name:"Unravel the Æther", Cost:"2", Color:["G"], Rarity:"U", Type:["I"], Rating:"3", Sort:"5", Set:"BNG", Number:"143", Image:"/Images/BNG/143.jpg"},
{Name:"Chromanticore", Cost:"5", Color:["W","U","B","R","G"], Rarity:"M", Type:["C","E"], Rating:"3", Sort:"6", Set:"BNG", Number:"144", Image:"/Images/BNG/144.jpg"},
{Name:"Ephara, God of the Polis ", Cost:"4", Color:["W","U"], Rarity:"M", Type:["C","E"], Rating:"8", Sort:"6", Set:"BNG", Number:"145", Image:"/Images/BNG/145.jpg"},
{Name:"Ephara's Enlightenment", Cost:"3", Color:["W","U"], Rarity:"U", Type:["E"], Rating:"6", Sort:"6", Set:"BNG", Number:"146", Image:"/Images/BNG/146.jpg"},
{Name:"Fanatic of Xenagos", Cost:"3", Color:["R","G"], Rarity:"U", Type:["C"], Rating:"7", Sort:"6", Set:"BNG", Number:"147", Image:"/Images/BNG/147.jpg"},
{Name:"Karametra, God of Harvests", Cost:"5", Color:["G","W"], Rarity:"M", Type:["C","E"], Rating:"4", Sort:"6", Set:"BNG", Number:"148", Image:"/Images/BNG/148.jpg"},
{Name:"Kiora, the Crashing Wave", Cost:"4", Color:["G","U"], Rarity:"M", Type:["P"], Rating:"8", Sort:"6", Set:"BNG", Number:"149", Image:"/Images/BNG/149.jpg"},
{Name:"Kiora's Follower", Cost:"2", Color:["G","U"], Rarity:"U", Type:["C"], Rating:"7", Sort:"6", Set:"BNG", Number:"150", Image:"/Images/BNG/150.jpg"},
{Name:"Mogis, God of Slaughter", Cost:"4", Color:["B","R"], Rarity:"M", Type:["C","E"], Rating:"8", Sort:"6", Set:"BNG", Number:"151", Image:"/Images/BNG/151.jpg"},
{Name:"Phenax, God of Deception", Cost:"5", Color:["U","B"], Rarity:"M", Type:["C","E"], Rating:"8", Sort:"6", Set:"BNG", Number:"152", Image:"/Images/BNG/152.jpg"},
{Name:"Ragemonger", Cost:"3", Color:["B","R"], Rarity:"U", Type:["C"], Rating:"3", Sort:"6", Set:"BNG", Number:"153", Image:"/Images/BNG/153.jpg"},
{Name:"Reap What Is Sown", Cost:"3", Color:["G","W"], Rarity:"U", Type:["I"], Rating:"7", Sort:"6", Set:"BNG", Number:"154", Image:"/Images/BNG/154.jpg"},
{Name:"Siren of Silent Song", Cost:"3", Color:["U","B"], Rarity:"U", Type:["C"], Rating:"7", Sort:"6", Set:"BNG", Number:"155", Image:"/Images/BNG/155.jpg"},
{Name:"Xenagos, God of Revels", Cost:"5", Color:["R","G"], Rarity:"M", Type:["C","E"], Rating:"8", Sort:"6", Set:"BNG", Number:"156", Image:"/Images/BNG/156.jpg"},
{Name:"Astral Cornucopia", Cost:"0", Color:["C"], Rarity:"R", Type:["A"], Rating:"3", Sort:"7", Set:"BNG", Number:"157", Image:"/Images/BNG/157.jpg"},
{Name:"Gorgon’s Head ", Cost:"1", Color:["C"], Rarity:"U", Type:["A"], Rating:"5", Sort:"7", Set:"BNG", Number:"158", Image:"/Images/BNG/158.jpg"},
{Name:"Heroes' Podium", Cost:"5", Color:["C"], Rarity:"R", Type:["A"], Rating:"1", Sort:"7", Set:"BNG", Number:"159", Image:"/Images/BNG/159.jpg"},
{Name:"Pillar of War", Cost:"3", Color:["C"], Rarity:"U", Type:["A","C"], Rating:"4", Sort:"7", Set:"BNG", Number:"160", Image:"/Images/BNG/160.jpg"},
{Name:"Siren Song Lyre ", Cost:"2", Color:["C"], Rarity:"U", Type:["A"], Rating:"4", Sort:"7", Set:"BNG", Number:"161", Image:"/Images/BNG/161.jpg"},
{Name:"Springleaf Drum", Cost:"1", Color:["C"], Rarity:"U", Type:["A"], Rating:"3", Sort:"7", Set:"BNG", Number:"162", Image:"/Images/BNG/162.jpg"},
{Name:"Temple of Enlightenment", Cost:"0", Color:["W","U"], Rarity:"R", Type:["L"], Rating:"6", Sort:"6", Set:"BNG", Number:"163", Image:"/Images/BNG/163.jpg"},
{Name:"Temple of Malice", Cost:"0", Color:["B","R"], Rarity:"R", Type:["L"], Rating:"6", Sort:"6", Set:"BNG", Number:"164", Image:"/Images/BNG/164.jpg"},
{Name:"Temple of Plenty", Cost:"0", Color:["G","W"], Rarity:"R", Type:["L"], Rating:"6", Sort:"6", Set:"BNG", Number:"165", Image:"/Images/BNG/165.jpg"},
];