var EMA = [
{Name:"Aven Riftwatcher", Cost:"2W", Color:["W"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"1", Image:"/Images/EMA/AvenRiftwatcher.jpg"},
{Name:"Balance", Cost:"1W", Color:["W"], Rarity:"M", Type:["S"], Rating:"7", Sort:"1", Set:"EMA", Number:"2", Image:"/Images/EMA/Balance.jpg"},
{Name:"Ballynock Cohort", Cost:"2W", Color:["W"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"3", Image:"/Images/EMA/BallynockCohort.jpg"},
{Name:"Benevolent Bodyguard", Cost:"W", Color:["W"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"4", Image:"/Images/EMA/BenevolentBodyguard.jpg"},
{Name:"Calciderm", Cost:"2WW", Color:["W"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"5", Image:"/Images/EMA/Calciderm.jpg"},
{Name:"Coalition Honor Guard", Cost:"3W", Color:["W"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"6", Image:"/Images/EMA/CoalitionHonorGuard.jpg"},
{Name:"Eight-and-a-Half-Tails", Cost:"0WW", Color:["W"], Rarity:"R", Type:["C"], Rating:"6", Sort:"1", Set:"EMA", Number:"7", Image:"/Images/EMA/Eight-and-a-Half-Tails.jpg"},
{Name:"Elite Vanguard", Cost:"0W", Color:["W"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"8", Image:"/Images/EMA/EliteVanguard.jpg"},
{Name:"Enlightened Tutor", Cost:"0W", Color:["W"], Rarity:"R", Type:["I"], Rating:"6", Sort:"1", Set:"EMA", Number:"9", Image:"/Images/EMA/EnlightenedTutor.jpg"},
{Name:"Faith's Fetters", Cost:"3W", Color:["W"], Rarity:"U", Type:["E"], Rating:"4", Sort:"1", Set:"EMA", Number:"10", Image:"/Images/EMA/FaithsFetters.jpg"},
{Name:"Field of Souls", Cost:"2WW", Color:["W"], Rarity:"U", Type:["E"], Rating:"4", Sort:"1", Set:"EMA", Number:"11", Image:"/Images/EMA/FieldofSouls.jpg"},
{Name:"Glimmerpoint Stag", Cost:"2WW", Color:["W"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"12", Image:"/Images/EMA/GlimmerpointStag.jpg"},
{Name:"Honden of Cleansing Fire", Cost:"3W", Color:["W"], Rarity:"U", Type:["E"], Rating:"4", Sort:"1", Set:"EMA", Number:"13", Image:"/Images/EMA/HondenofCleansingFire.jpg"},
{Name:"Humble", Cost:"1W", Color:["W"], Rarity:"C", Type:["I"], Rating:"4", Sort:"1", Set:"EMA", Number:"14", Image:"/Images/EMA/Humble.jpg"},
{Name:"Intangible Virtue", Cost:"1W", Color:["W"], Rarity:"U", Type:["E"], Rating:"4", Sort:"1", Set:"EMA", Number:"15", Image:"/Images/EMA/IntangibleVirtue.jpg"},
{Name:"Jareth, Leonine Titan", Cost:"3WWW", Color:["W"], Rarity:"R", Type:["C"], Rating:"6", Sort:"1", Set:"EMA", Number:"16", Image:"/Images/EMA/Jareth--LeonineTitan.jpg"},
{Name:"Karmic Guide", Cost:"3WW", Color:["W"], Rarity:"R", Type:["C"], Rating:"6", Sort:"1", Set:"EMA", Number:"17", Image:"/Images/EMA/KarmicGuide.jpg"},
{Name:"Kor Hookmaster", Cost:"2W", Color:["W"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"18", Image:"/Images/EMA/KorHookmaster.jpg"},
{Name:"Mesa Enchantress", Cost:"1WW", Color:["W"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"19", Image:"/Images/EMA/MesaEnchantress.jpg"},
{Name:"Mistral Charger", Cost:"1W", Color:["W"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"20", Image:"/Images/EMA/MistralCharger.jpg"},
{Name:"Monk Idealist", Cost:"2W", Color:["W"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"21", Image:"/Images/EMA/MonkIdealist.jpg"},
{Name:"Mother of Runes", Cost:"0W", Color:["W"], Rarity:"R", Type:["C"], Rating:"6", Sort:"1", Set:"EMA", Number:"22", Image:"/Images/EMA/MotherofRunes.jpg"},
{Name:"Pacifism", Cost:"1W", Color:["W"], Rarity:"C", Type:["E"], Rating:"4", Sort:"1", Set:"EMA", Number:"23", Image:"/Images/EMA/Pacifism.jpg"},
{Name:"Raise the Alarm", Cost:"1W", Color:["W"], Rarity:"C", Type:["I"], Rating:"4", Sort:"1", Set:"EMA", Number:"24", Image:"/Images/EMA/RaisetheAlarm.jpg"},
{Name:"Rally the Peasants", Cost:"2W", Color:["W"], Rarity:"C", Type:["I"], Rating:"4", Sort:"1", Set:"EMA", Number:"25", Image:"/Images/EMA/RallythePeasants.jpg"},
{Name:"Seal of Cleansing", Cost:"1W", Color:["W"], Rarity:"C", Type:["E"], Rating:"4", Sort:"1", Set:"EMA", Number:"26", Image:"/Images/EMA/SealofCleansing.jpg"},
{Name:"Second Thoughts", Cost:"4W", Color:["W"], Rarity:"C", Type:["I"], Rating:"4", Sort:"1", Set:"EMA", Number:"27", Image:"/Images/EMA/SecondThoughts.jpg"},
{Name:"Serra Angel", Cost:"3WW", Color:["W"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"28", Image:"/Images/EMA/SerraAngel.jpg"},
{Name:"Shelter", Cost:"1W", Color:["W"], Rarity:"C", Type:["I"], Rating:"4", Sort:"1", Set:"EMA", Number:"29", Image:"/Images/EMA/Shelter.jpg"},
{Name:"Soulcatcher", Cost:"1W", Color:["W"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"30", Image:"/Images/EMA/Soulcatcher.jpg"},
{Name:"Squadron Hawk", Cost:"1W", Color:["W"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"31", Image:"/Images/EMA/SquadronHawk.jpg"},
{Name:"Swords to Plowshares", Cost:"0W", Color:["W"], Rarity:"U", Type:["I"], Rating:"4", Sort:"1", Set:"EMA", Number:"32", Image:"/Images/EMA/SwordstoPlowshares.jpg"},
{Name:"Unexpectedly Absent", Cost:"0WW", Color:["W"], Rarity:"R", Type:["I"], Rating:"6", Sort:"1", Set:"EMA", Number:"33", Image:"/Images/EMA/UnexpectedlyAbsent.jpg"},
{Name:"Wall of Omens", Cost:"1W", Color:["W"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"34", Image:"/Images/EMA/WallofOmens.jpg"},
{Name:"War Priest of Thune", Cost:"1W", Color:["W"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"35", Image:"/Images/EMA/WarPriestofThune.jpg"},
{Name:"Welkin Guide", Cost:"4W", Color:["W"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"36", Image:"/Images/EMA/WelkinGuide.jpg"},
{Name:"Whitemane Lion", Cost:"1W", Color:["W"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"37", Image:"/Images/EMA/WhitemaneLion.jpg"},
{Name:"Wrath of God", Cost:"2WW", Color:["W"], Rarity:"R", Type:["S"], Rating:"6", Sort:"1", Set:"EMA", Number:"38", Image:"/Images/EMA/WrathofGod.jpg"},
{Name:"Arcanis the Omnipotent", Cost:"3UUU", Color:["U"], Rarity:"R", Type:["C"], Rating:"6", Sort:"1", Set:"EMA", Number:"39", Image:"/Images/EMA/ArcanistheOmnipotent.jpg"},
{Name:"Brainstorm", Cost:"0U", Color:["U"], Rarity:"U", Type:["I"], Rating:"4", Sort:"1", Set:"EMA", Number:"40", Image:"/Images/EMA/Brainstorm.jpg"},
{Name:"Cephalid Sage", Cost:"3U", Color:["U"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"41", Image:"/Images/EMA/CephalidSage.jpg"},
{Name:"Control Magic", Cost:"2UU", Color:["U"], Rarity:"R", Type:["E"], Rating:"6", Sort:"1", Set:"EMA", Number:"42", Image:"/Images/EMA/ControlMagic.jpg"},
{Name:"Counterspell", Cost:"0UU", Color:["U"], Rarity:"C", Type:["I"], Rating:"4", Sort:"1", Set:"EMA", Number:"43", Image:"/Images/EMA/Counterspell.jpg"},
{Name:"Daze", Cost:"1U", Color:["U"], Rarity:"U", Type:["I"], Rating:"4", Sort:"1", Set:"EMA", Number:"44", Image:"/Images/EMA/Daze.jpg"},
{Name:"Deep Analysis", Cost:"3UU", Color:["U"], Rarity:"C", Type:["S"], Rating:"4", Sort:"1", Set:"EMA", Number:"45", Image:"/Images/EMA/DeepAnalysis.jpg"},
{Name:"Diminishing Returns", Cost:"2UU", Color:["U"], Rarity:"R", Type:["S"], Rating:"6", Sort:"1", Set:"EMA", Number:"46", Image:"/Images/EMA/DiminishingReturns.jpg"},
{Name:"Dream Twist", Cost:"0U", Color:["U"], Rarity:"C", Type:["I"], Rating:"4", Sort:"1", Set:"EMA", Number:"47", Image:"/Images/EMA/DreamTwist.jpg"},
{Name:"Fact or Fiction", Cost:"3U", Color:["U"], Rarity:"U", Type:["I"], Rating:"4", Sort:"1", Set:"EMA", Number:"48", Image:"/Images/EMA/FactorFiction.jpg"},
{Name:"Force of Will", Cost:"3UU", Color:["U"], Rarity:"M", Type:["I"], Rating:"7", Sort:"1", Set:"EMA", Number:"49", Image:"/Images/EMA/ForceofWill.jpg"},
{Name:"Future Sight", Cost:"2UUU", Color:["U"], Rarity:"R", Type:["E"], Rating:"6", Sort:"1", Set:"EMA", Number:"50", Image:"/Images/EMA/FutureSight.jpg"},
{Name:"Gaseous Form", Cost:"2U", Color:["U"], Rarity:"C", Type:["E"], Rating:"4", Sort:"1", Set:"EMA", Number:"51", Image:"/Images/EMA/GaseousForm.jpg"},
{Name:"Giant Tortoise", Cost:"1U", Color:["U"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"52", Image:"/Images/EMA/GiantTortoise.jpg"},
{Name:"Glacial Wall", Cost:"2U", Color:["U"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"53", Image:"/Images/EMA/GlacialWall.jpg"},
{Name:"Honden of Seeing Winds", Cost:"4U", Color:["U"], Rarity:"U", Type:["E"], Rating:"4", Sort:"1", Set:"EMA", Number:"54", Image:"/Images/EMA/HondenofSeeingWinds.jpg"},
{Name:"Hydroblast", Cost:"0U", Color:["U"], Rarity:"U", Type:["I"], Rating:"4", Sort:"1", Set:"EMA", Number:"55", Image:"/Images/EMA/Hydroblast.jpg"},
{Name:"Inkwell Leviathan", Cost:"7UU", Color:["U"], Rarity:"R", Type:["C"], Rating:"6", Sort:"1", Set:"EMA", Number:"56", Image:"/Images/EMA/InkwellLeviathan.jpg"},
{Name:"Jace, the Mind Sculptor", Cost:"2UU", Color:["U"], Rarity:"M", Type:["P"], Rating:"10", Sort:"1", Set:"EMA", Number:"57", Image:"/Images/EMA/Jace--theMindSculptor.jpg"},
{Name:"Jetting Glasskite", Cost:"4UU", Color:["U"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"58", Image:"/Images/EMA/JettingGlasskite.jpg"},
{Name:"Man-o'-War", Cost:"2U", Color:["U"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"59", Image:"/Images/EMA/Man-o-War.jpg"},
{Name:"Memory Lapse", Cost:"1U", Color:["U"], Rarity:"C", Type:["I"], Rating:"4", Sort:"1", Set:"EMA", Number:"60", Image:"/Images/EMA/MemoryLapse.jpg"},
{Name:"Merfolk Looter", Cost:"1U", Color:["U"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"61", Image:"/Images/EMA/MerfolkLooter.jpg"},
{Name:"Mystical Tutor", Cost:"0U", Color:["U"], Rarity:"R", Type:["I"], Rating:"6", Sort:"1", Set:"EMA", Number:"62", Image:"/Images/EMA/MysticalTutor.jpg"},
{Name:"Oona's Grace", Cost:"2U", Color:["U"], Rarity:"C", Type:["I"], Rating:"4", Sort:"1", Set:"EMA", Number:"63", Image:"/Images/EMA/OonasGrace.jpg"},
{Name:"Peregrine Drake", Cost:"4U", Color:["U"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"64", Image:"/Images/EMA/PeregrineDrake.jpg"},
{Name:"Phantom Monster", Cost:"3U", Color:["U"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"65", Image:"/Images/EMA/PhantomMonster.jpg"},
{Name:"Phyrexian Ingester", Cost:"6U", Color:["U"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"66", Image:"/Images/EMA/PhyrexianIngester.jpg"},
{Name:"Prodigal Sorcerer", Cost:"2U", Color:["U"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"67", Image:"/Images/EMA/ProdigalSorcerer.jpg"},
{Name:"Quiet Speculation", Cost:"1U", Color:["U"], Rarity:"U", Type:["S"], Rating:"4", Sort:"1", Set:"EMA", Number:"68", Image:"/Images/EMA/QuietSpeculation.jpg"},
{Name:"Screeching Skaab", Cost:"1U", Color:["U"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"69", Image:"/Images/EMA/ScreechingSkaab.jpg"},
{Name:"Serendib Efreet", Cost:"2U", Color:["U"], Rarity:"R", Type:["C"], Rating:"6", Sort:"1", Set:"EMA", Number:"70", Image:"/Images/EMA/SerendibEfreet.jpg"},
{Name:"Shoreline Ranger", Cost:"5U", Color:["U"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"71", Image:"/Images/EMA/ShorelineRanger.jpg"},
{Name:"Silent Departure", Cost:"0U", Color:["U"], Rarity:"C", Type:["S"], Rating:"4", Sort:"1", Set:"EMA", Number:"72", Image:"/Images/EMA/SilentDeparture.jpg"},
{Name:"Sprite Noble", Cost:"1UU", Color:["U"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"73", Image:"/Images/EMA/SpriteNoble.jpg"},
{Name:"Stupefying Touch", Cost:"1U", Color:["U"], Rarity:"C", Type:["E"], Rating:"4", Sort:"1", Set:"EMA", Number:"74", Image:"/Images/EMA/StupefyingTouch.jpg"},
{Name:"Tidal Wave", Cost:"2U", Color:["U"], Rarity:"C", Type:["I"], Rating:"4", Sort:"1", Set:"EMA", Number:"75", Image:"/Images/EMA/TidalWave.jpg"},
{Name:"Warden of Evos Isle", Cost:"2U", Color:["U"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"76", Image:"/Images/EMA/WardenofEvosIsle.jpg"},
{Name:"Wonder", Cost:"3U", Color:["U"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"77", Image:"/Images/EMA/Wonder.jpg"},
{Name:"Animate Dead", Cost:"1B", Color:["B"], Rarity:"U", Type:["E"], Rating:"4", Sort:"1", Set:"EMA", Number:"78", Image:"/Images/EMA/AnimateDead.jpg"},
{Name:"Annihilate", Cost:"3BB", Color:["B"], Rarity:"U", Type:["I"], Rating:"4", Sort:"1", Set:"EMA", Number:"79", Image:"/Images/EMA/Annihilate.jpg"},
{Name:"Blightsoil Druid", Cost:"1B", Color:["B"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"80", Image:"/Images/EMA/BlightsoilDruid.jpg"},
{Name:"Blood Artist", Cost:"1B", Color:["B"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"81", Image:"/Images/EMA/BloodArtist.jpg"},
{Name:"Braids, Cabal Minion", Cost:"2BB", Color:["B"], Rarity:"R", Type:["C"], Rating:"6", Sort:"1", Set:"EMA", Number:"82", Image:"/Images/EMA/Braids--CabalMinion.jpg"},
{Name:"Cabal Therapy", Cost:"0B", Color:["B"], Rarity:"U", Type:["S"], Rating:"4", Sort:"1", Set:"EMA", Number:"83", Image:"/Images/EMA/CabalTherapy.jpg"},
{Name:"Carrion Feeder", Cost:"0B", Color:["B"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"84", Image:"/Images/EMA/CarrionFeeder.jpg"},
{Name:"Deadbridge Shaman", Cost:"2B", Color:["B"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"85", Image:"/Images/EMA/DeadbridgeShaman.jpg"},
{Name:"Duress", Cost:"0B", Color:["B"], Rarity:"C", Type:["S"], Rating:"4", Sort:"1", Set:"EMA", Number:"86", Image:"/Images/EMA/Duress.jpg"},
{Name:"Entomb", Cost:"0B", Color:["B"], Rarity:"R", Type:["I"], Rating:"6", Sort:"1", Set:"EMA", Number:"87", Image:"/Images/EMA/Entomb.jpg"},
{Name:"Eyeblight's Ending", Cost:"2B", Color:["B"], Rarity:"C", Type:["I"], Rating:"4", Sort:"1", Set:"EMA", Number:"88", Image:"/Images/EMA/EyeblightsEnding.jpg"},
{Name:"Gravedigger", Cost:"3B", Color:["B"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"89", Image:"/Images/EMA/Gravedigger.jpg"},
{Name:"Havoc Demon", Cost:"5BB", Color:["B"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"90", Image:"/Images/EMA/HavocDemon.jpg"},
{Name:"Honden of Night's Reach", Cost:"3B", Color:["B"], Rarity:"U", Type:["E"], Rating:"4", Sort:"1", Set:"EMA", Number:"91", Image:"/Images/EMA/HondenofNightsReach.jpg"},
{Name:"Hymn to Tourach", Cost:"0BB", Color:["B"], Rarity:"U", Type:["S"], Rating:"4", Sort:"1", Set:"EMA", Number:"92", Image:"/Images/EMA/HymntoTourach.jpg"},
{Name:"Ichorid", Cost:"3B", Color:["B"], Rarity:"R", Type:["C"], Rating:"6", Sort:"1", Set:"EMA", Number:"93", Image:"/Images/EMA/Ichorid.jpg"},
{Name:"Innocent Blood", Cost:"0B", Color:["B"], Rarity:"C", Type:["S"], Rating:"4", Sort:"1", Set:"EMA", Number:"94", Image:"/Images/EMA/InnocentBlood.jpg"},
{Name:"Lys Alana Scarblade", Cost:"2B", Color:["B"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"95", Image:"/Images/EMA/LysAlanaScarblade.jpg"},
{Name:"Malicious Affliction", Cost:"0BB", Color:["B"], Rarity:"R", Type:["I"], Rating:"6", Sort:"1", Set:"EMA", Number:"96", Image:"/Images/EMA/MaliciousAffliction.jpg"},
{Name:"Nausea", Cost:"1B", Color:["B"], Rarity:"C", Type:["S"], Rating:"4", Sort:"1", Set:"EMA", Number:"97", Image:"/Images/EMA/Nausea.jpg"},
{Name:"Necropotence", Cost:"0BBB", Color:["B"], Rarity:"M", Type:["E"], Rating:"10", Sort:"1", Set:"EMA", Number:"98", Image:"/Images/EMA/Necropotence.jpg"},
{Name:"Nekrataal", Cost:"2BB", Color:["B"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"99", Image:"/Images/EMA/Nekrataal.jpg"},
{Name:"Night's Whisper", Cost:"1B", Color:["B"], Rarity:"C", Type:["S"], Rating:"4", Sort:"1", Set:"EMA", Number:"100", Image:"/Images/EMA/NightsWhisper.jpg"},
{Name:"Phyrexian Gargantua", Cost:"4BB", Color:["B"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"101", Image:"/Images/EMA/PhyrexianGargantua.jpg"},
{Name:"Phyrexian Rager", Cost:"2B", Color:["B"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"102", Image:"/Images/EMA/PhyrexianRager.jpg"},
{Name:"Plague Witch", Cost:"1B", Color:["B"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"103", Image:"/Images/EMA/PlagueWitch.jpg"},
{Name:"Prowling Pangolin", Cost:"3BB", Color:["B"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"104", Image:"/Images/EMA/ProwlingPangolin.jpg"},
{Name:"Sengir Autocrat", Cost:"3B", Color:["B"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"105", Image:"/Images/EMA/SengirAutocrat.jpg"},
{Name:"Sinkhole", Cost:"0BB", Color:["B"], Rarity:"R", Type:["S"], Rating:"6", Sort:"1", Set:"EMA", Number:"106", Image:"/Images/EMA/Sinkhole.jpg"},
{Name:"Skulking Ghost", Cost:"1B", Color:["B"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"107", Image:"/Images/EMA/SkulkingGhost.jpg"},
{Name:"Toxic Deluge", Cost:"2B", Color:["B"], Rarity:"R", Type:["S"], Rating:"6", Sort:"1", Set:"EMA", Number:"108", Image:"/Images/EMA/ToxicDeluge.jpg"},
{Name:"Tragic Slip", Cost:"0B", Color:["B"], Rarity:"C", Type:["I"], Rating:"4", Sort:"1", Set:"EMA", Number:"109", Image:"/Images/EMA/TragicSlip.jpg"},
{Name:"Twisted Abomination", Cost:"5B", Color:["B"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"110", Image:"/Images/EMA/TwistedAbomination.jpg"},
{Name:"Urborg Uprising", Cost:"4B", Color:["B"], Rarity:"C", Type:["S"], Rating:"4", Sort:"1", Set:"EMA", Number:"111", Image:"/Images/EMA/UrborgUprising.jpg"},
{Name:"Vampiric Tutor", Cost:"0B", Color:["B"], Rarity:"M", Type:["I"], Rating:"7", Sort:"1", Set:"EMA", Number:"112", Image:"/Images/EMA/VampiricTutor.jpg"},
{Name:"Victimize", Cost:"2B", Color:["B"], Rarity:"U", Type:["S"], Rating:"4", Sort:"1", Set:"EMA", Number:"113", Image:"/Images/EMA/Victimize.jpg"},
{Name:"Visara the Dreadful", Cost:"3BBB", Color:["B"], Rarity:"R", Type:["C"], Rating:"6", Sort:"1", Set:"EMA", Number:"114", Image:"/Images/EMA/VisaratheDreadful.jpg"},
{Name:"Wake of Vultures", Cost:"3B", Color:["B"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"115", Image:"/Images/EMA/WakeofVultures.jpg"},
{Name:"Wakedancer", Cost:"2B", Color:["B"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"116", Image:"/Images/EMA/Wakedancer.jpg"},
{Name:"Avarax", Cost:"3RR", Color:["R"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"117", Image:"/Images/EMA/Avarax.jpg"},
{Name:"Battle Squadron", Cost:"3RR", Color:["R"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"118", Image:"/Images/EMA/BattleSquadron.jpg"},
{Name:"Beetleback Chief", Cost:"2RR", Color:["R"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"119", Image:"/Images/EMA/BeetlebackChief.jpg"},
{Name:"Borderland Marauder", Cost:"1R", Color:["R"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"120", Image:"/Images/EMA/BorderlandMarauder.jpg"},
{Name:"Burning Vengeance", Cost:"2R", Color:["R"], Rarity:"U", Type:["E"], Rating:"4", Sort:"1", Set:"EMA", Number:"121", Image:"/Images/EMA/BurningVengeance.jpg"},
{Name:"Carbonize", Cost:"2R", Color:["R"], Rarity:"C", Type:["I"], Rating:"4", Sort:"1", Set:"EMA", Number:"122", Image:"/Images/EMA/Carbonize.jpg"},
{Name:"Chain Lightning", Cost:"0R", Color:["R"], Rarity:"U", Type:["S"], Rating:"4", Sort:"1", Set:"EMA", Number:"123", Image:"/Images/EMA/ChainLightning.jpg"},
{Name:"Crater Hellion", Cost:"4RR", Color:["R"], Rarity:"R", Type:["C"], Rating:"6", Sort:"1", Set:"EMA", Number:"124", Image:"/Images/EMA/CraterHellion.jpg"},
{Name:"Desperate Ravings", Cost:"1R", Color:["R"], Rarity:"C", Type:["I"], Rating:"4", Sort:"1", Set:"EMA", Number:"125", Image:"/Images/EMA/DesperateRavings.jpg"},
{Name:"Dragon Egg", Cost:"2R", Color:["R"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"126", Image:"/Images/EMA/DragonEgg.jpg"},
{Name:"Dualcaster Mage", Cost:"1RR", Color:["R"], Rarity:"R", Type:["C"], Rating:"6", Sort:"1", Set:"EMA", Number:"127", Image:"/Images/EMA/DualcasterMage.jpg"},
{Name:"Faithless Looting", Cost:"0R", Color:["R"], Rarity:"C", Type:["S"], Rating:"4", Sort:"1", Set:"EMA", Number:"128", Image:"/Images/EMA/FaithlessLooting.jpg"},
{Name:"Fervent Cathar", Cost:"2R", Color:["R"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"129", Image:"/Images/EMA/FerventCathar.jpg"},
{Name:"Firebolt", Cost:"0R", Color:["R"], Rarity:"C", Type:["S"], Rating:"4", Sort:"1", Set:"EMA", Number:"130", Image:"/Images/EMA/Firebolt.jpg"},
{Name:"Flame Jab", Cost:"0R", Color:["R"], Rarity:"U", Type:["S"], Rating:"4", Sort:"1", Set:"EMA", Number:"131", Image:"/Images/EMA/FlameJab.jpg"},
{Name:"Gamble", Cost:"0R", Color:["R"], Rarity:"R", Type:["S"], Rating:"6", Sort:"1", Set:"EMA", Number:"132", Image:"/Images/EMA/Gamble.jpg"},
{Name:"Ghitu Slinger", Cost:"2R", Color:["R"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"133", Image:"/Images/EMA/GhituSlinger.jpg"},
{Name:"Honden of Infinite Rage", Cost:"2R", Color:["R"], Rarity:"U", Type:["E"], Rating:"4", Sort:"1", Set:"EMA", Number:"134", Image:"/Images/EMA/HondenofInfiniteRage.jpg"},
{Name:"Keldon Champion", Cost:"2RR", Color:["R"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"135", Image:"/Images/EMA/KeldonChampion.jpg"},
{Name:"Keldon Marauders", Cost:"1R", Color:["R"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"136", Image:"/Images/EMA/KeldonMarauders.jpg"},
{Name:"Kird Ape", Cost:"0R", Color:["R"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"137", Image:"/Images/EMA/KirdApe.jpg"},
{Name:"Mogg Fanatic", Cost:"0R", Color:["R"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"138", Image:"/Images/EMA/MoggFanatic.jpg"},
{Name:"Mogg War Marshal", Cost:"1R", Color:["R"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"139", Image:"/Images/EMA/MoggWarMarshal.jpg"},
{Name:"Orcish Oriflamme", Cost:"3R", Color:["R"], Rarity:"C", Type:["E"], Rating:"4", Sort:"1", Set:"EMA", Number:"140", Image:"/Images/EMA/OrcishOriflamme.jpg"},
{Name:"Price of Progress", Cost:"1R", Color:["R"], Rarity:"U", Type:["I"], Rating:"4", Sort:"1", Set:"EMA", Number:"141", Image:"/Images/EMA/PriceofProgress.jpg"},
{Name:"Pyroblast", Cost:"0R", Color:["R"], Rarity:"U", Type:["I"], Rating:"4", Sort:"1", Set:"EMA", Number:"142", Image:"/Images/EMA/Pyroblast.jpg"},
{Name:"Pyrokinesis", Cost:"4RR", Color:["R"], Rarity:"R", Type:["I"], Rating:"6", Sort:"1", Set:"EMA", Number:"143", Image:"/Images/EMA/Pyrokinesis.jpg"},
{Name:"Reckless Charge", Cost:"0R", Color:["R"], Rarity:"C", Type:["S"], Rating:"4", Sort:"1", Set:"EMA", Number:"144", Image:"/Images/EMA/RecklessCharge.jpg"},
{Name:"Rorix Bladewing", Cost:"3RRR", Color:["R"], Rarity:"R", Type:["C"], Rating:"6", Sort:"1", Set:"EMA", Number:"145", Image:"/Images/EMA/RorixBladewing.jpg"},
{Name:"Seismic Stomp", Cost:"1R", Color:["R"], Rarity:"C", Type:["S"], Rating:"4", Sort:"1", Set:"EMA", Number:"146", Image:"/Images/EMA/SeismicStomp.jpg"},
{Name:"Siege-Gang Commander", Cost:"3RR", Color:["R"], Rarity:"R", Type:["C"], Rating:"6", Sort:"1", Set:"EMA", Number:"147", Image:"/Images/EMA/Siege-GangCommander.jpg"},
{Name:"Sneak Attack", Cost:"3R", Color:["R"], Rarity:"M", Type:["E"], Rating:"7", Sort:"1", Set:"EMA", Number:"148", Image:"/Images/EMA/SneakAttack.jpg"},
{Name:"Stingscourger", Cost:"1R", Color:["R"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"149", Image:"/Images/EMA/Stingscourger.jpg"},
{Name:"Sulfuric Vortex", Cost:"1RR", Color:["R"], Rarity:"R", Type:["E"], Rating:"6", Sort:"1", Set:"EMA", Number:"150", Image:"/Images/EMA/SulfuricVortex.jpg"},
{Name:"Tooth and Claw", Cost:"3R", Color:["R"], Rarity:"U", Type:["E"], Rating:"4", Sort:"1", Set:"EMA", Number:"151", Image:"/Images/EMA/ToothandClaw.jpg"},
{Name:"Undying Rage", Cost:"2R", Color:["R"], Rarity:"C", Type:["E"], Rating:"4", Sort:"1", Set:"EMA", Number:"152", Image:"/Images/EMA/UndyingRage.jpg"},
{Name:"Wildfire Emissary", Cost:"3R", Color:["R"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"153", Image:"/Images/EMA/WildfireEmissary.jpg"},
{Name:"Worldgorger Dragon", Cost:"3RRR", Color:["R"], Rarity:"M", Type:["C"], Rating:"7", Sort:"1", Set:"EMA", Number:"154", Image:"/Images/EMA/WorldgorgerDragon.jpg"},
{Name:"Young Pyromancer", Cost:"1R", Color:["R"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"155", Image:"/Images/EMA/YoungPyromancer.jpg"},
{Name:"Abundant Growth", Cost:"0G", Color:["G"], Rarity:"C", Type:["E"], Rating:"4", Sort:"1", Set:"EMA", Number:"156", Image:"/Images/EMA/AbundantGrowth.jpg"},
{Name:"Ancestral Mask", Cost:"2G", Color:["G"], Rarity:"U", Type:["E"], Rating:"4", Sort:"1", Set:"EMA", Number:"157", Image:"/Images/EMA/AncestralMask.jpg"},
{Name:"Argothian Enchantress", Cost:"1G", Color:["G"], Rarity:"M", Type:["C"], Rating:"7", Sort:"1", Set:"EMA", Number:"158", Image:"/Images/EMA/ArgothianEnchantress.jpg"},
{Name:"Brawn", Cost:"3G", Color:["G"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"159", Image:"/Images/EMA/Brawn.jpg"},
{Name:"Centaur Chieftain", Cost:"3G", Color:["G"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"160", Image:"/Images/EMA/CentaurChieftain.jpg"},
{Name:"Civic Wayfinder", Cost:"2G", Color:["G"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"161", Image:"/Images/EMA/CivicWayfinder.jpg"},
{Name:"Commune with the Gods", Cost:"1G", Color:["G"], Rarity:"C", Type:["S"], Rating:"4", Sort:"1", Set:"EMA", Number:"162", Image:"/Images/EMA/CommunewiththeGods.jpg"},
{Name:"Elephant Guide", Cost:"2G", Color:["G"], Rarity:"C", Type:["E"], Rating:"4", Sort:"1", Set:"EMA", Number:"163", Image:"/Images/EMA/ElephantGuide.jpg"},
{Name:"Elvish Vanguard", Cost:"1G", Color:["G"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"164", Image:"/Images/EMA/ElvishVanguard.jpg"},
{Name:"Emperor Crocodile", Cost:"3G", Color:["G"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"165", Image:"/Images/EMA/EmperorCrocodile.jpg"},
{Name:"Flinthoof Boar", Cost:"1G", Color:["G"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"166", Image:"/Images/EMA/FlinthoofBoar.jpg"},
{Name:"Fog", Cost:"0G", Color:["G"], Rarity:"C", Type:["I"], Rating:"4", Sort:"1", Set:"EMA", Number:"167", Image:"/Images/EMA/Fog.jpg"},
{Name:"Gaea's Blessing", Cost:"1G", Color:["G"], Rarity:"U", Type:["S"], Rating:"4", Sort:"1", Set:"EMA", Number:"168", Image:"/Images/EMA/GaeasBlessing.jpg"},
{Name:"Green Sun's Zenith", Cost:"0G", Color:["G"], Rarity:"R", Type:["S"], Rating:"6", Sort:"1", Set:"EMA", Number:"169", Image:"/Images/EMA/GreenSunsZenith.jpg"},
{Name:"Harmonize", Cost:"2GG", Color:["G"], Rarity:"U", Type:["S"], Rating:"4", Sort:"1", Set:"EMA", Number:"170", Image:"/Images/EMA/Harmonize.jpg"},
{Name:"Heritage Druid", Cost:"0G", Color:["G"], Rarity:"R", Type:["C"], Rating:"6", Sort:"1", Set:"EMA", Number:"171", Image:"/Images/EMA/HeritageDruid.jpg"},
{Name:"Honden of Life's Web", Cost:"4G", Color:["G"], Rarity:"U", Type:["E"], Rating:"4", Sort:"1", Set:"EMA", Number:"172", Image:"/Images/EMA/HondenofLifesWeb.jpg"},
{Name:"Imperious Perfect", Cost:"2G", Color:["G"], Rarity:"R", Type:["C"], Rating:"6", Sort:"1", Set:"EMA", Number:"173", Image:"/Images/EMA/ImperiousPerfect.jpg"},
{Name:"Invigorate", Cost:"2G", Color:["G"], Rarity:"U", Type:["I"], Rating:"4", Sort:"1", Set:"EMA", Number:"174", Image:"/Images/EMA/Invigorate.jpg"},
{Name:"Llanowar Elves", Cost:"0G", Color:["G"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"175", Image:"/Images/EMA/LlanowarElves.jpg"},
{Name:"Lys Alana Huntmaster", Cost:"2GG", Color:["G"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"176", Image:"/Images/EMA/LysAlanaHuntmaster.jpg"},
{Name:"Natural Order", Cost:"2GG", Color:["G"], Rarity:"M", Type:["S"], Rating:"7", Sort:"1", Set:"EMA", Number:"177", Image:"/Images/EMA/NaturalOrder.jpg"},
{Name:"Nature's Claim", Cost:"0G", Color:["G"], Rarity:"C", Type:["I"], Rating:"4", Sort:"1", Set:"EMA", Number:"178", Image:"/Images/EMA/NaturesClaim.jpg"},
{Name:"Nimble Mongoose", Cost:"0G", Color:["G"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"179", Image:"/Images/EMA/NimbleMongoose.jpg"},
{Name:"Rancor", Cost:"0G", Color:["G"], Rarity:"U", Type:["E"], Rating:"4", Sort:"1", Set:"EMA", Number:"180", Image:"/Images/EMA/Rancor.jpg"},
{Name:"Regal Force", Cost:"4GGG", Color:["G"], Rarity:"R", Type:["C"], Rating:"6", Sort:"1", Set:"EMA", Number:"181", Image:"/Images/EMA/RegalForce.jpg"},
{Name:"Roar of the Wurm", Cost:"6G", Color:["G"], Rarity:"U", Type:["S"], Rating:"4", Sort:"1", Set:"EMA", Number:"182", Image:"/Images/EMA/RoaroftheWurm.jpg"},
{Name:"Roots", Cost:"3G", Color:["G"], Rarity:"C", Type:["E"], Rating:"4", Sort:"1", Set:"EMA", Number:"183", Image:"/Images/EMA/Roots.jpg"},
{Name:"Seal of Strength", Cost:"0G", Color:["G"], Rarity:"C", Type:["E"], Rating:"4", Sort:"1", Set:"EMA", Number:"184", Image:"/Images/EMA/SealofStrength.jpg"},
{Name:"Sentinel Spider", Cost:"3GG", Color:["G"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"185", Image:"/Images/EMA/SentinelSpider.jpg"},
{Name:"Silvos, Rogue Elemental", Cost:"3GGG", Color:["G"], Rarity:"R", Type:["C"], Rating:"6", Sort:"1", Set:"EMA", Number:"186", Image:"/Images/EMA/Silvos--RogueElemental.jpg"},
{Name:"Sylvan Library", Cost:"1G", Color:["G"], Rarity:"R", Type:["E"], Rating:"6", Sort:"1", Set:"EMA", Number:"187", Image:"/Images/EMA/SylvanLibrary.jpg"},
{Name:"Sylvan Might", Cost:"1G", Color:["G"], Rarity:"C", Type:["I"], Rating:"4", Sort:"1", Set:"EMA", Number:"188", Image:"/Images/EMA/SylvanMight.jpg"},
{Name:"Thornweald Archer", Cost:"1G", Color:["G"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"189", Image:"/Images/EMA/ThornwealdArcher.jpg"},
{Name:"Timberwatch Elf", Cost:"2G", Color:["G"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"190", Image:"/Images/EMA/TimberwatchElf.jpg"},
{Name:"Werebear", Cost:"1G", Color:["G"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"191", Image:"/Images/EMA/Werebear.jpg"},
{Name:"Wirewood Symbiote", Cost:"0G", Color:["G"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"192", Image:"/Images/EMA/WirewoodSymbiote.jpg"},
{Name:"Xantid Swarm", Cost:"0G", Color:["G"], Rarity:"R", Type:["C"], Rating:"6", Sort:"1", Set:"EMA", Number:"193", Image:"/Images/EMA/XantidSwarm.jpg"},
{Name:"Yavimaya Enchantress", Cost:"2G", Color:["G"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"194", Image:"/Images/EMA/YavimayaEnchantress.jpg"},
{Name:"Armadillo Cloak", Cost:"1GW", Color:["W","G"], Rarity:"U", Type:["E"], Rating:"4", Sort:"1", Set:"EMA", Number:"195", Image:"/Images/EMA/ArmadilloCloak.jpg"},
{Name:"Baleful Strix", Cost:"0UB", Color:["U","B"], Rarity:"R", Type:["C"], Rating:"6", Sort:"1", Set:"EMA", Number:"196", Image:"/Images/EMA/BalefulStrix.jpg"},
{Name:"Bloodbraid Elf", Cost:"2RG", Color:["R","G"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"197", Image:"/Images/EMA/BloodbraidElf.jpg"},
{Name:"Brago, King Eternal", Cost:"2WU", Color:["W","U"], Rarity:"R", Type:["C"], Rating:"6", Sort:"1", Set:"EMA", Number:"198", Image:"/Images/EMA/Brago--KingEternal.jpg"},
{Name:"Dack Fayden", Cost:"1UR", Color:["U","R"], Rarity:"M", Type:["P"], Rating:"7", Sort:"1", Set:"EMA", Number:"199", Image:"/Images/EMA/DackFayden.jpg"},
{Name:"Extract from Darkness", Cost:"3UB", Color:["U","B"], Rarity:"U", Type:["S"], Rating:"4", Sort:"1", Set:"EMA", Number:"200", Image:"/Images/EMA/ExtractfromDarkness.jpg"},
{Name:"Flame-Kin Zealot", Cost:"1RRW", Color:["R","W"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"201", Image:"/Images/EMA/Flame-KinZealot.jpg"},
{Name:"Glare of Subdual", Cost:"2GW", Color:["G","W"], Rarity:"R", Type:["E"], Rating:"6", Sort:"1", Set:"EMA", Number:"202", Image:"/Images/EMA/GlareofSubdual.jpg"},
{Name:"Goblin Trenches", Cost:"1RW", Color:["R","W"], Rarity:"R", Type:["E"], Rating:"6", Sort:"1", Set:"EMA", Number:"203", Image:"/Images/EMA/GoblinTrenches.jpg"},
{Name:"Maelstrom Wanderer", Cost:"5URG", Color:["U","R","G"], Rarity:"M", Type:["C"], Rating:"7", Sort:"1", Set:"EMA", Number:"204", Image:"/Images/EMA/MaelstromWanderer.jpg"},
{Name:"Shaman of the Pack", Cost:"1BG", Color:["B","G"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"205", Image:"/Images/EMA/ShamanofthePack.jpg"},
{Name:"Shardless Agent", Cost:"1UG", Color:["G","U"], Rarity:"R", Type:["C"], Rating:"6", Sort:"1", Set:"EMA", Number:"206", Image:"/Images/EMA/ShardlessAgent.jpg"},
{Name:"Sphinx of the Steel Wind", Cost:"5WUB", Color:["W","U","B"], Rarity:"M", Type:["C"], Rating:"7", Sort:"1", Set:"EMA", Number:"207", Image:"/Images/EMA/SphinxoftheSteelWind.jpg"},
{Name:"Thunderclap Wyvern", Cost:"2WU", Color:["W","U"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"208", Image:"/Images/EMA/ThunderclapWyvern.jpg"},
{Name:"Trygon Predator", Cost:"1GU", Color:["G","U"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"209", Image:"/Images/EMA/TrygonPredator.jpg"},
{Name:"Vindicate", Cost:"1WB", Color:["W","B"], Rarity:"R", Type:["S"], Rating:"6", Sort:"1", Set:"EMA", Number:"210", Image:"/Images/EMA/Vindicate.jpg"},
{Name:"Void", Cost:"3BR", Color:["B","R"], Rarity:"R", Type:["S"], Rating:"6", Sort:"1", Set:"EMA", Number:"211", Image:"/Images/EMA/Void.jpg"},
{Name:"Wee Dragonauts", Cost:"1UR", Color:["U","R"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"212", Image:"/Images/EMA/WeeDragonauts.jpg"},
{Name:"Zealous Persecution", Cost:"0WB", Color:["W","B"], Rarity:"U", Type:["I"], Rating:"4", Sort:"1", Set:"EMA", Number:"213", Image:"/Images/EMA/ZealousPersecution.jpg"},
{Name:"Call the Skybreaker", Cost:"5UR", Color:["U","R"], Rarity:"R", Type:["S"], Rating:"6", Sort:"1", Set:"EMA", Number:"214", Image:"/Images/EMA/CalltheSkybreaker.jpg"},
{Name:"Deathrite Shaman", Cost:"0B", Color:["B","G"], Rarity:"R", Type:["C"], Rating:"6", Sort:"1", Set:"EMA", Number:"215", Image:"/Images/EMA/DeathriteShaman.jpg"},
{Name:"Giant Solifuge", Cost:"2RG", Color:["R","G"], Rarity:"R", Type:["C"], Rating:"6", Sort:"1", Set:"EMA", Number:"216", Image:"/Images/EMA/GiantSolifuge.jpg"},
{Name:"Torrent of Souls", Cost:"4R", Color:["B","R"], Rarity:"U", Type:["S"], Rating:"4", Sort:"1", Set:"EMA", Number:"217", Image:"/Images/EMA/TorrentofSouls.jpg"},
{Name:"Ashnod's Altar", Cost:"3", Color:["C"], Rarity:"U", Type:["A"], Rating:"4", Sort:"1", Set:"EMA", Number:"218", Image:"/Images/EMA/AshnodsAltar.jpg"},
{Name:"Chrome Mox", Cost:"0", Color:["C"], Rarity:"M", Type:["A"], Rating:"7", Sort:"1", Set:"EMA", Number:"219", Image:"/Images/EMA/ChromeMox.jpg"},
{Name:"Duplicant", Cost:"6", Color:["C"], Rarity:"R", Type:["C"], Rating:"6", Sort:"1", Set:"EMA", Number:"220", Image:"/Images/EMA/Duplicant.jpg"},
{Name:"Emmessi Tome", Cost:"4", Color:["C"], Rarity:"U", Type:["A"], Rating:"4", Sort:"1", Set:"EMA", Number:"221", Image:"/Images/EMA/EmmessiTome.jpg"},
{Name:"Goblin Charbelcher", Cost:"4", Color:["C"], Rarity:"R", Type:["A"], Rating:"6", Sort:"1", Set:"EMA", Number:"222", Image:"/Images/EMA/GoblinCharbelcher.jpg"},
{Name:"Isochron Scepter", Cost:"2", Color:["C"], Rarity:"R", Type:["A"], Rating:"6", Sort:"1", Set:"EMA", Number:"223", Image:"/Images/EMA/IsochronScepter.jpg"},
{Name:"Juggernaut", Cost:"4", Color:["C"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"224", Image:"/Images/EMA/Juggernaut.jpg"},
{Name:"Mana Crypt", Cost:"0", Color:["C"], Rarity:"M", Type:["A"], Rating:"7", Sort:"1", Set:"EMA", Number:"225", Image:"/Images/EMA/ManaCrypt.jpg"},
{Name:"Millikin", Cost:"2", Color:["C"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"226", Image:"/Images/EMA/Millikin.jpg"},
{Name:"Mindless Automaton", Cost:"4", Color:["C"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"227", Image:"/Images/EMA/MindlessAutomaton.jpg"},
{Name:"Nevinyrral's Disk", Cost:"4", Color:["C"], Rarity:"R", Type:["A"], Rating:"6", Sort:"1", Set:"EMA", Number:"228", Image:"/Images/EMA/NevinyrralsDisk.jpg"},
{Name:"Pilgrim's Eye", Cost:"3", Color:["C"], Rarity:"C", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"229", Image:"/Images/EMA/PilgrimsEye.jpg"},
{Name:"Prismatic Lens", Cost:"2", Color:["C"], Rarity:"U", Type:["A"], Rating:"4", Sort:"1", Set:"EMA", Number:"230", Image:"/Images/EMA/PrismaticLens.jpg"},
{Name:"Relic of Progenitus", Cost:"1", Color:["C"], Rarity:"U", Type:["A"], Rating:"4", Sort:"1", Set:"EMA", Number:"231", Image:"/Images/EMA/RelicofProgenitus.jpg"},
{Name:"Sensei's Divining Top", Cost:"1", Color:["C"], Rarity:"R", Type:["A"], Rating:"6", Sort:"1", Set:"EMA", Number:"232", Image:"/Images/EMA/SenseisDiviningTop.jpg"},
{Name:"Ticking Gnomes", Cost:"3", Color:["C"], Rarity:"U", Type:["C"], Rating:"4", Sort:"1", Set:"EMA", Number:"233", Image:"/Images/EMA/TickingGnomes.jpg"},
{Name:"Winter Orb", Cost:"2", Color:["C"], Rarity:"R", Type:["A"], Rating:"6", Sort:"1", Set:"EMA", Number:"234", Image:"/Images/EMA/WinterOrb.jpg"},
{Name:"Worn Powerstone", Cost:"3", Color:["C"], Rarity:"U", Type:["A"], Rating:"4", Sort:"1", Set:"EMA", Number:"235", Image:"/Images/EMA/WornPowerstone.jpg"},
{Name:"Bloodfell Caves", Cost:"0", Color:["B","R"], Rarity:"C", Type:["L"], Rating:"4", Sort:"1", Set:"EMA", Number:"236", Image:"/Images/EMA/BloodfellCaves.jpg"},
{Name:"Blossoming Sands", Cost:"0", Color:["W","G"], Rarity:"C", Type:["L"], Rating:"4", Sort:"1", Set:"EMA", Number:"237", Image:"/Images/EMA/BlossomingSands.jpg"},
{Name:"Dismal Backwater", Cost:"0", Color:["U","B"], Rarity:"C", Type:["L"], Rating:"4", Sort:"1", Set:"EMA", Number:"238", Image:"/Images/EMA/DismalBackwater.jpg"},
{Name:"Jungle Hollow", Cost:"0", Color:["B","G"], Rarity:"C", Type:["L"], Rating:"4", Sort:"1", Set:"EMA", Number:"239", Image:"/Images/EMA/JungleHollow.jpg"},
{Name:"Karakas", Cost:"0", Color:["W"], Rarity:"M", Type:["L"], Rating:"7", Sort:"1", Set:"EMA", Number:"240", Image:"/Images/EMA/Karakas.jpg"},
{Name:"Maze of Ith", Cost:"0", Color:["C"], Rarity:"R", Type:["L"], Rating:"6", Sort:"1", Set:"EMA", Number:"241", Image:"/Images/EMA/MazeofIth.jpg"},
{Name:"Mishra's Factory", Cost:"0", Color:["C"], Rarity:"U", Type:["L"], Rating:"4", Sort:"1", Set:"EMA", Number:"242", Image:"/Images/EMA/MishrasFactory.jpg"},
{Name:"Rugged Highlands", Cost:"0", Color:["R","G"], Rarity:"C", Type:["L"], Rating:"4", Sort:"1", Set:"EMA", Number:"243", Image:"/Images/EMA/RuggedHighlands.jpg"},
{Name:"Scoured Barrens", Cost:"0", Color:["W","B"], Rarity:"C", Type:["L"], Rating:"4", Sort:"1", Set:"EMA", Number:"244", Image:"/Images/EMA/ScouredBarrens.jpg"},
{Name:"Swiftwater Cliffs", Cost:"0", Color:["U","R"], Rarity:"C", Type:["L"], Rating:"4", Sort:"1", Set:"EMA", Number:"245", Image:"/Images/EMA/SwiftwaterCliffs.jpg"},
{Name:"Thornwood Falls", Cost:"0", Color:["G","U"], Rarity:"C", Type:["L"], Rating:"4", Sort:"1", Set:"EMA", Number:"246", Image:"/Images/EMA/ThornwoodFalls.jpg"},
{Name:"Tranquil Cove", Cost:"0", Color:["W","U"], Rarity:"C", Type:["L"], Rating:"4", Sort:"1", Set:"EMA", Number:"247", Image:"/Images/EMA/TranquilCove.jpg"},
{Name:"Wasteland", Cost:"0", Color:["C"], Rarity:"R", Type:["L"], Rating:"6", Sort:"1", Set:"EMA", Number:"248", Image:"/Images/EMA/Wasteland.jpg"},
{Name:"Wind-Scarred Crag", Cost:"0", Color:["R","W"], Rarity:"C", Type:["L"], Rating:"4", Sort:"1", Set:"EMA", Number:"249", Image:"/Images/EMA/Wind-ScarredCrag.jpg"},
];